// ═══════════════════════════════════════════════════════════════════════
// proefexamen-bi.js — ORIGINEEL Slagio-proefexamen in examenstijl (havo bio).
// Volledig eigen content (eigen contexten, vragen, figuren), géén reproductie
// van een officieel CvTE-examen. Draait op de examenrunner (sc-examen).
//
// Opgave-model: elke opgave heeft een gedeeld ONDERWERP + context + (vaak) één
// figuur; daar gaan MEERDERE vragen over — net als op een echt examen.
//   opgaven[]  = {nr, titel, context, afb?, afb_cap?}
//   vragen[]   = {nr, opgave, punten, type, vraag, antwoord, antwoord_rubric,
//                 domein, afb?/afb_cap? (optionele vraag-eigen extra figuur)}
// ═══════════════════════════════════════════════════════════════════════
var SLAGIO_EXAMENS = (typeof SLAGIO_EXAMENS !== 'undefined' && SLAGIO_EXAMENS) || {};
SLAGIO_EXAMENS.havo = SLAGIO_EXAMENS.havo || {};

// ── Eigen figuren (zelf getekend, SVG) ──
var _BIAFB = {
  hart:`<svg viewBox="0 0 360 190" role="img" aria-label="grafiek van de hartfrequentie tegen de tijd"><line x1="48" y1="16" x2="48" y2="158" stroke="#1b2230" stroke-width="2"/><line x1="48" y1="158" x2="344" y2="158" stroke="#1b2230" stroke-width="2"/><polyline points="56,130 110,130 176,44 246,44 320,124" fill="none" stroke="#e8580c" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/><text x="0" y="0" transform="translate(16,150) rotate(-90)" font-family="sans-serif" font-size="11" font-weight="700" fill="#1b2230">hartslag (per min)</text><text x="296" y="178" font-family="sans-serif" font-size="11" font-weight="700" fill="#1b2230">tijd &#8594;</text><g font-family="sans-serif" font-size="10" fill="#4a5568" text-anchor="middle"><text x="82" y="152">rust</text><text x="205" y="152">inspanning</text><text x="305" y="152">herstel</text></g></svg>`,
  piramide:`<svg viewBox="0 0 360 200" role="img" aria-label="energiepiramide van de sloot"><polygon points="44,172 316,172 282,134 78,134" fill="#cfe8d6" stroke="#1b2230" stroke-width="1.6"/><polygon points="78,134 282,134 248,96 112,96" fill="#a9d8b8" stroke="#1b2230" stroke-width="1.6"/><polygon points="112,96 248,96 214,58 146,58" fill="#79c79a" stroke="#1b2230" stroke-width="1.6"/><polygon points="146,58 214,58 197,26 163,26" fill="#4bb17c" stroke="#1b2230" stroke-width="1.6"/><g font-family="sans-serif" font-size="11" fill="#1b2230" text-anchor="middle" font-weight="600"><text x="180" y="157">algen</text><text x="180" y="119">watervlooien</text><text x="180" y="81">visjes</text><text x="180" y="46">snoek</text></g><g stroke="#1b2230" stroke-width="1.6" fill="none"><path d="M338 168 L338 34"/><path d="M334 42 L338 32 L342 42"/></g><text x="352" y="104" font-family="sans-serif" font-size="10" fill="#4a5568" transform="rotate(-90 352 104)" text-anchor="middle">energie neemt af</text></svg>`,
  punnett:`<svg viewBox="0 0 260 212" role="img" aria-label="leeg kruisingsschema om in te vullen"><text x="140" y="18" text-anchor="middle" font-family="sans-serif" font-size="12" font-weight="700" fill="#1b2230">kruisingsschema  Zz &#215; zz</text><text x="147" y="40" text-anchor="middle" font-family="sans-serif" font-size="10.5" fill="#4a5568">gameten van zz</text><text x="0" y="0" transform="translate(30 152) rotate(-90)" font-family="sans-serif" font-size="10.5" fill="#4a5568" text-anchor="middle">gameten van Zz</text><g stroke="#1b2230" stroke-width="1.6" fill="none"><rect x="72" y="52" width="150" height="150"/><line x1="72" y1="102" x2="222" y2="102"/><line x1="72" y1="152" x2="222" y2="152"/><line x1="122" y1="52" x2="122" y2="202"/><line x1="172" y1="52" x2="172" y2="202"/></g><text x="97" y="83" text-anchor="middle" font-family="sans-serif" font-size="14" fill="#c0c8d6">&#215;</text></svg>`,
  afweer:`<svg viewBox="0 0 360 200" role="img" aria-label="antistofconcentratie na eerste en tweede blootstelling"><line x1="48" y1="14" x2="48" y2="156" stroke="#1b2230" stroke-width="2"/><line x1="48" y1="156" x2="344" y2="156" stroke="#1b2230" stroke-width="2"/><path d="M70 156 Q112 150 132 122 Q148 102 164 122 Q182 146 205 152" fill="none" stroke="#e8580c" stroke-width="2.6"/><path d="M205 152 Q214 58 240 42 Q262 30 282 58 Q302 90 332 120" fill="none" stroke="#2e9e5b" stroke-width="2.8"/><g stroke="#1b2230" stroke-width="1.3"><line x1="70" y1="156" x2="70" y2="168"/><line x1="205" y1="156" x2="205" y2="168"/></g><g font-family="sans-serif" font-size="9.5" fill="#4a5568" text-anchor="middle"><text x="70" y="182">1e blootstelling</text><text x="205" y="182">2e blootstelling</text></g><text x="0" y="0" transform="translate(16,150) rotate(-90)" font-family="sans-serif" font-size="10.5" font-weight="700" fill="#1b2230" text-anchor="middle">antistofconcentratie</text><text x="316" y="148" font-family="sans-serif" font-size="10.5" font-weight="700" fill="#1b2230">tijd &#8594;</text></svg>`,
  opstelling:`<svg viewBox="0 0 360 172" role="img" aria-label="proefopstelling met lamp en waterpest"><circle cx="52" cy="64" r="20" fill="#fff3c4" stroke="#1b2230" stroke-width="2"/><rect x="45" y="82" width="14" height="9" fill="#cbd2e0" stroke="#1b2230" stroke-width="1.4"/><g stroke="#e8a400" stroke-width="2" stroke-linecap="round"><line x1="80" y1="50" x2="94" y2="45"/><line x1="82" y1="64" x2="98" y2="64"/><line x1="80" y1="78" x2="94" y2="83"/></g><g stroke="#1b2230" stroke-width="1.4" fill="none"><line x1="70" y1="120" x2="250" y2="120"/><path d="M76 116 L70 120 L76 124"/><path d="M244 116 L250 120 L244 124"/></g><text x="160" y="113" font-family="sans-serif" font-size="10.5" fill="#4a5568" text-anchor="middle" font-weight="700">afstand tot de lamp</text><path d="M258 40 L258 138 Q258 150 270 150 L306 150 Q318 150 318 138 L318 40" fill="#e7f4ff" stroke="#1b2230" stroke-width="2"/><line x1="258" y1="58" x2="318" y2="58" stroke="#9cc7ea" stroke-width="1.2"/><path d="M288 146 L288 72" stroke="#2e9e5b" stroke-width="3"/><g fill="#2e9e5b"><ellipse cx="281" cy="88" rx="7" ry="3.4" transform="rotate(-30 281 88)"/><ellipse cx="295" cy="100" rx="7" ry="3.4" transform="rotate(30 295 100)"/><ellipse cx="281" cy="112" rx="7" ry="3.4" transform="rotate(-30 281 112)"/></g><g fill="none" stroke="#5b8def" stroke-width="1.3"><circle cx="299" cy="80" r="3"/><circle cx="304" cy="66" r="2.4"/><circle cx="300" cy="54" r="2"/></g></svg>`,
  fotosynthese:`<svg viewBox="0 0 360 190" role="img" aria-label="grafiek fotosynthesesnelheid tegen lichtsterkte"><line x1="48" y1="16" x2="48" y2="158" stroke="#1b2230" stroke-width="2"/><line x1="48" y1="158" x2="344" y2="158" stroke="#1b2230" stroke-width="2"/><path d="M56 150 Q112 150 152 96 Q190 52 250 50 L332 50" fill="none" stroke="#2e9e5b" stroke-width="3" stroke-linecap="round"/><line x1="250" y1="50" x2="250" y2="158" stroke="#94a0b8" stroke-width="1.2" stroke-dasharray="4 4"/><text x="0" y="0" transform="translate(16,154) rotate(-90)" font-family="sans-serif" font-size="11" font-weight="700" fill="#1b2230">fotosynthesesnelheid</text><text x="244" y="178" font-family="sans-serif" font-size="11" font-weight="700" fill="#1b2230">lichtsterkte &#8594;</text></svg>`,
};

SLAGIO_EXAMENS.havo.bi = {
  origineel: true,
  titel: 'Biologie',
  niveau: 'havo',
  jaar: new Date().getFullYear(),
  duur_minuten: 90,
  max_punten: 42,
  bron: 'Slagio origineel · examenstijl',
  bijlagen: [],
  opgaven: [
    { nr:1, titel:'Hardlopen',
      context:'Isa traint voor een hardloopwedstrijd. In afbeelding 1 is haar hartfrequentie weergegeven vóór, tijdens en na de inspanning. Haar spieren verbruiken tijdens het hardlopen meer energie dan in rust.',
      afb:_BIAFB.hart, afb_cap:'afbeelding 1 — hartfrequentie vóór, tijdens en na de inspanning' },
    { nr:2, titel:'Brood bakken',
      context:'Bij het bakken van brood voegt een bakker gist toe aan het deeg. De gistcellen zetten suikers om en het deeg rijst. In het deeg is weinig zuurstof aanwezig.' },
    { nr:3, titel:'De sloot',
      context:'In een sloot leven algen, watervlooien, kleine visjes en snoeken. De boer bemest het naastgelegen weiland. Afbeelding 2 toont de energiepiramide van deze sloot.',
      afb:_BIAFB.piramide, afb_cap:'afbeelding 2 — energiepiramide van de sloot' },
    { nr:4, titel:'Cavia\'s',
      context:'Bij cavia\'s is een zwarte vacht (allel Z) dominant over een witte vacht (allel z). Een kweker kruist een zwarte cavia met genotype Zz met een witte cavia (zz). Gebruik het lege kruisingsschema in afbeelding 3.',
      afb:_BIAFB.punnett, afb_cap:'afbeelding 3 — vul het kruisingsschema zelf in' },
    { nr:5, titel:'Vaccinatie',
      context:'Tijdens een griepcampagne krijgen mensen een vaccin met onschadelijk gemaakte delen van het griepvirus (antigenen). Afbeelding 4 toont de antistofconcentratie in het bloed na een eerste en een tweede blootstelling aan hetzelfde antigeen.',
      afb:_BIAFB.afweer, afb_cap:'afbeelding 4 — antistofconcentratie na een eerste en tweede blootstelling' },
    { nr:6, titel:'Onderzoek naar fotosynthese',
      context:'Een leerling onderzoekt de invloed van lichtsterkte op de fotosynthesesnelheid van waterpest. Ze telt het aantal zuurstofbelletjes per minuut bij verschillende afstanden tussen de lamp en de plant (afbeelding 5).',
      afb:_BIAFB.opstelling, afb_cap:'afbeelding 5 — de proefopstelling' },
  ],
  vragen: [
    // ── Opgave 1 · Hardlopen ──
    { nr:1, opgave:1, punten:2, type:'open', domein:'A',
      vraag:'In welk deel van afbeelding 1 — rust, inspanning of herstel — is Isa aan het hardlopen? Leg je antwoord uit met de grafiek.',
      antwoord:'Tijdens de inspanning. In dat deel is de hartfrequentie het hoogst en ongeveer constant (het plateau in de grafiek), omdat het hart dan het hardst moet werken.',
      antwoord_rubric:'1 punt: inspanning. 1 punt: onderbouwing met de grafiek (hoogste/constante hartslag = plateau).' },
    { nr:2, opgave:1, punten:2, type:'open', domein:'O',
      vraag:'Leg uit waarom Isa tijdens het hardlopen sneller gaat ademen. Betrek de gaswisseling in je antwoord.',
      antwoord:'Haar spieren verbruiken meer zuurstof en produceren meer koolstofdioxide door de toegenomen verbranding (celademhaling). Sneller ademen voert meer zuurstof aan en meer koolstofdioxide af, zodat de gaswisseling de vraag bijhoudt.',
      antwoord_rubric:'1 punt: meer O₂ nodig / meer CO₂ door toegenomen verbranding. 1 punt: sneller ademen zorgt voor aanvoer O₂ en afvoer CO₂.' },
    { nr:3, opgave:1, punten:2, type:'open', domein:'O',
      vraag:'Tijdens de inspanning neemt het hartminuutvolume toe. Noem twee manieren waarop het hart het hartminuutvolume kan verhogen.',
      antwoord:'Door de hartslagfrequentie te verhogen (vaker kloppen) en door het slagvolume te vergroten (meer bloed per slag).',
      antwoord_rubric:'1 punt: hogere hartfrequentie. 1 punt: groter slagvolume.' },
    { nr:4, opgave:1, punten:2, type:'open', domein:'M',
      vraag:'In de spieren wordt glucose verbrand. Geef de woordvergelijking van de volledige (aerobe) verbranding van glucose.',
      antwoord:'glucose + zuurstof → koolstofdioxide + water + energie',
      antwoord_rubric:'1 punt: juiste uitgangsstoffen (glucose + zuurstof). 1 punt: juiste producten (koolstofdioxide + water + energie).' },
    { nr:5, opgave:1, punten:1, type:'open', domein:'M',
      vraag:'Bij een eindsprint ontstaat zuurstoftekort in de spieren. Welke stof hoopt zich dan op door melkzuurgisting?',
      antwoord:'melkzuur (lactaat)',
      antwoord_rubric:'1 punt: melkzuur / lactaat.' },
    // ── Opgave 2 · Brood bakken ──
    { nr:6, opgave:2, punten:2, type:'open', domein:'M',
      vraag:'Gist zet onder zuurstofarme omstandigheden suiker om via alcoholgisting. Geef de woordvergelijking van alcoholgisting.',
      antwoord:'glucose → alcohol (ethanol) + koolstofdioxide + energie',
      antwoord_rubric:'1 punt: glucose als uitgangsstof. 1 punt: ethanol + koolstofdioxide (+ energie) als producten.' },
    { nr:7, opgave:2, punten:2, type:'open', domein:'M',
      vraag:'Leg uit waardoor het deeg rijst.',
      antwoord:'Bij de gisting komt koolstofdioxidegas vrij. Dit gas blijft als belletjes in het deeg zitten en zet uit, waardoor het volume van het deeg toeneemt: het deeg rijst.',
      antwoord_rubric:'1 punt: bij gisting ontstaat CO₂-gas. 1 punt: gas blijft in het deeg → volume neemt toe.' },
    { nr:8, opgave:2, punten:2, type:'open', domein:'M',
      vraag:'De omzettingen in de gistcel worden versneld door enzymen. Leg uit waarom de gisting vrijwel stopt als het deeg in een hete oven van 220 °C komt.',
      antwoord:'Bij deze hoge temperatuur denatureren de enzymen: hun ruimtelijke structuur (en dus de actieve plaats) verandert onherstelbaar. Daardoor kunnen ze het substraat niet meer omzetten en stopt de gisting.',
      antwoord_rubric:'1 punt: enzymen denatureren door de hoge temperatuur. 1 punt: daardoor geen omzetting/gisting meer.' },
    { nr:9, opgave:2, punten:1, type:'open', domein:'M',
      vraag:'Wordt een enzym tijdens de reactie verbruikt? Leg je antwoord kort uit.',
      antwoord:'Nee. Een enzym is een biokatalysator en komt onveranderd uit de reactie; het kan daarna opnieuw een omzetting versnellen.',
      antwoord_rubric:'1 punt: nee, want een enzym is een katalysator / komt onveranderd uit de reactie.' },
    // ── Opgave 3 · De sloot ──
    { nr:10, opgave:3, punten:2, type:'open', domein:'P',
      vraag:'Stel met algen, watervlooien, kleine visjes en snoek een voedselketen op van vier schakels. Gebruik pijlen in de richting van de energiestroom.',
      antwoord:'algen → watervlooien → kleine visjes → snoek',
      antwoord_rubric:'1 punt: producent onderaan en juiste volgorde. 1 punt: vier correcte schakels met pijlen richting de verbruiker.' },
    { nr:11, opgave:3, punten:2, type:'open', domein:'P',
      vraag:'Door de bemesting spoelen extra stikstof en fosfaat in de sloot. Leg uit hoe dit tot een zuurstoftekort in het water kan leiden (eutrofiëring).',
      antwoord:'De extra voedingsstoffen zorgen voor sterke algengroei (algenbloei). Als de algen afsterven, worden ze door bacteriën afgebroken. Bij die afbraak wordt veel zuurstof verbruikt, waardoor een zuurstoftekort ontstaat.',
      antwoord_rubric:'1 punt: extra nutriënten → sterke algengroei. 1 punt: afbraak dode algen door bacteriën verbruikt zuurstof → tekort.' },
    { nr:12, opgave:3, punten:2, type:'open', domein:'P',
      vraag:'Gebruik afbeelding 2. Leg uit waarom er in de sloot veel minder snoeken dan algen kunnen leven. Gebruik in je antwoord het begrip energie.',
      antwoord:'De piramide wordt naar boven toe smaller omdat bij elke schakel energie verloren gaat, onder andere als warmte bij de dissimilatie. Daardoor is er hogerop steeds minder energie beschikbaar en kan de bovenste schakel (snoek) maar een kleine biomassa in stand houden.',
      antwoord_rubric:'1 punt: bij elke schakel gaat energie verloren. 1 punt: daardoor minder energie/biomassa hogerop → minder snoeken.' },
    { nr:13, opgave:3, punten:1, type:'open', domein:'P',
      vraag:'Welke rol in de kringloop hebben de bacteriën die de dode algen afbreken?',
      antwoord:'reducenten (afbrekers)',
      antwoord_rubric:'1 punt: reducent / afbreker.' },
    // ── Opgave 4 · Cavia's ──
    { nr:14, opgave:4, punten:2, type:'open', domein:'O',
      vraag:'Vul het kruisingsschema van afbeelding 3 in en geef de genotypen van de nakomelingen met hun verhouding.',
      antwoord:'Gameten: Z en z (van Zz) en z en z (van zz). Nakomelingen: Zz en zz in de verhouding 1 : 1 (50% Zz, 50% zz).',
      antwoord_rubric:'1 punt: juiste gameten in het schema. 1 punt: nakomelingen Zz en zz in verhouding 1 : 1.' },
    { nr:15, opgave:4, punten:2, type:'open', domein:'O',
      vraag:'Welk deel van de nakomelingen is naar verwachting wit? Onderbouw je antwoord met het schema.',
      antwoord:'De helft (50%). De nakomelingen met genotype zz zijn wit, omdat zij geen dominant allel Z bezitten; volgens het schema is dat de helft van de nakomelingen.',
      antwoord_rubric:'1 punt: de helft / 50%. 1 punt: onderbouwing dat zz wit is (geen dominant Z).' },
    { nr:16, opgave:4, punten:1, type:'open', domein:'O',
      vraag:'Een zwarte cavia kan genotype ZZ of Zz hebben. Met welke kruising kun je bepalen welk van beide genotypen een zwarte cavia heeft?',
      antwoord:'Een testkruising (terugkruising) met een witte cavia (zz).',
      antwoord_rubric:'1 punt: testkruising/terugkruising met een witte (zz) cavia.' },
    // ── Opgave 5 · Vaccinatie ──
    { nr:17, opgave:5, punten:2, type:'open', domein:'O',
      vraag:'Leg met afbeelding 4 uit waarom iemand na vaccinatie bij een tweede blootstelling sneller en sterker reageert dan bij de eerste.',
      antwoord:'Bij de eerste blootstelling maakt het lichaam langzaam en weinig antistoffen én geheugencellen (de lage, late piek). Bij de tweede blootstelling herkennen de geheugencellen het antigeen meteen, waardoor er sneller en veel meer antistoffen worden gemaakt (de hoge, snelle piek).',
      antwoord_rubric:'1 punt: bij de eerste blootstelling ontstaan geheugencellen. 1 punt: die zorgen bij de tweede blootstelling voor een snellere en hogere antistofpiek (afgelezen uit de grafiek).' },
    { nr:18, opgave:5, punten:2, type:'open', domein:'O',
      vraag:'Is de immuniteit die door dit vaccin ontstaat actief of passief? Leg je antwoord uit.',
      antwoord:'Actieve immuniteit: het lichaam maakt zélf antistoffen en geheugencellen als reactie op de antigenen in het vaccin.',
      antwoord_rubric:'1 punt: actief. 1 punt: omdat het lichaam zelf antistoffen/geheugencellen maakt.' },
    { nr:19, opgave:5, punten:2, type:'open', domein:'O',
      vraag:'Een baby van drie maanden krijgt dit vaccin nog niet, maar heeft wel tijdelijke bescherming gekregen via antistoffen van de moeder. Hoe heet deze bescherming en waarom is die tijdelijk?',
      antwoord:'Passieve immuniteit. Die is tijdelijk omdat de baby de antistoffen niet zelf aanmaakt en geen geheugencellen heeft; de gekregen antistoffen worden na verloop van tijd afgebroken en verdwijnen.',
      antwoord_rubric:'1 punt: passieve immuniteit. 1 punt: geen eigen aanmaak/geheugencellen → antistoffen worden afgebroken.' },
    // ── Opgave 6 · Onderzoek naar fotosynthese ──
    { nr:20, opgave:6, punten:1, type:'open', domein:'A',
      vraag:'Wat is in dit onderzoek de onafhankelijke variabele?',
      antwoord:'de lichtsterkte (geregeld via de afstand tot de lamp)',
      antwoord_rubric:'1 punt: lichtsterkte / afstand tot de lamp.' },
    { nr:21, opgave:6, punten:1, type:'open', domein:'A',
      vraag:'Wat is de afhankelijke variabele?',
      antwoord:'de fotosynthesesnelheid (het aantal zuurstofbelletjes per minuut)',
      antwoord_rubric:'1 punt: fotosynthesesnelheid / aantal zuurstofbelletjes per minuut.' },
    { nr:22, opgave:6, punten:2, type:'open', domein:'A',
      vraag:'Noem twee factoren die de leerling constant moet houden om een betrouwbare conclusie te kunnen trekken.',
      antwoord:'Bijvoorbeeld: de temperatuur van het water, de CO₂-concentratie in het water, dezelfde (hoeveelheid) waterpest en dezelfde lamp/lichtkleur. Twee hiervan volstaan.',
      antwoord_rubric:'1 punt per correcte constant te houden factor (maximaal 2).' },
    { nr:23, opgave:6, punten:2, type:'open', domein:'A',
      vraag:'De leerling herhaalt elke meting drie keer. Leg uit waarom herhalen de betrouwbaarheid van het onderzoek vergroot.',
      antwoord:'Door metingen te herhalen en te middelen wordt de invloed van toevallige meetfouten en variatie kleiner. De gemiddelde meetwaarde is daardoor consistenter en betrouwbaarder.',
      antwoord_rubric:'1 punt: herhalen vermindert invloed van toevallige (meet)fouten. 1 punt: gemiddelde is betrouwbaarder/consistenter.' },
    { nr:24, opgave:6, punten:2, type:'open', domein:'A',
      afb:_BIAFB.fotosynthese, afb_cap:'afbeelding 6 — fotosynthesesnelheid bij toenemende lichtsterkte',
      vraag:'De leerling zet de resultaten uit in een grafiek (afbeelding 6). Vanaf een bepaalde lichtsterkte neemt de fotosynthesesnelheid niet verder toe. Noem een factor die de fotosynthese daar waarschijnlijk beperkt en leg uit hoe je zo\'n factor noemt.',
      antwoord:'Bijvoorbeeld de CO₂-concentratie of de temperatuur. Zo\'n factor die op dat moment de snelheid begrenst, heet de beperkende (limiterende) factor.',
      antwoord_rubric:'1 punt: noemt CO₂-concentratie of temperatuur. 1 punt: benoemt dit als beperkende/limiterende factor.' },
  ]
};
