// HAVO Bedrijfseconomie - situaties per begrip.
export default {
  B: {
    'Samengestelde interest': ['Je krijgt rente over je inleg én over de rente van vorige jaren', 'Rente die ook over eerdere rente wordt berekend'],
    BV: ['De aandeelhouders zijn beperkt aansprakelijk en de aandelen zijn niet vrij verhandelbaar', 'Een rechtspersoon met beperkte aansprakelijkheid'],
    Eenmanszaak: ['Eén eigenaar die met zijn privévermogen aansprakelijk is', 'Een onderneming met één onbeperkt aansprakelijke eigenaar'],
    Rechtspersoon: ['De onderneming sluit zelf contracten en kan zelf worden aangeklaagd', 'Een organisatie die zelfstandig rechtssubject is'],
    NV: ['De aandelen worden vrij verhandeld op de beurs', 'Een rechtspersoon met vrij verhandelbare aandelen'],
    VOF: ['Twee ondernemers werken samen en zijn allebei hoofdelijk aansprakelijk', 'Een samenwerkingsverband met hoofdelijk aansprakelijke vennoten'],
    'Continuïteit': ['De onderneming wil op lange termijn blijven voortbestaan', 'Het streven om op lange termijn voort te bestaan'],
    Factoring: ['Een bedrijf verkoopt zijn openstaande facturen om sneller geld te krijgen', 'Het verkopen van vorderingen voor geld'],
    Vennootschapsbelasting: ['Een BV betaalt deze belasting over de gemaakte winst', 'De belasting die een BV over de winst betaalt'],
    Aandelenkapitaal: ['Het geld dat aandeelhouders in de onderneming hebben ingebracht', 'Het kapitaal van de aandeelhouders'],
  },
  C: {
    'Lijn-staforganisatie': ['Er zijn gezagslijnen van hoog naar laag, met adviseurs zonder bevelsbevoegdheid', 'Gezagslijnen aangevuld met adviserende specialisten'],
    'Arbeidsovereenkomst bepaalde tijd': ['Het contract loopt vanzelf af op de afgesproken einddatum', 'Een contract dat automatisch eindigt'],
    CAO: ['In dit akkoord staan loon en arbeidsvoorwaarden voor een hele sector', 'Collectieve afspraken over loon en arbeidsvoorwaarden'],
    Ontslaggronden: ['Bedrijfseconomisch, disfunctioneren of een verstoorde arbeidsrelatie', 'De wettelijke redenen voor ontslag'],
    'Platte organisatie': ['Weinig lagen tussen de top en de werkvloer, dus veel medewerkers per baas', 'Een structuur met weinig hiërarchische lagen'],
    'Steile organisatie': ['Veel lagen tussen de top en de werkvloer, dus weinig medewerkers per baas', 'Een structuur met veel hiërarchische lagen'],
    Decentralisatie: ['Beslissingsbevoegdheden worden lager in de organisatie gelegd', 'Bevoegdheden toewijzen aan lagere niveaus'],
    'Piramide van Maslow': ['De behoeftenhiërarchie van basisbehoeften tot zelfontplooiing', 'De vijf behoefteniveaus van Maslow'],
    'Span of control': ['Het aantal medewerkers dat direct onder één leidinggevende valt', 'Het aantal medewerkers per leidinggevende'],
    'Formele communicatie': ['Informatie stroomt via de officiële lijnen van hoog naar laag', 'De officiële informatieroutes in een organisatie'],
  },
  D: {
    Marketingmix: ['Je stemt Product, Prijs, Plaats en Promotie op elkaar af', 'De vier P\'s van de marketing'],
    Penetratiestrategie: ['Je begint met een lage prijs om snel veel klanten te winnen', 'Een lage introductieprijs voor marktaandeel'],
    'Secundair onderzoek': ['Je gebruikt bestaande CBS-rapporten en sectorstatistieken', 'Onderzoek met bestaande bronnen'],
    Bedrijfskolom: ['De schakels van producent via groothandel naar de winkel', 'De opeenvolgende schakels van de distributieketen'],
    'Kwalitatief onderzoek': ['Met interviews en focusgroepen achterhaal je meningen en motieven', 'Diepgaand onderzoek via interviews'],
    'Marktoriëntatie': ['Je onderzoekt eerst wat de klant wil voordat je een product maakt', 'Eerst de klantbehoeften begrijpen'],
    Productlevenscyclus: ['Een product gaat van introductie via groei en rijpheid naar neergang', 'De levensfasen van een product'],
    'Intensieve distributie': ['Het product ligt in zo veel mogelijk winkels', 'Zo veel mogelijk verkooppunten'],
    'Public relations': ['Je krijgt gratis, redactionele aandacht in de media', 'Onbetaalde media-aandacht'],
    'Enquête': ['Je legt een vragenlijst aan honderden mensen voor', 'Een vragenlijst voor kwantitatieve data'],
  },
  E: {
    Dekkingsbijdrage: ['De verkoopprijs min de variabele kosten per stuk', 'Prijs min variabele kosten per stuk'],
    'Vaste kosten': ['De huur en het vaste salaris lopen door, ook bij nulproductie', 'Kosten die niet met de productie meebewegen'],
    'Variabele kosten': ['De grondstofkosten stijgen als je meer produceert', 'Kosten die met de productieomvang meebewegen'],
    'Break-evenafzet': ['De afzet waarbij de opbrengsten precies alle kosten dekken', 'De afzet waarbij de winst nul is'],
    Hefboomwerking: ['Vreemd vermogen tilt de rentabiliteit van het eigen vermogen op of omlaag', 'Het effect van vreemd vermogen op de REV'],
    'Netto contante waarde': ['Je verdisconteert alle toekomstige kasstromen naar nu', 'Een criterium dat de tijdswaarde van geld meeneemt'],
    Solvabiliteit: ['De verhouding tussen eigen vermogen en het totale vermogen', 'Het aandeel eigen vermogen in het totaal'],
    REV: ['Het rendement dat de eigenaren op hun eigen vermogen halen', 'De rentabiliteit van het eigen vermogen'],
    RTV: ['Het rendement op het totale vermogen van de onderneming', 'De rentabiliteit van het totale vermogen'],
    'Interne rentabiliteit': ['Het rendementspercentage waarbij de netto contante waarde nul is', 'Het percentage waarbij de NCW nul is'],
  },
  F: {
    'Quick ratio': ['Je meet de liquiditeit maar telt de voorraden niet mee', 'Liquiditeitskengetal zonder voorraden'],
    Solvabiliteit: ['De verhouding tussen eigen vermogen en het totale vermogen', 'Het aandeel eigen vermogen in het totaal'],
    'Lineaire afschrijving': ['Je schrijft elk jaar hetzelfde bedrag af', 'Afschrijven in gelijke jaarlijkse bedragen'],
    Balans: ['Een momentopname waarbij de activa gelijk zijn aan de passiva', 'Een momentopname van bezit en financiering'],
    Passiva: ['De financieringskant met eigen vermogen en schulden', 'De kant met eigen vermogen en langlopende schulden'],
    'Winst-en-verliesrekening': ['Een overzicht van de baten en lasten over een periode', 'Een overzicht van baten en lasten'],
    Brutowinst: ['De omzet min de inkoopwaarde van de verkochte producten', 'Omzet min inkoopwaarde'],
    'Vaste activa': ['Machines en gebouwen die langer dan een jaar meegaan', 'Bezittingen die langer dan een jaar in gebruik zijn'],
    Werkkapitaal: ['De vlottende activa min de kortlopende schulden', 'Vlottende activa min kortlopende schulden'],
    'Eigen vermogen': ['Het ingebrachte kapitaal plus de opgebouwde reserves', 'Ingebracht kapitaal plus reserves'],
  },
};
