// HAVO Nederlands - gouden-stijl contentspec. Vervangt crude generatorvragen
// door authored inzichtvragen met per-optie-uitleg + situatiebegrippen.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'havo', vak: 'nl', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Leesvaardigheid',
    `Bij leesvaardigheid bepaal je de <strong>hoofdgedachte</strong> en het <strong>communicatieve doel</strong>, herken je het <strong>teksttype</strong> (betoog, beschouwing, uiteenzetting) en volg je de <strong>signaalwoorden</strong>. Je onderscheidt een <strong>feit</strong> van een <strong>mening</strong> en herkent middelen als de <strong>concessie</strong>.`,
    [
      { h: '1. Doel en tekstsoort', p: [
        `De <strong>hoofdgedachte</strong> is de centrale boodschap die de hele tekst draagt. Het <strong>communicatieve doel</strong> is de bedoeling: informeren, overtuigen of beschrijven. Een <strong>betoog</strong> wil overtuigen van één standpunt; een <strong>beschouwing</strong> verkent een vraagstuk van meerdere kanten zonder een hard standpunt.`] },
      { h: '2. Argumentatie en signaalwoorden', p: [
        `Een <strong>feit</strong> is objectief controleerbaar, een <strong>mening</strong> een persoonlijk oordeel. Een <strong>concessie</strong> erkent een tegenargument maar handhaaft het eigen standpunt ("weliswaar X, maar toch…"). <strong>Signaalwoorden</strong> sturen de tekst: "echter" (tegenstelling), "ten eerste/vervolgens" (opsomming), "daardoor" (gevolg). Bij <strong>deductie</strong> trek je uit een algemene regel een specifieke conclusie.`] },
    ],
    [
      { t: 'Hoofdgedachte', d: 'de centrale boodschap die de hele tekst draagt', k: 'centrale boodschap', fout: ['Communicatief doel'] },
      { t: 'Betoog', d: 'een tekst die de lezer van één standpunt wil overtuigen', k: 'wil overtuigen', fout: ['Beschouwing'] },
      { t: 'Beschouwing', d: 'een tekst die een vraagstuk van meerdere kanten verkent', k: 'meerdere kanten, geen hard standpunt', fout: ['Betoog'] },
      { t: 'Concessie', d: 'een tegenargument erkennen en daarna het eigen standpunt handhaven', k: 'toegeven en toch volhouden', fout: ['Feit'] },
      { t: 'Feit', d: 'een objectief controleerbare uitspraak', k: 'controleerbaar', fout: ['Mening'] },
      { t: 'Mening', d: 'een persoonlijk oordeel dat niet te bewijzen is', k: 'persoonlijk oordeel', fout: ['Feit'] },
      { t: 'Communicatief doel', d: 'de bedoeling van de schrijver: informeren, overtuigen of beschrijven', k: 'de bedoeling van de tekst', fout: ['Hoofdgedachte'] },
      { t: 'Deductie', d: 'uit een algemene regel een specifieke conclusie trekken', k: 'algemeen naar specifiek', fout: ['Signaalwoord'] },
      { t: 'Signaalwoord', d: 'een woord dat het verband tussen zinnen aangeeft', k: 'geeft verband aan', fout: ['Argument'] },
      { t: 'Argument', d: 'een reden die een standpunt onderbouwt', k: 'onderbouwt een standpunt', fout: ['Concessie'] },
    ],
    [
      { v: 'Welk element is de overkoepelende boodschap die de hele tekst draagt?', o: ['de hoofdgedachte', 'een detail', 'de titel', 'een signaalwoord'], c: 0, d: 2, uo: ['Klopt: de hoofdgedachte draagt de tekst.', 'Nee, een detail is bijzaak.', 'Nee, de titel is niet altijd de kern.', 'Nee, dat markeert een verband.'], uh: 'Hoofdgedachte: de centrale boodschap van de tekst.' },
      { v: 'Welk signaalwoord geeft een tegenstelling aan?', o: ['echter', 'daardoor', 'ten eerste', 'namelijk'], c: 0, d: 2, uo: ['Klopt: "echter" markeert een tegenstelling.', 'Nee, dat is een gevolg.', 'Nee, dat is een opsomming.', 'Nee, dat is een reden.'], uh: 'Signaalwoord "echter": tegenstelling.' },
      { v: 'Welk teksttype wil de lezer van één standpunt overtuigen?', o: ['het betoog', 'de uiteenzetting', 'de beschouwing', 'het verslag'], c: 0, d: 2, uo: ['Klopt: een betoog wil overtuigen.', 'Nee, dat informeert.', 'Nee, dat weegt af.', 'Nee, dat doet neutraal verslag.'], uh: 'Betoog: de lezer overtuigen.' },
      { v: 'Welk retorisch middel erkent een tegenargument maar handhaaft daarna het standpunt?', o: ['de concessie', 'de herhaling', 'de opsomming', 'de vergelijking'], c: 0, d: 3, uo: ['Klopt: bij een concessie geef je een punt toe en houd je toch vol.', 'Nee, dat is iets herhalen.', 'Nee, dat is een reeks.', 'Nee, dat is een stijlfiguur.'], uh: 'Concessie: toegeven en toch je standpunt houden.' },
      { v: 'Welke uitspraak is objectief controleerbaar en niet afhankelijk van een waardering?', o: ['een feit', 'een mening', 'een concessie', 'een drogreden'], c: 0, d: 2, uo: ['Klopt: een feit is controleerbaar.', 'Nee, dat is een persoonlijk oordeel.', 'Nee, dat is een middel.', 'Nee, dat is een denkfout.'], uh: 'Feit: objectief controleerbaar.' },
      { v: 'Welk kenmerk verwijst naar de bedoeling waarmee een schrijver een tekst schreef?', o: ['het communicatieve doel', 'de hoofdgedachte', 'het signaalwoord', 'de titel'], c: 0, d: 2, uo: ['Klopt: informeren, overtuigen of beschrijven is het doel.', 'Nee, dat is de kernboodschap.', 'Nee, dat markeert een verband.', 'Nee, dat is de kop.'], uh: 'Communicatief doel: de bedoeling van de tekst.' },
      { v: 'Welke redenering trekt uit een algemene regel een specifieke conclusie?', o: ['deductie', 'inductie', 'concessie', 'opsomming'], c: 0, d: 3, uo: ['Klopt: van algemeen naar specifiek is deductie.', 'Nee, dat gaat van specifiek naar algemeen.', 'Nee, dat is een middel.', 'Nee, dat is een reeks.'], uh: 'Deductie: van algemene regel naar specifieke conclusie.' },
      { v: 'Welk signaalwoord geeft een opsomming of volgorde aan?', o: ['ten eerste / vervolgens / ten slotte', 'echter', 'daardoor', 'want'], c: 0, d: 2, uo: ['Klopt: deze woorden ordenen een reeks.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een gevolg.', 'Nee, dat is een reden.'], uh: '"Ten eerste/vervolgens": opsomming.' },
      { v: 'Hoe onderscheidt een beschouwing zich van een betoog?', o: ['ze verkent een vraagstuk van meerdere kanten zonder een hard standpunt', 'ze wil per se overtuigen', 'ze geeft alleen instructies', 'ze bevat alleen feiten'], c: 0, d: 3, uo: ['Klopt: een beschouwing weegt af zonder één standpunt op te dringen.', 'Nee, dat is een betoog.', 'Nee, dat is een instructie.', 'Nee, ook meningen komen aan bod.'], uh: 'Beschouwing: meerdere kanten, geen hard standpunt.' },
      { v: 'Wat is een mening?', o: ['een persoonlijk oordeel dat niet te bewijzen is', 'een controleerbaar feit', 'een signaalwoord', 'een titel'], c: 0, d: 2, uo: ['Klopt: een mening is subjectief.', 'Nee, dat is een feit.', 'Nee, dat markeert een verband.', 'Nee, dat is de kop.'], uh: 'Mening: een persoonlijk, onbewijsbaar oordeel.' },
      { v: 'Welk signaalwoord geeft een oorzaak-gevolgrelatie aan?', o: ['daardoor', 'echter', 'bijvoorbeeld', 'ten eerste'], c: 0, d: 2, uo: ['Klopt: "daardoor" leidt een gevolg in.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een voorbeeld.', 'Nee, dat is een opsomming.'], uh: '"Daardoor": oorzaak-gevolg.' },
    ]),

  V('B', 'Mondelinge taalvaardigheid',
    `Een goede <strong>presentatie</strong> heeft een <strong>inleiding, kern en conclusie</strong>. <strong>Non-verbale communicatie</strong> als <strong>oogcontact</strong> versterkt je geloofwaardigheid. In een <strong>debat</strong> bouw je een sterk argument op (standpunt, redenering, bewijs) en sluit je af met een <strong>slotpleidooi</strong>. Je past je <strong>register</strong> aan.`,
    [
      { h: '1. Presenteren', p: [
        `Een <strong>presentatiestructuur</strong> bestaat uit een <strong>inleiding</strong>, een <strong>kern</strong> en een <strong>conclusie</strong>. Bij <strong>non-verbale communicatie</strong> heeft <strong>oogcontact</strong> de meeste invloed op je geloofwaardigheid. Een <strong>informatieve</strong> presentatie informeert neutraal, een <strong>overtuigende</strong> zet aan tot een mening of actie.`] },
      { h: '2. Debat en register', p: [
        `Een sterk <strong>debatargument</strong> heeft een standpunt, een redenering en bewijs. Het <strong>slotpleidooi</strong> vat de sterkste argumenten samen en overtuigt de jury. In een <strong>formeel register</strong> gebruik je volledige zinnen, de u-vorm en geen afkortingen. Bij <strong>actief luisteren</strong> noteer je kernwoorden per punt, geen hele zinnen.`] },
    ],
    [
      { t: 'Presentatiestructuur', d: 'de opbouw met een inleiding, kern en conclusie', k: 'inleiding, kern, conclusie', fout: ['Debatargument'] },
      { t: 'Non-verbale communicatie', d: 'communicatie via houding, gebaren en oogcontact', k: 'lichaamstaal', fout: ['Register'] },
      { t: 'Debatargument', d: 'een argument met een standpunt, een redenering en bewijs', k: 'standpunt, redenering, bewijs', fout: ['Slotpleidooi'] },
      { t: 'Formeel register', d: 'nette taal met volledige zinnen en de u-vorm', k: 'volledige zinnen, u-vorm', fout: ['Informatieve presentatie'] },
      { t: 'Informatieve presentatie', d: 'een presentatie die neutraal informeert', k: 'informeert neutraal', fout: ['Overtuigende presentatie'] },
      { t: 'Overtuigende presentatie', d: 'een presentatie die aanzet tot een mening of actie', k: 'zet aan tot mening of actie', fout: ['Informatieve presentatie'] },
      { t: 'Slotpleidooi', d: 'de afsluiting die de sterkste argumenten samenvat en overtuigt', k: 'argumenten samenvatten', fout: ['Debatargument'] },
      { t: 'Oogcontact', d: 'het aankijken van je publiek, versterkt de geloofwaardigheid', k: 'publiek aankijken', fout: ['Non-verbale communicatie'] },
      { t: 'Actief luisteren', d: 'meedenken en per punt kernwoorden noteren', k: 'kernwoorden noteren', fout: ['Register'] },
      { t: 'Register', d: 'de mate van formaliteit van je taalgebruik', k: 'mate van formaliteit', fout: ['Non-verbale communicatie'] },
    ],
    [
      { v: 'Wat zijn de drie onderdelen van een goede presentatiestructuur?', o: ['inleiding, kern en conclusie', 'titel, tekst en plaatje', 'begin, pauze en einde', 'vraag, antwoord en applaus'], c: 0, d: 2, uo: ['Klopt: inleiding, kern en conclusie.', 'Nee, dat is geen structuur.', 'Nee, dat is te vaag.', 'Nee, dat is geen opbouw.'], uh: 'Presentatie: inleiding, kern en conclusie.' },
      { v: 'Welk kenmerk van non-verbale communicatie heeft de meeste invloed op geloofwaardigheid?', o: ['oogcontact met het publiek', 'de kleur van je kleding', 'de lengte van je zinnen', 'het aantal slides'], c: 0, d: 2, uo: ['Klopt: oogcontact wekt vertrouwen.', 'Nee, dat is minder bepalend.', 'Nee, dat is verbaal.', 'Nee, dat is vormgeving.'], uh: 'Oogcontact: versterkt de geloofwaardigheid.' },
      { v: 'Wat zijn de kenmerken van een sterk debatargument?', o: ['een standpunt, een redenering en bewijs', 'alleen een mening', 'een grap en een plaatje', 'een lange zin'], c: 0, d: 3, uo: ['Klopt: standpunt, redenering en bewijs samen.', 'Nee, een mening alleen overtuigt niet.', 'Nee, dat is geen argument.', 'Nee, lengte is geen kracht.'], uh: 'Sterk argument: standpunt, redenering, bewijs.' },
      { v: 'Hoe noteer je bij het luisteren naar een lezing de hoofdpunten effectief?', o: ['signaalwoorden en kernwoorden per punt, geen hele zinnen', 'elke zin letterlijk opschrijven', 'alleen de titel', 'niets, gewoon luisteren'], c: 0, d: 2, uo: ['Klopt: kernwoorden vangen de hoofdzaken.', 'Nee, dat is niet vol te houden.', 'Nee, dat is te weinig.', 'Nee, noteren helpt het onthouden.'], uh: 'Luisteren: kernwoorden en signaalwoorden noteren.' },
      { v: 'Wanneer is een presentatie informatief en wanneer overtuigend?', o: ['informatief informeert neutraal, overtuigend zet aan tot een mening of actie', 'ze zijn hetzelfde', 'informatief overtuigt, overtuigend informeert', 'beide zijn altijd neutraal'], c: 0, d: 3, uo: ['Klopt: informeren tegenover aanzetten tot mening/actie.', 'Nee, ze verschillen.', 'Nee, dat is omgedraaid.', 'Nee, overtuigend is niet neutraal.'], uh: 'Informatief: neutraal; overtuigend: naar mening of actie.' },
      { v: 'Welke zinsbouw hoort bij een formeel register?', o: ['volledige zinnen, de u-vorm en geen afkortingen', 'straattaal en emoji', 'losse woorden', 'alleen uitroepen'], c: 0, d: 2, uo: ['Klopt: formeel is verzorgd en volledig.', 'Nee, dat is informeel.', 'Nee, dat is te los.', 'Nee, dat is geen nette taal.'], uh: 'Formeel register: volledige zinnen, u-vorm.' },
      { v: 'Wat is het doel van het slotpleidooi in een debat?', o: ['de sterkste argumenten samenvatten en de jury overtuigen', 'een nieuw onderwerp aansnijden', 'de tegenstander uitlachen', 'de tijd rekken'], c: 0, d: 3, uo: ['Klopt: je bundelt je sterkste punten en overtuigt.', 'Nee, dat hoort niet aan het eind.', 'Nee, dat is onbeleefd.', 'Nee, dat is geen doel.'], uh: 'Slotpleidooi: sterkste argumenten samenvatten.' },
      { v: 'Wat is non-verbale communicatie?', o: ['communicatie via houding, gebaren en oogcontact', 'de woorden die je kiest', 'de lengte van je zinnen', 'de titel van je presentatie'], c: 0, d: 2, uo: ['Klopt: lichaamstaal is non-verbaal.', 'Nee, woorden zijn verbaal.', 'Nee, dat is zinsbouw.', 'Nee, dat is een kop.'], uh: 'Non-verbaal: houding, gebaren, oogcontact.' },
      { v: 'Wat doe je bij actief luisteren?', o: ['meedenken en per punt kernwoorden noteren', 'wachten tot je aan de beurt bent', 'alleen knikken', 'meteen je mening geven'], c: 0, d: 2, uo: ['Klopt: je verwerkt actief wat de spreker zegt.', 'Nee, dat is passief.', 'Nee, dat is te weinig.', 'Nee, eerst luisteren.'], uh: 'Actief luisteren: meedenken en kern noteren.' },
      { v: 'Waarmee begint een goede presentatie?', o: ['met een inleiding die het onderwerp aankondigt', 'met de conclusie', 'met een pauze', 'met vragen uit het publiek'], c: 0, d: 2, uo: ['Klopt: de inleiding opent en trekt de aandacht.', 'Nee, dat komt aan het eind.', 'Nee, dat is geen opening.', 'Nee, dat komt meestal later.'], uh: 'Presentatie begint met de inleiding.' },
    ]),

  V('C', 'Schrijfvaardigheid',
    `In een <strong>betoog</strong> zet je een <strong>stelling</strong> neer, onderbouw je die met <strong>argumenten</strong> en een heldere <strong>redenering</strong>, en verbind je alles met <strong>signaalwoorden</strong>. Je vermijdt <strong>drogredenen</strong>, kiest het juiste <strong>register</strong> en sluit af met een sterke <strong>conclusie</strong>.`,
    [
      { h: '1. Opbouw van een betoog', p: [
        `De <strong>stelling</strong> (het standpunt) staat expliciet in de <strong>inleiding</strong>. Elke <strong>alinea</strong> heeft een <strong>kernzin</strong>; de <strong>redenering</strong> legt het verband tussen de kernzin en de stelling uit. De <strong>conclusie</strong> herhaalt het standpunt in andere woorden en benadrukt de kracht van de argumenten.`] },
      { h: '2. Signaalwoorden en valkuilen', p: [
        `<strong>Signaalwoorden</strong> markeren verbanden: "daardoor/waardoor" (gevolg), "echter" (tegenstelling), "want/omdat" (reden). Vermijd <strong>drogredenen</strong> zoals het beroep op de massa ("iedereen weet dat…"). In een <strong>formele brief</strong> aan een onbekende gebruik je de aanhef "Geachte heer/mevrouw,".`] },
    ],
    [
      { t: 'Stelling', d: 'het standpunt dat je in een betoog verdedigt', k: 'het verdedigde standpunt', fout: ['Redenering'] },
      { t: 'Redenering', d: 'de uitleg van het verband tussen de kernzin en de stelling', k: 'verklaart het verband', fout: ['Stelling'] },
      { t: 'Inleiding', d: 'het begin van de tekst, met de expliciete stelling', k: 'begin met de stelling', fout: ['Conclusie'] },
      { t: 'Kernzin', d: 'de zin met het hoofdpunt van een alinea', k: 'hoofdpunt van een alinea', fout: ['Alinea'] },
      { t: 'Signaalwoord', d: 'een woord dat het verband tussen zinnen aangeeft', k: 'geeft verband aan', fout: ['Redenering'] },
      { t: 'Drogreden', d: 'een argument dat schijnbaar geldig is maar niet klopt', k: 'schijnbaar geldig', fout: ['Argument'] },
      { t: 'Formele brief', d: 'een nette brief met de aanhef "Geachte heer/mevrouw,"', k: 'Geachte heer/mevrouw', fout: ['Register'] },
      { t: 'Conclusie', d: 'de afsluiting die het standpunt herhaalt en de argumenten benadrukt', k: 'herhaalt het standpunt', fout: ['Inleiding'] },
      { t: 'Alinea', d: 'een tekstdeel over één deelonderwerp', k: 'één deelonderwerp', fout: ['Kernzin'] },
      { t: 'Argument', d: 'een reden die de stelling onderbouwt', k: 'onderbouwt de stelling', fout: ['Drogreden'] },
    ],
    [
      { v: 'Welk signaalwoord geeft een oorzaak-gevolgrelatie aan?', o: ['daardoor / waardoor / als gevolg hiervan', 'echter', 'bijvoorbeeld', 'ten eerste'], c: 0, d: 2, uo: ['Klopt: deze woorden leiden een gevolg in.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een voorbeeld.', 'Nee, dat is een opsomming.'], uh: '"Daardoor/waardoor": oorzaak-gevolg.' },
      { v: 'Welk tekstonderdeel bevat de expliciete stelling in een betoog?', o: ['de inleiding', 'de conclusie', 'een voetnoot', 'de titel'], c: 0, d: 2, uo: ['Klopt: de stelling staat in de inleiding.', 'Nee, daar herhaal je haar.', 'Nee, dat is een terzijde.', 'Nee, de titel is niet de stelling.'], uh: 'Stelling: expliciet in de inleiding.' },
      { v: 'Welk element ontbreekt: "Scholen moeten mediawijsheid geven. Jongeren gebruiken veel sociale media."?', o: ['een redenering die het verband verklaart', 'een kernzin', 'een titel', 'een signaalwoord van tijd'], c: 0, d: 3, uo: ['Klopt: het verband tussen beide zinnen wordt niet uitgelegd.', 'Nee, de eerste zin is de kernzin.', 'Nee, een titel is geen alinea-element.', 'Nee, tijd is hier niet het probleem.'], uh: 'Zonder redenering ontbreekt het verband.' },
      { v: 'Wat is de juiste aanhef van een formele brief aan een onbekende persoon?', o: ['Geachte heer/mevrouw,', 'Hoi,', 'Beste vriend,', 'Hey!'], c: 0, d: 2, uo: ['Klopt: bij een onbekende gebruik je deze nette aanhef.', 'Nee, dat is te informeel.', 'Nee, je kent de persoon niet.', 'Nee, dat is veel te los.'], uh: 'Formele brief, onbekende: "Geachte heer/mevrouw,".' },
      { v: 'Welk deel van een betoogende alinea legt het verband tussen kernzin en stelling uit?', o: ['de redenering', 'de titel', 'het signaalwoord van tijd', 'de bijlage'], c: 0, d: 3, uo: ['Klopt: de redenering verbindt de kernzin met de stelling.', 'Nee, dat is de kop.', 'Nee, dat legt geen verband uit.', 'Nee, dat is een aanhangsel.'], uh: 'Redenering: verklaart het verband met de stelling.' },
      { v: 'Wat is de fout in: "Iedereen weet dat telefoons slecht zijn voor jongeren"?', o: ['een drogreden: het beroep op de massa', 'een spelfout', 'een te lange zin', 'een ontbrekende titel'], c: 0, d: 3, uo: ['Klopt: "iedereen weet" bewijst niets, het is een drogreden.', 'Nee, er is geen spelfout.', 'Nee, de lengte is niet het probleem.', 'Nee, dat is geen alinea-element.'], uh: 'Beroep op de massa: een drogreden.' },
      { v: 'Wat kenmerkt een sterke conclusie in een betoog?', o: ['het standpunt in andere woorden herhalen én de kracht van de argumenten benadrukken', 'een nieuw argument toevoegen', 'een grap maken', 'de tekst abrupt stoppen'], c: 0, d: 3, uo: ['Klopt: je bundelt en versterkt, zonder nieuw materiaal.', 'Nee, nieuwe argumenten horen in de kern.', 'Nee, dat verzwakt de conclusie.', 'Nee, dat is geen afronding.'], uh: 'Conclusie: standpunt herhalen en argumenten benadrukken.' },
      { v: 'Wat is een stelling?', o: ['het standpunt dat je verdedigt', 'een controleerbaar feit', 'een signaalwoord', 'een titel'], c: 0, d: 2, uo: ['Klopt: de stelling is je te verdedigen standpunt.', 'Nee, een feit is controleerbaar.', 'Nee, dat markeert een verband.', 'Nee, dat is de kop.'], uh: 'Stelling: het verdedigde standpunt.' },
      { v: 'Wat is een kernzin?', o: ['de zin met het hoofdpunt van een alinea', 'de langste zin', 'de laatste zin van de tekst', 'de titel'], c: 0, d: 2, uo: ['Klopt: de kernzin draagt het hoofdpunt.', 'Nee, lengte bepaalt het niet.', 'Nee, dat kan, maar hoeft niet.', 'Nee, dat is de kop.'], uh: 'Kernzin: hoofdpunt van een alinea.' },
      { v: 'Wat is een redenering in een betoog?', o: ['de onderbouwing die het verband tussen kernzin en stelling uitlegt', 'een willekeurige mening', 'een spelregel', 'een opsomming van feiten zonder verband'], c: 0, d: 2, uo: ['Klopt: de redenering legt het verband uit.', 'Nee, dat onderbouwt niets.', 'Nee, dat is geen tekstelement.', 'Nee, zonder verband is het geen redenering.'], uh: 'Redenering: onderbouwt het verband.' },
    ]),

  V('D', 'Samenvatten',
    `Bij <strong>samenvatten</strong> lees je eerst <strong>globaal</strong>, noteer je de <strong>kernzinnen</strong> en schrijf je in eigen woorden de kern op. Een goede samenvatting is <strong>volledig</strong> (alle hoofdpunten), <strong>coherent</strong> (heldere verbanden) en laat de <strong>stelling</strong> niet weg.`,
    [
      { h: '1. Aanpak', p: [
        `De eerste stap is <strong>globaal lezen</strong> om onderwerp, doel en tekstsoort te bepalen. Daarna noteer je de <strong>kernzinnen</strong> (het hoofdpunt van elke alinea, niet de <strong>details</strong>). De volgorde: globaal lezen → kernzinnen noteren → samenvatting schrijven → controleren.`] },
      { h: '2. Kwaliteit', p: [
        `<strong>Volledigheid</strong> betekent dat alle hoofd- en kernpunten aanwezig zijn. <strong>Coherentie</strong> beoordeelt of de onderlinge verbanden duidelijk zijn; gebruik signaalwoorden als "toch/echter" (tegenstelling) en "kortom/concluderend" (conclusie). Je mag de <strong>stelling</strong> van de auteur niet weglaten, want die draagt de hele tekst. Vermijd vage formuleringen als "de auteur vindt dit goed".`] },
    ],
    [
      { t: 'Samenvatten', d: 'de kern van een tekst in eigen woorden kort weergeven', k: 'kort en in eigen woorden', fout: ['Globaal lezen'] },
      { t: 'Globaal lezen', d: 'snel lezen om onderwerp, doel en tekstsoort te bepalen', k: 'snel lezen voor de kern', fout: ['Kernzin'] },
      { t: 'Kernzin', d: 'de zin met het hoofdpunt van een alinea', k: 'hoofdpunt van een alinea', fout: ['Detail'] },
      { t: 'Coherentie', d: 'de duidelijkheid van de onderlinge verbanden', k: 'duidelijke verbanden', fout: ['Volledigheid'] },
      { t: 'Volledigheid', d: 'dat alle hoofd- en kernpunten aanwezig zijn', k: 'alle hoofdpunten aanwezig', fout: ['Coherentie'] },
      { t: 'Detail', d: 'een bijzaak die een hoofdpunt verduidelijkt of illustreert', k: 'illustreert een hoofdpunt', fout: ['Kernzin'] },
      { t: 'Stelling', d: 'het centrale standpunt dat de hele tekst draagt', k: 'centrale standpunt', fout: ['Detail'] },
      { t: 'Signaalwoord', d: 'een woord dat het verband tussen zinnen aangeeft', k: 'geeft verband aan', fout: ['Coherentie'] },
      { t: 'Hoofdpunt', d: 'een belangrijk punt dat in de samenvatting moet staan', k: 'belangrijk punt', fout: ['Detail'] },
      { t: 'Objectiviteit', d: 'zonder eigen mening, trouw aan de brontekst samenvatten', k: 'zonder eigen mening', fout: ['Volledigheid'] },
    ],
    [
      { v: 'Wat is de eerste stap bij het samenvatten van een tekst?', o: ['globaal lezen om onderwerp, doel en tekstsoort te bepalen', 'meteen de eerste zin overschrijven', 'de conclusie gokken', 'de tekst inkorten zonder te lezen'], c: 0, d: 2, uo: ['Klopt: eerst overzicht, dan pas samenvatten.', 'Nee, dat is te vroeg.', 'Nee, je moet eerst lezen.', 'Nee, lezen is noodzakelijk.'], uh: 'Samenvatten begint met globaal lezen.' },
      { v: 'Welk signaalwoord geeft in een samenvatting een tegenstelling aan?', o: ['toch / echter', 'daardoor', 'kortom', 'bijvoorbeeld'], c: 0, d: 2, uo: ['Klopt: "toch/echter" markeert een tegenstelling.', 'Nee, dat is een gevolg.', 'Nee, dat is een conclusie.', 'Nee, dat is een voorbeeld.'], uh: '"Toch/echter": tegenstelling.' },
      { v: 'Wat is het probleem met de zin "De auteur vindt dit een goed idee"?', o: ['de formulering is vaag: welk idee, en met welke reden?', 'de zin is te lang', 'er staat een spelfout in', 'de zin is te formeel'], c: 0, d: 3, uo: ['Klopt: "dit" en "goed" zijn te vaag om de kern weer te geven.', 'Nee, de zin is juist kort.', 'Nee, er is geen spelfout.', 'Nee, register is niet het probleem.'], uh: 'Vermijd vage formuleringen in een samenvatting.' },
      { v: 'Welk criterium beoordeelt of de onderlinge verbanden in een samenvatting duidelijk zijn?', o: ['coherentie', 'volledigheid', 'spelling', 'lengte'], c: 0, d: 3, uo: ['Klopt: coherentie gaat over de samenhang.', 'Nee, dat gaat over of alles erin staat.', 'Nee, dat is een schrijfregel.', 'Nee, lengte is geen samenhang.'], uh: 'Coherentie: duidelijke verbanden.' },
      { v: 'Wat is het verschil tussen een kernzin en een detail in een alinea?', o: ['de kernzin bevat het hoofdpunt, het detail verduidelijkt of illustreert dat', 'ze zijn hetzelfde', 'het detail is het hoofdpunt', 'de kernzin is altijd de laatste zin'], c: 0, d: 3, uo: ['Klopt: hoofdpunt tegenover illustratie.', 'Nee, ze verschillen.', 'Nee, dat is omgedraaid.', 'Nee, dat hoeft niet.'], uh: 'Kernzin: hoofdpunt; detail: illustratie.' },
      { v: 'Welk signaalwoord kondigt in een samenvatting een conclusie aan?', o: ['kortom / concluderend / dus', 'echter', 'ten eerste', 'bijvoorbeeld'], c: 0, d: 2, uo: ['Klopt: deze woorden leiden een conclusie in.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een opsomming.', 'Nee, dat is een voorbeeld.'], uh: '"Kortom/dus": conclusie.' },
      { v: 'Waarom mag je in een samenvatting de stelling van de auteur niet weglaten?', o: ['omdat de stelling het centrale standpunt is dat de hele tekst draagt', 'omdat de stelling altijd het langst is', 'omdat het verboden is', 'omdat de stelling grappig is'], c: 0, d: 3, uo: ['Klopt: zonder de stelling mis je de kern.', 'Nee, lengte doet er niet toe.', 'Nee, dat is geen reden.', 'Nee, dat is niet ter zake.'], uh: 'De stelling draagt de tekst, dus laat haar niet weg.' },
      { v: 'Wat betekent volledigheid bij het beoordelen van een samenvatting?', o: ['alle hoofd- en kernpunten van de originele tekst zijn aanwezig', 'de samenvatting is even lang als het origineel', 'er staan geen spelfouten in', 'de zinnen zijn kort'], c: 0, d: 3, uo: ['Klopt: geen belangrijk punt ontbreekt.', 'Nee, een samenvatting is juist korter.', 'Nee, dat is spelling.', 'Nee, zinslengte is geen maat.'], uh: 'Volledigheid: alle hoofdpunten aanwezig.' },
      { v: 'Welke volgorde is correct bij het schrijven van een samenvatting?', o: ['globaal lezen → kernzinnen noteren → schrijven → controleren', 'meteen schrijven → lezen → weggooien', 'controleren → lezen → schrijven', 'alleen de conclusie overschrijven'], c: 0, d: 2, uo: ['Klopt: dat is de logische volgorde.', 'Nee, dat is de omgekeerde volgorde.', 'Nee, dat klopt niet.', 'Nee, dat is te weinig.'], uh: 'Volgorde: lezen, kernzinnen, schrijven, controleren.' },
      { v: 'Wat is globaal lezen?', o: ['snel lezen om onderwerp, doel en tekstsoort te bepalen', 'elk woord nauwkeurig lezen', 'alleen de titel lezen', 'de tekst overschrijven'], c: 0, d: 2, uo: ['Klopt: globaal lezen geeft snel overzicht.', 'Nee, dat is nauwkeurig lezen.', 'Nee, de titel alleen is te weinig.', 'Nee, dat is kopiëren.'], uh: 'Globaal lezen: snel voor onderwerp, doel en tekstsoort.' },
    ]),

  V('E', 'Argumentatieve vaardigheden',
    `Je analyseert <strong>argumentatie</strong>: het <strong>standpunt</strong>, de <strong>argumenten</strong> en de <strong>structuur</strong> (meervoudig of onderschikkend). Je onderscheidt een <strong>feitelijk</strong> van een <strong>waarderend</strong> argument, herkent <strong>argumentatieschema's</strong> zoals het <strong>autoriteitsschema</strong>, en spoort <strong>drogredenen</strong> op.`,
    [
      { h: '1. Structuur en soorten', p: [
        `Bij een <strong>meervoudige</strong> argumentatie steunen losse argumenten elk apart het standpunt; bij een <strong>onderschikkende</strong> structuur vormen ze een keten (het ene ondersteunt het volgende). Een <strong>feitelijk</strong> argument is controleerbaar, een <strong>waarderend</strong> argument berust op normen en waarden. Het <strong>autoriteitsschema</strong> gebruikt een deskundige als onderbouwing.`] },
      { h: '2. Drogredenen', p: [
        `Een <strong>drogreden</strong> lijkt geldig maar klopt niet. Voorbeelden: het <strong>vals dilemma</strong> (maar twee opties terwijl er meer zijn) en de <strong>cirkelredenering</strong> (het standpunt bewijst zichzelf: "mijn voorstel is goed omdat het goed is"). Signaalwoorden als "want/omdat/immers" wijzen op een argument.`] },
    ],
    [
      { t: 'Vals dilemma', d: 'de drogreden die maar twee opties toont terwijl er meer zijn', k: 'maar twee opties', fout: ['Cirkelredenering'] },
      { t: 'Feitelijk argument', d: 'een controleerbaar argument', k: 'controleerbaar', fout: ['Waarderend argument'] },
      { t: 'Waarderend argument', d: 'een argument dat op normen en waarden berust', k: 'op normen en waarden', fout: ['Feitelijk argument'] },
      { t: 'Onderschikkende argumentatie', d: 'argumenten vormen een keten: het ene ondersteunt het volgende', k: 'keten van argumenten', fout: ['Meervoudige argumentatie'] },
      { t: 'Meervoudige argumentatie', d: 'meerdere losse argumenten steunen elk apart het standpunt', k: 'losse argumenten', fout: ['Onderschikkende argumentatie'] },
      { t: 'Autoriteitsschema', d: 'een deskundige gebruiken als onderbouwing van een standpunt', k: 'deskundige als bewijs', fout: ['Cirkelredenering'] },
      { t: 'Cirkelredenering', d: 'de drogreden waarbij het standpunt zichzelf bewijst', k: 'bewijst zichzelf', fout: ['Vals dilemma'] },
      { t: 'Drogreden', d: 'een argument dat schijnbaar geldig is maar niet klopt', k: 'schijnbaar geldig', fout: ['Argument'] },
      { t: 'Standpunt', d: 'de mening die met argumenten wordt verdedigd', k: 'de verdedigde mening', fout: ['Argument'] },
      { t: 'Argument', d: 'een reden die het standpunt ondersteunt', k: 'ondersteunt het standpunt', fout: ['Standpunt'] },
    ],
    [
      { v: 'Wat is een vals dilemma?', o: ['slechts twee opties presenteren terwijl er meer mogelijk zijn', 'de persoon aanvallen', 'iets met zichzelf bewijzen', 'een deskundige aanhalen'], c: 0, d: 2, uo: ['Klopt: een vals dilemma verzwijgt de andere opties.', 'Nee, dat is een persoonlijke aanval.', 'Nee, dat is een cirkelredenering.', 'Nee, dat is het autoriteitsschema.'], uh: 'Vals dilemma: maar twee opties.' },
      { v: 'Wat is het verschil tussen een feitelijk en een waarderend argument?', o: ['feitelijk is controleerbaar, waarderend berust op normen en waarden', 'ze zijn hetzelfde', 'feitelijk berust op waarden', 'waarderend is controleerbaar'], c: 0, d: 3, uo: ['Klopt: controleerbaar tegenover op waarden gebaseerd.', 'Nee, ze verschillen.', 'Nee, dat is omgedraaid.', 'Nee, dat is omgedraaid.'], uh: 'Feitelijk: controleerbaar; waarderend: op waarden.' },
      { v: 'Welk signaalwoord wijst op een argument dat een standpunt ondersteunt?', o: ['want / omdat / immers', 'echter', 'ten eerste', 'bijvoorbeeld'], c: 0, d: 2, uo: ['Klopt: deze woorden leiden een reden in.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een opsomming.', 'Nee, dat is een voorbeeld.'], uh: '"Want/omdat/immers": een argument.' },
      { v: 'Wat kenmerkt een onderschikkende argumentatiestructuur?', o: ['de argumenten vormen een keten: het ene ondersteunt het volgende', 'losse argumenten steunen elk apart', 'er is maar één argument', 'er zijn geen argumenten'], c: 0, d: 3, uo: ['Klopt: de argumenten hangen als een ketting samen.', 'Nee, dat is meervoudig.', 'Nee, dat is enkelvoudig.', 'Nee, er zijn juist argumenten.'], uh: 'Onderschikkend: een keten van argumenten.' },
      { v: 'Welk argumentatieschema gebruik je bij "Artsen adviseren dit medicijn, dus het werkt"?', o: ['het autoriteitsschema', 'het vals dilemma', 'de cirkelredenering', 'de persoonlijke aanval'], c: 0, d: 3, uo: ['Klopt: een deskundige dient als onderbouwing.', 'Nee, er zijn geen twee opties.', 'Nee, het bewijst zichzelf niet.', 'Nee, er wordt niemand aangevallen.'], uh: 'Deskundige als bewijs: autoriteitsschema.' },
      { v: '"Je bent óf vóór strengere klimaatwetten, óf je wil de planeet vernietigen." Welke drogreden?', o: ['een vals dilemma', 'een cirkelredenering', 'het autoriteitsschema', 'een feitelijk argument'], c: 0, d: 3, uo: ['Klopt: er zijn meer standpunten dan deze twee.', 'Nee, het bewijst zichzelf niet.', 'Nee, er is geen deskundige.', 'Nee, dit is een drogreden.'], uh: 'Maar twee opties: vals dilemma.' },
      { v: 'Wat is een meervoudige argumentatiestructuur?', o: ['meerdere losse argumenten steunen elk apart het standpunt', 'de argumenten vormen een keten', 'er is maar één argument', 'het standpunt bewijst zichzelf'], c: 0, d: 3, uo: ['Klopt: elk argument staat op zichzelf.', 'Nee, dat is onderschikkend.', 'Nee, dat is enkelvoudig.', 'Nee, dat is een cirkelredenering.'], uh: 'Meervoudig: losse argumenten, elk apart.' },
      { v: '"Mijn voorstel is goed omdat het een goed voorstel is." Welke drogreden is dit?', o: ['een cirkelredenering', 'een vals dilemma', 'het autoriteitsschema', 'een persoonlijke aanval'], c: 0, d: 3, uo: ['Klopt: het standpunt bewijst zichzelf.', 'Nee, er zijn geen twee opties.', 'Nee, er is geen deskundige.', 'Nee, er wordt niemand aangevallen.'], uh: 'Bewijst zichzelf: cirkelredenering.' },
      { v: 'Wat is een drogreden?', o: ['een argument dat schijnbaar geldig is maar niet klopt', 'een sterk onderbouwd argument', 'een controleerbaar feit', 'een kernzin'], c: 0, d: 2, uo: ['Klopt: een drogreden lijkt te kloppen maar is onjuist.', 'Nee, dat is juist een goed argument.', 'Nee, een feit is controleerbaar.', 'Nee, dat is een tekstbegrip.'], uh: 'Drogreden: schijnbaar geldig, maar onjuist.' },
      { v: 'Wat is een standpunt?', o: ['de mening die met argumenten wordt verdedigd', 'een controleerbaar feit', 'een signaalwoord', 'een terugblik'], c: 0, d: 1, uo: ['Klopt: het standpunt is de te verdedigen mening.', 'Nee, een feit is controleerbaar.', 'Nee, dat markeert een verband.', 'Nee, dat is een verteltechniek.'], uh: 'Standpunt: de verdedigde mening.' },
    ]),

  V('F', 'Literatuur',
    `Bij literatuur herken je het <strong>vertelstandpunt</strong> (ik-verteller, focalisatie) en verteltechnieken als de <strong>analepse</strong>. Je kent <strong>stijlfiguren</strong> als de <strong>vergelijking</strong>, structuurbegrippen als het <strong>motief</strong> en <strong>stromingen</strong> als het <strong>realisme</strong>, <strong>naturalisme</strong> en <strong>modernisme</strong>.`,
    [
      { h: '1. Vertellen en structuur', p: [
        `De <strong>ik-verteller</strong> vertelt in de eerste persoon met een begrensd perspectief. <strong>Focalisatie</strong> beschrijft door wiens ogen de wereld wordt waargenomen. Een <strong>analepse</strong> is een terugblik (flashback). Een <strong>motief</strong> is een concreet terugkerend element dat het abstracte thema ondersteunt.`] },
      { h: '2. Stijl en stromingen', p: [
        `Een <strong>vergelijking</strong> koppelt twee zaken met "als" of "zoals". Het <strong>realisme</strong> geeft sociale misstanden objectief weer; het <strong>naturalisme</strong> ziet de mens als bepaald door milieu en erfelijkheid (determinisme). Het <strong>modernisme</strong> experimenteert met de <strong>stream of consciousness</strong>. Een <strong>bildungsroman</strong> volgt de innerlijke ontwikkeling van een opgroeiende hoofdpersoon.`] },
    ],
    [
      { t: 'Ik-verteller', d: 'een verteller in de eerste persoon met een begrensd perspectief', k: 'vertelt in de ik-vorm', fout: ['Focalisatie'] },
      { t: 'Focalisatie', d: 'door wiens ogen de wereld van het verhaal wordt waargenomen', k: 'door wiens ogen', fout: ['Ik-verteller'] },
      { t: 'Motief', d: 'een concreet terugkerend element dat het thema ondersteunt', k: 'terugkerend element', fout: ['Analepse'] },
      { t: 'Analepse', d: 'een terugblik naar een eerder moment in het verhaal', k: 'terugblik/flashback', fout: ['Motief'] },
      { t: 'Modernisme', d: 'een stroming die experimenteert met de stream of consciousness', k: 'stream of consciousness', fout: ['Realisme'] },
      { t: 'Realisme', d: 'een stroming die sociale misstanden objectief weergeeft', k: 'objectieve weergave', fout: ['Naturalisme'] },
      { t: 'Naturalisme', d: 'een stroming die de mens als bepaald door milieu en erfelijkheid ziet', k: 'determinisme', fout: ['Realisme'] },
      { t: 'Bildungsroman', d: 'een roman over de innerlijke ontwikkeling van een opgroeiende held', k: 'opgroeiroman', fout: ['Motief'] },
      { t: 'Vergelijking', d: 'een stijlfiguur die twee zaken koppelt met "als" of "zoals"', k: 'met "als" of "zoals"', fout: ['Motief'] },
      { t: 'Thema', d: 'de centrale gedachte of boodschap van een werk', k: 'centrale gedachte', fout: ['Motief'] },
    ],
    [
      { v: 'Welk vertelstandpunt gebruikt de eerste persoon met een begrensd perspectief?', o: ['de ik-verteller', 'de alwetende verteller', 'de hij-verteller', 'de personale verteller'], c: 0, d: 3, uo: ['Klopt: de ik-verteller ziet alleen zijn eigen ervaringen.', 'Nee, die weet juist alles.', 'Nee, die staat buiten het verhaal.', 'Nee, dat is een ander standpunt.'], uh: 'Ik-verteller: eerste persoon, begrensd perspectief.' },
      { v: 'Welke literaire stroming kenmerkt zich door de stream of consciousness?', o: ['het modernisme', 'het realisme', 'het naturalisme', 'de romantiek'], c: 0, d: 3, uo: ['Klopt: het modernisme geeft de gedachtestroom direct weer.', 'Nee, dat geeft de werkelijkheid objectief weer.', 'Nee, dat draait om determinisme.', 'Nee, dat is een oudere stroming.'], uh: 'Modernisme: stream of consciousness.' },
      { v: 'Welk begrip verwijst naar een concreet terugkerend element dat het thema ondersteunt?', o: ['het motief', 'het thema', 'de analepse', 'de focalisatie'], c: 0, d: 3, uo: ['Klopt: een motief keert terug en verwijst naar het abstracte thema.', 'Nee, dat is de centrale gedachte zelf.', 'Nee, dat is een terugblik.', 'Nee, dat is het gezichtspunt.'], uh: 'Motief: terugkerend concreet element.' },
      { v: 'Welke stroming (19e eeuw) richtte zich op een objectieve weergave van sociale misstanden?', o: ['het realisme', 'het modernisme', 'de romantiek', 'het postmodernisme'], c: 0, d: 3, uo: ['Klopt: het realisme toont de werkelijkheid zoals ze is.', 'Nee, dat is 20e-eeuws en experimenteel.', 'Nee, dat draait om gevoel.', 'Nee, dat is later en speelt met fictie.'], uh: 'Realisme: objectieve weergave van misstanden.' },
      { v: 'Welk begrip beschrijft door wiens ogen de wereld van het verhaal wordt waargenomen?', o: ['de focalisatie', 'het motief', 'de analepse', 'het thema'], c: 0, d: 3, uo: ['Klopt: focalisatie is het waarnemingspunt.', 'Nee, dat is een terugkerend element.', 'Nee, dat is een terugblik.', 'Nee, dat is de kerngedachte.'], uh: 'Focalisatie: door wiens ogen verteld wordt.' },
      { v: 'Welk begrip beschrijft een terugblik naar een eerder moment in het verhaal?', o: ['de analepse (flashback)', 'de prolepse', 'het motief', 'de climax'], c: 0, d: 2, uo: ['Klopt: een analepse is een terugblik.', 'Nee, dat is een vooruitblik.', 'Nee, dat is een terugkerend element.', 'Nee, dat is het spanningshoogtepunt.'], uh: 'Analepse: terugblik/flashback.' },
      { v: 'Welk stijlfiguur vergelijkt twee zaken met het woord "als" of "zoals"?', o: ['de vergelijking', 'de metafoor', 'het motief', 'de analepse'], c: 0, d: 2, uo: ['Klopt: een vergelijking gebruikt "als" of "zoals".', 'Nee, die vergelijkt juist zonder die woorden.', 'Nee, dat is een terugkerend element.', 'Nee, dat is een terugblik.'], uh: 'Vergelijking: met "als" of "zoals".' },
      { v: 'Wat kenmerkt de naturalistische roman ten opzichte van het realisme?', o: ['de mens wordt volledig bepaald door milieu en erfelijkheid (determinisme)', 'de mens is volledig vrij', 'er komt geen werkelijkheid in voor', 'het speelt in de toekomst'], c: 0, d: 3, uo: ['Klopt: het naturalisme voegt determinisme toe.', 'Nee, juist het tegenovergestelde.', 'Nee, ook het naturalisme is realistisch.', 'Nee, dat is niet het kenmerk.'], uh: 'Naturalisme: mens bepaald door milieu en erfelijkheid.' },
      { v: 'Welk begrip beschrijft een verhaal waarin de hoofdpersoon opgroeit tot volwassenheid?', o: ['de bildungsroman', 'de detective', 'de sciencefiction', 'de satire'], c: 0, d: 3, uo: ['Klopt: een bildungsroman volgt de innerlijke ontwikkeling.', 'Nee, dat draait om een misdaad.', 'Nee, dat draait om toekomst en techniek.', 'Nee, dat bespot misstanden.'], uh: 'Bildungsroman: opgroeiroman.' },
      { v: 'Wat is het thema van een literair werk?', o: ['de centrale gedachte of boodschap', 'de eerste zin', 'de naam van de hoofdpersoon', 'het aantal hoofdstukken'], c: 0, d: 2, uo: ['Klopt: het thema is de kerngedachte.', 'Nee, dat is de opening.', 'Nee, dat is een personage.', 'Nee, dat is de omvang.'], uh: 'Thema: de centrale gedachte.' },
      { v: 'Wat is een metafoor?', o: ['een beeldspraak die twee zaken direct gelijkstelt, zonder "als"', 'een vergelijking met "als" of "zoals"', 'een terugblik in het verhaal', 'een terugkerend element'], c: 0, d: 2, uo: ['Klopt: een metafoor vergelijkt direct, zonder "als".', 'Nee, dat is een vergelijking.', 'Nee, dat is een analepse.', 'Nee, dat is een motief.'], uh: 'Metafoor: directe beeldspraak, zonder "als".' },
    ]),
];
