// HAVO Scheikunde - situaties per begrip.
export default {
  A: {
    'Onafhankelijke variabele': ['De concentratie die je zelf per proef instelt', 'De grootheid die je bewust verandert'],
    'Afhankelijke variabele': ['De reactiesnelheid die je als resultaat meet', 'De grootheid die je meet als reactie'],
    'Controle-experiment': ['Een proef zonder de testvariabele, als vergelijking', 'Een referentie zonder de testvariabele'],
    Hypothese: ['Je verwacht: als de temperatuur stijgt, dan gaat de reactie sneller', 'Een toetsbare verwachting vooraf'],
    'GHS-pictogram': ['Een vlamsymbool op het etiket waarschuwt voor brandgevaar', 'Een gevaarsymbool op een chemicaliën-etiket'],
    'Lineair verband': ['Een rechte lijn door de oorsprong: y is evenredig met x', 'Een recht evenredig verband'],
    Molariteit: ['De concentratie in mol opgeloste stof per liter', 'De concentratie in mol per liter'],
    'Significante cijfers': ['Het getal 0,0340 heeft drie betekenisvolle cijfers', 'De cijfers die de nauwkeurigheid aangeven'],
    Betrouwbaarheid: ['Herhaal je de meting, dan krijg je dezelfde uitkomst', 'De herhaalbaarheid van een meting'],
    Verdunnen: ['Je voegt water toe om de concentratie te verlagen', 'De concentratie verlagen met water'],
  },
  B: {
    Ionbinding: ['Een metaal geeft elektronen aan een niet-metaal, er ontstaan ionen', 'De binding tussen metaal- en niet-metaalionen'],
    'Covalente binding': ['Twee niet-metalen delen elektronen, zoals in H2', 'Een binding waarbij atomen elektronen delen'],
    Waterstofbrug: ['Tussen de OH-groepen van water werkt een sterke aantrekking', 'De sterke kracht tussen H en N, O of F'],
    'Van der Waalskrachten': ['Tussen apolaire moleculen werken zwakke, tijdelijke krachten', 'Zwakke krachten tussen moleculen'],
    'Polair molecuul': ['Water heeft een plus- en een minkant: een netto dipool', 'Een molecuul met een netto-dipoolmoment'],
    'Apolair molecuul': ['CO2 is lineair, de dipolen heffen elkaar op', 'Een molecuul zonder netto-dipoolmoment'],
    'Valentie-elektronen': ['De buitenste elektronen die het chemisch gedrag bepalen', 'De elektronen in de buitenste schil'],
    'Periodiek systeem': ['De ordening van de elementen op atoomnummer en groep', 'De tabel die de elementen ordent'],
    'Elektronegativiteit': ['De mate waarin een atoom elektronen naar zich toe trekt', 'De aantrekkingskracht op bindingselektronen'],
    Roosterenergie: ['De energie die vrijkomt als gasionen een ionrooster vormen', 'De energie van roostervorming'],
  },
  C: {
    'Le Chatelier-principe': ['Verstoor je een evenwicht, dan verschuift het om dat te compenseren', 'Een verstoord evenwicht compenseert de verstoring'],
    'Chemisch evenwicht': ['De heen- en terugreactie lopen even snel door', 'De toestand waarin beide reacties even snel zijn'],
    Katalysator: ['Een stof versnelt de reactie zonder zelf te worden verbruikt', 'Een stof die een reactie versnelt zonder verbruik'],
    'Zwak zuur': ['Azijnzuur splitst maar deels in water', 'Een zuur dat maar gedeeltelijk dissocieert'],
    'Sterk zuur': ['Zoutzuur splitst volledig in water', 'Een zuur dat volledig dissocieert'],
    Oxidatie: ['Een atoom staat elektronen af en het oxidatiegetal stijgt', 'Het afstaan van elektronen'],
    Reductie: ['Een atoom neemt elektronen op en het oxidatiegetal daalt', 'Het opnemen van elektronen'],
    Stoichiometrie: ['In N2 plus 3H2 reageert 1 mol met 3 mol tot 2 mol NH3', 'De molverhoudingen in een reactie'],
    Amfoteer: ['Water kan als zuur én als base reageren', 'Een stof die zuur én base kan zijn'],
    pH: ['Een lage pH betekent een zure oplossing', 'Een maat voor de zuurgraad'],
  },
  D: {
    Esterificatie: ['Een carbonzuur en een alcohol vormen samen een ester en water', 'De reactie van carbonzuur en alcohol tot een ester'],
    'Condensatiepolymerisatie': ['Bij het koppelen komt telkens water vrij, zoals bij nylon', 'Polymerisatie met een bijproduct'],
    'Additiepolymerisatie': ['De monomeren koppelen zonder dat er een bijproduct vrijkomt', 'Polymerisatie zonder bijproduct'],
    Hydroxylgroep: ['De OH-groep die een alcohol kenmerkt', 'De −OH-groep'],
    Carboxylgroep: ['De COOH-groep die een carbonzuur kenmerkt', 'De −COOH-groep'],
    Alkaan: ['Methaan en butaan zijn verzadigde koolwaterstoffen', 'Een verzadigde koolwaterstof'],
    Substitutie: ['Onder UV vervangt chloor een waterstofatoom in een alkaan', 'Een reactie waarbij een atoom wordt vervangen'],
    Verbranding: ['Methaan reageert met zuurstof tot CO2 en water', 'De reactie van een stof met zuurstof'],
    'Homologe reeks': ['Methaan, ethaan en propaan verschillen telkens een CH2-groep', 'Een reeks met een vaste stap'],
    'Functionele groep': ['De atoomgroep die de eigenschappen van een stof bepaalt', 'De groep die de reacties bepaalt'],
  },
  E: {
    'Haber-Bosch-proces': ['Uit stikstof en waterstof wordt onder hoge druk ammoniak gemaakt', 'Het proces dat ammoniak maakt'],
    Thermoplast: ['Deze kunststof wordt zacht bij verhitting en is recyclebaar', 'Een kunststof die smelt bij verhitting'],
    Thermoharder: ['Deze kunststof is vernetwerkt en kan niet meer smelten', 'Een niet-smeltbare kunststof'],
    Emulgator: ['Met een water- én vetminnend deel houdt hij water en vet gemengd', 'Een stof die water en vet mengt'],
    Atoomeconomie: ['Hoeveel van de gevormde stof echt nuttig product is', 'Het aandeel nuttig product'],
    Ozonlaag: ['De laag in de stratosfeer die schadelijke UV-straling tegenhoudt', 'De laag die UV-straling absorbeert'],
    Broeikaseffect: ['Gassen houden warmte vast en de aarde warmt op', 'Het vasthouden van warmte door gassen'],
    'Zure regen': ['Zwaveldioxide en stikstofoxiden maken de regen zuur', 'Zure neerslag door SO2 en NOx'],
    PLA: ['Een composteerbaar bioplastic gemaakt van bijvoorbeeld maïs', 'Een bioplastic uit hernieuwbare grondstoffen'],
    Osmose: ['Zout onttrekt water aan bacteriën, die daardoor uitdrogen', 'De verplaatsing van water door een membraan'],
  },
};
