// HAVO Economie - situaties per begrip.
export default {
  B: {
    Schaarste: ['Er is minder van iets dan mensen willen hebben, dus je moet kiezen', 'Behoeften groter dan de beschikbare middelen'],
    Opportuniteitskosten: ['Kies je voor studeren, dan mis je het loon van werken', 'De waarde van het beste alternatief dat je opgeeft'],
    Productiefactoren: ['Arbeid, natuur, kapitaal en ondernemerschap samen maken productie mogelijk', 'De vier bronnen waarmee je produceert'],
    BBP: ['De totale marktwaarde van alles wat een land in een jaar produceert', 'De totale productie van een land per jaar'],
    'BBP per hoofd': ['Het BBP gedeeld door het aantal inwoners, om welvaart te vergelijken', 'Het BBP per inwoner'],
    'Marginale kosten': ['De extra kosten om één product meer te maken', 'De kosten van één eenheid extra'],
    Lek: ['Sparen en belasting halen geld uit de kringloop', 'Geld dat de economische kringloop verlaat'],
    Injectie: ['Investeringen en overheidsuitgaven pompen geld in de kringloop', 'Geld dat in de kringloop komt'],
    'Collectief goed': ['Iedereen profiteert van straatverlichting, niemand kun je uitsluiten', 'Een goed dat niet-uitsluitbaar en niet-rivaliserend is'],
    'Vrij goed': ['Lucht is er in overvloed en kost niets', 'Een goed dat niet schaars is en geen prijs heeft'],
  },
  C: {
    Evenwichtsprijs: ['De prijs waarbij de gevraagde en aangeboden hoeveelheid precies gelijk zijn', 'De prijs waar vraag en aanbod elkaar kruisen'],
    'Elastische vraag': ['Bij een luxeproduct daalt de vraag sterk als de prijs stijgt', 'Vraag die sterk reageert op de prijs'],
    'Inelastische vraag': ['Voor benzine blijft de vraag vrijwel gelijk, ook als de prijs stijgt', 'Vraag die nauwelijks op de prijs reageert'],
    'Extern effect': ['Fabrieksrook schaadt omwonenden die er niets mee te maken hebben', 'Kosten of baten die derden treffen buiten de prijs'],
    Oligopolie: ['Een paar grote supermarktketens houden elkaars prijzen in de gaten', 'Een markt met weinig grote aanbieders'],
    Maximumprijs: ['De overheid stelt een huurgrens onder de evenwichtsprijs in, met een tekort', 'Een prijsplafond dat een tekort veroorzaakt'],
    Minimumprijs: ['Een prijsbodem boven het evenwicht zorgt voor een overschot', 'Een prijsbodem die een overschot veroorzaakt'],
    Consumentensurplus: ['Je betaalt minder dan je maximaal had willen betalen', 'Het verschil tussen betalingsbereidheid en prijs'],
    Meritgoed: ['De overheid subsidieert cultuur en onderwijs omdat er te weinig van komt', 'Een goed dat de overheid stimuleert'],
    'Volkomen concurrentie': ['Op een groentemarkt verkopen veel kraampjes hetzelfde zonder prijsmacht', 'Een markt met veel kleine aanbieders'],
  },
  D: {
    Allocatiefunctie: ['De overheid legt wegen aan en zorgt voor defensie: collectieve goederen', 'De overheid levert wat de markt niet voortbrengt'],
    Herverdelingsfunctie: ['Via belasting en uitkeringen verkleint de overheid de inkomensverschillen', 'De overheid verkleint de inkomensongelijkheid'],
    Stabilisatiefunctie: ['In een recessie stimuleert de overheid, in een hausse remt ze af', 'De overheid dempt de conjunctuur'],
    'Directe belasting': ['Loonbelasting en winstbelasting zitten op inkomen en winst', 'Belasting op inkomen of winst'],
    'Indirecte belasting': ['Btw en accijns zitten op wat je koopt', 'Belasting op bestedingen'],
    'Progressief belastingstelsel': ['Wie meer verdient, betaalt een hoger belastingpercentage', 'Hoger inkomen, hoger percentage'],
    'Automatische stabilisatoren': ['In een recessie lopen de WW-uitgaven vanzelf op en dempen de klap', 'Mechanismen die de economie vanzelf dempen'],
    Begrotingstekort: ['De overheid geeft in een jaar meer uit dan ze binnenkrijgt', 'Uitgaven groter dan inkomsten in een jaar'],
    Staatsschuld: ['Alle tekorten van vroeger bij elkaar opgeteld', 'De som van alle historische tekorten'],
    'Sociale verzekering': ['De WW wordt uit premies van werkenden betaald', 'Sociale zekerheid uit premies'],
  },
  E: {
    'Conjuncturele werkloosheid': ['In een recessie ontslaan bedrijven personeel door te lage vraag', 'Tijdelijke werkloosheid door lage vraag'],
    'Structurele werkloosheid': ['Iemands vak verdwijnt en zijn vaardigheden passen niet meer', 'Werkloosheid door een mismatch'],
    Frictiewerkloosheid: ['Iemand is kort werkloos tussen twee banen in', 'Tijdelijke werkloosheid tussen twee banen'],
    Inflatie: ['De prijzen stijgen algemeen en je geld wordt minder waard', 'Een prijsstijging waardoor de koopkracht daalt'],
    Bestedingsinflatie: ['Er is te veel vraag: veel geld jaagt op weinig goederen', 'Inflatie door te veel vraag'],
    Kosteninflatie: ['Duurdere grondstoffen worden in de prijzen doorberekend', 'Inflatie door hogere productiekosten'],
    Conjunctuur: ['De economie beweegt op en neer rond de trend', 'De op- en neergang van de economie'],
    'Reëel BBP': ['Het BBP nadat je de prijsstijging eruit hebt gehaald', 'Het BBP gecorrigeerd voor inflatie'],
    CPI: ['De prijsindex van een vast boodschappenpakket', 'De prijsindex van een huishoudpakket'],
    Recessie: ['De economie krimpt twee kwartalen achter elkaar', 'Twee kwartalen economische krimp'],
  },
};
