// HAVO Maatschappijwetenschappen - situaties per begrip.
export default {
  A: {
    Triangulatie: ['Je combineert een enquête, interviews en observaties in één onderzoek', 'Meerdere methoden om de validiteit te verhogen'],
    'Deductief onderzoek': ['Je begint met een theorie en toetst of die klopt', 'Onderzoek dat een theorie toetst'],
    'Inductief onderzoek': ['Je verzamelt waarnemingen en bouwt er een theorie uit op', 'Onderzoek dat een theorie opbouwt'],
    'Diepte-interview': ['In een gesprek vraag je door om nuance te achterhalen', 'Een gesprek waarin je kunt doorvragen'],
    'Onafhankelijke variabele': ['De factor die je als oorzaak instelt of onderzoekt', 'De variabele die de oorzaak vormt'],
    'Afhankelijke variabele': ['Het effect dat je meet als resultaat', 'De variabele die het effect is'],
    'Open vraag': ['Je laat mensen in eigen woorden antwoorden', 'Een vraag met een eigen antwoord'],
    'Gesloten vraag': ['Je laat mensen kiezen uit vaste antwoordopties', 'Een vraag met vaste opties'],
    Generaliseerbaarheid: ['In hoeverre je uitkomst geldt voor de hele bevolking', 'De mate waarin resultaten voor de populatie gelden'],
    Validiteit: ['Je meet echt wat je bedoelt te meten', 'Of je meet wat je bedoelt'],
  },
  B: {
    Socialisatie: ['Via opvoeding, school en media neem je normen en waarden over', 'Het internaliseren van normen en waarden'],
    'Primaire socialisatie': ['In het gezin leert een klein kind de eerste normen', 'De socialisatie in het gezin in de vroege jeugd'],
    'Sociologische benadering': ['Je verklaart gedrag vanuit groepen en instituties', 'Gedrag verklaren vanuit de samenleving'],
    'Psychologische benadering': ['Je verklaart gedrag vanuit de persoon zelf', 'Gedrag verklaren vanuit het individu'],
    Macht: ['Iemand kan het gedrag van anderen bepalen, ook tegen hun wil', 'Het vermogen om gedrag van anderen te bepalen'],
    Bindingstheorie: ['Wie weinig binding heeft met de samenleving, komt eerder in de criminaliteit', 'Zwakke bindingen verlagen de drempel voor crimineel gedrag'],
    'Formele institutie': ['Een instituut dat in de wet is vastgelegd, zoals de rechtbank', 'Een wettelijk vastgelegde institutie'],
    'Informele institutie': ['Ongeschreven gewoonten en tradities die toch sturen', 'Een institutie op basis van gewoonte'],
    Norm: ['Een gedragsregel, zoals: je zegt netjes gedag', 'Een concrete gedragsregel'],
    Waarde: ['Een ideaal dat je nastreeft, zoals eerlijkheid', 'Een nastrevenswaardig ideaal'],
  },
  C: {
    'Sociaal grondrecht': ['De overheid moet zorgen voor onderwijs en huisvesting', 'Een grondrecht dat de overheid tot actie verplicht'],
    'Klassiek grondrecht': ['De overheid mag je vrijheid van meningsuiting niet inperken', 'Een vrijheidsrecht dat de overheid moet respecteren'],
    Populisme: ['Een beweging die de volkswil tegenover de elite plaatst', 'Een stroming die de volkswil centraal stelt'],
    Lobbyisme: ['Een bedrijf probeert een minister te beïnvloeden', 'Het beïnvloeden van besluitvorming door groepen'],
    'Actief kiesrecht': ['Je mag zelf gaan stemmen bij verkiezingen', 'Het recht om te stemmen'],
    'Passief kiesrecht': ['Je mag je verkiesbaar stellen als kandidaat', 'Het recht om verkiesbaar te zijn'],
    'Raad van State': ['Het hoogste adviesorgaan dat over wetgeving adviseert', 'Het adviesorgaan en de hoogste bestuursrechter'],
    'Recht van amendement': ['De Tweede Kamer past een wetsvoorstel aan', 'Het recht om wetsvoorstellen te wijzigen'],
    Agendering: ['Een probleem krijgt zoveel aandacht dat de politiek het oppakt', 'Problemen komen op de politieke agenda'],
    'Politieke besluitvorming': ['Het hele proces waarin de politiek tot een besluit komt', 'Het proces waarin de politiek besluit'],
  },
  D: {
    'Intergenerationele mobiliteit': ['Je vergelijkt je eigen positie met die van je ouders', 'De vergelijking met de positie van je ouders'],
    Straintheorie: ['Wie de doelen niet langs legale weg kan halen, kiest soms voor criminaliteit', 'Criminaliteit uit spanning tussen doelen en middelen'],
    'Pluriforme samenleving': ['Een land met veel culturen, religies en achtergronden', 'Een samenleving met grote diversiteit'],
    Integratie: ['Een nieuwkomer doet mee én behoudt zijn eigen cultuur', 'Meedoen met behoud van de eigen identiteit'],
    Meritocratie: ['Je komt vooruit door talent en inzet, niet door afkomst', 'Een samenleving waar prestatie de positie bepaalt'],
    Individualisering: ['Mensen komen losser te staan van kerk, buurt en familie', 'Mensen worden minder afhankelijk van vaste groepen'],
    'Sociale reproductie': ['Kinderen van hoogopgeleiden krijgen vaak weer meer kansen', 'De overdracht van ongelijkheid van ouder op kind'],
    'Sociale ongelijkheid': ['De ene groep heeft veel welvaart en macht, de andere weinig', 'De ongelijke verdeling van welvaart en kansen'],
    Segregatie: ['Groepen wonen en leven gescheiden van elkaar', 'Het gescheiden leven van groepen'],
    'Sociale cohesie': ['De mate waarin mensen zich met elkaar verbonden voelen', 'De samenhang in een samenleving'],
  },
};
