// HAVO Biologie - situaties per begrip.
export default {
  A: {
    'Onafhankelijke variabele': ['De hoeveelheid mest die je zelf per plantje varieert', 'De grootheid die je zelf instelt in de proef'],
    'Afhankelijke variabele': ['De hoogte van de plant die je aan het eind meet', 'De grootheid die je meet als resultaat'],
    Controlegroep: ['De planten die geen mest krijgen, als vergelijking', 'De groep zonder behandeling waarmee je vergelijkt'],
    Betrouwbaarheid: ['Meer metingen maken je resultaat hiervan beter', 'De mate waarin herhaling hetzelfde geeft'],
    Validiteit: ['Je meet echt de invloed van licht en niet iets anders', 'Of je meet wat je bedoelt te meten'],
    Replicatie: ['Je herhaalt de meting een aantal keer om toeval uit te middelen', 'Een herhaling van de meting'],
    Hypothese: ['Je gok van tevoren over de uitkomst van de proef', 'Een toetsbare verwachting vooraf'],
    Correlatie: ['Twee dingen veranderen samen, maar het een hoeft het ander niet te veroorzaken', 'Gelijktijdige verandering zonder bewijs van oorzaak'],
    Causaliteit: ['Een gecontroleerd experiment bewijst dat het een het ander veroorzaakt', 'Een bewezen oorzaak-gevolgrelatie'],
    'Storende variabele': ['Je vergeet de temperatuur constant te houden, wat de meting bederft', 'Een variabele die de meting verstoort'],
  },
  M: {
    'DNA-basenparen': ['Adenine paart met thymine en guanine met cytosine', 'De vaste paren in de DNA-streng'],
    Translatie: ['Op het ribosoom wordt mRNA vertaald naar een eiwit', 'De stap van mRNA naar een aminozuurketen'],
    Replicatie: ['Vóór een celdeling wordt het DNA verdubbeld', 'De verdubbeling van het DNA'],
    Fenotype: ['De oogkleur die je echt kunt zien', 'De waarneembare eigenschap van een organisme'],
    Genotype: ['De genen die iemand van zijn ouders kreeg', 'De genetische samenstelling'],
    Enzym: ['Een biologische katalysator die de activeringsenergie verlaagt', 'Een stof die een reactie versnelt'],
    Chloroplast: ['Het groene organel waarin de fotosynthese plaatsvindt', 'Het fotosynthese-organel in plantencellen'],
    'Mitochondriën': ['De energiecentrales met eigen DNA waar de celademhaling gebeurt', 'De organellen van de celademhaling'],
    Prokaryoot: ['Een bacterie zonder kernmembraan', 'Een cel zonder membraanomgeven kern'],
    Frameshiftmutatie: ['Eén nucleotide erbij verschuift het hele leesraam', 'Een mutatie die het leesraam verschuift'],
  },
  O: {
    Homeostase: ['Je lichaam houdt de temperatuur rond 37 graden, ongeacht buiten', 'Het constant houden van het interne milieu'],
    'Negatieve terugkoppeling': ['Stijgt de bloedsuiker, dan komt insuline vrij die hem weer verlaagt', 'Een afwijking wordt automatisch tegengewerkt'],
    Insuline: ['Na een maaltijd laat dit hormoon glucose de cellen in', 'Het hormoon dat de bloedsuiker verlaagt'],
    Glucagon: ['Bij honger breekt dit hormoon glycogeen in de lever af', 'Het hormoon dat de bloedsuiker verhoogt'],
    Alvleesklier: ['Dit orgaan maakt zowel insuline als glucagon', 'Het orgaan dat de bloedsuikerhormonen produceert'],
    Lever: ['Dit orgaan bewaart glycogeen als reservesuiker', 'Het orgaan dat glycogeen opslaat'],
    'Specifieke afweer': ['Na een ziekte onthoudt je afweer de ziekteverwekker', 'De gerichte afweer met immunologisch geheugen'],
    'Autonoom zenuwstelsel': ['Je hartslag en vertering gaan vanzelf, zonder dat je nadenkt', 'Het deel dat onbewuste functies regelt'],
    Longslagader: ['Dit vat brengt zuurstofarm bloed van het hart naar de longen', 'Het bloedvat naar de longen'],
    'Cytotoxische T-cel': ['Deze cel doodt lichaamscellen die door een virus zijn geïnfecteerd', 'De cel die geïnfecteerde cellen opruimt'],
  },
  P: {
    'Trofisch niveau': ['Elke schakel in de voedselketen geeft ongeveer tien procent door', 'Een schakel in de voedselketen'],
    'Natuurlijke selectie': ['De best aangepaste dieren krijgen meer nakomelingen', 'De best aangepaste individuen planten zich meer voort'],
    'Allopatrische speciatie': ['Een rivier splitst een populatie en er ontstaan twee soorten', 'Soortvorming door een geografische barrière'],
    'Hardy-Weinberg-evenwicht': ['Zonder selectie, mutatie of migratie blijven de allelfrequenties gelijk', 'Het geval zonder evolutie'],
    'Genetische drift': ['In een klein groepje verandert de kleurverdeling puur door toeval', 'Toevallige verandering van allelfrequenties'],
    Producent: ['Een plant maakt met licht zijn eigen voedsel', 'Een organisme dat organische stof aanmaakt'],
    'Primaire productie': ['De totale hoeveelheid suiker die planten per tijd aanmaken', 'De totale aanmaak door producenten'],
    Successie: ['Op kaal zand komen eerst mossen, dan grassen, dan bos', 'De geleidelijke opeenvolging naar een climaxstadium'],
    Niche: ['De rol van een soort: wat hij eet, waar hij leeft en wanneer hij actief is', 'De functionele rol van een soort'],
    'Bottleneck-effect': ['Na een ramp blijft een kleine groep met weinig variatie over', 'Een sterke krimp met verlies van variatie'],
  },
};
