// VMBO GL/TL - Aardrijkskunde. Gouden-stijl contentspec.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vmbo', vak: 'ak', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Weer en klimaat',
    `<strong>Weer</strong> is de toestand van de atmosfeer op een moment; <strong>klimaat</strong> is het gemiddelde weer over dertig jaar. Lucht stroomt van een <strong>hogedrukgebied</strong> naar een <strong>lagedrukgebied</strong>: dat is <strong>wind</strong>.`,
    [
      { h: '1. Weer en klimaat', p: [
        `<strong>Weer</strong> beschrijft de toestand van de lucht op één moment (nu regen, straks zon). <strong>Klimaat</strong> is het gemiddelde weer over een lange periode, meestal dertig jaar. Nederland heeft een <strong>zeeklimaat</strong>: milde winters en koele zomers door de invloed van de zee. Ver van zee heerst een <strong>landklimaat</strong> met koude winters en warme zomers.`] },
      { h: '2. Luchtdruk en wind', p: [
        `De <strong>luchtdruk</strong> is de druk die de lucht uitoefent. In een <strong>lagedrukgebied</strong> stijgt lucht op: vaak bewolkt en nat. In een <strong>hogedrukgebied</strong> daalt lucht: vaak droog en zonnig. Lucht stroomt van hoge naar lage druk, en die stroming is de <strong>wind</strong>. De <strong>wet van Buys Ballot</strong> beschrijft hoe de wind rond die gebieden draait.`,
        `Op een weerkaart verbindt een <strong>isobar</strong> punten met dezelfde luchtdruk, en een <strong>front</strong> is de grens tussen warme en koude lucht.`] },
      { h: '3. Een klimaatgrafiek lezen', p: [
        `Een <strong>klimaatgrafiek</strong> laat per maand de gemiddelde <strong>temperatuur</strong> (als lijn) en de <strong>neerslag</strong> (als staven) zien. Zo herken je bijvoorbeeld een natte winter en een droge zomer, of andersom.`] },
    ],
    [
      { t: 'Weer', d: 'de toestand van de atmosfeer op een bepaald moment', k: 'toestand van de lucht nu', fout: ['Klimaat'],
        vb: [{ s: 'Vanochtend scheen de zon, nu regent het en straks waait het hard', d: 1 }, 'Het waait, het is bewolkt en het is nu twaalf graden'] },
      { t: 'Klimaat', d: 'het gemiddelde weer over een lange periode van dertig jaar', k: 'gemiddeld weer, lange termijn', fout: ['Weer'],
        vb: [{ s: 'Over de laatste dertig jaar valt hier gemiddeld de meeste regen in de winter', d: 2 }, 'Dit gebied staat bekend om zijn droge, hete zomers en zachte winters'] },
      { t: 'Luchtdruk', d: 'de druk die de lucht op het aardoppervlak uitoefent', k: 'druk van de lucht', fout: ['Lagedrukgebied', 'Hogedrukgebied'],
        vb: [{ s: 'Een barometer meet hoe hard de lucht op de grond drukt', d: 2 }, 'Hoog in de bergen is de druk van de lucht lager dan aan zee'] },
      { t: 'Lagedrukgebied', d: 'een gebied met lage luchtdruk, vaak bewolkt en nat', k: 'lage druk, nat weer', fout: ['Hogedrukgebied'],
        vb: [{ s: 'Het is de hele dag grijs bewolkt en het regent flink door', d: 1 }, { s: 'De weerman verwacht opstijgende lucht en de hele middag buien', d: 3 }] },
      { t: 'Hogedrukgebied', d: 'een gebied met hoge luchtdruk, vaak droog en zonnig', k: 'hoge druk, droog weer', fout: ['Lagedrukgebied'],
        vb: [{ s: 'Het blijft droog en de zon schijnt de hele dag volop', d: 1 }, { s: 'De lucht daalt en er is nauwelijks een wolk te zien', d: 3 }] },
      { t: 'Wind', d: 'bewegende lucht van een hogedruk- naar een lagedrukgebied', k: 'bewegende lucht', fout: ['Luchtdruk'],
        vb: [{ s: 'Lucht stroomt van een gebied met hoge druk naar een gebied met lage druk', d: 2 }] },
      { t: 'Wet van Buys Ballot', d: 'de regel die de windrichting rond hoge- en lagedrukgebieden beschrijft', k: 'regel voor windrichting', fout: ['Isobar'],
        vb: [{ s: 'Een vaste regel voorspelt hoe de wind om hoge- en lagedrukgebieden heen draait', d: 3 }] },
      { t: 'Neerslag', d: 'water dat uit de lucht valt, zoals regen en sneeuw', k: 'regen en sneeuw', fout: ['Temperatuur', 'Verdamping'],
        vb: [{ s: 'Uit de wolken vallen eerst regendruppels en later natte sneeuw', d: 1 }, 'De regenmeter vangt al het water op dat uit de lucht is gevallen'] },
      { t: 'Temperatuur', d: 'de mate van warmte, gemeten in graden', k: 'hoe warm het is', fout: ['Neerslag'],
        vb: [{ s: 'De thermometer op het schoolplein wijst 19 graden aan', d: 1 }] },
      { t: 'Klimaatgrafiek', d: 'een grafiek met de gemiddelde temperatuur en neerslag per maand', k: 'temperatuur en neerslag per maand', fout: ['Isobar'],
        vb: [{ s: 'In een diagram staan per maand de gemiddelde warmte als lijn en de regen als staafjes', d: 3 }] },
      { t: 'Isobar', d: 'een lijn op een weerkaart die punten met gelijke luchtdruk verbindt', k: 'lijn van gelijke druk', fout: ['Klimaatgrafiek'],
        vb: [{ s: 'Op de weerkaart loopt een lijn langs alle plaatsen met precies dezelfde luchtdruk', d: 3 }] },
      { t: 'Front', d: 'de grens tussen warme en koude lucht', k: 'grens warme en koude lucht', fout: ['Isobar'],
        vb: [{ s: 'Op de weerkaart schuift een massa warme lucht tegen een massa koude lucht aan', d: 2 }, 'Een botsing van aanrukkende koude en warme lucht brengt buien'] },
      { t: 'Zeeklimaat', d: 'een klimaat met milde winters en koele zomers door de zee', k: 'mild door de zee', fout: ['Landklimaat'],
        vb: [{ s: 'Vlak aan de kust zijn de winters zacht en de zomers koel door het water', d: 2 }, 'Doordat de zee de temperatuur dempt, vriest het hier zelden hard'] },
      { t: 'Landklimaat', d: 'een klimaat met koude winters en warme zomers, ver van zee', k: 'extreem, ver van zee', fout: ['Zeeklimaat'],
        vb: [{ s: 'Diep in het binnenland, ver van zee, zijn de winters ijzig en de zomers snikheet', d: 2 }] },
    ],
    [
      { v: 'Wat is het verschil tussen weer en klimaat?', o: ['Ze zijn hetzelfde', 'Weer is nu, klimaat is gemiddeld over 30 jaar', 'Weer is gemiddeld', 'Klimaat is van vandaag'], c: 1, d: 2, uo: ['Nee.', 'Klopt: weer is nu, klimaat over lange tijd.', 'Nee, dat is klimaat.', 'Nee.'] },
      { v: 'Wat gebeurt er in een lagedrukgebied?', o: ['Droog en zonnig', 'De lucht daalt', 'Vaak bewolkt en nat', 'Geen wind'], c: 2, d: 2, uo: ['Dat is hogedruk.', 'De lucht stijgt juist.', 'Klopt: opstijgende lucht, vaak nat.', 'Er is juist wind.'] },
      { v: 'Wat is wind?', o: ['Bewegende lucht van hoge naar lage druk', 'Stilstaande lucht', 'Warme grond', 'Regen'], c: 0, d: 1, uo: ['Klopt: lucht stroomt van hoge naar lage druk.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat lees je af aan een klimaatgrafiek?', o: ['Alleen de wind', 'De hoogte', 'De bevolking', 'Temperatuur en neerslag per maand'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: gemiddelde temperatuur en neerslag per maand.'] },
      { v: 'Nederland heeft een...', o: ['woestijnklimaat', 'zeeklimaat', 'poolklimaat', 'landklimaat'], c: 1, d: 2, uo: ['Nee.', 'Klopt: mild door de zee.', 'Nee.', 'Dat is ver van zee.'] },
      { v: 'Wat is een hogedrukgebied?', o: ['Nat en bewolkt', 'Veel wind', 'Vaak droog en zonnig', 'Vol neerslag'], c: 2, d: 2, uo: ['Dat is lagedruk.', 'Nee.', 'Klopt: dalende lucht, droog weer.', 'Nee.'] },
      { v: 'Wat is neerslag?', o: ['Regen en sneeuw', 'Wind', 'Temperatuur', 'Luchtdruk'], c: 0, d: 1, uo: ['Klopt: water dat uit de lucht valt.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een isobar op een weerkaart?', o: ['Een grens tussen landen', 'Een rivier', 'Een weg', 'Een lijn van gelijke luchtdruk'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: verbindt punten met dezelfde luchtdruk.'] },
      { v: 'Wat is een landklimaat?', o: ['Mild door de zee', 'Koude winters en warme zomers', 'Altijd warm', 'Altijd nat'], c: 1, d: 2, uo: ['Dat is zeeklimaat.', 'Klopt: extreem, ver van zee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een front?', o: ['Een hogedrukgebied', 'Een isobar', 'De grens tussen warme en koude lucht', 'Een klimaatgrafiek'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: de grens tussen warme en koude lucht.', 'Nee.'] },
      { v: 'Waarom is het bij een zeeklimaat mild?', o: ['Door de invloed van de zee', 'Door de woestijn', 'Door bergen', 'Door de stad'], c: 0, d: 3, uo: ['Klopt: de zee zorgt voor milde temperaturen.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('B', 'Water',
    `In de <strong>waterkringloop</strong> verdampt water, valt het als <strong>neerslag</strong> en stroomt het via <strong>rivieren</strong> terug naar zee. Nederland ligt laag en beschermt zich met <strong>dijken</strong>, <strong>polders</strong> en <strong>gemalen</strong>.`,
    [
      { h: '1. De waterkringloop', p: [
        `Water is voortdurend in beweging. Door <strong>verdamping</strong> wordt zeewater waterdamp, die als <strong>neerslag</strong> weer valt. Een deel zakt weg als <strong>grondwater</strong>, een deel stroomt via een <strong>rivier</strong> naar zee, waar de rivier zich in een <strong>delta</strong> vertakt. Dit geheel heet de <strong>waterkringloop</strong>.`] },
      { h: '2. Nederland en het water', p: [
        `Grote delen van Nederland liggen onder zeeniveau. Een <strong>dijk</strong> houdt het water tegen, een <strong>polder</strong> is drooggelegd land en een <strong>gemaal</strong> pompt overtollig water weg. Het <strong>waterschap</strong> beheert de dijken en het waterpeil. Door <strong>zeespiegelstijging</strong> neemt het risico op <strong>overstroming</strong> toe.`] },
    ],
    [
      { t: 'Waterkringloop', d: 'de kringloop van verdamping, neerslag en afstroming van water', k: 'water gaat rond', fout: ['Verdamping'],
        vb: [{ s: 'Zeewater verdampt, wordt een wolk, valt als regen en komt weer bij de zee', d: 1 }, { s: 'Water gaat steeds rond: verdampen, neerslag en afstromen naar zee', d: 2 }] },
      { t: 'Verdamping', d: 'het overgaan van water in waterdamp', k: 'water wordt damp', fout: ['Neerslag'],
        vb: [{ s: 'Door de warme zon verandert het water in de plas langzaam in waterdamp', d: 1 }, { s: 'Het natte schoolplein droogt op zodra de zon gaat schijnen', d: 2 }] },
      { t: 'Neerslag', d: 'water dat uit de lucht valt, zoals regen en sneeuw', k: 'regen en sneeuw', fout: ['Verdamping'],
        vb: [{ s: 'Uit de donkere wolken valt eerst regen en later hagel', d: 1 }, { s: "'s Winters komt er water uit de lucht in de vorm van sneeuw", d: 2 }] },
      { t: 'Grondwater', d: 'water dat zich in de bodem bevindt', k: 'water in de bodem', fout: ['Rivier'],
        vb: [{ s: 'Als je diep genoeg graaft, komt er vanzelf water uit de bodem omhoog', d: 2 }, { s: 'Een boer pompt voor zijn gewassen water op dat onder de grond zit', d: 3 }] },
      { t: 'Rivier', d: 'stromend water dat richting de zee gaat', k: 'stromend water naar zee', fout: ['Delta', 'Grondwater'],
        vb: [{ s: 'Water stroomt vanuit de bergen door het land tot in de zee', d: 1 }, { s: 'Schepen varen over het stromende water richting de monding', d: 2 }] },
      { t: 'Delta', d: 'het gebied waar een rivier zich vertakt en in zee uitmondt', k: 'riviermonding in zee', fout: ['Rivier'],
        vb: [{ s: 'Vlak voor de zee splitst de rivier zich in allemaal kleine takken', d: 2 }, { s: 'Waar de grote rivier de zee bereikt, waaiert hij uit in vele armen', d: 3 }] },
      { t: 'Dijk', d: 'een verhoging die het land tegen water beschermt', k: 'waterkering', fout: ['Gemaal', 'Polder'],
        vb: [{ s: 'Een hoge wal langs het water houdt het lager gelegen land droog', d: 1 }, { s: 'Bij hoogwater beschermt een verhoging het dorp tegen de rivier', d: 2 }] },
      { t: 'Polder', d: 'laaggelegen land dat door dijken en gemalen droog blijft', k: 'drooggelegd laagland', fout: ['Dijk', 'Gemaal'],
        vb: [{ s: 'Dit lage stuk land ligt onder zeeniveau maar blijft droog door dijken en pompen', d: 2 }, { s: 'Vroeger stond hier een meer, nu zijn het weilanden op drooggelegd land', d: 3 }] },
      { t: 'Gemaal', d: 'een installatie die overtollig water wegpompt', k: 'pompt water weg', fout: ['Dijk'],
        vb: [{ s: 'Een installatie pompt het overtollige water uit het lage land weg', d: 1 }, { s: 'Als het te nat wordt, pompt een machine het water over de dijk', d: 2 }] },
      { t: 'Overstroming', d: 'het onderlopen van land met water', k: 'land loopt onder', fout: ['Zeespiegelstijging'],
        vb: [{ s: 'Na de zware regen liep het hele weiland onder water', d: 1 }, { s: 'De rivier trad buiten zijn oevers en zette de straten blank', d: 2 }] },
      { t: 'Zeespiegelstijging', d: 'het stijgen van het gemiddelde zeeniveau', k: 'zee komt hoger', fout: ['Overstroming'],
        vb: [{ s: 'Door de opwarming smelt er ijs en komt het zeeniveau langzaam omhoog', d: 2 }, { s: 'De gemiddelde stand van de zee wordt elk jaar een beetje hoger', d: 3 }] },
      { t: 'Waterschap', d: 'het bestuur dat zorgt voor dijken en het waterpeil', k: 'bestuur voor water', fout: ['Gemaal'],
        vb: [{ s: 'Een apart bestuur zorgt voor de dijken en het waterpeil in de regio', d: 2 }, { s: 'Deze overheid houdt de sloten op peil en onderhoudt de dijken', d: 3 }] },
    ],
    [
      { v: 'Wat is de waterkringloop?', o: ['Water dat verdwijnt', 'Verdamping, neerslag en afstroming', 'Alleen regen', 'Een rivier'], c: 1, d: 2, uo: ['Water verdwijnt niet.', 'Klopt: water gaat rond via verdamping en neerslag.', 'Nee, dat is één deel.', 'Nee.'] },
      { v: 'Wat is verdamping?', o: ['Regen die valt', 'Water dat bevriest', 'Water dat waterdamp wordt', 'Water in de bodem'], c: 2, d: 1, uo: ['Dat is neerslag.', 'Nee.', 'Klopt: water wordt waterdamp.', 'Dat is grondwater.'] },
      { v: 'Wat doet een dijk?', o: ['Houdt het water tegen', 'Pompt water weg', 'Maakt regen', 'Legt land droog'], c: 0, d: 1, uo: ['Klopt: een dijk houdt het water tegen.', 'Dat doet een gemaal.', 'Nee.', 'Dat doet een polder.'] },
      { v: 'Wat is een polder?', o: ['Een berg', 'Een woestijn', 'Een zee', 'Drooggelegd laaggelegen land'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: laag land dat door dijken en gemalen droog blijft.'] },
      { v: 'Wat doet een gemaal?', o: ['Water tegenhouden', 'Overtollig water wegpompen', 'Regen maken', 'Dijken bouwen'], c: 1, d: 2, uo: ['Dat doet een dijk.', 'Klopt: het pompt overtollig water weg.', 'Nee.', 'Nee.'] },
      { v: 'Wat is grondwater?', o: ['Water in de zee', 'Regen in de lucht', 'Water in de bodem', 'Water in een rivier'], c: 2, d: 1, uo: ['Nee.', 'Nee.', 'Klopt: water dat in de bodem zit.', 'Nee.'] },
      { v: 'Wat is een delta?', o: ['Waar een rivier in zee uitmondt', 'Een berg', 'Een woestijn', 'Een dijk'], c: 0, d: 2, uo: ['Klopt: waar een rivier zich vertakt en in zee uitmondt.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Waardoor neemt het overstromingsrisico toe?', o: ['Door minder regen', 'Door een lagere zeespiegel', 'Door meer dijken', 'Door zeespiegelstijging'], c: 3, d: 3, uo: ['Nee.', 'Juist andersom.', 'Dijken helpen juist.', 'Klopt: door de stijgende zeespiegel.'] },
      { v: 'Wat beheert het waterschap?', o: ['De wegen', 'De dijken en het waterpeil', 'De scholen', 'De belasting'], c: 1, d: 2, uo: ['Nee.', 'Klopt: het waterschap zorgt voor dijken en waterpeil.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een rivier?', o: ['Stilstaand water', 'Water in de bodem', 'Stromend water naar de zee', 'Regen'], c: 2, d: 1, uo: ['Nee.', 'Dat is grondwater.', 'Klopt: stromend water dat naar zee gaat.', 'Nee.'] },
      { v: 'Waarom is Nederland kwetsbaar voor water?', o: ['Grote delen liggen laag', 'Het ligt hoog', 'Er is geen zee', 'Er valt nooit regen'], c: 0, d: 3, uo: ['Klopt: veel land ligt onder zeeniveau.', 'Juist niet.', 'Er is wel zee.', 'Er valt wel regen.'] },
    ]),

  V('C', 'Bevolking en ruimte',
    `De <strong>bevolkingsgroei</strong> hangt af van het <strong>geboortecijfer</strong>, het <strong>sterftecijfer</strong> en <strong>migratie</strong>. Door <strong>verstedelijking</strong> trekken mensen naar de stad.`,
    [
      { h: '1. Waardoor groeit een bevolking?', p: [
        `Een bevolking groeit door geboorte en immigratie, en krimpt door sterfte en emigratie. Het <strong>geboortecijfer</strong> en het <strong>sterftecijfer</strong> geven het aantal geboorten en sterfgevallen per duizend inwoners. Het verschil is de <strong>natuurlijke aanwas</strong>. Daarnaast telt <strong>migratie</strong> mee: <strong>immigratie</strong> is een land binnenkomen, <strong>emigratie</strong> is vertrekken.`] },
      { h: '2. Steden en spreiding', p: [
        `Door <strong>verstedelijking</strong> groeien steden en neemt het aandeel stadsbewoners toe; het trekken van het platteland naar de stad heet <strong>urbanisatie</strong>. De <strong>bevolkingsdichtheid</strong> zegt hoeveel mensen er per vierkante kilometer wonen. In veel landen speelt ook <strong>vergrijzing</strong>: het aandeel ouderen stijgt.`] },
    ],
    [
      { t: 'Bevolkingsgroei', d: 'de toename van het aantal inwoners van een gebied', k: 'meer inwoners', fout: ['Natuurlijke aanwas'],
        vb: [{ s: 'Er wonen elk jaar meer mensen in het land dan het jaar ervoor', d: 1 }, { s: 'In tien jaar tijd is het aantal inwoners van de stad flink toegenomen', d: 2 }] },
      { t: 'Geboortecijfer', d: 'het aantal geboorten per duizend inwoners per jaar', k: 'geboorten per 1000', fout: ['Sterftecijfer'],
        vb: [{ s: 'Per duizend inwoners worden er in dit land twaalf baby\'s per jaar geboren', d: 2 }, { s: 'De statistiek toont hoeveel kinderen er per duizend inwoners geboren worden', d: 3 }] },
      { t: 'Sterftecijfer', d: 'het aantal sterfgevallen per duizend inwoners per jaar', k: 'sterfgevallen per 1000', fout: ['Geboortecijfer'],
        vb: [{ s: 'Per duizend inwoners overlijden er in dit land acht mensen per jaar', d: 2 }, { s: 'De tabel toont hoeveel mensen er per duizend inwoners overlijden', d: 3 }] },
      { t: 'Natuurlijke aanwas', d: 'het geboortecijfer min het sterftecijfer', k: 'geboorten min sterfte', fout: ['Bevolkingsgroei'],
        vb: [{ s: 'Er worden meer kinderen geboren dan er mensen overlijden', d: 2 }, { s: 'Je trekt het aantal sterfgevallen af van het aantal geboorten', d: 3 }] },
      { t: 'Migratie', d: 'het verhuizen van mensen naar een ander gebied', k: 'mensen verhuizen', fout: ['Verstedelijking'],
        vb: [{ s: 'Een gezin verhuist van het ene land naar het andere om er te wonen', d: 1 }, { s: 'Grote groepen mensen trekken naar een ander gebied om te wonen', d: 2 }] },
      { t: 'Immigratie', d: 'het zich vestigen in een nieuw land', k: 'een land binnenkomen', fout: ['Emigratie'],
        vb: [{ s: 'Een familie uit het buitenland komt zich hier vestigen', d: 1 }, { s: 'Nieuwe inwoners komen van buiten de landsgrens het land binnen', d: 2 }] },
      { t: 'Emigratie', d: 'het vertrekken uit je eigen land om elders te wonen', k: 'je land verlaten', fout: ['Immigratie'],
        vb: [{ s: 'Een Nederlands gezin vertrekt om voorgoed in Canada te gaan wonen', d: 1 }, { s: 'Mensen verlaten hun eigen land om ergens anders te gaan wonen', d: 2 }] },
      { t: 'Verstedelijking', d: 'de groei van steden en van het aandeel stadsbewoners', k: 'steden groeien', fout: ['Migratie'],
        vb: [{ s: 'De stad groeit en er komen steeds meer stadsbewoners bij', d: 1 }, { s: 'Een steeds groter deel van de bevolking woont in steden', d: 2 }] },
      { t: 'Bevolkingsdichtheid', d: 'het aantal inwoners per vierkante kilometer', k: 'inwoners per km²', fout: ['Bevolkingsgroei'],
        vb: [{ s: 'In dit gebied wonen vijfhonderd mensen op elke vierkante kilometer', d: 2 }, { s: 'Je deelt het aantal inwoners door de oppervlakte in vierkante kilometers', d: 3 }] },
      { t: 'Vergrijzing', d: 'de toename van het aandeel ouderen in de bevolking', k: 'meer ouderen', fout: ['Bevolkingsgroei'],
        vb: [{ s: 'Het aandeel 65-plussers in de bevolking wordt steeds groter', d: 2 }, { s: 'Er komen steeds meer ouderen en relatief minder jongeren', d: 2 }] },
      { t: 'Urbanisatie', d: 'het trekken van mensen van het platteland naar de stad', k: 'van platteland naar stad', fout: ['Verstedelijking'],
        vb: [{ s: 'Mensen verhuizen van het platteland naar de stad', d: 1 }, { s: 'Boeren verlaten het dorp en trekken naar de grote stad voor werk', d: 2 }] },
      { t: 'Platteland', d: 'dunbevolkt gebied buiten de stad', k: 'buiten de stad', fout: ['Urbanisatie'],
        vb: [{ s: 'Buiten de stad, tussen de weilanden, staan maar een paar boerderijen', d: 1 }, { s: 'In dit dunbevolkte gebied is veel natuur en weinig bebouwing', d: 2 }] },
    ],
    [
      { v: 'Wat is het geboortecijfer?', o: ['Aantal doden per 1000', 'Aantal geboorten per 1000 inwoners', 'De bevolkingsdichtheid', 'Het aantal migranten'], c: 1, d: 2, uo: ['Dat is het sterftecijfer.', 'Klopt: geboorten per duizend inwoners.', 'Nee.', 'Nee.'] },
      { v: 'Wat is natuurlijke aanwas?', o: ['Migratie', 'Bevolkingsdichtheid', 'Geboortecijfer min sterftecijfer', 'Verstedelijking'], c: 2, d: 3, uo: ['Nee.', 'Nee.', 'Klopt: geboorten min sterfte.', 'Nee.'] },
      { v: 'Wat is immigratie?', o: ['Een land binnenkomen', 'Een land verlaten', 'In de stad wonen', 'Op het platteland wonen'], c: 0, d: 1, uo: ['Klopt: je vestigen in een nieuw land.', 'Dat is emigratie.', 'Nee.', 'Nee.'] },
      { v: 'Wat is emigratie?', o: ['Een land binnenkomen', 'In de stad gaan wonen', 'Kinderen krijgen', 'Je eigen land verlaten'], c: 3, d: 2, uo: ['Dat is immigratie.', 'Nee.', 'Nee.', 'Klopt: vertrekken uit je eigen land.'] },
      { v: 'Wat is verstedelijking?', o: ['Steden krimpen', 'Steden groeien', 'Minder mensen', 'Meer platteland'], c: 1, d: 2, uo: ['Juist niet.', 'Klopt: steden groeien, meer stadsbewoners.', 'Nee.', 'Nee.'] },
      { v: 'Wat is bevolkingsdichtheid?', o: ['Het aantal geboorten', 'Het aantal doden', 'Inwoners per vierkante kilometer', 'De migratie'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: inwoners per km².', 'Nee.'] },
      { v: 'Wat is vergrijzing?', o: ['Meer ouderen in de bevolking', 'Meer kinderen', 'Meer migranten', 'Meer steden'], c: 0, d: 2, uo: ['Klopt: het aandeel ouderen stijgt.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is urbanisatie?', o: ['Van stad naar platteland', 'Meer kinderen', 'Minder mensen', 'Van platteland naar de stad'], c: 3, d: 3, uo: ['Juist andersom.', 'Nee.', 'Nee.', 'Klopt: mensen trekken van het platteland naar de stad.'] },
      { v: 'Wat is het sterftecijfer?', o: ['Geboorten per 1000', 'Sterfgevallen per 1000 inwoners', 'De migratie', 'De dichtheid'], c: 1, d: 2, uo: ['Dat is het geboortecijfer.', 'Klopt: sterfgevallen per duizend inwoners.', 'Nee.', 'Nee.'] },
      { v: 'Wat is migratie?', o: ['Kinderen krijgen', 'In de stad wonen', 'Verhuizen naar een ander gebied', 'Sterven'], c: 2, d: 1, uo: ['Nee.', 'Nee.', 'Klopt: mensen verhuizen naar een ander gebied.', 'Nee.'] },
      { v: 'Wat is het platteland?', o: ['Dunbevolkt gebied buiten de stad', 'Het centrum van de stad', 'Een industriegebied', 'Een haven'], c: 0, d: 1, uo: ['Klopt: dunbevolkt gebied buiten de stad.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('D', 'Arm en rijk',
    `De <strong>welvaart</strong> verschilt sterk tussen landen; het <strong>bnp per inwoner</strong> is er een maat voor. Rijke <strong>centrumgebieden</strong> staan tegenover arme <strong>periferiegebieden</strong>.`,
    [
      { h: '1. Welvaart meten', p: [
        `<strong>Welvaart</strong> is de mate waarin mensen in hun behoeften kunnen voorzien. Je meet die onder meer met het <strong>bnp per inwoner</strong> (de gemiddelde productie per persoon), de <strong>levensverwachting</strong> en het <strong>analfabetisme</strong>. Landen met lage welvaart heten <strong>ontwikkelingslanden</strong>, landen met hoge welvaart <strong>ontwikkelde landen</strong>.`] },
      { h: '2. Centrum en periferie', p: [
        `Binnen en tussen landen zie je een rijk <strong>centrum</strong> met veel bedrijvigheid en een arme <strong>periferie</strong> aan de rand. Zulke <strong>welvaartsverschillen</strong> ontstaan door verschillen in <strong>grondstoffen</strong>, onderwijs, <strong>infrastructuur</strong> en handel. Met <strong>ontwikkelingssamenwerking</strong> worden armere landen geholpen.`] },
    ],
    [
      { t: 'Welvaart', d: 'de mate waarin mensen in hun behoeften kunnen voorzien', k: 'hoe goed men rondkomt', fout: ['Welvaartsverschil'],
        vb: [{ s: 'Mensen hebben er genoeg geld, eten en voorzieningen om goed rond te komen', d: 1 }, { s: 'In dit land kunnen de meeste mensen makkelijk in hun behoeften voorzien', d: 2 }] },
      { t: 'Bnp per inwoner', d: 'de gemiddelde productie per persoon in een land', k: 'productie per persoon', fout: ['Levensverwachting'],
        vb: [{ s: 'Dit getal laat zien hoeveel een land gemiddeld per persoon produceert', d: 2 }, { s: 'Je deelt de totale productie van een land door het aantal inwoners', d: 3 }] },
      { t: 'Ontwikkelingsland', d: 'een land met een lage welvaart', k: 'arm land', fout: ['Ontwikkeld land'],
        vb: [{ s: 'In dit arme land is weinig industrie en een lage welvaart', d: 1 }, { s: 'Veel inwoners zijn arm en er is weinig geld voor onderwijs en zorg', d: 2 }] },
      { t: 'Ontwikkeld land', d: 'een land met een hoge welvaart', k: 'rijk land', fout: ['Ontwikkelingsland'],
        vb: [{ s: 'Dit rijke land heeft veel industrie, goede zorg en hoge welvaart', d: 1 }, { s: 'De inwoners zijn welvarend en er is goed onderwijs en gezondheidszorg', d: 2 }] },
      { t: 'Centrum', d: 'een rijk en welvarend gebied met veel bedrijvigheid', k: 'rijk kerngebied', fout: ['Periferie'],
        vb: [{ s: 'In dit rijke kerngebied zijn veel bedrijven, banen en voorzieningen', d: 2 }, { s: 'In het welvarende hart van het land gebeurt de meeste economie', d: 3 }] },
      { t: 'Periferie', d: 'een arm en afgelegen gebied aan de rand', k: 'arm randgebied', fout: ['Centrum'],
        vb: [{ s: 'Dit arme gebied ligt ver van de stad, met weinig werk en voorzieningen', d: 2 }, { s: 'Aan de afgelegen, arme rand van het land trekken mensen juist weg', d: 3 }] },
      { t: 'Welvaartsverschil', d: 'het verschil in rijkdom tussen gebieden of landen', k: 'verschil in rijkdom', fout: ['Welvaart'],
        vb: [{ s: 'De ene groep in het land is heel rijk, de andere heel arm', d: 1 }, { s: 'Tussen twee landen zit een groot verschil in rijkdom en inkomen', d: 2 }] },
      { t: 'Analfabetisme', d: 'het niet kunnen lezen en schrijven', k: 'niet kunnen lezen', fout: ['Levensverwachting'],
        vb: [{ s: 'Veel volwassenen in dit gebied kunnen niet lezen of schrijven', d: 1 }, { s: 'Doordat er weinig onderwijs is, kan een deel van de mensen niet lezen', d: 2 }] },
      { t: 'Levensverwachting', d: 'het gemiddelde aantal jaren dat iemand naar verwachting leeft', k: 'gemiddelde levensduur', fout: ['Bnp per inwoner'],
        vb: [{ s: 'In dit land worden mensen gemiddeld tachtig jaar oud', d: 2 }, { s: 'Dit getal zegt hoe oud iemand gemiddeld naar verwachting wordt', d: 3 }] },
      { t: 'Grondstoffen', d: 'natuurlijke stoffen waarmee een land geld kan verdienen', k: 'natuurlijke rijkdommen', fout: ['Infrastructuur'],
        vb: [{ s: 'Dit land verdient veel geld met olie en metalen uit de bodem', d: 2 }, { s: 'Natuurlijke rijkdommen zoals hout en erts worden gewonnen en verkocht', d: 2 }] },
      { t: 'Infrastructuur', d: 'voorzieningen zoals wegen, havens en spoor', k: 'wegen en verbindingen', fout: ['Grondstoffen'],
        vb: [{ s: 'Goede wegen, havens en spoorlijnen verbinden alle delen van het land', d: 2 }, { s: 'Dankzij nieuwe wegen en verbindingen worden goederen snel vervoerd', d: 3 }] },
      { t: 'Ontwikkelingssamenwerking', d: 'hulp aan armere landen om zich te ontwikkelen', k: 'hulp aan arme landen', fout: ['Welvaartsverschil'],
        vb: [{ s: 'Een rijk land helpt een arm land met geld en kennis om vooruit te komen', d: 2 }, { s: 'Via hulpprojecten steunen rijke landen de ontwikkeling van arme landen', d: 3 }] },
    ],
    [
      { v: 'Wat is welvaart?', o: ['Alleen geld', 'Hoe goed mensen in hun behoeften kunnen voorzien', 'Het weer', 'De bevolking'], c: 1, d: 2, uo: ['Het is meer dan alleen geld.', 'Klopt: hoe goed men kan rondkomen.', 'Nee.', 'Nee.'] },
      { v: 'Wat meet het bnp per inwoner?', o: ['De bevolking', 'Het weer', 'De gemiddelde productie per persoon', 'De oppervlakte'], c: 2, d: 3, uo: ['Nee.', 'Nee.', 'Klopt: de gemiddelde productie per persoon.', 'Nee.'] },
      { v: 'Wat is een ontwikkelingsland?', o: ['Een land met lage welvaart', 'Een rijk land', 'Een groot land', 'Een klein land'], c: 0, d: 1, uo: ['Klopt: een land met lage welvaart.', 'Dat is een ontwikkeld land.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een centrumgebied?', o: ['Een arm randgebied', 'Een leeg gebied', 'Een woestijn', 'Een rijk gebied met veel bedrijvigheid'], c: 3, d: 2, uo: ['Dat is de periferie.', 'Nee.', 'Nee.', 'Klopt: een rijk, welvarend kerngebied.'] },
      { v: 'Wat is de periferie?', o: ['Het rijke centrum', 'Een arm, afgelegen randgebied', 'De hoofdstad', 'Een fabriek'], c: 1, d: 2, uo: ['Juist het tegenovergestelde.', 'Klopt: arm gebied aan de rand.', 'Nee.', 'Nee.'] },
      { v: 'Wat is levensverwachting?', o: ['Het geboortecijfer', 'De bevolking', 'Het gemiddelde aantal jaren dat iemand leeft', 'De welvaart'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: de gemiddelde levensduur.', 'Nee.'] },
      { v: 'Wat is analfabetisme?', o: ['Niet kunnen lezen en schrijven', 'Rijk zijn', 'Ziek zijn', 'Werkloos zijn'], c: 0, d: 1, uo: ['Klopt: niet kunnen lezen en schrijven.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Waardoor ontstaan welvaartsverschillen?', o: ['Door het weer alleen', 'Door toeval', 'Door de kleur van de vlag', 'Door grondstoffen, onderwijs en handel'], c: 3, d: 3, uo: ['Niet alleen.', 'Nee.', 'Nee.', 'Klopt: verschillen in grondstoffen, onderwijs en handel.'] },
      { v: 'Wat is een ontwikkeld land?', o: ['Een land met lage welvaart', 'Een land met hoge welvaart', 'Een klein land', 'Een warm land'], c: 1, d: 1, uo: ['Dat is een ontwikkelingsland.', 'Klopt: een rijk land met hoge welvaart.', 'Nee.', 'Nee.'] },
      { v: 'Wat is ontwikkelingssamenwerking?', o: ['Handel met winst', 'Belasting', 'Hulp aan armere landen', 'Een oorlog'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: hulp aan armere landen.', 'Nee.'] },
      { v: 'Waarmee kan een land geld verdienen?', o: ['Met grondstoffen', 'Met het weer', 'Met de vlag', 'Met de tijd'], c: 0, d: 2, uo: ['Klopt: met grondstoffen kan een land geld verdienen.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('E', 'Ruimtelijke ordening',
    `<strong>Ruimtelijke ordening</strong> is het plannen van het gebruik van de ruimte. In een <strong>bestemmingsplan</strong> legt de overheid vast welke <strong>bestemming</strong> een gebied krijgt: wonen, werken of natuur.`,
    [
      { h: '1. De ruimte plannen', p: [
        `Nederland is klein en dichtbevolkt, dus de ruimte wordt zorgvuldig verdeeld: dat is <strong>ruimtelijke ordening</strong>. In een <strong>bestemmingsplan</strong> legt de gemeente vast waarvoor grond gebruikt mag worden. De <strong>bestemming</strong> is de functie die een gebied krijgt; de <strong>functie</strong> is het gebruik ervan, zoals wonen of natuur.`] },
      { h: '2. Belangen afwegen', p: [
        `Bij het inrichten van een gebied botsen vaak verschillende <strong>belangen</strong>. De overheid maakt dan een <strong>belangenafweging</strong>. Zo kies je tussen een <strong>woonfunctie</strong> en een <strong>recreatiefunctie</strong>, of tussen een <strong>industriegebied</strong> en een beschermd <strong>natuurgebied</strong>.`] },
    ],
    [
      { t: 'Ruimtelijke ordening', d: 'het indelen en plannen van het gebruik van de ruimte', k: 'de ruimte plannen', fout: ['Bestemmingsplan'],
        vb: [{ s: 'De gemeente bepaalt welk stuk grond voor wonen, werken of natuur is', d: 2 }, { s: 'De overheid plant zorgvuldig waar in het land alles mag komen', d: 2 }] },
      { t: 'Bestemmingsplan', d: 'een plan dat vastlegt waarvoor grond gebruikt mag worden', k: 'plan voor grondgebruik', fout: ['Bestemming', 'Ruimtelijke ordening'],
        vb: [{ s: 'In een officieel plan staat waarvoor elk stuk grond gebruikt mag worden', d: 2 }, { s: 'Het document van de gemeente legt vast wat je op een perceel mag bouwen', d: 3 }] },
      { t: 'Bestemming', d: 'de functie die een gebied volgens het plan krijgt', k: 'toegewezen functie', fout: ['Functie'],
        vb: [{ s: 'Dit stuk grond heeft in het plan de functie natuur gekregen', d: 2 }, { s: 'Aan een gebied is toegewezen dat het voor wonen bedoeld is', d: 3 }] },
      { t: 'Functie', d: 'het gebruik of doel van een gebied', k: 'gebruik van een gebied', fout: ['Bestemming'],
        vb: [{ s: 'Dit gebied wordt gebruikt om in te wonen', d: 1 }, { s: 'Het doel of gebruik van een stuk grond, zoals werken of ontspannen', d: 2 }] },
      { t: 'Belang', d: 'het voordeel dat iemand bij iets heeft', k: 'wat iemand wil', fout: ['Belangenafweging'],
        vb: [{ s: 'De boer wil zijn land houden, de bouwer wil er huizen neerzetten', d: 2 }, { s: 'Iedere partij heeft een eigen voordeel dat ze wil behouden', d: 2 }] },
      { t: 'Belangenafweging', d: 'het tegen elkaar afwegen van verschillende belangen', k: 'belangen afwegen', fout: ['Belang'],
        vb: [{ s: 'De gemeente weegt de wensen van bewoners, bedrijven en natuur tegen elkaar af', d: 3 }, { s: 'Voor de beslissing worden alle voor- en nadelen tegen elkaar gezet', d: 3 }] },
      { t: 'Woonfunctie', d: 'het gebruik van een gebied om te wonen', k: 'gebied om te wonen', fout: ['Recreatiefunctie'],
        vb: [{ s: 'In deze wijk staan alleen maar huizen waar mensen wonen', d: 1 }, { s: 'Dit gebied is bedoeld om in te wonen', d: 2 }] },
      { t: 'Recreatiefunctie', d: 'het gebruik van een gebied voor ontspanning', k: 'gebied voor ontspanning', fout: ['Woonfunctie'],
        vb: [{ s: 'In dit park kunnen mensen wandelen, spelen en ontspannen', d: 1 }, { s: 'Dit gebied is bedoeld voor vrije tijd en ontspanning', d: 2 }] },
      { t: 'Industriegebied', d: 'een gebied bestemd voor bedrijven en fabrieken', k: 'gebied voor bedrijven', fout: ['Natuurgebied'],
        vb: [{ s: 'Aan de rand van de stad staan grote fabrieken en bedrijfshallen', d: 1 }, { s: 'Op dit terrein zijn bedrijven en fabrieken gevestigd', d: 2 }] },
      { t: 'Natuurgebied', d: 'een gebied dat beschermd is voor planten en dieren', k: 'beschermde natuur', fout: ['Industriegebied'],
        vb: [{ s: 'Dit stuk land is beschermd zodat planten en dieren er veilig zijn', d: 1 }, { s: 'Hier mag niet gebouwd worden om de natuur te sparen', d: 2 }] },
      { t: 'Verstedelijking', d: 'de groei van steden en het stedelijk ruimtegebruik', k: 'steden groeien', fout: ['Woonfunctie'],
        vb: [{ s: 'De stad breidt steeds verder uit over het omliggende land', d: 2 }, { s: 'Er komen steeds meer gebouwen en stadsbewoners bij', d: 2 }] },
      { t: 'Infrastructuur', d: 'voorzieningen zoals wegen en verbindingen in een gebied', k: 'wegen en verbindingen', fout: ['Industriegebied'],
        vb: [{ s: 'Nieuwe wegen en een station verbinden de wijk met de rest van de stad', d: 2 }, { s: 'Wegen, bruggen en spoor zorgen dat je je kunt verplaatsen', d: 3 }] },
    ],
    [
      { v: 'Wat is ruimtelijke ordening?', o: ['De ruimte laten zoals hij is', 'Het plannen van het gebruik van de ruimte', 'Alleen bouwen', 'Alleen natuur'], c: 1, d: 2, uo: ['Nee.', 'Klopt: het indelen en plannen van de ruimte.', 'Nee.', 'Nee.'] },
      { v: 'Wat legt een bestemmingsplan vast?', o: ['De belasting', 'Het weer', 'Waarvoor grond gebruikt mag worden', 'De bevolking'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: waarvoor grond gebruikt mag worden.', 'Nee.'] },
      { v: 'Wat is de bestemming van een gebied?', o: ['De functie die het krijgt', 'De prijs', 'De bevolking', 'Het weer'], c: 0, d: 2, uo: ['Klopt: de functie, zoals wonen of natuur.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat doe je bij een belangenafweging?', o: ['Eén belang blind kiezen', 'Niets doen', 'Alles verbieden', 'Belangen tegen elkaar afwegen'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: verschillende belangen tegen elkaar afwegen.'] },
      { v: 'Wat is een woonfunctie?', o: ['Een gebied voor fabrieken', 'Een gebied om te wonen', 'Een natuurgebied', 'Een haven'], c: 1, d: 1, uo: ['Dat is industrie.', 'Klopt: een gebied om te wonen.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een natuurgebied?', o: ['Een industrieterrein', 'Een woonwijk', 'Beschermd gebied voor planten en dieren', 'Een haven'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: beschermde natuur.', 'Nee.'] },
      { v: 'Waarom is ruimtelijke ordening in Nederland belangrijk?', o: ['Het land is klein en dichtbevolkt', 'Er is veel lege ruimte', 'Er wonen weinig mensen', 'Er is geen water'], c: 0, d: 3, uo: ['Klopt: weinig ruimte, veel mensen.', 'Juist niet.', 'Er wonen juist veel mensen.', 'Er is juist veel water.'] },
      { v: 'Wat is een recreatiefunctie?', o: ['Wonen', 'Werken in een fabriek', 'Een haven', 'Een gebied voor ontspanning'], c: 3, d: 2, uo: ['Dat is wonen.', 'Dat is industrie.', 'Nee.', 'Klopt: een gebied voor ontspanning.'] },
      { v: 'Wat is een industriegebied?', o: ['Een natuurgebied', 'Een gebied voor bedrijven en fabrieken', 'Een woonwijk', 'Een park'], c: 1, d: 1, uo: ['Juist niet.', 'Klopt: een gebied voor bedrijven.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een belang?', o: ['Een gebouw', 'Een wet', 'Het voordeel dat iemand ergens bij heeft', 'Een straf'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: wat iemand ergens bij te winnen heeft.', 'Nee.'] },
      { v: 'Wie bepaalt mede de ruimtelijke ordening?', o: ['De overheid', 'Een winkel', 'Een school', 'Een sportclub'], c: 0, d: 2, uo: ['Klopt: de overheid bepaalt mede het ruimtegebruik.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('F', 'Grenzen en identiteit',
    `Een <strong>grens</strong> scheidt gebieden; soms valt hij samen met een rivier of gebergte. <strong>Migratiestromen</strong> verplaatsen mensen tussen <strong>cultuurgebieden</strong>, en gedeelde taal en gewoonten vormen een <strong>identiteit</strong>.`,
    [
      { h: '1. Grenzen en gebied', p: [
        `Een <strong>grens</strong> is de lijn die twee gebieden scheidt. Een <strong>natuurlijke grens</strong> valt samen met bijvoorbeeld een rivier of gebergte. Het gebied waarover een land zeggenschap heeft, is het <strong>territorium</strong>; over het bezit ervan ontstaat soms een <strong>territoriaal conflict</strong>.`] },
      { h: '2. Migratie, cultuur en identiteit', p: [
        `Door <strong>migratiestromen</strong> verhuizen grote groepen mensen, soms als <strong>vluchteling</strong>. Een <strong>cultuurgebied</strong> deelt taal en gewoonten (de <strong>cultuur</strong>) en soms een <strong>godsdienst</strong>. Dat gedeelde gevoel erbij te horen is de <strong>identiteit</strong>. <strong>Integratie</strong> is het meedoen van nieuwkomers in de samenleving.`] },
    ],
    [
      { t: 'Grens', d: 'de lijn die twee gebieden of landen van elkaar scheidt', k: 'scheidingslijn', fout: ['Natuurlijke grens'],
        vb: [{ s: 'Bij de slagboom houdt het ene land op en begint het andere', d: 1 }, { s: 'Een lijn op de kaart scheidt twee landen van elkaar', d: 2 }] },
      { t: 'Natuurlijke grens', d: 'een grens die samenvalt met een rivier of gebergte', k: 'grens langs de natuur', fout: ['Grens'],
        vb: [{ s: 'Een grote rivier vormt precies de scheiding tussen twee landen', d: 2 }, { s: 'Een hoog gebergte scheidt de twee landen van elkaar', d: 2 }] },
      { t: 'Migratiestroom', d: 'een grote verplaatsing van mensen tussen gebieden', k: 'grote verhuisstroom', fout: ['Vluchteling'],
        vb: [{ s: 'Een grote groep mensen verhuist massaal naar een ander land', d: 1 }, { s: 'Duizenden mensen trekken tegelijk vanuit één gebied naar een ander', d: 2 }] },
      { t: 'Cultuurgebied', d: 'een gebied met een gedeelde cultuur en taal', k: 'gebied met gedeelde cultuur', fout: ['Cultuur'],
        vb: [{ s: 'In deze streek leven en spreken alle mensen op dezelfde manier', d: 2 }, { s: 'Een gebied waar iedereen dezelfde taal en gewoonten deelt', d: 3 }] },
      { t: 'Identiteit', d: 'het gevoel bij een groep of gebied te horen', k: 'gevoel van erbij horen', fout: ['Cultuur'],
        vb: [{ s: 'Het gevoel dat je ergens bij hoort', d: 1 }, { s: 'Je voelt je thuis bij je groep en bent er trots op', d: 2 }] },
      { t: 'Nationaliteit', d: 'het behoren tot een bepaald land', k: 'bij een land horen', fout: ['Identiteit'],
        vb: [{ s: 'In je paspoort staat dat je bij Nederland hoort', d: 1 }, { s: 'Je bent officieel burger van een bepaald land', d: 2 }] },
      { t: 'Territorium', d: 'het gebied waarover een land zeggenschap heeft', k: 'grondgebied van een land', fout: ['Territoriaal conflict'],
        vb: [{ s: 'Het volledige grondgebied waarover een land de baas is', d: 2 }, { s: 'Het land met alles binnen zijn grenzen waar het over gaat', d: 3 }] },
      { t: 'Territoriaal conflict', d: 'een conflict over het bezit van een gebied', k: 'ruzie over gebied', fout: ['Territorium'],
        vb: [{ s: 'Twee landen maken ruzie over wie een stuk grond mag hebben', d: 2 }, { s: 'Er is oorlog omdat beide landen hetzelfde gebied opeisen', d: 3 }] },
      { t: 'Integratie', d: 'het opgaan van migranten in de samenleving', k: 'meedoen in de samenleving', fout: ['Migratiestroom'],
        vb: [{ s: 'Nieuwkomers leren de taal en doen mee in de samenleving', d: 2 }, { s: 'Migranten gaan meedoen met werk, school en contact met anderen', d: 2 }] },
      { t: 'Vluchteling', d: 'iemand die zijn land ontvlucht vanwege gevaar', k: 'ontvlucht gevaar', fout: ['Migratiestroom'],
        vb: [{ s: 'Iemand ontvlucht zijn land vanwege oorlog en geweld', d: 1 }, { s: 'Uit angst voor vervolging verlaat een persoon halsoverkop zijn land', d: 2 }] },
      { t: 'Cultuur', d: 'de gewoonten, taal en gebruiken van een groep', k: 'gewoonten en gebruiken', fout: ['Identiteit', 'Cultuurgebied'],
        vb: [{ s: 'De taal, gewoonten, feesten en gebruiken van een groep', d: 1 }, { s: 'Hoe een groep mensen leeft: hun eten, kleding en tradities', d: 2 }] },
      { t: 'Godsdienst', d: 'een gedeeld geloof binnen een cultuur', k: 'gedeeld geloof', fout: ['Cultuur'],
        vb: [{ s: 'Een groep deelt hetzelfde geloof en gaat naar dezelfde gebedsplek', d: 2 }, { s: 'Het gedeelde geloof binnen een cultuur', d: 2 }] },
    ],
    [
      { v: 'Wat is een grens?', o: ['Altijd een rivier', 'De lijn die twee gebieden scheidt', 'Een stad', 'Altijd een berg'], c: 1, d: 1, uo: ['Niet altijd.', 'Klopt: de scheidingslijn tussen gebieden.', 'Nee.', 'Niet altijd.'] },
      { v: 'Wat is een natuurlijke grens?', o: ['Een rechte lijn op de kaart', 'Een muur', 'Een grens langs een rivier of gebergte', 'Een stad'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: valt samen met een rivier of gebergte.', 'Nee.'] },
      { v: 'Wat is een migratiestroom?', o: ['Een grote verplaatsing van mensen', 'Een rivier', 'Een grens', 'Een cultuur'], c: 0, d: 2, uo: ['Klopt: een grote verhuizing van mensen tussen gebieden.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is identiteit?', o: ['Een grens', 'Een rivier', 'Een wet', 'Het gevoel bij een groep te horen'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: het gevoel ergens bij te horen.'] },
      { v: 'Wat is een cultuurgebied?', o: ['Een leeg gebied', 'Een gebied met een gedeelde cultuur en taal', 'Een woestijn', 'Een zee'], c: 1, d: 2, uo: ['Nee.', 'Klopt: een gebied met een gedeelde cultuur.', 'Nee.', 'Nee.'] },
      { v: 'Wat is integratie?', o: ['Gescheiden leven', 'Vertrekken', 'Meedoen in de samenleving', 'Een grens'], c: 2, d: 2, uo: ['Dat is het tegenovergestelde.', 'Nee.', 'Klopt: nieuwkomers doen mee in de samenleving.', 'Nee.'] },
      { v: 'Wat is een vluchteling?', o: ['Iemand die zijn land ontvlucht', 'Een toerist', 'Een handelaar', 'Een ambtenaar'], c: 0, d: 1, uo: ['Klopt: ontvlucht gevaar.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een territoriaal conflict?', o: ['Een sportwedstrijd', 'Een verkiezing', 'Een handelsdeal', 'Een conflict over gebied'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: een conflict over het bezit van een gebied.'] },
      { v: 'Wat hoort bij cultuur?', o: ['Alleen het weer', 'Gewoonten, taal en gebruiken', 'Alleen de economie', 'Alleen grenzen'], c: 1, d: 2, uo: ['Nee.', 'Klopt: gewoonten, taal en gebruiken van een groep.', 'Nee.', 'Nee.'] },
      { v: 'Wat is nationaliteit?', o: ['Een cultuur', 'Een grens', 'Het behoren tot een bepaald land', 'Een rivier'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: bij een bepaald land horen.', 'Nee.'] },
      { v: 'Wat is een territorium?', o: ['Het gebied waarover een land zeggenschap heeft', 'Een cultuur', 'Een migratiestroom', 'Een rivier'], c: 0, d: 2, uo: ['Klopt: het grondgebied van een land.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),
];
