// VMBO GL/TL - Natuur- en scheikunde 1 (nask1). Gouden-stijl contentspec.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vmbo', vak: 'na1', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Stoffen en materialen',
    `De <strong>dichtheid</strong> is de massa per volume van een stof. Bij een <strong>faseovergang</strong> gaat een stof van vast naar vloeibaar of van vloeibaar naar gas. Een <strong>temperatuur-tijdgrafiek</strong> laat zien hoe de temperatuur tijdens verwarmen verandert.`,
    [
      { h: '1. Dichtheid', p: [
        `De <strong>dichtheid</strong> vertelt hoe zwaar een stof is voor zijn grootte: de <strong>massa</strong> per <strong>volume</strong>. IJzer heeft een grote dichtheid, piepschuim een kleine. Je berekent de dichtheid door de massa te delen door het volume.`],
        formula: { label: 'Dichtheid', eq: 'ρ = m / V', note: 'ρ de dichtheid (g/cm³ of kg/m³), m de massa, V het volume.' },
        worked: { q: 'Een blok heeft een massa van 200 g en een volume van 100 cm³. Bereken de dichtheid.', steps: ['Gebruik ρ = m / V.', 'ρ = 200 / 100.'], ans: 'De dichtheid is 2 g/cm³.' } },
      { h: '2. Faseovergangen', p: [
        `Een stof kan <strong>vast</strong>, <strong>vloeibaar</strong> of <strong>gas</strong> zijn. De overgangen hebben eigen namen: <strong>smelten</strong> (vast → vloeibaar) en <strong>stollen</strong> (vloeibaar → vast), en <strong>verdampen</strong> (vloeibaar → gas) en <strong>condenseren</strong> (gas → vloeibaar). Het <strong>smeltpunt</strong> en het <strong>kookpunt</strong> zijn de temperaturen waarbij dat gebeurt.`] },
      { h: '3. Temperatuur-tijdgrafiek', p: [
        `In een <strong>temperatuur-tijdgrafiek</strong> zet je de temperatuur uit tegen de tijd bij verwarmen. Tijdens een faseovergang blijft de temperatuur even gelijk (een vlak stuk in de grafiek), omdat alle warmte in de overgang gaat zitten.`] },
    ],
    [
      { t: 'Dichtheid', d: 'de massa per volume van een stof', k: 'massa per volume', fout: ['Massa', 'Volume'] },
      { t: 'Massa', d: 'de hoeveelheid stof, in kilogram of gram', k: 'hoeveelheid stof', fout: ['Volume', 'Dichtheid'] },
      { t: 'Volume', d: 'de ruimte die een stof inneemt', k: 'ingenomen ruimte', fout: ['Massa', 'Dichtheid'] },
      { t: 'Faseovergang', d: 'de overgang van de ene fase naar de andere', k: 'wisseling van fase', fout: ['Smelten', 'Verdampen'] },
      { t: 'Smelten', d: 'de overgang van vast naar vloeibaar', k: 'vast wordt vloeibaar', fout: ['Stollen'] },
      { t: 'Stollen', d: 'de overgang van vloeibaar naar vast', k: 'vloeibaar wordt vast', fout: ['Smelten'] },
      { t: 'Verdampen', d: 'de overgang van vloeibaar naar gas', k: 'vloeibaar wordt gas', fout: ['Condenseren'] },
      { t: 'Condenseren', d: 'de overgang van gas naar vloeibaar', k: 'gas wordt vloeibaar', fout: ['Verdampen'] },
      { t: 'Smeltpunt', d: 'de temperatuur waarbij een stof smelt', k: 'smelttemperatuur', fout: ['Kookpunt'] },
      { t: 'Kookpunt', d: 'de temperatuur waarbij een stof kookt', k: 'kooktemperatuur', fout: ['Smeltpunt'] },
      { t: 'Vaste stof', d: 'een stof met een vaste vorm en een vast volume', k: 'vaste vorm', fout: ['Vloeistof', 'Gas'] },
      { t: 'Vloeistof', d: 'een stof die vloeit en de vorm van de bak aanneemt', k: 'neemt vorm van de bak aan', fout: ['Vaste stof', 'Gas'] },
      { t: 'Gas', d: 'een stof die de hele beschikbare ruimte vult', k: 'vult de ruimte', fout: ['Vloeistof', 'Vaste stof'] },
      { t: 'Temperatuur-tijdgrafiek', d: 'een grafiek van de temperatuur tegen de tijd bij verwarmen', k: 'temperatuur tegen tijd', fout: ['Faseovergang'] },
    ],
    [
      { v: 'Wat is dichtheid?', o: ['De massa', 'Het volume', 'De massa per volume', 'De temperatuur'], c: 2, d: 1, uo: ['Massa is maar een deel.', 'Volume is maar een deel.', 'Klopt: massa gedeeld door volume.', 'Temperatuur is iets anders.'] },
      { v: 'Een blok van 200 g heeft een volume van 100 cm³. Wat is de dichtheid?', o: ['2 g/cm³', '200 g/cm³', '100 g/cm³', '0,5 g/cm³'], c: 0, d: 3, uo: ['Klopt: 200 / 100 = 2 g/cm³.', 'Dat is de massa.', 'Dat is het volume.', 'Deel massa door volume.'] },
      { v: 'Hoe heet de overgang van vast naar vloeibaar?', o: ['Stollen', 'Smelten', 'Verdampen', 'Condenseren'], c: 1, d: 1, uo: ['Stollen is andersom.', 'Klopt: vast wordt vloeibaar.', 'Dat is vloeibaar naar gas.', 'Dat is gas naar vloeibaar.'] },
      { v: 'Water verdampt. Welke faseovergang is dit?', o: ['Vast naar vloeibaar', 'Gas naar vloeibaar', 'Vloeibaar naar gas', 'Vast naar gas'], c: 2, d: 2, uo: ['Dat is smelten.', 'Dat is condenseren.', 'Klopt: vloeibaar wordt gas.', 'Dat is iets anders.'] },
      { v: 'Bij welke temperatuur smelt een stof?', o: ['Bij het kookpunt', 'Altijd bij nul graden', 'Bij kamertemperatuur', 'Bij het smeltpunt'], c: 3, d: 2, uo: ['Dat is bij koken.', 'Niet elke stof bij nul.', 'Niet per se.', 'Klopt: bij het smeltpunt.'] },
      { v: 'Wat gebeurt er met de temperatuur tijdens het smelten?', o: ['Die blijft even gelijk', 'Die stijgt snel', 'Die daalt', 'Die verdwijnt'], c: 0, d: 2, uo: ['Klopt: tijdens de faseovergang blijft de temperatuur gelijk.', 'Nee, even niet.', 'Nee.', 'Temperatuur verdwijnt niet.'] },
      { v: 'Wat is massa?', o: ['De ruimte die iets inneemt', 'De hoeveelheid stof', 'De dichtheid', 'De temperatuur'], c: 1, d: 1, uo: ['Dat is volume.', 'Klopt: de hoeveelheid stof in gram of kg.', 'Iets anders.', 'Iets anders.'] },
      { v: 'Wat is volume?', o: ['De hoeveelheid stof', 'De massa per volume', 'De ruimte die iets inneemt', 'De warmte'], c: 2, d: 1, uo: ['Dat is massa.', 'Dat is dichtheid.', 'Klopt: de ingenomen ruimte.', 'Iets anders.'] },
      { v: 'IJs wordt water. Hoe heet dat?', o: ['Verdampen', 'Condenseren', 'Stollen', 'Smelten'], c: 3, d: 2, uo: ['Dat is vloeibaar naar gas.', 'Dat is gas naar vloeibaar.', 'Dat is vloeibaar naar vast.', 'Klopt: vast wordt vloeibaar.'] },
      { v: 'Waterdamp wordt weer water. Hoe heet dat?', o: ['Condenseren', 'Smelten', 'Verdampen', 'Stollen'], c: 0, d: 2, uo: ['Klopt: gas wordt vloeibaar.', 'Dat is vast naar vloeibaar.', 'Dat is vloeibaar naar gas.', 'Dat is vloeibaar naar vast.'] },
      { v: 'Een stof met een grote dichtheid is...', o: ['licht voor zijn grootte', 'zwaar voor zijn grootte', 'altijd een vaste stof', 'altijd warm'], c: 1, d: 2, uo: ['Nee, juist zwaar.', 'Klopt: veel massa in weinig volume.', 'Niet per se.', 'Niet per se.'] },
      { v: 'Welke fase heeft een vaste vorm én een vast volume?', o: ['Gas', 'Vloeistof', 'Vaste stof', 'Damp'], c: 2, d: 1, uo: ['Gas vult de ruimte.', 'Vloeistof neemt de vorm van de bak aan.', 'Klopt: een vaste stof.', 'Damp is een gas.'] },
    ]),

  V('B', 'Elektrische energie',
    `In een stroomkring horen <strong>spanning</strong>, <strong>stroomsterkte</strong> en <strong>weerstand</strong> bij elkaar, verbonden door de <strong>wet van Ohm</strong>. In een <strong>serieschakeling</strong> heeft de stroom één weg, in een <strong>parallelschakeling</strong> meerdere.`,
    [
      { h: '1. Stroom, spanning en weerstand', p: [
        `De <strong>stroomsterkte</strong> (in ampère) is de hoeveelheid lading die per seconde stroomt. De <strong>spanning</strong> (in volt) is de duw die de stroom veroorzaakt. De <strong>weerstand</strong> (in ohm) werkt de stroom tegen. Een <strong>geleider</strong> laat stroom goed door, een <strong>isolator</strong> niet.`] },
      { h: '2. De wet van Ohm', p: [
        `Spanning, stroom en weerstand hangen samen: hoe hoger de weerstand bij dezelfde spanning, hoe kleiner de stroom.`],
        formula: { label: 'Wet van Ohm', eq: 'U = I × R', note: 'U de spanning (V), I de stroomsterkte (A), R de weerstand (Ω).' },
        worked: { q: 'Door een lampje loopt 0,5 A bij een spanning van 6 V. Bereken de weerstand.', steps: ['Herschrijf U = I × R naar R = U / I.', 'R = 6 / 0,5.'], ans: 'De weerstand is 12 Ω.' } },
      { h: '3. Serie en parallel', p: [
        `In een <strong>serieschakeling</strong> heeft de stroom maar één weg: gaat één lampje stuk, dan doet de rest het ook niet. In een <strong>parallelschakeling</strong> zijn er takken naast elkaar. Een <strong>kortsluiting</strong> is een verbinding met bijna geen weerstand; een <strong>zekering</strong> onderbreekt dan de stroom.`] },
      { h: '4. Vermogen en energie', p: [
        `Het <strong>vermogen</strong> (in watt) is de energie die per seconde wordt omgezet. De <strong>elektrische energie</strong> die een apparaat gebruikt, hangt af van het vermogen én de tijd dat het aanstaat.`],
        formula: { label: 'Vermogen en energie', eq: 'P = U × I   en   E = P × t', note: 'P het vermogen (W), E de energie (J of Wh), t de tijd.' },
        worked: { q: 'Een apparaat van 100 W staat 2 uur aan. Bereken de gebruikte energie.', steps: ['Gebruik E = P × t.', 'E = 100 W × 2 h.'], ans: 'De energie is 200 Wh (0,2 kWh).' } },
    ],
    [
      { t: 'Stroomsterkte', d: 'de hoeveelheid lading die per seconde stroomt, in ampère', k: 'lading per seconde', fout: ['Spanning', 'Weerstand'] },
      { t: 'Spanning', d: 'de duw die de stroom veroorzaakt, in volt', k: 'de elektrische duw', fout: ['Stroomsterkte', 'Weerstand'] },
      { t: 'Weerstand', d: 'de mate waarin een component de stroom tegenwerkt, in ohm', k: 'werkt de stroom tegen', fout: ['Stroomsterkte', 'Spanning'] },
      { t: 'Wet van Ohm', d: 'het verband tussen spanning, stroom en weerstand (U = I × R)', k: 'U is I maal R', fout: ['Vermogen'] },
      { t: 'Serieschakeling', d: 'een schakeling waarin de stroom maar één weg heeft', k: 'één stroomweg', fout: ['Parallelschakeling'] },
      { t: 'Parallelschakeling', d: 'een schakeling met meerdere takken naast elkaar', k: 'takken naast elkaar', fout: ['Serieschakeling'] },
      { t: 'Vermogen', d: 'de energie die per seconde wordt omgezet, in watt', k: 'energie per seconde', fout: ['Elektrische energie'] },
      { t: 'Elektrische energie', d: 'de energie die een apparaat gebruikt in een bepaalde tijd', k: 'gebruikte energie', fout: ['Vermogen'] },
      { t: 'Geleider', d: 'een materiaal dat de stroom goed doorlaat', k: 'laat stroom door', fout: ['Isolator'] },
      { t: 'Isolator', d: 'een materiaal dat de stroom niet doorlaat', k: 'laat geen stroom door', fout: ['Geleider'] },
      { t: 'Kortsluiting', d: 'een verbinding met heel weinig weerstand', k: 'te weinig weerstand', fout: ['Zekering'] },
      { t: 'Zekering', d: 'een beveiliging die de stroom onderbreekt bij te veel stroom', k: 'beveiliging tegen te veel stroom', fout: ['Kortsluiting'] },
    ],
    [
      { v: 'Wat meet je in ampère?', o: ['De spanning', 'De stroomsterkte', 'De weerstand', 'Het vermogen'], c: 1, d: 1, uo: ['Spanning is in volt.', 'Klopt: stroomsterkte in ampère.', 'Weerstand is in ohm.', 'Vermogen is in watt.'] },
      { v: 'Wat meet je in volt?', o: ['De stroom', 'De weerstand', 'De spanning', 'Het vermogen'], c: 2, d: 1, uo: ['Stroom is in ampère.', 'Weerstand is in ohm.', 'Klopt: spanning in volt.', 'Vermogen in watt.'] },
      { v: 'Wat meet je in ohm?', o: ['De weerstand', 'De spanning', 'De stroom', 'De energie'], c: 0, d: 1, uo: ['Klopt: weerstand in ohm.', 'Spanning in volt.', 'Stroom in ampère.', 'Energie in joule.'] },
      { v: 'Door een lamp loopt 0,5 A bij 6 V. Wat is de weerstand?', o: ['3 ohm', '6 ohm', '0,5 ohm', '12 ohm'], c: 3, d: 3, uo: ['Deel U door I.', 'Dat is de spanning.', 'Dat is de stroom.', 'Klopt: R = U / I = 6 / 0,5 = 12 ohm.'] },
      { v: 'In een serieschakeling heeft de stroom...', o: ['meerdere wegen', 'maar één weg', 'geen weg', 'een dubbele weg'], c: 1, d: 2, uo: ['Dat is parallel.', 'Klopt: één weg door de keten.', 'Er is wel stroom.', 'Onjuist.'] },
      { v: 'Eén lampje gaat stuk en de rest gaat ook uit. Wat voor schakeling?', o: ['Parallel', 'Kortsluiting', 'Serie', 'Geen schakeling'], c: 2, d: 3, uo: ['Bij parallel blijft de rest aan.', 'Iets anders.', 'Klopt: in serie valt alles uit.', 'Er is wel een schakeling.'] },
      { v: 'Wat laat een geleider door?', o: ['Stroom', 'Geen stroom', 'Alleen warmte', 'Alleen licht'], c: 0, d: 1, uo: ['Klopt: een geleider laat stroom door.', 'Dat is een isolator.', 'Niet alleen warmte.', 'Niet alleen licht.'] },
      { v: 'Wat doet een isolator?', o: ['Stroom goed doorlaten', 'Stroom versterken', 'Stroom opwekken', 'Stroom tegenhouden'], c: 3, d: 2, uo: ['Dat is een geleider.', 'Nee.', 'Nee.', 'Klopt: een isolator laat geen stroom door.'] },
      { v: 'Wat is vermogen?', o: ['De totale energie', 'De energie per seconde', 'De spanning', 'De weerstand'], c: 1, d: 2, uo: ['Dat is energie.', 'Klopt: de energie per seconde, in watt.', 'Spanning is iets anders.', 'Weerstand is iets anders.'] },
      { v: 'Een apparaat van 100 W staat 2 uur aan. Hoeveel energie?', o: ['50 Wh', '100 Wh', '200 Wh', '2 Wh'], c: 2, d: 3, uo: ['Onjuist.', 'Dat is het vermogen.', 'Klopt: E = P × t = 100 × 2 = 200 Wh.', 'Dat is de tijd.'] },
      { v: 'Wat is een zekering?', o: ['Een beveiliging tegen te veel stroom', 'Een batterij', 'Een lamp', 'Een schakelaar'], c: 0, d: 1, uo: ['Klopt: onderbreekt de stroom bij te veel stroom.', 'Een batterij levert stroom.', 'Een lamp geeft licht.', 'Iets anders.'] },
      { v: 'Wat gebeurt er bij kortsluiting?', o: ['De stroom stopt netjes', 'Er loopt geen stroom', 'De weerstand stijgt', 'Er loopt heel veel stroom'], c: 3, d: 3, uo: ['Nee.', 'Er loopt juist veel.', 'Nee, juist heel laag.', 'Klopt: bijna geen weerstand, dus heel veel stroom.'] },
    ]),

  V('C', 'Verbranden en verwarmen',
    `Warmte gaat over door <strong>geleiding</strong>, <strong>stroming</strong> of <strong>straling</strong>. Met <strong>isolatie</strong> houd je warmte tegen. Bij <strong>verbranding</strong> reageert een <strong>brandstof</strong> met <strong>zuurstof</strong> en komt er warmte vrij.`,
    [
      { h: '1. Warmtetransport', p: [
        `Warmte kan op drie manieren van warm naar koud gaan. Bij <strong>warmtegeleiding</strong> geeft een stof de warmte door zonder zelf te bewegen (metaal). Bij <strong>warmtestroming</strong> beweegt een vloeistof of gas mee (verwarming in huis). Bij <strong>warmtestraling</strong> gaat de warmte door straling, zonder tussenstof (de zon). Met <strong>isolatie</strong> hou je warmtetransport tegen.`] },
      { h: '2. Verbranding', p: [
        `Bij een <strong>verbranding</strong> reageert een <strong>brandstof</strong> met <strong>zuurstof</strong> en komt warmte vrij. Het <strong>rendement</strong> zegt welk deel van de energie nuttig wordt gebruikt; de rest gaat als warmte verloren.`] },
      { h: '3. Soortelijke warmte', p: [
        `Hoeveel warmte een stof nodig heeft om op te warmen, hangt af van de <strong>soortelijke warmte</strong> (c), de massa en de temperatuurstijging.`],
        formula: { label: 'Warmte', eq: 'Q = c × m × ΔT', note: 'Q de warmte (J), c de soortelijke warmte, m de massa (kg), ΔT de temperatuurstijging (°C).' },
        worked: { q: 'Je verwarmt 2 kg water (c = 4180) van 20 °C naar 30 °C. Bereken de warmte.', steps: ['Bepaal ΔT = 30 − 20 = 10 °C.', 'Q = c × m × ΔT = 4180 × 2 × 10.'], ans: 'Er is 83.600 J warmte nodig.' } },
    ],
    [
      { t: 'Warmtegeleiding', d: 'warmtetransport door een stof zonder dat de stof zelf beweegt', k: 'warmte door een stof', fout: ['Warmtestroming', 'Warmtestraling'] },
      { t: 'Warmtestroming', d: 'warmtetransport doordat een vloeistof of gas beweegt', k: 'warmte met bewegende stof', fout: ['Warmtegeleiding', 'Warmtestraling'] },
      { t: 'Warmtestraling', d: 'warmtetransport via straling, zonder tussenstof', k: 'warmte via straling', fout: ['Warmtegeleiding', 'Warmtestroming'] },
      { t: 'Isolatie', d: 'het tegenhouden van warmtetransport', k: 'warmte tegenhouden', fout: ['Warmtegeleiding'] },
      { t: 'Verbranding', d: 'een reactie met zuurstof waarbij warmte vrijkomt', k: 'reactie met zuurstof', fout: ['Isolatie'] },
      { t: 'Brandstof', d: 'een stof die je verbrandt om energie te krijgen', k: 'stof die je verbrandt', fout: ['Zuurstof'] },
      { t: 'Zuurstof', d: 'het gas dat nodig is voor verbranding', k: 'nodig voor verbranden', fout: ['Brandstof'] },
      { t: 'Soortelijke warmte', d: 'de warmte om één kilogram van een stof één graad op te warmen', k: 'warmte per kg per graad', fout: ['Rendement'] },
      { t: 'Warmtegeleider', d: 'een materiaal dat warmte goed doorlaat', k: 'laat warmte door', fout: ['Warmte-isolator'] },
      { t: 'Warmte-isolator', d: 'een materiaal dat warmte slecht doorlaat', k: 'houdt warmte tegen', fout: ['Warmtegeleider'] },
      { t: 'Rendement', d: 'het deel van de energie dat nuttig wordt gebruikt', k: 'nuttig deel van de energie', fout: ['Soortelijke warmte'] },
      { t: 'Convectie', d: 'een andere naam voor warmtestroming in vloeistof of gas', k: 'stroming van warmte', fout: ['Warmtestroming'] },
    ],
    [
      { v: 'Metaal geeft warmte door zonder zelf te bewegen. Hoe heet dat?', o: ['Warmtestroming', 'Warmtegeleiding', 'Warmtestraling', 'Isolatie'], c: 1, d: 2, uo: ['Bij stroming beweegt de stof.', 'Klopt: geleiding, de stof beweegt niet.', 'Straling gaat door de ruimte.', 'Isolatie houdt warmte tegen.'] },
      { v: 'De zon warmt de aarde op. Hoe gaat die warmte?', o: ['Geleiding', 'Stroming', 'Straling', 'Isolatie'], c: 2, d: 2, uo: ['Geleiding heeft een stof nodig.', 'Stroming heeft een stof nodig.', 'Klopt: straling, zonder tussenstof.', 'Isolatie houdt warmte tegen.'] },
      { v: 'Wat is isolatie?', o: ['Warmte tegenhouden', 'Warmte doorgeven', 'Warmte opwekken', 'Warmte meten'], c: 0, d: 1, uo: ['Klopt: warmtetransport tegenhouden.', 'Dat is geleiding.', 'Nee.', 'Nee.'] },
      { v: 'Wat is nodig voor verbranding?', o: ['Alleen warmte', 'Alleen licht', 'Water', 'Brandstof en zuurstof'], c: 3, d: 2, uo: ['Niet genoeg.', 'Nee.', 'Nee, juist niet.', 'Klopt: brandstof reageert met zuurstof.'] },
      { v: 'Warme lucht stijgt op, koude zakt. Hoe heet dit warmtetransport?', o: ['Geleiding', 'Stroming', 'Straling', 'Verbranding'], c: 1, d: 2, uo: ['Daar beweegt de stof niet.', 'Klopt: stroming met bewegende lucht.', 'Straling gaat door de ruimte.', 'Iets anders.'] },
      { v: 'Wat is rendement?', o: ['Alle energie', 'De verloren energie', 'Het nuttig gebruikte deel', 'De brandstof'], c: 2, d: 2, uo: ['Nee, niet alles.', 'Juist het tegenovergestelde.', 'Klopt: het deel dat nuttig wordt gebruikt.', 'Brandstof is iets anders.'] },
      { v: 'Wat is een goede warmte-isolator?', o: ['Piepschuim', 'Metaal', 'Water', 'Koper'], c: 0, d: 2, uo: ['Klopt: piepschuim houdt warmte tegen.', 'Metaal geleidt juist goed.', 'Water geleidt redelijk.', 'Koper geleidt heel goed.'] },
      { v: 'Waarom voelt metaal koud aan?', o: ['Het maakt zelf kou', 'Het is altijd koud', 'Het straalt kou uit', 'Het geleidt de warmte snel weg'], c: 3, d: 3, uo: ['Kou bestaat niet als stof.', 'Niet altijd.', 'Kou straal je niet uit.', 'Klopt: metaal geleidt je lichaamswarmte snel weg.'] },
      { v: 'Wat komt vrij bij een verbranding?', o: ['Kou', 'Warmte', 'Alleen water', 'Niets'], c: 1, d: 1, uo: ['Nee.', 'Klopt: er komt warmte vrij.', 'Niet alleen water.', 'Er gebeurt wel iets.'] },
      { v: 'Wat is soortelijke warmte?', o: ['De temperatuur', 'De massa', 'De warmte per kg per graad', 'Het volume'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: warmte om 1 kg 1 graad op te warmen.', 'Nee.'] },
      { v: 'Je verwarmt 2 kg water (c = 4180) 10 °C op. Q = c·m·ΔT is...', o: ['83.600 J', '4.180 J', '20.900 J', '2.000 J'], c: 0, d: 3, uo: ['Klopt: 4180 × 2 × 10 = 83.600 J.', 'Dat is c.', 'Onjuist.', 'Dat is de massa in gram.'] },
      { v: 'Waarom draag je in de kou een dikke jas?', o: ['Om warmte te maken', 'Om te stralen', 'Om te verbranden', 'Om warmte binnen te houden'], c: 3, d: 2, uo: ['Een jas maakt geen warmte.', 'Nee.', 'Nee.', 'Klopt: de jas isoleert en houdt je warmte binnen.'] },
    ]),

  V('D', 'Licht en beeld',
    `Licht gaat rechtdoor tot het wordt <strong>teruggekaatst</strong> of <strong>gebroken</strong>. Een <strong>bolle lens</strong> bundelt licht in het <strong>brandpunt</strong>, een <strong>holle lens</strong> spreidt het.`,
    [
      { h: '1. Terugkaatsing en breking', p: [
        `Een <strong>lichtstraal</strong> gaat rechtdoor tot hij een oppervlak raakt. Bij <strong>spiegeling</strong> kaatst het licht terug; de <strong>invalshoek</strong> is dan gelijk aan de terugkaatshoek. Gaat licht van de ene stof naar de andere (lucht naar water), dan verandert het van richting: <strong>lichtbreking</strong>.`] },
      { h: '2. Lenzen en beeld', p: [
        `Een <strong>bolle lens</strong> brengt lichtstralen bij elkaar in het <strong>brandpunt</strong>; een <strong>holle lens</strong> laat ze juist uit elkaar gaan. Zo ontstaat een <strong>beeld</strong>. Een <strong>reëel beeld</strong> kun je op een scherm opvangen; een <strong>virtueel beeld</strong> niet, zoals je spiegelbeeld.`] },
    ],
    [
      { t: 'Lichtstraal', d: 'een rechte lijn die de richting van het licht aangeeft', k: 'richting van licht', fout: ['Lichtbreking'] },
      { t: 'Spiegeling', d: 'het terugkaatsen van licht door een spiegel', k: 'licht kaatst terug', fout: ['Lichtbreking'] },
      { t: 'Lichtbreking', d: 'het veranderen van richting van licht bij overgang naar een andere stof', k: 'licht verandert richting', fout: ['Spiegeling'] },
      { t: 'Lens', d: 'een doorzichtig voorwerp dat licht bundelt of spreidt', k: 'bundelt of spreidt licht', fout: ['Bolle lens', 'Holle lens'] },
      { t: 'Bolle lens', d: 'een lens die lichtstralen bij elkaar brengt', k: 'brengt licht samen', fout: ['Holle lens'] },
      { t: 'Holle lens', d: 'een lens die lichtstralen uit elkaar laat gaan', k: 'spreidt licht', fout: ['Bolle lens'] },
      { t: 'Brandpunt', d: 'het punt waar een bolle lens evenwijdige stralen samenbrengt', k: 'punt waar licht samenkomt', fout: ['Bolle lens'] },
      { t: 'Beeld', d: 'de afbeelding die door een lens of spiegel ontstaat', k: 'afbeelding via lens/spiegel', fout: ['Reëel beeld', 'Virtueel beeld'] },
      { t: 'Reëel beeld', d: 'een beeld dat je op een scherm kunt opvangen', k: 'op te vangen op scherm', fout: ['Virtueel beeld'] },
      { t: 'Virtueel beeld', d: 'een beeld dat je niet kunt opvangen, zoals in een spiegel', k: 'niet op te vangen', fout: ['Reëel beeld'] },
      { t: 'Invalshoek', d: 'de hoek waaronder licht op een oppervlak valt', k: 'hoek van inval', fout: ['Terugkaatsing'] },
      { t: 'Terugkaatsing', d: 'het weerkaatsen van licht tegen een oppervlak', k: 'licht weerkaatst', fout: ['Spiegeling'] },
    ],
    [
      { v: 'Wat gebeurt er bij spiegeling?', o: ['Licht buigt af', 'Licht kaatst terug', 'Licht verdwijnt', 'Licht wordt warmer'], c: 1, d: 2, uo: ['Dat is breking.', 'Klopt: licht kaatst terug.', 'Licht verdwijnt niet.', 'Nee.'] },
      { v: 'Licht gaat van lucht in water en verandert van richting. Hoe heet dat?', o: ['Spiegeling', 'Terugkaatsing', 'Lichtbreking', 'Straling'], c: 2, d: 2, uo: ['Dat is terugkaatsen.', 'Idem.', 'Klopt: lichtbreking bij overgang naar een andere stof.', 'Iets anders.'] },
      { v: 'Wat doet een bolle lens?', o: ['Licht bundelen', 'Licht spreiden', 'Licht tegenhouden', 'Licht kleuren'], c: 0, d: 1, uo: ['Klopt: een bolle lens brengt licht samen.', 'Dat doet een holle lens.', 'Nee.', 'Nee.'] },
      { v: 'Wat doet een holle lens?', o: ['Licht bundelen', 'Licht opwarmen', 'Licht tegenhouden', 'Licht spreiden'], c: 3, d: 2, uo: ['Dat doet een bolle lens.', 'Nee.', 'Nee.', 'Klopt: een holle lens spreidt het licht.'] },
      { v: 'Wat is het brandpunt van een bolle lens?', o: ['Waar de lens breekt', 'Waar het licht samenkomt', 'De rand van de lens', 'Het midden van de lens'], c: 1, d: 2, uo: ['Nee.', 'Klopt: waar evenwijdige stralen samenkomen.', 'Nee.', 'Nee.'] },
      { v: 'Welk beeld kun je op een scherm opvangen?', o: ['Een virtueel beeld', 'Een spiegelbeeld', 'Een reëel beeld', 'Geen enkel beeld'], c: 2, d: 2, uo: ['Dat kun je niet opvangen.', 'Idem.', 'Klopt: een reëel beeld vang je op een scherm.', 'Er is wel een beeld.'] },
      { v: 'Wat voor beeld zie je in een spiegel?', o: ['Een virtueel beeld', 'Een reëel beeld', 'Geen beeld', 'Een warm beeld'], c: 0, d: 2, uo: ['Klopt: een virtueel beeld, niet op te vangen.', 'Dat vang je juist op.', 'Er is wel een beeld.', 'Nee.'] },
      { v: 'Wat is een lichtstraal?', o: ['Een warm punt', 'Een gekleurd vlak', 'Een spiegel', 'Een rechte lijn die de richting toont'], c: 3, d: 1, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: een rechte lijn die de richting van licht toont.'] },
      { v: 'Bij spiegeling is de invalshoek...', o: ['groter dan de terugkaatshoek', 'gelijk aan de terugkaatshoek', 'veel kleiner', 'niet te meten'], c: 1, d: 3, uo: ['Nee.', 'Klopt: de invalshoek is gelijk aan de terugkaatshoek.', 'Nee.', 'Je kunt hem meten.'] },
      { v: 'Waardoor lijkt een rietje in een glas water geknikt?', o: ['Door spiegeling', 'Door warmte', 'Door lichtbreking', 'Door de kleur'], c: 2, d: 3, uo: ['Nee.', 'Nee.', 'Klopt: het licht breekt bij de overgang water-lucht.', 'Nee.'] },
      { v: 'Wat is een lens?', o: ['Doorzichtig voorwerp dat licht buigt', 'Een spiegel', 'Een lamp', 'Een gekleurd glas'], c: 0, d: 1, uo: ['Klopt: een lens bundelt of spreidt licht.', 'Een spiegel kaatst terug.', 'Een lamp geeft licht.', 'Nee.'] },
      { v: 'Een loep vergroot. Wat voor lens zit erin?', o: ['Een holle lens', 'Een spiegel', 'Geen lens', 'Een bolle lens'], c: 3, d: 3, uo: ['Die spreidt juist.', 'Nee.', 'Er zit wel een lens in.', 'Klopt: een bolle lens.'] },
    ]),

  V('E', 'Geluid',
    `<strong>Geluid</strong> bestaat uit <strong>trillingen</strong> die zich door een stof voortplanten. De <strong>frequentie</strong> bepaalt de <strong>toonhoogte</strong>, de <strong>amplitude</strong> de <strong>geluidssterkte</strong>.`,
    [
      { h: '1. Trillingen en geluid', p: [
        `Een <strong>geluidsbron</strong> maakt <strong>trillingen</strong>: heen-en-weergaande bewegingen. Die trillingen planten zich als <strong>geluid</strong> voort door een stof, bijvoorbeeld lucht. In het luchtledige is er geen geluid, want er is niets om te trillen.`] },
      { h: '2. Frequentie en amplitude', p: [
        `De <strong>frequentie</strong> is het aantal trillingen per seconde (in hertz); de <strong>trillingstijd</strong> is de duur van één trilling. Een hoge frequentie geeft een hoge <strong>toonhoogte</strong>. De <strong>amplitude</strong> is de grootte van de uitwijking en bepaalt de <strong>geluidssterkte</strong>: hoe harder het klinkt.`],
        formula: { label: 'Frequentie', eq: 'f = 1 / T', note: 'f de frequentie (Hz), T de trillingstijd (s).' },
        worked: { q: 'Eén trilling duurt 0,01 s. Bereken de frequentie.', steps: ['Gebruik f = 1 / T.', 'f = 1 / 0,01.'], ans: 'De frequentie is 100 Hz.' } },
      { h: '3. Echo en geluidssnelheid', p: [
        `Geluid heeft een <strong>geluidssnelheid</strong> (in lucht ongeveer 340 m/s). Kaatst geluid terug, dan hoor je een <strong>echo</strong>. Met <strong>echopeiling</strong> meet je een afstand door de tijd van de echo te gebruiken.`] },
    ],
    [
      { t: 'Geluid', d: 'trillingen die zich door een stof voortplanten', k: 'voortplantende trillingen', fout: ['Trilling'] },
      { t: 'Trilling', d: 'een heen-en-weergaande beweging', k: 'heen en weer bewegen', fout: ['Frequentie'] },
      { t: 'Frequentie', d: 'het aantal trillingen per seconde, in hertz', k: 'trillingen per seconde', fout: ['Trillingstijd'] },
      { t: 'Trillingstijd', d: 'de tijd van één volledige trilling', k: 'tijd van één trilling', fout: ['Frequentie'] },
      { t: 'Amplitude', d: 'de grootte van de uitwijking van een trilling', k: 'grootte van de uitwijking', fout: ['Frequentie'] },
      { t: 'Toonhoogte', d: 'hoe hoog of laag een toon klinkt; hangt af van de frequentie', k: 'hoog of laag, via frequentie', fout: ['Geluidssterkte'] },
      { t: 'Geluidssterkte', d: 'hoe hard een geluid klinkt; hangt af van de amplitude', k: 'hard of zacht, via amplitude', fout: ['Toonhoogte'] },
      { t: 'Geluidssnelheid', d: 'de snelheid waarmee geluid zich voortplant', k: 'snelheid van geluid', fout: ['Echo'] },
      { t: 'Echo', d: 'geluid dat terugkaatst en je opnieuw hoort', k: 'teruggekaatst geluid', fout: ['Echopeiling'] },
      { t: 'Echopeiling', d: 'het meten van een afstand met teruggekaatst geluid', k: 'afstand meten met echo', fout: ['Echo'] },
      { t: 'Geluidsbron', d: 'het voorwerp dat het geluid maakt', k: 'maakt het geluid', fout: ['Geluid'] },
      { t: 'Decibel', d: 'de eenheid van geluidssterkte', k: 'eenheid van sterkte', fout: ['Geluidssterkte'] },
    ],
    [
      { v: 'Waaruit bestaat geluid?', o: ['Uit licht', 'Uit trillingen', 'Uit warmte', 'Uit stroom'], c: 1, d: 1, uo: ['Nee.', 'Klopt: trillingen die zich voortplanten.', 'Nee.', 'Nee.'] },
      { v: 'Wat is de frequentie?', o: ['De hardheid', 'De duur van één trilling', 'Het aantal trillingen per seconde', 'De snelheid'], c: 2, d: 2, uo: ['Dat is geluidssterkte.', 'Dat is de trillingstijd.', 'Klopt: trillingen per seconde, in hertz.', 'Iets anders.'] },
      { v: 'Wat bepaalt de toonhoogte?', o: ['De frequentie', 'De amplitude', 'De kleur', 'De temperatuur'], c: 0, d: 2, uo: ['Klopt: een hoge frequentie geeft een hoge toon.', 'Dat bepaalt de sterkte.', 'Nee.', 'Nee.'] },
      { v: 'Wat bepaalt hoe hard een geluid klinkt?', o: ['De frequentie', 'De trillingstijd', 'De temperatuur', 'De amplitude'], c: 3, d: 2, uo: ['Dat bepaalt de toonhoogte.', 'Iets anders.', 'Nee.', 'Klopt: de amplitude bepaalt de geluidssterkte.'] },
      { v: 'Een trilling duurt 0,01 s. Wat is de frequentie? (f = 1/T)', o: ['10 Hz', '100 Hz', '1 Hz', '0,01 Hz'], c: 1, d: 3, uo: ['Onjuist.', 'Klopt: 1 / 0,01 = 100 Hz.', 'Onjuist.', 'Dat is de tijd.'] },
      { v: 'Waardoor kan geluid zich NIET voortplanten?', o: ['Door lucht', 'Door water', 'Door het luchtledige', 'Door een muur'], c: 2, d: 3, uo: ['Lucht kan trillen.', 'Water kan trillen.', 'Klopt: in vacuüm is er niets om te trillen.', 'Een muur trilt ook.'] },
      { v: 'Wat is een echo?', o: ['Teruggekaatst geluid', 'Heel hard geluid', 'Een hoge toon', 'Een lichtstraal'], c: 0, d: 1, uo: ['Klopt: geluid dat terugkaatst.', 'Niet per se hard.', 'Nee.', 'Geluid is geen licht.'] },
      { v: 'Waarmee meet je met geluid een afstand?', o: ['Met een frequentie', 'Met de amplitude', 'Met een lens', 'Met echopeiling'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Een lens is voor licht.', 'Klopt: echopeiling gebruikt de tijd van de echo.'] },
      { v: 'Wat is de trillingstijd?', o: ['Het aantal trillingen', 'De tijd van één trilling', 'De hardheid', 'De snelheid'], c: 1, d: 2, uo: ['Dat is de frequentie.', 'Klopt: de duur van één trilling.', 'Nee.', 'Nee.'] },
      { v: 'Wat is de amplitude?', o: ['Het aantal trillingen', 'De toonhoogte', 'De grootte van de uitwijking', 'De snelheid'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: de grootte van de uitwijking.', 'Nee.'] },
      { v: 'Wat is de geluidssnelheid in lucht ongeveer?', o: ['340 m/s', '34 m/s', '3.400 m/s', '1 m/s'], c: 0, d: 2, uo: ['Klopt: ongeveer 340 m/s.', 'Te laag.', 'Te hoog.', 'Veel te laag.'] },
      { v: 'Een lage bromtoon heeft een...', o: ['hoge frequentie', 'grote amplitude', 'korte trillingstijd', 'lage frequentie'], c: 3, d: 3, uo: ['Nee, dat is een hoge toon.', 'Dat gaat over hardheid.', 'Nee.', 'Klopt: een lage toon heeft een lage frequentie.'] },
    ]),

  V('F', 'Kracht en veiligheid',
    `Een <strong>kracht</strong> is een duw of trek, gemeten in <strong>newton</strong>. Een <strong>hefboom</strong> vergroot kracht rond een <strong>draaipunt</strong>. Je <strong>stopafstand</strong> is de reactieafstand plus de <strong>remweg</strong>.`,
    [
      { h: '1. Krachten', p: [
        `Een <strong>kracht</strong> is een duw of trek die een voorwerp kan vervormen of versnellen; de eenheid is de <strong>newton</strong>. De <strong>zwaartekracht</strong> trekt alles naar de aarde. Werken meerdere krachten, dan tel je ze samen tot de <strong>resultante</strong>. Heffen ze elkaar op, dan is er <strong>evenwicht</strong>. De <strong>wrijvingskracht</strong> werkt beweging tegen.`] },
      { h: '2. Hefbomen', p: [
        `Een <strong>hefboom</strong> draait om een <strong>draaipunt</strong> en maakt het mogelijk met weinig kracht een zware last te tillen. Het draai-effect heet het <strong>moment</strong>: kracht maal arm.`],
        formula: { label: 'Moment', eq: 'M = F × r', note: 'M het moment, F de kracht (N), r de arm (afstand tot het draaipunt).' } },
      { h: '3. Snelheid en veiligheid', p: [
        `Voordat je remt, verstrijkt eerst je <strong>reactietijd</strong>: de tijd tussen zien en reageren. De afstand tijdens het remmen is de <strong>remweg</strong>. Samen vormen de reactieafstand en de remweg de <strong>stopafstand</strong>. Bij een hogere snelheid worden beide groter.`] },
    ],
    [
      { t: 'Kracht', d: 'een duw of trek die een voorwerp kan vervormen of versnellen', k: 'duw of trek', fout: ['Moment', 'Zwaartekracht'] },
      { t: 'Zwaartekracht', d: 'de kracht waarmee de aarde aan massa trekt', k: 'aantrekking van de aarde', fout: ['Kracht'] },
      { t: 'Newton', d: 'de eenheid van kracht', k: 'eenheid van kracht', fout: ['Moment'] },
      { t: 'Resultante', d: 'de som van alle krachten op een voorwerp', k: 'som van de krachten', fout: ['Evenwicht'] },
      { t: 'Evenwicht', d: 'de toestand waarin de krachten elkaar opheffen', k: 'krachten heffen elkaar op', fout: ['Resultante'] },
      { t: 'Hefboom', d: 'een staaf die om een draaipunt draait om kracht te vergroten', k: 'staaf om een draaipunt', fout: ['Draaipunt', 'Moment'] },
      { t: 'Draaipunt', d: 'het vaste punt waar een hefboom omheen draait', k: 'punt van draaien', fout: ['Hefboom'] },
      { t: 'Moment', d: 'het draai-effect van een kracht: kracht maal arm', k: 'draai-effect van kracht', fout: ['Kracht'] },
      { t: 'Remweg', d: 'de afstand die je aflegt tijdens het remmen', k: 'afstand tijdens remmen', fout: ['Stopafstand', 'Reactietijd'] },
      { t: 'Reactietijd', d: 'de tijd tussen iets zien en erop reageren', k: 'tijd van zien tot reageren', fout: ['Remweg'] },
      { t: 'Stopafstand', d: 'de reactieafstand plus de remweg', k: 'reactieafstand plus remweg', fout: ['Remweg'] },
      { t: 'Wrijvingskracht', d: 'een kracht die beweging tegenwerkt', k: 'werkt beweging tegen', fout: ['Zwaartekracht'] },
    ],
    [
      { v: 'Wat is een kracht?', o: ['Een soort energie', 'Een duw of trek', 'Een snelheid', 'Een temperatuur'], c: 1, d: 1, uo: ['Nee.', 'Klopt: een duw of trek op een voorwerp.', 'Snelheid is iets anders.', 'Nee.'] },
      { v: 'In welke eenheid meet je kracht?', o: ['In meter', 'In seconde', 'In newton', 'In watt'], c: 2, d: 1, uo: ['Meter is afstand.', 'Seconde is tijd.', 'Klopt: kracht in newton.', 'Watt is vermogen.'] },
      { v: 'Wat is de zwaartekracht?', o: ['De aantrekking van de aarde', 'De wrijving', 'De snelheid', 'De temperatuur'], c: 0, d: 1, uo: ['Klopt: de aarde trekt aan massa.', 'Wrijving is iets anders.', 'Nee.', 'Nee.'] },
      { v: 'Twee even grote krachten heffen elkaar op. Wat is er dan?', o: ['Versnelling', 'Wrijving', 'Beweging', 'Evenwicht'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Niet per se.', 'Klopt: de krachten zijn in evenwicht.'] },
      { v: 'Wat doet een hefboom?', o: ['Kracht altijd verkleinen', 'Met weinig kracht veel tillen', 'Warmte maken', 'Licht buigen'], c: 1, d: 2, uo: ['Niet altijd verkleinen.', 'Klopt: met weinig kracht een zware last tillen.', 'Nee.', 'Nee.'] },
      { v: 'Waar draait een hefboom omheen?', o: ['Om de last', 'Om de kracht', 'Om het draaipunt', 'Om de arm'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: om het draaipunt.', 'De arm is de afstand.'] },
      { v: 'Wat is de stopafstand?', o: ['Reactieafstand plus remweg', 'Alleen de remweg', 'Alleen de reactietijd', 'De snelheid'], c: 0, d: 2, uo: ['Klopt: reactieafstand plus remweg.', 'Dat is maar een deel.', 'Dat is een tijd.', 'Nee.'] },
      { v: 'Wat gebeurt met de remweg bij een hogere snelheid?', o: ['Die wordt korter', 'Die blijft gelijk', 'Die verdwijnt', 'Die wordt langer'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: bij hogere snelheid wordt de remweg langer.'] },
      { v: 'Wat is de reactietijd?', o: ['De tijd van het remmen', 'De tijd tussen zien en reageren', 'De totale ritduur', 'De snelheid'], c: 1, d: 2, uo: ['Dat is de remtijd.', 'Klopt: de tijd tussen zien en reageren.', 'Nee.', 'Nee.'] },
      { v: 'Wat is de resultante?', o: ['Eén losse kracht', 'De wrijving', 'De som van alle krachten', 'Het gewicht'], c: 2, d: 2, uo: ['Nee.', 'Wrijving is één kracht.', 'Klopt: de som van alle krachten samen.', 'Nee.'] },
      { v: 'Wat doet de wrijvingskracht?', o: ['Beweging tegenwerken', 'Beweging versnellen', 'Warmte tegenhouden', 'Licht buigen'], c: 0, d: 2, uo: ['Klopt: wrijving werkt beweging tegen.', 'Juist niet.', 'Nee.', 'Nee.'] },
      { v: 'Waarom is meer afstand houden veiliger bij hoge snelheid?', o: ['De reactietijd verdwijnt', 'De remweg wordt korter', 'Er is geen risico', 'De stopafstand is groter'], c: 3, d: 3, uo: ['Nee.', 'Juist langer.', 'Er is wel risico.', 'Klopt: bij hoge snelheid is de stopafstand groter.'] },
    ]),

  V('G', 'Bouw van de materie',
    `Alle stoffen bestaan uit <strong>atomen</strong>. Zitten atomen aan elkaar, dan vormen ze een <strong>molecuul</strong>. Een <strong>zuivere stof</strong> heeft één soort deeltjes; een <strong>mengsel</strong> meerdere.`,
    [
      { h: '1. Atomen en moleculen', p: [
        `Het kleinste deeltje van een stof is het <strong>atoom</strong>. Zitten atomen aan elkaar vast, dan vormen ze een <strong>molecuul</strong>. Een <strong>element</strong> bestaat uit één soort atomen (bijvoorbeeld zuurstof); een <strong>verbinding</strong> uit meerdere soorten (bijvoorbeeld water).`] },
      { h: '2. Zuivere stof en mengsel', p: [
        `Een <strong>zuivere stof</strong> bestaat uit één soort deeltjes. Een <strong>mengsel</strong> bevat meerdere soorten deeltjes door elkaar. Door <strong>scheiden</strong> (zoals filtreren of indampen) haal je een mengsel weer uit elkaar.`] },
      { h: '3. In het atoom', p: [
        `Een atoom heeft een <strong>atoomkern</strong> met <strong>protonen</strong> (positief) en <strong>neutronen</strong> (ongeladen). Daaromheen bewegen <strong>elektronen</strong> (negatief). Krijgt een atoom lading, bijvoorbeeld door elektronen op te nemen of af te staan, dan is het een <strong>ion</strong>.`] },
    ],
    [
      { t: 'Atoom', d: 'het kleinste deeltje van een element', k: 'kleinste deeltje', fout: ['Molecuul'] },
      { t: 'Molecuul', d: 'een groepje atomen dat aan elkaar zit', k: 'groepje atomen', fout: ['Atoom'] },
      { t: 'Element', d: 'een stof die uit één soort atomen bestaat', k: 'één soort atomen', fout: ['Verbinding'] },
      { t: 'Verbinding', d: 'een stof die uit meerdere soorten atomen bestaat', k: 'meerdere soorten atomen', fout: ['Element'] },
      { t: 'Zuivere stof', d: 'een stof die uit één soort deeltjes bestaat', k: 'één soort deeltjes', fout: ['Mengsel'] },
      { t: 'Mengsel', d: 'een stof die uit meerdere soorten deeltjes door elkaar bestaat', k: 'deeltjes door elkaar', fout: ['Zuivere stof'] },
      { t: 'Atoomkern', d: 'het midden van een atoom met protonen en neutronen', k: 'midden van het atoom', fout: ['Elektron'] },
      { t: 'Elektron', d: 'een negatief geladen deeltje om de kern', k: 'negatief deeltje', fout: ['Proton', 'Neutron'] },
      { t: 'Proton', d: 'een positief geladen deeltje in de kern', k: 'positief deeltje in de kern', fout: ['Neutron', 'Elektron'] },
      { t: 'Neutron', d: 'een ongeladen deeltje in de kern', k: 'ongeladen deeltje', fout: ['Proton', 'Elektron'] },
      { t: 'Ion', d: 'een atoom met een elektrische lading', k: 'geladen atoom', fout: ['Atoom'] },
      { t: 'Scheiden', d: 'een mengsel uit elkaar halen in zuivere stoffen', k: 'mengsel uit elkaar halen', fout: ['Mengsel'] },
    ],
    [
      { v: 'Wat is het kleinste deeltje van een stof?', o: ['Een molecuul', 'Een atoom', 'Een cel', 'Een ion'], c: 1, d: 1, uo: ['Een molecuul bestaat uit atomen.', 'Klopt: het atoom.', 'Een cel hoort bij biologie.', 'Een ion is een geladen atoom.'] },
      { v: 'Wat is een molecuul?', o: ['Eén los atoom', 'Een geladen deeltje', 'Atomen die aan elkaar zitten', 'Een mengsel'], c: 2, d: 2, uo: ['Nee, meer atomen.', 'Dat is een ion.', 'Klopt: een groepje atomen aan elkaar.', 'Iets anders.'] },
      { v: 'Wat is een element?', o: ['Eén soort atomen', 'Meerdere soorten atomen', 'Een mengsel', 'Een ion'], c: 0, d: 2, uo: ['Klopt: bestaat uit één soort atomen.', 'Dat is een verbinding.', 'Nee.', 'Nee.'] },
      { v: 'Water bestaat uit waterstof en zuurstof. Water is een...', o: ['element', 'ion', 'mengsel', 'verbinding'], c: 3, d: 3, uo: ['Element is één soort atoom.', 'Nee.', 'Een verbinding is geen mengsel.', 'Klopt: meerdere soorten atomen verbonden.'] },
      { v: 'Wat is een zuivere stof?', o: ['Deeltjes door elkaar', 'Eén soort deeltjes', 'Een geladen atoom', 'Een oplossing'], c: 1, d: 2, uo: ['Dat is een mengsel.', 'Klopt: één soort deeltjes.', 'Nee.', 'Een oplossing is een mengsel.'] },
      { v: 'Wat is een mengsel?', o: ['Eén soort deeltjes', 'Een enkel atoom', 'Meerdere stoffen door elkaar', 'Een element'], c: 2, d: 2, uo: ['Dat is een zuivere stof.', 'Nee.', 'Klopt: meerdere soorten deeltjes door elkaar.', 'Nee.'] },
      { v: 'Welk deeltje is positief geladen?', o: ['Het proton', 'Het elektron', 'Het neutron', 'Het molecuul'], c: 0, d: 1, uo: ['Klopt: het proton is positief.', 'Het elektron is negatief.', 'Het neutron is ongeladen.', 'Nee.'] },
      { v: 'Welk deeltje is negatief geladen?', o: ['Het proton', 'Het neutron', 'Het atoom', 'Het elektron'], c: 3, d: 2, uo: ['Positief.', 'Ongeladen.', 'Meestal neutraal.', 'Klopt: het elektron is negatief.'] },
      { v: 'Waar zitten de protonen en neutronen?', o: ['In de elektronen', 'In de atoomkern', 'Buiten het atoom', 'Apart in een molecuul'], c: 1, d: 2, uo: ['Nee.', 'Klopt: in de atoomkern.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een ion?', o: ['Een neutraal atoom', 'Een molecuul', 'Een atoom met een lading', 'Een mengsel'], c: 2, d: 2, uo: ['Een ion is juist geladen.', 'Nee.', 'Klopt: een atoom met een elektrische lading.', 'Nee.'] },
      { v: 'Hoe haal je zout uit zout water?', o: ['Door indampen', 'Door bevriezen', 'Door schudden', 'Door te wachten'], c: 0, d: 3, uo: ['Klopt: het water verdampt, het zout blijft achter.', 'Werkt niet goed.', 'Nee.', 'Nee.'] },
      { v: 'Zuurstofgas bestaat uit één soort atomen. Het is een...', o: ['verbinding', 'mengsel', 'ion', 'element'], c: 3, d: 3, uo: ['Verbinding heeft meerdere soorten.', 'Nee.', 'Nee.', 'Klopt: één soort atomen, dus een element.'] },
    ]),

  V('H', 'Straling en stralingsbescherming',
    `<strong>Radioactiviteit</strong> is het uitzenden van <strong>straling</strong> door onstabiele kernen. Er zijn drie soorten: <strong>alfa</strong>, <strong>bèta</strong> en <strong>gamma</strong>. Met <strong>afscherming</strong> en afstand bescherm je jezelf.`,
    [
      { h: '1. Soorten straling', p: [
        `<strong>Radioactiviteit</strong> ontstaat als onstabiele atoomkernen <strong>straling</strong> uitzenden. Er zijn drie soorten: <strong>alfastraling</strong> (zware, geladen deeltjes, weinig doordringend), <strong>betastraling</strong> (snelle elektronen) en <strong>gammastraling</strong> (zeer doordringend, zonder lading). Omdat deze straling deeltjes geladen kan maken, heet ze <strong>ioniserende straling</strong>.`] },
      { h: '2. Halveringstijd en bescherming', p: [
        `De <strong>halveringstijd</strong> is de tijd waarin de helft van de radioactieve kernen vervalt: daarna is de straling gehalveerd. Straling van buitenaf heet <strong>bestraling</strong>; zit het radioactieve materiaal op of in je lichaam, dan is er <strong>besmetting</strong>. Je beschermt je met <strong>afscherming</strong>, afstand en korte blootstelling. De ontvangen hoeveelheid heet de <strong>dosis</strong>, die je meet met een <strong>geigerteller</strong>.`] },
    ],
    [
      { t: 'Straling', d: 'energie die zich door de ruimte verplaatst als golven of deeltjes', k: 'energie door de ruimte', fout: ['Radioactiviteit'] },
      { t: 'Radioactiviteit', d: 'het uitzenden van straling door onstabiele kernen', k: 'kernen zenden straling uit', fout: ['Straling'] },
      { t: 'Alfastraling', d: 'straling van zware, positief geladen deeltjes', k: 'zware geladen deeltjes', fout: ['Betastraling', 'Gammastraling'] },
      { t: 'Betastraling', d: 'straling van snelle elektronen', k: 'snelle elektronen', fout: ['Alfastraling', 'Gammastraling'] },
      { t: 'Gammastraling', d: 'zeer doordringende straling zonder lading', k: 'doordringend, geen lading', fout: ['Alfastraling', 'Betastraling'] },
      { t: 'Ioniserende straling', d: 'straling die deeltjes geladen kan maken', k: 'maakt deeltjes geladen', fout: ['Straling'] },
      { t: 'Halveringstijd', d: 'de tijd waarin de helft van de kernen vervalt', k: 'tijd tot de helft vervalt', fout: ['Dosis'] },
      { t: 'Besmetting', d: 'radioactief materiaal op of in het lichaam', k: 'radioactief materiaal aan je', fout: ['Bestraling'] },
      { t: 'Bestraling', d: 'blootstelling aan straling van buitenaf', k: 'straling van buitenaf', fout: ['Besmetting'] },
      { t: 'Afscherming', d: 'het tegenhouden van straling met een laag materiaal', k: 'straling tegenhouden', fout: ['Halveringstijd'] },
      { t: 'Dosis', d: 'de hoeveelheid ontvangen straling', k: 'hoeveelheid straling', fout: ['Halveringstijd'] },
      { t: 'Geigerteller', d: 'een apparaat dat straling meet', k: 'meet straling', fout: ['Dosis'] },
    ],
    [
      { v: 'Wat is radioactiviteit?', o: ['Licht dat straalt', 'Straling uit onstabiele kernen', 'Warmte uit de zon', 'Geluid'], c: 1, d: 2, uo: ['Nee.', 'Klopt: onstabiele kernen zenden straling uit.', 'Nee.', 'Nee.'] },
      { v: 'Welke straling is het meest doordringend?', o: ['Alfastraling', 'Betastraling', 'Gammastraling', 'Geen enkele'], c: 2, d: 2, uo: ['Alfa is het minst doordringend.', 'Beta zit ertussen.', 'Klopt: gammastraling is zeer doordringend.', 'Nee.'] },
      { v: 'Wat is alfastraling?', o: ['Zware, geladen deeltjes', 'Snelle elektronen', 'Straling zonder lading', 'Gewoon licht'], c: 0, d: 2, uo: ['Klopt: zware, positief geladen deeltjes.', 'Dat is beta.', 'Dat is gamma.', 'Nee.'] },
      { v: 'Wat is de halveringstijd?', o: ['De totale straling', 'De dosis', 'De afstand', 'De tijd waarin de helft vervalt'], c: 3, d: 3, uo: ['Nee.', 'Dosis is iets anders.', 'Nee.', 'Klopt: de tijd waarin de helft van de kernen vervalt.'] },
      { v: 'Hoe bescherm je je tegen straling?', o: ['Dichterbij gaan staan', 'Afscherming en afstand', 'Langer blootstellen', 'Niets doen'], c: 1, d: 2, uo: ['Juist verder weg.', 'Klopt: afscherming, afstand en korte tijd.', 'Juist korter.', 'Bescherming helpt wel.'] },
      { v: 'Radioactief materiaal zit op je huid. Dat heet...', o: ['bestraling', 'halvering', 'een dosis', 'besmetting'], c: 3, d: 3, uo: ['Bestraling komt van buitenaf.', 'Nee.', 'Een dosis is een hoeveelheid.', 'Klopt: materiaal op of in je lichaam is besmetting.'] },
      { v: 'Straling van buitenaf op je lichaam heet...', o: ['bestraling', 'besmetting', 'halvering', 'geleiding'], c: 0, d: 2, uo: ['Klopt: bestraling komt van buitenaf.', 'Besmetting is op of in je lichaam.', 'Nee.', 'Nee.'] },
      { v: 'Waarmee meet je straling?', o: ['Met een thermometer', 'Met een lens', 'Met een weegschaal', 'Met een geigerteller'], c: 3, d: 1, uo: ['Die meet temperatuur.', 'Die is voor licht.', 'Die meet massa.', 'Klopt: een geigerteller meet straling.'] },
      { v: 'Wat is betastraling?', o: ['Zware geladen deeltjes', 'Snelle elektronen', 'Straling zonder lading', 'Warmte'], c: 1, d: 2, uo: ['Dat is alfa.', 'Klopt: snelle elektronen.', 'Dat is gamma.', 'Nee.'] },
      { v: 'Waarom is ioniserende straling gevaarlijk?', o: ['Ze maakt licht', 'Ze warmt op', 'Ze kan cellen beschadigen', 'Ze geeft geluid'], c: 2, d: 3, uo: ['Nee.', 'Niet vooral.', 'Klopt: ze kan deeltjes geladen maken en cellen beschadigen.', 'Nee.'] },
      { v: 'Wat is de dosis?', o: ['De hoeveelheid ontvangen straling', 'De halveringstijd', 'De afstand', 'De soort straling'], c: 0, d: 2, uo: ['Klopt: de hoeveelheid ontvangen straling.', 'Iets anders.', 'Nee.', 'Nee.'] },
      { v: 'Wat houdt gammastraling het beste tegen?', o: ['Een vel papier', 'Je hand', 'Lucht', 'Een dikke laag lood'], c: 3, d: 3, uo: ['Papier houdt alfa tegen.', 'Nee.', 'Nee.', 'Klopt: gamma is doordringend, dik lood helpt.'] },
    ]),
];
