// VMBO Economie - situaties per begrip. { domein: { begrip: [situatie1, situatie2] } }
export default {
  A: {
    Koopkracht: ['Door de prijsstijging kun je van hetzelfde loon minder kopen dan vorig jaar', 'Hoeveel spullen je met je inkomen kunt kopen'],
    Inkomen: ['Aan het eind van de maand krijg je je salaris op je rekening', 'Het geld dat je binnenkrijgt uit werk of uitkering'],
    Uitgaven: ['Je betaalt deze maand huur, boodschappen en je telefoonabonnement', 'Al het geld dat je besteedt'],
    Sparen: ['Je zet elke maand een deel van je zakgeld opzij voor later', 'Geld niet uitgeven maar bewaren'],
    Budget: ['Op een lijstje zet je wat er binnenkomt en wat eruit gaat', 'Een overzicht van je inkomsten en uitgaven'],
    Budgetteren: ['Voordat de maand begint, plan je precies waar je geld aan uitgeeft', 'Van tevoren je uitgaven plannen zodat je niet tekortkomt'],
    Inflatie: ['De boodschappen worden elk jaar duurder, alles kost meer', 'Het algemeen stijgen van de prijzen'],
    Deflatie: ['De prijzen in de winkels dalen, alles wordt goedkoper', 'Het algemeen dalen van de prijzen'],
    Indexcijfer: ['Ten opzichte van het basisjaar honderd staan de prijzen nu op honderdtien', 'Een getal dat een verandering ten opzichte van een basisjaar laat zien'],
    'Reëel inkomen': ['Je loon is gestegen, maar door de inflatie kun je er niet meer van kopen', 'Je inkomen gecorrigeerd voor de prijsstijging'],
    'Nominaal inkomen': ['Op je loonstrook staat gewoon het bedrag in euro\'s dat je verdient', 'Je inkomen in euro\'s, zonder rekening te houden met inflatie'],
    Verzekering: ['Je betaalt maandelijks een bedrag zodat schade aan je fiets vergoed wordt', 'Een afspraak die je beschermt tegen de kosten van pech of schade'],
    Premie: ['Elke maand schrijf je een vast bedrag over aan je zorgverzekeraar', 'Het bedrag dat je periodiek voor een verzekering betaalt'],
    'Eigen risico': ['De eerste 385 euro van je zorgkosten betaal je zelf, de rest vergoedt de verzekeraar', 'Het deel van de schade dat je zelf moet betalen'],
  },
  B: {
    Consumentenrecht: ['Als koper heb je wettelijke rechten als een product kapot blijkt', 'De rechten die jij als koper hebt tegenover de verkoper'],
    Garantie: ['Je nieuwe telefoon gaat binnen een jaar stuk en de winkel repareert hem gratis', 'De belofte dat een gebrekkig product hersteld of vervangen wordt'],
    Retourrecht: ['De trui die je online kocht mag je binnen veertien dagen terugsturen', 'Het recht om een aankoop terug te sturen'],
    Bedenktijd: ['Na een online bestelling heb je nog twee weken om je te bedenken', 'De periode waarin je een koop nog kunt annuleren'],
    Consumentenorganisatie: ['Een club komt op voor de belangen van kopers en waarschuwt voor oplichting', 'Een organisatie die de belangen van consumenten behartigt'],
    Consumentenbond: ['Deze organisatie test producten en geeft kopers advies', 'De vereniging die producten test en consumenten adviseert'],
    Klacht: ['Je stuurt de winkel een bericht dat je bestelling beschadigd aankwam', 'Een melding dat een product of dienst niet voldoet'],
    Keurmerk: ['Op de verpakking staat een logo dat de kwaliteit garandeert', 'Een teken dat aangeeft dat iets aan bepaalde eisen voldoet'],
    'Algemene voorwaarden': ['In de kleine lettertjes staan alle regels van de koop', 'De vaste regels en voorwaarden bij een overeenkomst'],
    Koopovereenkomst: ['Zodra je akkoord gaat, ontstaat er een afspraak tussen jou en de verkoper', 'De afspraak tussen koper en verkoper over een product'],
    'Aankoop op afstand': ['Je koopt een spel via een webshop zonder de winkel te bezoeken', 'Iets kopen zonder in de winkel te zijn, bijvoorbeeld online'],
    Consument: ['Jij koopt en gebruikt producten voor jezelf', 'De persoon die producten koopt en gebruikt'],
  },
  C: {
    Brutoloon: ['Dit is je loon voordat er belasting en premies vanaf gaan', 'Je loon vóór de inhoudingen'],
    Nettoloon: ['Dit is het bedrag dat je uiteindelijk op je rekening krijgt', 'Je loon nadat de inhoudingen eraf zijn'],
    Loonheffing: ['De werkgever houdt belasting en premies al in op je loon', 'De belasting en premies die van je brutoloon worden ingehouden'],
    Arbeidsverdeling: ['In de fabriek doet ieder een eigen deel van het werk', 'Het werk opsplitsen in aparte taken'],
    Specialisatie: ['Eén werknemer doet alleen nog het lassen en wordt daar heel goed in', 'Je richten op één taak, die je daardoor beter beheerst'],
    Arbeidsproductiviteit: ['Elke werknemer maakt gemiddeld tien producten per uur', 'De hoeveelheid productie per werknemer'],
    Werknemer: ['Je werkt tegen loon in dienst van een baas', 'Iemand die in loondienst werkt'],
    Werkgever: ['Het bedrijf neemt nieuwe mensen aan en betaalt hun loon', 'Degene die mensen in dienst neemt'],
    Cao: ['In een akkoord voor de hele bedrijfstak staan de arbeidsvoorwaarden', 'Afspraken over loon en werk voor een hele bedrijfstak'],
    Minimumloon: ['De wet bepaalt het laagste loon dat een baas mag betalen', 'Het wettelijk laagste loon'],
    Vakbond: ['Een organisatie onderhandelt namens de werknemers over hun loon', 'Een organisatie die opkomt voor werknemers'],
    Productiefactor: ['Arbeid, grond en kapitaal zijn nodig om iets te maken', 'Een middel dat je nodig hebt om te produceren'],
  },
  D: {
    Omzet: ['Je verkocht honderd broden van twee euro, samen tweehonderd euro', 'De prijs vermenigvuldigd met het aantal verkochte producten'],
    Verkoopprijs: ['De prijs op het kaartje die de klant betaalt', 'De prijs waarvoor je een product verkoopt'],
    Inkoopprijs: ['De winkel betaalt de leverancier één euro per brood', 'De prijs die je zelf voor een product betaalt bij inkoop'],
    Btw: ['Op de bon staat naast de prijs ook de belasting die je meebetaalt', 'De belasting die in de verkoopprijs zit'],
    Winst: ['Na aftrek van alle kosten houdt de ondernemer geld over', 'Wat er overblijft als je de kosten van de opbrengst aftrekt'],
    Kosten: ['De ondernemer betaalt voor grondstoffen, huur en loon', 'De uitgaven die je maakt om te kunnen produceren'],
    'Constante kosten': ['De huur van het pand blijft elke maand hetzelfde, hoeveel je ook maakt', 'Kosten die gelijk blijven, ongeacht hoeveel je produceert'],
    'Variabele kosten': ['Hoe meer broden je bakt, hoe meer meel je moet kopen', 'Kosten die meebewegen met de hoeveelheid productie'],
    'Totale kosten': ['Je telt de vaste huur en de meebewegende grondstofkosten bij elkaar op', 'De vaste plus de meebewegende kosten samen'],
    Brutowinst: ['Je trekt van de omzet af wat de verkochte spullen je aan inkoop kostten', 'De omzet min de inkoopwaarde van wat je verkocht'],
    Winstmarge: ['Op elk product zit het verschil tussen wat je ervoor betaalt en verkoopt', 'Het verschil tussen verkoop- en inkoopprijs'],
    'Break-even': ['Je verkoopt precies genoeg om je kosten te dekken, zonder winst of verlies', 'Het punt waarop de omzet precies gelijk is aan de kosten'],
  },
  E: {
    Belasting: ['Iedereen betaalt verplicht een deel van zijn inkomen aan de staat', 'Een verplichte betaling aan de overheid'],
    'Directe belasting': ['Over je inkomen betaal je rechtstreeks belasting aan de staat', 'Belasting die je rechtstreeks over je inkomen betaalt'],
    'Indirecte belasting': ['In de prijs van je frisdrank zit al belasting verstopt', 'Belasting die verstopt zit in de prijs van een product'],
    Inkomstenbelasting: ['Over wat je verdient draag je een percentage af aan de staat', 'De belasting die je over je inkomen betaalt'],
    Accijns: ['Op benzine, alcohol en tabak zit een extra heffing', 'Een extra belasting op bepaalde producten'],
    'Collectieve voorziening': ['De overheid regelt wegen en onderwijs voor iedereen samen', 'Iets dat de overheid voor alle burgers regelt'],
    Subsidie: ['De overheid geeft geld om zonnepanelen aantrekkelijker te maken', 'Geld van de overheid om iets te stimuleren'],
    Uitkering: ['Wie geen werk heeft, krijgt geld van de overheid om rond te komen', 'Geld van de overheid voor wie te weinig inkomen heeft'],
    Begroting: ['De overheid maakt vooraf een plan van alle inkomsten en uitgaven', 'Een plan van verwachte inkomsten en uitgaven'],
    Staatsschuld: ['Alles wat de overheid in de loop van de jaren heeft geleend', 'Het totale bedrag dat de staat heeft geleend'],
    Infrastructuur: ['Wegen, bruggen en spoorlijnen verbinden het hele land', 'De voorzieningen zoals wegen en verbindingen'],
    Overheidstaak: ['Zorgen voor veiligheid en onderwijs hoort bij de overheid', 'Een taak die de overheid op zich neemt'],
  },
  F: {
    Import: ['Nederland koopt bananen uit het buitenland', 'Het invoeren van goederen uit het buitenland'],
    Export: ['Nederland verkoopt kaas aan andere landen', 'Het uitvoeren van goederen naar het buitenland'],
    Handelsbalans: ['Je vergelijkt wat een land uitvoert met wat het invoert', 'Het verschil tussen de export en de import van een land'],
    Wisselkoers: ['Voor één euro krijg je vandaag ongeveer één dollar en tien cent', 'De prijs van de ene munt uitgedrukt in een andere'],
    Euro: ['In Nederland, Duitsland en Frankrijk betaal je met dezelfde munt', 'De gemeenschappelijke munt van veel EU-landen'],
    'Europese Unie': ['Zevenentwintig landen werken samen op het gebied van handel en regels', 'Het samenwerkingsverband van Europese landen'],
    'Interne markt': ['Binnen de EU mogen goederen vrij over de grenzen', 'De vrije handel zonder grenzen binnen de EU'],
    Invoerrechten: ['Op producten van buiten de EU moet extra belasting betaald worden', 'Belasting die je betaalt bij het invoeren van goederen'],
    Ontwikkelingssamenwerking: ['Rijke landen helpen arme landen met geld en kennis', 'Hulp van rijke landen aan arme landen'],
    Vrijhandel: ['Landen handelen met elkaar zonder heffingen of drempels', 'Handel drijven zonder belemmeringen'],
    Protectionisme: ['Een land heft hoge invoerrechten om eigen bedrijven te beschermen', 'De eigen markt beschermen tegen buitenlandse concurrentie'],
    Globalisering: ['Bedrijven, landen en mensen over de hele wereld raken steeds meer verbonden', 'Het steeds meer verweven raken van landen en economieën'],
  },
  G: {
    Milieukosten: ['De schade aan de natuur door een fabriek kost de samenleving geld', 'De kosten die milieuschade met zich meebrengt'],
    'Externe kosten': ['De vervuiling van een bedrijf wordt betaald door de hele samenleving', 'Kosten die niet de veroorzaker maar de samenleving draagt'],
    'Vervuiler-betaalt-principe': ['Het bedrijf dat vervuilt, moet zelf voor de opruiming opdraaien', 'De regel dat degene die vervuilt de kosten betaalt'],
    'Duurzaam produceren': ['De fabriek maakt spullen met zo min mogelijk schade aan het milieu', 'Produceren met zorg voor mens en milieu'],
    'Circulaire economie': ['Oude producten worden weer grondstof voor nieuwe, niets is afval', 'Een economie waarin grondstoffen steeds hergebruikt worden'],
    Recycling: ['Van oud papier wordt weer nieuw papier gemaakt', 'Afval verwerken tot nieuwe grondstof'],
    Grondstof: ['Uit hout wordt papier gemaakt', 'Het basismateriaal waarmee je een product maakt'],
    Uitputting: ['Als we doorgaan met winnen, raakt de olie ooit op', 'Het opraken van een grondstof'],
    'Duurzame ontwikkeling': ['Groei die ook voor toekomstige generaties leefbaar blijft', 'Vooruitgang die de aarde niet uitput'],
    'Fossiele brandstof': ['Een kolencentrale draait op brandstof uit de aarde die opraakt', 'Brandstof zoals olie, gas en kolen die opraakt'],
    'Groene energie': ['Windmolens leveren stroom uit een bron die niet opraakt', 'Energie uit bronnen die niet opraken'],
    Consuminderen: ['Je koopt bewust minder spullen om het milieu te sparen', 'Bewust minder spullen kopen en gebruiken'],
  },
  H: {
    Rente: ['Voor het lenen van geld betaal je de bank een vergoeding', 'De vergoeding die je betaalt of krijgt voor geld'],
    'Samengestelde interest': ['Je krijgt niet alleen rente over je inleg, maar ook rente over eerdere rente', 'Rente die je ook over de eerder bijgeschreven rente krijgt'],
    'Enkelvoudige interest': ['Je krijgt elk jaar rente alleen over het bedrag dat je in het begin inlegde', 'Rente die alleen over het startbedrag wordt berekend'],
    Sparen: ['Je zet elke maand geld op je spaarrekening opzij', 'Geld opzijzetten voor later'],
    Lenen: ['Je krijgt van de bank geld dat je later moet terugbetalen', 'Geld tijdelijk gebruiken dat je moet terugbetalen'],
    Hypotheek: ['Voor de aankoop van een huis sluit je een grote lening af', 'Een lening om een huis te kopen'],
    'Centrale bank': ['Deze bank bewaakt de waarde van het geld in een land', 'De bank die het geldstelsel bewaakt'],
    Rentestand: ['De bank verlaagt het percentage dat je voor een lening betaalt', 'De hoogte van de rente op dat moment'],
    Aflossing: ['Elke maand betaal je een deel van je lening terug', 'Het terugbetalen van een lening'],
    Onderpand: ['Als je de lening niet betaalt, mag de bank je huis verkopen', 'Iets van waarde als zekerheid voor een lening'],
    Krediet: ['De winkel biedt je de mogelijkheid om later te betalen', 'De mogelijkheid om geld te lenen'],
    Inflatie: ['Je spaargeld wordt minder waard omdat alles duurder wordt', 'Het algemeen stijgen van de prijzen'],
  },
  I: {
    Ondernemer: ['Zij start haar eigen bedrijf en neemt daarbij risico', 'Iemand die een eigen bedrijf begint en runt'],
    Ondernemingsplan: ['Voor de start schrijft ze op wat ze gaat doen en hoe', 'Een plan waarin staat hoe je je bedrijf opzet'],
    Startkapitaal: ['Om te beginnen heeft ze geld nodig voor voorraad en een pand', 'Het geld dat je nodig hebt om een bedrijf te starten'],
    Investering: ['Ze koopt een oven en een bakfiets voor haar bedrijf', 'Geld dat je in bedrijfsmiddelen steekt'],
    Marktonderzoek: ['Voor de start vraagt ze klanten wat zij willen', 'Onderzoek naar wat de markt en klanten willen'],
    Doelgroep: ['Haar broodjes zijn vooral bedoeld voor studenten', 'De groep klanten waar je je op richt'],
    Concurrent: ['Twee straten verderop zit een andere bakker', 'Een ander bedrijf dat om dezelfde klanten strijdt'],
    Kostprijs: ['Eén broodje maken kost haar tachtig cent aan ingrediënten en werk', 'De kosten die één product je kosten'],
    Winstmarge: ['Ze verkoopt voor twee euro wat haar tachtig cent kost, dat verschil is haar winst', 'Het verschil tussen verkoopprijs en kostprijs'],
    Financiering: ['Ze regelt geld via spaargeld en een banklening', 'De manier waarop je aan geld komt voor je bedrijf'],
    Risico: ['Als niemand haar broodjes koopt, verliest ze haar geld', 'De kans dat je verlies lijdt'],
    Rechtsvorm: ['Ze kiest of ze een eenmanszaak of een bv wordt', 'De juridische vorm van een bedrijf'],
  },
};
