// VMBO Natuur- en scheikunde 1 - situaties per begrip.
export default {
  A: {
    Dichtheid: ['Een blok ijzer is veel zwaarder dan een even groot blok hout', 'De massa van een stof per hoeveelheid ruimte'],
    Massa: ['Op de weegschaal lees je af hoeveel stof een voorwerp bevat', 'De hoeveelheid stof in een voorwerp, in kilogram'],
    Volume: ['Hoeveel ruimte een pak melk inneemt, meet je in liters', 'De ruimte die een voorwerp inneemt'],
    Faseovergang: ['Water gaat van ijs naar vloeibaar of naar damp', 'Een overgang van de ene fase naar de andere'],
    Smelten: ['Een ijsblokje wordt in de zon vanzelf water', 'De overgang van vast naar vloeibaar'],
    Stollen: ['Vloeibaar kaarsvet wordt weer hard als het afkoelt', 'De overgang van vloeibaar naar vast'],
    Verdampen: ['Een natte plas droogt op doordat het water damp wordt', 'De overgang van vloeibaar naar gas'],
    Condenseren: ['Op een koude spiegel slaat de waterdamp neer tot druppels', 'De overgang van gas naar vloeibaar'],
    Smeltpunt: ['De temperatuur waarbij ijs overgaat in water is nul graden', 'De temperatuur waarbij een stof smelt'],
    Kookpunt: ['De temperatuur waarbij water gaat koken is honderd graden', 'De temperatuur waarbij een stof kookt'],
    'Vaste stof': ['Een steen houdt zijn eigen vaste vorm', 'Een stof met een eigen, vaste vorm'],
    Vloeistof: ['Water neemt de vorm aan van het glas waarin je het giet', 'Een stof die de vorm van de bak aanneemt'],
    Gas: ['Lucht verspreidt zich door de hele ruimte', 'Een stof die de hele beschikbare ruimte vult'],
    'Temperatuur-tijdgrafiek': ['In een grafiek zie je hoe de temperatuur tijdens het opwarmen oploopt', 'Een grafiek van de temperatuur tegen de tijd'],
  },
  B: {
    Stroomsterkte: ['Hoeveel lading er per seconde door de draad gaat, meet je in ampère', 'De hoeveelheid lading die per seconde stroomt'],
    Spanning: ['De batterij geeft de elektrische duw die de stroom laat lopen, in volt', 'De elektrische duw die de stroom aandrijft'],
    Weerstand: ['Een dunne draad werkt de stroom tegen en wordt warm', 'Datgene wat de stroom tegenwerkt, in ohm'],
    'Wet van Ohm': ['Spanning is stroomsterkte maal weerstand', 'De formule U is I maal R'],
    Serieschakeling: ['De lampjes staan achter elkaar op één draad, gaat er één stuk dan gaan ze allemaal uit', 'Een schakeling met maar één stroomweg'],
    Parallelschakeling: ['De lampjes hangen in aparte takken naast elkaar, gaat er één stuk dan branden de andere door', 'Een schakeling met meerdere takken naast elkaar'],
    Vermogen: ['Hoeveel energie een apparaat per seconde gebruikt, meet je in watt', 'De energie die per seconde wordt gebruikt'],
    'Elektrische energie': ['De energiemeter telt hoeveel stroom je huis in totaal verbruikt', 'De hoeveelheid elektrische energie die gebruikt wordt'],
    Geleider: ['Een koperdraad laat de stroom makkelijk door', 'Een stof die de stroom goed doorlaat'],
    Isolator: ['Het rubber om een stekker laat geen stroom door', 'Een stof die de stroom niet doorlaat'],
    Kortsluiting: ['Twee draden raken elkaar en de stroom neemt een te korte weg', 'Een verbinding met veel te weinig weerstand'],
    Zekering: ['Bij te veel stroom smelt een draadje door en valt de stroom uit', 'Een beveiliging die de stroom bij gevaar onderbreekt'],
  },
  C: {
    Warmtegeleiding: ['De steel van een metalen pan wordt vanzelf ook heet', 'Warmte die zich door een vaste stof verplaatst'],
    Warmtestroming: ['Warme lucht boven de verwarming stijgt op en verspreidt de warmte', 'Warmte die meebeweegt met een stromende stof'],
    Warmtestraling: ['De zon warmt je gezicht op zonder dat er iets tussen zit', 'Warmte die via straling door de lege ruimte gaat'],
    Isolatie: ['Dubbel glas houdt de warmte binnen in huis', 'Het tegenhouden van warmte'],
    Verbranding: ['Hout brandt op doordat het met zuurstof reageert en warmte geeft', 'Een reactie van een brandstof met zuurstof'],
    Brandstof: ['In de kachel stook je hout of gas om warmte te krijgen', 'Een stof die je verbrandt om energie te krijgen'],
    Zuurstof: ['Zonder dit gas uit de lucht kan een vuur niet branden', 'Het gas dat nodig is voor verbranding'],
    'Soortelijke warmte': ['Water heeft veel energie nodig om één graad op te warmen', 'De warmte die nodig is om één kilogram één graad op te warmen'],
    Warmtegeleider: ['Een metalen lepel wordt snel heet in de soep', 'Een stof die warmte goed doorlaat'],
    'Warmte-isolator': ['Een houten pannenlepel blijft koel aan het uiteinde', 'Een stof die warmte slecht doorlaat'],
    Rendement: ['Van alle energie die een lamp gebruikt, wordt maar een deel nuttig licht', 'Het deel van de energie dat nuttig wordt gebruikt'],
    Convectie: ['In een pan water stijgt het warme water op en zakt het koude', 'Warmtetransport door een stromende vloeistof of gas'],
  },
  D: {
    Lichtstraal: ['Een dunne bundel licht gaat in een rechte lijn vooruit', 'De rechte lijn die de richting van licht aangeeft'],
    Spiegeling: ['Het licht kaatst terug op het gladde wateroppervlak', 'Het terugkaatsen van licht op een oppervlak'],
    Lichtbreking: ['Een rietje in een glas water lijkt geknikt doordat het licht van richting verandert', 'Het van richting veranderen van licht bij een overgang'],
    Lens: ['Door dit gebogen stukje glas zie je dingen groter of kleiner', 'Een gebogen stuk glas dat licht bundelt of spreidt'],
    'Bolle lens': ['Deze lens brengt de lichtstralen samen in één punt', 'Een lens die het licht bundelt'],
    'Holle lens': ['Deze lens laat de lichtstralen juist uit elkaar gaan', 'Een lens die het licht spreidt'],
    Brandpunt: ['Achter een bolle lens komen alle stralen in één punt samen', 'Het punt waar een bolle lens het licht samenbrengt'],
    Beeld: ['Via de lens ontstaat een afbeelding van het voorwerp', 'De afbeelding die door een lens of spiegel ontstaat'],
    'Reëel beeld': ['Dit beeld kun je opvangen op een scherm, zoals in de bioscoop', 'Een beeld dat je op een scherm kunt opvangen'],
    'Virtueel beeld': ['Het beeld in de spiegel kun je niet op een scherm opvangen', 'Een beeld dat je niet op een scherm kunt opvangen'],
    Invalshoek: ['De hoek waaronder de lichtstraal op de spiegel valt', 'De hoek tussen de invallende straal en de loodlijn'],
    Terugkaatsing: ['Het licht botst op de spiegel en gaat weer terug', 'Het weerkaatsen van licht op een oppervlak'],
  },
  E: {
    Geluid: ['Trillingen planten zich door de lucht voort en bereiken je oor', 'Trillingen die zich door de lucht voortplanten'],
    Trilling: ['Een gitaarsnaar beweegt snel heen en weer', 'Het heen en weer bewegen om een ruststand'],
    Frequentie: ['Het aantal trillingen per seconde, gemeten in hertz', 'Het aantal trillingen per seconde'],
    Trillingstijd: ['De tijd die één volledige trilling duurt', 'De tijd van één trilling'],
    Amplitude: ['Hoe ver de snaar maximaal uit zijn ruststand komt', 'De grootte van de uitwijking van een trilling'],
    Toonhoogte: ['Een fluit klinkt hoger dan een basgitaar door de snellere trilling', 'Hoe hoog of laag een toon klinkt, bepaald door de frequentie'],
    Geluidssterkte: ['Hoe harder je slaat, hoe luider het geluid door de grotere uitwijking', 'Hoe hard of zacht een geluid is, bepaald door de amplitude'],
    Geluidssnelheid: ['Geluid gaat door lucht met ongeveer 340 meter per seconde', 'De snelheid waarmee geluid zich voortplant'],
    Echo: ['Je roept in de bergen en hoort je stem even later terug', 'Geluid dat wordt teruggekaatst'],
    Echopeiling: ['Een schip meet de diepte door een geluid naar de bodem te sturen en terug te horen', 'Afstand meten met behulp van een echo'],
    Geluidsbron: ['De luidspreker maakt de trillingen die je hoort', 'Datgene wat het geluid maakt'],
    Decibel: ['De sterkte van geluid meet je in deze eenheid', 'De eenheid van geluidssterkte'],
  },
  F: {
    Kracht: ['Je duwt of trekt aan een kar om hem te laten bewegen', 'Een duw of trek op een voorwerp'],
    Zwaartekracht: ['Een appel valt naar beneden doordat de aarde hem aantrekt', 'De aantrekkingskracht van de aarde'],
    Newton: ['De grootte van een kracht meet je in deze eenheid', 'De eenheid waarin je kracht meet'],
    Resultante: ['Twee mensen duwen dezelfde kant op, samen is de kracht groter', 'De totale kracht als je alle krachten optelt'],
    Evenwicht: ['Bij touwtrekken trekken beide teams even hard en beweegt het touw niet', 'De toestand waarin de krachten elkaar opheffen'],
    Hefboom: ['Met een lange staaf over een steunpunt til je makkelijk een zware steen', 'Een staaf die om een draaipunt draait'],
    Draaipunt: ['Het steunpunt waar de wip omheen kantelt', 'Het punt waar een hefboom om draait'],
    Moment: ['Hoe verder van het draaipunt je duwt, hoe sterker het draai-effect', 'Het draai-effect van een kracht'],
    Remweg: ['De afstand die de auto nog aflegt vanaf het moment dat je remt', 'De afstand die je aflegt tijdens het remmen'],
    Reactietijd: ['De tijd tussen het zien van gevaar en het intrappen van de rem', 'De tijd tussen zien en reageren'],
    Stopafstand: ['De totale afstand van gevaar zien tot volledig stilstaan', 'De reactieafstand plus de remweg'],
    Wrijvingskracht: ['Een rollende bal komt vanzelf tot stilstand door de wrijving', 'De kracht die een beweging tegenwerkt'],
  },
  G: {
    Atoom: ['Het allerkleinste deeltje waaruit een stof is opgebouwd', 'Het kleinste bouwsteentje van een stof'],
    Molecuul: ['Een groepje atomen zit aan elkaar vast, zoals in water', 'Een groepje atomen dat aan elkaar zit'],
    Element: ['Zuiver goud bestaat uit maar één soort atomen', 'Een stof die uit één soort atomen bestaat'],
    Verbinding: ['Water bestaat uit waterstof- en zuurstofatomen samen', 'Een stof uit meerdere soorten atomen'],
    'Zuivere stof': ['Puur, gedestilleerd water bevat maar één soort moleculen', 'Een stof die uit één soort deeltjes bestaat'],
    Mengsel: ['In zeewater zitten water en zout door elkaar', 'Twee of meer stoffen door elkaar'],
    Atoomkern: ['In het midden van het atoom zit de zware, positieve kern', 'Het zware midden van een atoom'],
    Elektron: ['Om de kern heen bewegen de negatief geladen deeltjes', 'Het negatief geladen deeltje in een atoom'],
    Proton: ['In de kern zit dit positief geladen deeltje', 'Het positief geladen deeltje in de kern'],
    Neutron: ['In de kern zit ook dit deeltje zonder lading', 'Het ongeladen deeltje in de kern'],
    Ion: ['Een atoom dat een elektron mist of er een extra heeft, is geladen', 'Een atoom met een elektrische lading'],
    Scheiden: ['Je haalt zout en water uit elkaar door in te dampen', 'Een mengsel weer uit elkaar halen'],
  },
  H: {
    Straling: ['Energie die door de ruimte reist, zoals van de zon of een radioactieve stof', 'Energie die zich door de ruimte verplaatst'],
    Radioactiviteit: ['Sommige stoffen zenden vanzelf straling uit doordat hun kernen vervallen', 'Het uitzenden van straling door onstabiele kernen'],
    Alfastraling: ['Deze zware, geladen deeltjes worden al door een vel papier tegengehouden', 'Zware geladen deeltjes die weinig doordringen'],
    Betastraling: ['Deze snelle elektronen dringen verder door dan alfastraling', 'Snelle elektronen als straling'],
    Gammastraling: ['Deze straling zonder lading dringt zelfs door dik lood heen', 'Zeer doordringende straling zonder lading'],
    'Ioniserende straling': ['Deze straling slaat elektronen los en maakt deeltjes geladen', 'Straling die deeltjes geladen maakt'],
    Halveringstijd: ['Na deze tijd is de helft van de radioactieve stof vervallen', 'De tijd waarin de helft van een stof vervalt'],
    Besmetting: ['Er zit radioactief stof op je kleding of huid', 'Radioactief materiaal dat op of in je lichaam komt'],
    Bestraling: ['Je wordt van buitenaf door een stralingsbron geraakt', 'Het geraakt worden door straling van buitenaf'],
    Afscherming: ['Een dikke laag lood houdt de straling tegen', 'Het tegenhouden van straling met materiaal'],
    Dosis: ['De hoeveelheid straling die iemand heeft opgelopen', 'De hoeveelheid straling die je ontvangt'],
    Geigerteller: ['Een apparaat tikt sneller naarmate er meer straling is', 'Een apparaat dat straling meet'],
  },
};
