// VMBO Nederlands - situaties per begrip.
export default {
  A: {
    Feit: ['In de krant staat dat Amsterdam de hoofdstad van Nederland is', 'Iets wat je kunt controleren en wat voor iedereen waar is', 'Water kookt bij honderd graden, dat kun je nameten'],
    Mening: ['Iemand zegt dat vla het lekkerste toetje is', 'Een persoonlijk oordeel dat niet te bewijzen is', 'Volgens mij is de zomer het mooiste seizoen'],
    Hoofdzaak: ['De belangrijkste boodschap van het nieuwsbericht in één zin', 'Het belangrijkste punt van een verhaal'],
    Bijzaak: ['Een klein, onbelangrijk detail dat je makkelijk kunt weglaten', 'Een minder belangrijk detail naast de kern'],
    Argument: ['Ze zegt dat de school later moet beginnen, want tieners slapen langer', 'Een reden waarmee je een mening onderbouwt'],
    Standpunt: ['Hij verdedigt dat huiswerk afgeschaft moet worden', 'De mening die iemand in een discussie verdedigt'],
    Spreekdoel: ['De spreker wil dat je iets gaat doen, geloven of weten', 'Wat de spreker met zijn verhaal wil bereiken'],
    Informeren: ['De docent legt uit hoe de waterkringloop werkt', 'Iemand iets uitleggen of vertellen met feiten'],
    Overtuigen: ['De reclame wil je laten geloven dat dit merk het beste is', 'Iemands mening proberen te veranderen'],
    Amuseren: ['De cabaretier vertelt grappen om het publiek te laten lachen', 'Het publiek vermaken'],
  },
  B: {
    Formeel: ['In een sollicitatiebrief gebruik je nette, zakelijke taal', 'Nette taal die past bij onbekenden of een baas', 'De u-vorm, geen straattaal, keurige zinnen'],
    Informeel: ['Tegen je vrienden praat je los, met woorden als joh en gaaf', 'De losse taal die je onder vrienden gebruikt', 'De jij-vorm, afkortingen en spreektaal'],
    Register: ['Je kiest een andere toon bij je oma dan bij je vrienden', 'De stijl van taal die past bij de situatie', 'Aanpassen hoe je praat aan met wie je praat'],
    Standpunt: ['Zij verdedigt in het debat dat schooluniformen goed zijn', 'De mening die je in een discussie inneemt', 'Het punt dat jij verdedigt met argumenten'],
    Argument: ['Hij zegt: minder auto\'s, want dat is beter voor het milieu', 'Een reden die je eigen mening ondersteunt', 'Waarmee je onderbouwt waarom je gelijk hebt'],
    Tegenargument: ['De ander brengt in dat het juist duurder wordt', 'Een reden die tegen een standpunt ingaat', 'Een punt waarmee je iemands mening bestrijdt'],
    Overtuigen: ['Met sterke argumenten probeer je de ander mee te krijgen', 'De ander van je mening zien te winnen', 'Zorgen dat iemand het uiteindelijk met je eens is'],
    'Actief luisteren': ['Je knikt, vraagt door en gaat in op wat de ander zegt', 'Echt luisteren en op de ander reageren', 'Niet alleen wachten op je beurt, maar meedenken'],
  },
  C: {
    Tekstdoel: ['De schrijver wil je iets laten weten, geloven of doen', 'Wat de schrijver met de tekst wil bereiken', 'De ene tekst wil informeren, de andere overtuigen of vermaken'],
    Informerend: ['Een tekst legt met feiten uit hoe vulkanen werken', 'Een tekst die uitlegt en informatie geeft'],
    Overtuigend: ['Een betoog probeert je te laten geloven dat je minder vlees moet eten', 'Een tekst die je mening wil veranderen'],
    Instruerend: ['Een gebruiksaanwijzing legt stap voor stap uit hoe iets werkt', 'Een tekst die uitlegt hoe je iets moet doen'],
    Activerend: ['Een reclame zet je aan om meteen te kopen', 'Een tekst die je tot actie wil aanzetten'],
    Signaalwoord: ['Het woordje maar laat zien dat er een tegenstelling komt', 'Een woord dat het verband tussen zinnen aangeeft', 'Het woordje daarom laat zien dat er een gevolg komt'],
    Verwijswoord: ['Het woordje die verwijst terug naar iets dat eerder genoemd is', 'Een woord dat terugwijst naar iets eerder in de tekst'],
    Alinea: ['Een stukje tekst over één deelonderwerp, met een witregel ervoor', 'Een tekstdeel dat één onderwerp behandelt'],
    Kernzin: ['De ene zin waarin de hoofdgedachte van de alinea staat', 'De zin met de belangrijkste boodschap van een alinea'],
    Hoofdgedachte: ['Als je de hele tekst in één zin zou samenvatten', 'De belangrijkste boodschap van de hele tekst'],
  },
  D: {
    Stam: ['Van het werkwoord werken haal je -en eraf en houd je werk over', 'Het hele werkwoord zonder de uitgang -en', 'Bij lopen is dit loop'],
    'Ik-vorm': ['Bij ik hoort de kale vorm zonder -t: ik loop, ik werk', 'De vorm van het werkwoord die bij ik hoort', 'De stam zonder er iets achter'],
    'Stam plus t': ['Bij hij en zij komt er een -t achter: hij loopt, zij werkt', 'De vorm bij hij of zij, met een -t erachter', 'Bij hij vindt komt na de stam een t'],
    "'t Kofschip": ['Dit ezelsbruggetje helpt je kiezen tussen -t en -d in een voltooid deelwoord', 'De truc met de letters t, k, f, s, ch, p voor -t of -d', 'Eindigt de stam op een k, dan is het gewerkt met een t'],
    'Voltooid deelwoord': ['De ge-vorm van het werkwoord: gewerkt, gefietst, gelopen', 'De vorm met ge- ervoor, zoals in ik heb gewerkt', 'Bij hebben of zijn hoort deze ge-vorm'],
    Inleiding: ['Het eerste deel van je tekst, waarin je het onderwerp aankondigt', 'Het begin van een tekst dat het onderwerp introduceert', 'Hier open je en maak je de lezer nieuwsgierig'],
    Kern: ['Het middendeel waarin je het onderwerp helemaal uitwerkt', 'Het grootste deel van de tekst, met de uitwerking', 'Hier staat de meeste informatie van je betoog'],
    Slot: ['Het laatste deel waarin je samenvat en afsluit', 'Het einde van de tekst met een conclusie', 'Hier rond je af en trek je een conclusie'],
  },
  E: {
    'Ik-perspectief': ['Het verhaal wordt verteld door ik, een van de personages', 'De verteller doet mee in het verhaal en zegt ik', 'Je leest alles vanuit de ogen van ik'],
    'Hij-perspectief': ['Een buitenstaander vertelt over hem en haar', 'De verteller staat buiten het verhaal en gebruikt hij en zij', 'Iemand die niet meedoet vertelt over de personages'],
    Personage: ['Een van de figuren die in het verhaal voorkomt', 'Een karakter dat een rol speelt in het verhaal', 'De jongen en het meisje in het boek'],
    Hoofdpersoon: ['De figuur om wie het verhaal vooral draait', 'Het belangrijkste personage van het verhaal', 'De persoon die je door het hele boek volgt'],
    Thema: ['Waar het verhaal eigenlijk over gaat, bijvoorbeeld vriendschap', 'Het hoofdonderwerp of de boodschap van het verhaal', 'De grote gedachte achter het hele verhaal'],
    Spanning: ['Je leest door omdat je wil weten hoe het afloopt', 'Het gevoel dat je nieuwsgierig maakt naar de afloop', 'Je hart klopt sneller als de held in gevaar is'],
    Cliffhanger: ['Het hoofdstuk stopt precies op het spannendste moment', 'Een open, spannend einde waardoor je verder wil lezen', 'Net als het gevaarlijk wordt, is het hoofdstuk uit'],
    Genre: ['Dit boek is een echte thriller, vol spanning en misdaad', 'De soort waartoe een verhaal behoort, zoals sciencefiction', 'Een detective, een romance of een griezelverhaal'],
    Motief: ['Door het hele boek komt steeds het beeld van een sleutel terug', 'Een element of idee dat telkens terugkeert', 'Een steeds herhaald symbool of onderwerp'],
  },
};
