// VMBO GL/TL - Biologie. Gouden-stijl contentspec → scripts/expand-leerdoelen.mjs.
// Per domein: intro + secties (prosa, formuleboxen, voorbeeldopgaven) voor de
// samenvatting, plus concepten (t/d/k/fout) die de vraagbank én flashcards voeden.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vmbo', vak: 'bi', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Cellen aan de basis',
    `Alle levende wezens bestaan uit <strong>cellen</strong>. In dit domein leer je hoe cellen zijn opgebouwd, waarin een plantencel verschilt van een dierlijke cel, en hoe eigenschappen via <strong>DNA</strong> worden doorgegeven bij een <strong>monohybride kruising</strong>.`,
    [
      { h: '1. Van cel tot organisme', p: [
        `De <strong>cel</strong> is de kleinste bouwsteen van een organisme. Cellen met dezelfde vorm en functie vormen samen een <strong>weefsel</strong> (bijvoorbeeld spierweefsel). Meerdere weefsels die samen een taak uitvoeren vormen een <strong>orgaan</strong>, zoals het hart. Organen die samenwerken aan één functie vormen een <strong>orgaanstelsel</strong>, zoals het bloedvatenstelsel.`,
        `Deze volgorde van klein naar groot (cel → weefsel → orgaan → orgaanstelsel → organisme) heet de organisatie van het lichaam. Elke laag is opgebouwd uit de laag eronder.`] },
      { h: '2. De bouw van een cel', p: [
        `Elke cel wordt omsloten door een <strong>celmembraan</strong> dat bepaalt welke stoffen erin en eruit gaan. In de <strong>celkern</strong> ligt het <strong>DNA</strong>. De rest van de cel is gevuld met <strong>cytoplasma</strong>, de vloeistof waarin de celonderdelen liggen.`,
        `Een plantencel heeft drie extra onderdelen die een dierlijke cel niet heeft: een stevige <strong>celwand</strong>, <strong>bladgroenkorrels</strong> voor de fotosynthese en een grote <strong>vacuole</strong> met vocht.`] },
      { h: '3. DNA, genen en chromosomen', p: [
        `Het <strong>DNA</strong> bevat alle erfelijke informatie. Een klein stukje DNA met de code voor één eigenschap heet een <strong>gen</strong>. Als DNA sterk wordt opgerold, vormt het een <strong>chromosoom</strong>; die zijn zichtbaar bij een celdeling.`,
        `Het <strong>genotype</strong> is de erfelijke aanleg (alle genen), het <strong>fenotype</strong> is wat je daarvan ziet: de waarneembare eigenschappen. Het fenotype ontstaat uit het genotype én invloeden van de omgeving.`] },
      { h: '4. Kruisingen en overerving', p: [
        `Van elk gen heb je twee versies (allelen), één van elke ouder. Een <strong>dominant allel</strong> bepaalt de eigenschap al als het één keer aanwezig is; een <strong>recessief allel</strong> komt alleen tot uiting als beide allelen recessief zijn. Bij een <strong>monohybride kruising</strong> volg je één eigenschap.`],
        worked: { q: 'Kruis twee planten met genotype Aa. A (rood) is dominant over a (wit). Welke kleurverhouding krijg je?', steps: ['Zet de allelen in een kruisingsschema: Aa × Aa.', 'De mogelijke combinaties zijn AA, Aa, Aa en aa.', 'AA en Aa geven rood, aa geeft wit.'], ans: 'De verhouding is 3 rood : 1 wit.' } },
      { h: '5. Natuurlijke selectie', p: [
        `Individuen binnen een soort verschillen van elkaar. Bij <strong>natuurlijke selectie</strong> overleven en planten de individuen zich voort die het best zijn aangepast aan hun omgeving. Zo geven zij hun gunstige eigenschappen door en verandert een soort langzaam.`] },
    ],
    [
      { t: 'Cel', d: 'de kleinste bouwsteen van een organisme', k: 'kleinste bouwsteen', fout: ['Weefsel', 'Orgaan'] },
      { t: 'Weefsel', d: 'een groep cellen met dezelfde vorm en functie', k: 'groep gelijke cellen', fout: ['Cel', 'Orgaan'] },
      { t: 'Orgaan', d: 'een structuur van meerdere weefsels met een eigen taak', k: 'meerdere weefsels met een taak', fout: ['Weefsel', 'Orgaanstelsel'] },
      { t: 'Orgaanstelsel', d: 'organen die samen één functie uitvoeren', k: 'samenwerkende organen', fout: ['Orgaan', 'Weefsel'] },
      { t: 'Celmembraan', d: 'het dunne laagje dat de cel omsluit en stoffen doorlaat', k: 'omhulsel van de cel', fout: ['Celwand', 'Celkern'] },
      { t: 'Celkern', d: 'het celonderdeel waarin het DNA ligt', k: 'bevat het DNA', fout: ['Cytoplasma', 'Celmembraan'] },
      { t: 'Cytoplasma', d: 'de vloeistof in de cel waarin de onderdelen liggen', k: 'vloeistof in de cel', fout: ['Celkern', 'Vacuole'] },
      { t: 'Celwand', d: 'de stevige buitenlaag om een plantencel', k: 'stevige laag bij planten', fout: ['Celmembraan'] },
      { t: 'Bladgroenkorrel', d: 'plantencelonderdeel dat de fotosynthese uitvoert', k: 'doet fotosynthese', fout: ['Vacuole', 'Celwand'] },
      { t: 'Vacuole', d: 'een grote blaas met vocht in een plantencel', k: 'vochtblaas in plantencel', fout: ['Bladgroenkorrel', 'Cytoplasma'] },
      { t: 'Chromosoom', d: 'een streng van sterk opgerold DNA in de celkern', k: 'opgerold DNA', fout: ['Gen', 'DNA'] },
      { t: 'DNA', d: 'de stof met de erfelijke informatie', k: 'erfelijke informatie', fout: ['Gen', 'Chromosoom'] },
      { t: 'Gen', d: 'een stukje DNA met de code voor één eigenschap', k: 'code voor een eigenschap', fout: ['DNA', 'Chromosoom'] },
      { t: 'Genotype', d: 'de erfelijke aanleg (de genen) van een organisme', k: 'de genen', fout: ['Fenotype', 'DNA'] },
      { t: 'Fenotype', d: 'de waarneembare eigenschappen van een organisme', k: 'zichtbare eigenschappen', fout: ['Genotype'] },
      { t: 'Dominant allel', d: 'een allel dat het fenotype al bepaalt als het aanwezig is', k: 'overheerst altijd', fout: ['Recessief allel'] },
      { t: 'Recessief allel', d: 'een allel dat alleen tot uiting komt bij twee exemplaren', k: 'alleen dubbel zichtbaar', fout: ['Dominant allel'] },
      { t: 'Natuurlijke selectie', d: 'het beter overleven en voortplanten van best aangepaste individuen', k: 'best aangepasten overleven', fout: ['Fenotype'] },
    ],
    [
      { v: 'Cellen met dezelfde vorm en functie vormen samen...', o: ['een orgaan', 'een weefsel', 'een orgaanstelsel', 'een organisme'], c: 1, d: 2, u: 'Cellen met dezelfde vorm en functie vormen een weefsel.', uo: ['Een orgaan bestaat uit meerdere weefsels.', 'Klopt: gelijke cellen vormen een weefsel.', 'Een orgaanstelsel is een groep samenwerkende organen.', 'Een organisme is het hele levende wezen.'], uh: 'Cel → weefsel → orgaan → orgaanstelsel.' },
      { v: 'Het hart bestaat uit spierweefsel, zenuwweefsel en bloedvaten. Het hart is dus...', o: ['een cel', 'een weefsel', 'een orgaan', 'een orgaanstelsel'], c: 2, d: 2, u: 'Een orgaan bestaat uit meerdere weefsels die samen een taak hebben.', uo: ['Een cel is de kleinste bouwsteen.', 'Een weefsel is één soort cellen.', 'Klopt: meerdere weefsels vormen een orgaan.', 'Een orgaanstelsel is een groep organen.'], uh: 'Orgaan = meerdere weefsels met een taak.' },
      { v: 'Je ziet onder de microscoop een cel met een celwand en bladgroenkorrels. Wat voor cel is dit?', o: ['Een dierlijke cel', 'Een zenuwcel', 'Een rode bloedcel', 'Een plantencel'], c: 3, d: 3, u: 'Alleen plantencellen hebben een celwand en bladgroenkorrels.', uo: ['Een dierlijke cel heeft geen celwand.', 'Een zenuwcel is een dierlijke cel.', 'Een rode bloedcel is een dierlijke cel.', 'Klopt: celwand en bladgroen horen bij planten.'], uh: 'Celwand + bladgroen = plantencel.' },
      { v: 'Welk onderdeel heeft een plantencel wél en een dierlijke cel niet?', o: ['Een celwand', 'Een celkern', 'Een celmembraan', 'Cytoplasma'], c: 0, d: 2, u: 'De celwand komt alleen bij plantencellen voor.', uo: ['Klopt: de celwand is er bij planten.', 'Een celkern zit in beide.', 'Een celmembraan zit in beide.', 'Cytoplasma zit in beide.'], uh: 'Celwand: alleen bij planten.' },
      { v: 'Waar in de cel ligt het DNA?', o: ['In het cytoplasma', 'In de celkern', 'In het celmembraan', 'In de vacuole'], c: 1, d: 1, u: 'Het DNA ligt in de celkern.', uo: ['Het cytoplasma is de vloeistof eromheen.', 'Klopt: het DNA ligt in de celkern.', 'Het celmembraan is de buitenkant.', 'De vacuole is een vochtblaas in planten.'], uh: 'DNA zit in de celkern.' },
      { v: 'Hoe heet het dunne laagje dat de hele cel omsluit?', o: ['De celkern', 'De celwand', 'Het celmembraan', 'Het cytoplasma'], c: 2, d: 1, u: 'Het celmembraan omsluit de cel en regelt wat er in en uit gaat.', uo: ['De celkern bevat het DNA.', 'De celwand zit alleen bij planten.', 'Klopt: het celmembraan omsluit de cel.', 'Cytoplasma is de vloeistof in de cel.'], uh: 'Celmembraan = omhulsel van de cel.' },
      { v: 'Wat is de functie van de bladgroenkorrels in een plantencel?', o: ['Het DNA bewaren', 'De cel stevig maken', 'Vocht opslaan', 'Fotosynthese uitvoeren'], c: 3, d: 2, u: 'In de bladgroenkorrels vindt de fotosynthese plaats.', uo: ['Het DNA zit in de celkern.', 'De celwand maakt de cel stevig.', 'De vacuole slaat vocht op.', 'Klopt: bladgroen doet de fotosynthese.'], uh: 'Bladgroenkorrel = fotosynthese.' },
      { v: 'Hoe heet een stukje DNA met de code voor één eigenschap?', o: ['Een gen', 'Een chromosoom', 'Een cel', 'Een weefsel'], c: 0, d: 1, u: 'Een gen is een stukje DNA met de code voor één eigenschap.', uo: ['Klopt: een gen codeert voor één eigenschap.', 'Een chromosoom is opgerold DNA.', 'Een cel is de bouwsteen van het lichaam.', 'Een weefsel is een groep cellen.'], uh: 'Gen = code voor één eigenschap.' },
      { v: 'Wat is een chromosoom?', o: ['De vloeistof in de cel', 'Sterk opgerold DNA', 'Het omhulsel van de cel', 'Een soort weefsel'], c: 1, d: 2, u: 'Een chromosoom is sterk opgerold DNA in de celkern.', uo: ['De vloeistof in de cel is cytoplasma.', 'Klopt: een chromosoom is opgerold DNA.', 'Het omhulsel is het celmembraan.', 'Een weefsel is een groep cellen.'], uh: 'Chromosoom = opgerold DNA.' },
      { v: 'Iemand heeft blauwe ogen. Die blauwe ogen zijn een voorbeeld van het...', o: ['genotype', 'gen', 'fenotype', 'chromosoom'], c: 2, d: 2, u: 'Het fenotype is wat je aan de buitenkant ziet, zoals oogkleur.', uo: ['Het genotype is de erfelijke aanleg die je niet ziet.', 'Een gen is een stukje DNA.', 'Klopt: wat je ziet is het fenotype.', 'Een chromosoom is opgerold DNA.'], uh: 'Fenotype = wat je ziet.' },
      { v: 'Wat wordt bedoeld met het genotype van een organisme?', o: ['De zichtbare eigenschappen', 'Het aantal cellen', 'De grootte', 'De erfelijke aanleg (de genen)'], c: 3, d: 2, u: 'Het genotype is de erfelijke aanleg: alle genen samen.', uo: ['De zichtbare eigenschappen zijn het fenotype.', 'Het aantal cellen zegt niets over het genotype.', 'De grootte hoort bij het fenotype.', 'Klopt: het genotype is de erfelijke aanleg.'], uh: 'Genotype = de genen.' },
      { v: 'Je kruist twee planten met genotype Aa. A (rood) is dominant over a (wit). Welk deel is naar verwachting wit?', o: ['1 op de 4', '2 op de 4', '3 op de 4', '4 op de 4'], c: 0, d: 3, u: 'Aa × Aa geeft AA, Aa, Aa en aa: 1 op de 4 is aa (wit).', uo: ['Klopt: alleen aa is wit, dus 1 op de 4.', '2 op de 4 klopt niet, alleen aa is wit.', '3 op de 4 is juist rood.', 'Niet alle nakomelingen zijn wit.'], uh: 'Aa × Aa → 3 : 1.' },
      { v: 'Een plant heeft genotype Bb. B (paars) is dominant over b (wit). Welke kleur heeft de plant?', o: ['Wit', 'Paars', 'Half paars, half wit', 'Geen kleur'], c: 1, d: 3, u: 'Het dominante allel B bepaalt de kleur, dus de plant is paars.', uo: ['Wit zou alleen bij genotype bb.', 'Klopt: het dominante B maakt de plant paars.', 'Kleuren mengen niet bij dominantie.', 'Elke plant heeft een kleur.'], uh: 'Het dominante allel bepaalt het fenotype.' },
      { v: 'Een eigenschap komt alleen tot uiting als beide allelen ervoor aanwezig zijn. Zo\'n allel noem je...', o: ['dominant', 'een chromosoom', 'recessief', 'een fenotype'], c: 2, d: 2, u: 'Een recessief allel komt alleen tot uiting bij twee exemplaren.', uo: ['Een dominant allel is al bij één exemplaar zichtbaar.', 'Een chromosoom is opgerold DNA.', 'Klopt: recessief heeft er twee nodig.', 'Een fenotype is een zichtbare eigenschap.'], uh: 'Recessief = alleen dubbel zichtbaar.' },
      { v: 'Konijnen met een dikke vacht overleven de kou beter en krijgen meer jongen. Dit heet...', o: ['fotosynthese', 'een kruising', 'celdeling', 'natuurlijke selectie'], c: 3, d: 3, u: 'Bij natuurlijke selectie overleven de best aangepaste individuen en geven hun eigenschappen door.', uo: ['Fotosynthese is het maken van voedsel door planten.', 'Een kruising combineert twee ouders.', 'Celdeling is het delen van een cel.', 'Klopt: de best aangepaste konijnen overleven.'], uh: 'Best aangepast overleeft: natuurlijke selectie.' },
      { v: 'Waarom lijken kinderen vaak op hun ouders?', o: ['Doordat ze DNA van hun ouders erven', 'Doordat ze hetzelfde eten', 'Doordat ze in hetzelfde huis wonen', 'Doordat ze evenveel cellen hebben'], c: 0, d: 2, u: 'Kinderen erven DNA (genen) van hun ouders, met daarin de erfelijke eigenschappen.', uo: ['Klopt: ze erven het DNA van hun ouders.', 'Wat je eet verandert je DNA niet.', 'Waar je woont bepaalt je genen niet.', 'Iedereen heeft heel veel cellen.'], uh: 'Eigenschappen erf je via DNA.' },
      { v: 'Wat is de kleinste bouwsteen van een organisme?', o: ['Een orgaan', 'Een cel', 'Een weefsel', 'Een chromosoom'], c: 1, d: 1, u: 'De cel is de kleinste bouwsteen van een organisme.', uo: ['Een orgaan is uit veel cellen opgebouwd.', 'Klopt: de cel is de kleinste bouwsteen.', 'Een weefsel is een groep cellen.', 'Een chromosoom zit ín een cel.'], uh: 'Cel = kleinste bouwsteen.' },
      { v: 'Het hart en de bloedvaten werken samen om bloed rond te pompen. Samen vormen ze...', o: ['een weefsel', 'een orgaan', 'een orgaanstelsel', 'een cel'], c: 2, d: 2, u: 'Organen die samen één functie uitvoeren vormen een orgaanstelsel.', uo: ['Een weefsel is één soort cellen.', 'Een orgaan is één structuur, zoals het hart.', 'Klopt: samenwerkende organen vormen een orgaanstelsel.', 'Een cel is de kleinste bouwsteen.'], uh: 'Orgaanstelsel = samenwerkende organen.' },
      { v: 'Hoe heet de vloeistof in de cel waarin de onderdelen liggen?', o: ['De celkern', 'De celwand', 'De vacuole', 'Het cytoplasma'], c: 3, d: 2, u: 'Het cytoplasma is de vloeistof in de cel waarin de onderdelen zweven.', uo: ['De celkern bevat het DNA.', 'De celwand zit alleen bij planten.', 'De vacuole is een vochtblaas.', 'Klopt: het cytoplasma is de celvloeistof.'], uh: 'Cytoplasma = vloeistof in de cel.' },
      { v: 'Een grote vacuole vol vocht houdt een plant stevig. Bij welke cel hoort een grote vacuole?', o: ['Een plantencel', 'Een dierlijke cel', 'Een bacterie', 'Een rode bloedcel'], c: 0, d: 3, u: 'Een grote vacuole komt voor in plantencellen.', uo: ['Klopt: de vacuole hoort bij de plantencel.', 'Dierlijke cellen hebben geen grote vacuole.', 'Een bacterie is heel anders gebouwd.', 'Een rode bloedcel is een dierlijke cel.'], uh: 'Vacuole = plantencel.' },
      { v: 'Wat is de functie van het DNA in een cel?', o: ['De cel stevig maken', 'De erfelijke informatie bevatten', 'Vocht opslaan', 'Zuurstof vervoeren'], c: 1, d: 2, u: 'Het DNA bevat de erfelijke informatie van het organisme.', uo: ['Stevigheid komt van de celwand.', 'Klopt: DNA bevat de erfelijke informatie.', 'Vocht slaat de vacuole op.', 'Zuurstof vervoeren doen rode bloedcellen.'], uh: 'DNA = erfelijke informatie.' },
      { v: 'Bij een kruising is 3 op de 4 nakomelingen rood en 1 op de 4 wit. Wat weet je over de kleur rood?', o: ['Rood is recessief', 'Rood en wit zijn even sterk', 'Rood is dominant', 'Kleur is niet erfelijk'], c: 2, d: 3, u: 'De verhouding 3 op 1 hoort bij een dominante eigenschap (rood).', uo: ['Als rood recessief was, zou juist wit vaker voorkomen.', 'Dan zou je geen 3 op 1 zien.', 'Klopt: de verhouding 3 op 1 wijst op dominant rood.', 'Kleur wordt juist wél geërfd.'], uh: '3 op 1: de meerderheid is dominant.' },
      { v: 'Welk van deze hoort bij het organisatieniveau weefsel?', o: ['Het hart', 'Het bloedvatenstelsel', 'Een levercel', 'Spierweefsel'], c: 3, d: 2, u: 'Spierweefsel bestaat uit cellen met dezelfde vorm en functie: een weefsel.', uo: ['Het hart is een orgaan.', 'Het bloedvatenstelsel is een orgaanstelsel.', 'Een levercel is één cel.', 'Klopt: spierweefsel is een weefsel.'], uh: 'Weefsel = groep gelijke cellen.' },
      { v: 'Twee planten met hetzelfde genotype: de ene staat in de zon en groeit groter. Wat bepaalt dit verschil?', o: ['De omgeving', 'Alleen het genotype', 'Het aantal chromosomen', 'Het celmembraan'], c: 0, d: 3, u: 'Het fenotype ontstaat uit het genotype én invloeden van de omgeving.', uo: ['Klopt: de omgeving (zon) maakt het verschil.', 'Het genotype is juist gelijk.', 'Het aantal chromosomen is gelijk.', 'Het celmembraan speelt hier geen rol.'], uh: 'Fenotype = genotype + omgeving.' },
    ]),

  V('B', 'In stand houden van het organisme',
    `Het lichaam heeft <strong>stevigheid</strong> en <strong>bescherming</strong> nodig. De <strong>huid</strong> houdt ziekteverwekkers en uitdroging tegen, en het <strong>skelet</strong> geeft steun en vorm.`,
    [
      { h: '1. De huid beschermt', p: [
        `De <strong>huid</strong> is het grootste orgaan en beschermt tegen uitdroging, kou en ziekteverwekkers. Bovenop ligt de <strong>opperhuid</strong>, met daaronder de <strong>lederhuid</strong> vol zenuwen en bloedvaten, en daaronder het <strong>onderhuids bindweefsel</strong> met vet dat warmte vasthoudt.`,
        `In de huid zitten klieren: een <strong>talgklier</strong> geeft huidvet af dat de huid soepel houdt, en een <strong>zweetklier</strong> geeft zweet af waarmee het lichaam afkoelt.`] },
      { h: '2. Steun en stevigheid', p: [
        `Het <strong>skelet</strong> geeft het lichaam vorm en steun en beschermt kwetsbare organen: de <strong>steunfunctie</strong> en de <strong>beschermende functie</strong>. Botten zijn hard, terwijl <strong>kraakbeen</strong> stevig maar buigzaam is, zoals in het oor en de neus.`] },
    ],
    [
      { t: 'Huid', d: 'het orgaan dat het lichaam bedekt en beschermt', k: 'beschermende bedekking', fout: ['Opperhuid', 'Lederhuid'] },
      { t: 'Opperhuid', d: 'de buitenste laag van de huid', k: 'buitenste huidlaag', fout: ['Lederhuid', 'Huid'] },
      { t: 'Lederhuid', d: 'de laag onder de opperhuid met zenuwen en bloedvaten', k: 'laag onder de opperhuid', fout: ['Opperhuid', 'Onderhuids bindweefsel'] },
      { t: 'Onderhuids bindweefsel', d: 'de vetlaag onder de lederhuid die warmte vasthoudt', k: 'vetlaag, houdt warmte vast', fout: ['Lederhuid'] },
      { t: 'Skelet', d: 'alle botten samen die het lichaam steun en vorm geven', k: 'alle botten samen', fout: ['Bot', 'Gewricht'] },
      { t: 'Bot', d: 'een hard orgaan dat steun geeft en bloedcellen kan maken', k: 'hard steunorgaan', fout: ['Kraakbeen', 'Skelet'] },
      { t: 'Kraakbeen', d: 'stevig maar buigzaam steunweefsel, bijvoorbeeld in het oor', k: 'buigzaam steunweefsel', fout: ['Bot'] },
      { t: 'Beschermende functie', d: 'het afschermen van organen tegen schade van buiten', k: 'organen afschermen', fout: ['Steunfunctie'] },
      { t: 'Steunfunctie', d: 'het geven van stevigheid en vorm aan het lichaam', k: 'stevigheid en vorm', fout: ['Beschermende functie'] },
      { t: 'Talgklier', d: 'huidklier die vet afgeeft en de huid soepel houdt', k: 'geeft huidvet af', fout: ['Zweetklier'] },
      { t: 'Zweetklier', d: 'huidklier die zweet afgeeft en zo het lichaam koelt', k: 'geeft zweet af, koelt', fout: ['Talgklier'] },
      { t: 'Ziekteverwekker', d: 'een micro-organisme dat een ziekte kan veroorzaken', k: 'veroorzaakt ziekte', fout: ['Bacterie', 'Virus'] },
    ],
    [
      { v: 'Welke huidlaag ligt aan de buitenkant?', o: ['De diepe lederhuidlaag', 'De opperhuid', 'Het onderhuids vetweefsel', 'De vochtige celkern'], c: 1, d: 2, uo: ['De lederhuid ligt juist dieper.', 'Klopt: de opperhuid ligt bovenop.', 'Dat is de vetlaag nog dieper.', 'De celkern hoort bij een cel.'] },
      { v: 'Waar zitten de zenuwen en bloedvaten van de huid?', o: ['In de dode opperhuidlaag', 'In het haar op je huid', 'In de lederhuid', 'In de rand van je nagel'], c: 2, d: 2, uo: ['De opperhuid is de dode buitenlaag.', 'Haar is geen huidlaag.', 'Klopt: de lederhuid bevat zenuwen en bloedvaten.', 'Een nagel is geen huidlaag.'] },
      { v: 'Als je het warm hebt ga je zweten. Welke klier doet dat?', o: ['De zweetklier', 'De talgklier voor huidvet', 'De celkern in de cel', 'De beschermende opperhuid'], c: 0, d: 3, uo: ['Klopt: de zweetklier koelt je af.', 'De talgklier geeft juist huidvet af.', 'De celkern hoort bij een cel.', 'De opperhuid is een laag, geen klier.'] },
      { v: 'Wat is de belangrijkste functie van de huid?', o: ['Het bloed rondpompen', 'Het voedsel verteren', 'Het zuurstof opnemen', 'Beschermen'], c: 3, d: 2, uo: ['Bloed rondpompen doet het hart.', 'Verteren gebeurt in de darmen.', 'Zuurstof nemen de longen op.', 'Klopt: de huid beschermt het lichaam.'] },
      { v: 'Welke functie heeft het skelet, naast bescherming?', o: ['Het bloed zuiveren', 'Steun geven', 'Het zuurstof vervoeren', 'Het voedsel opslaan'], c: 1, d: 2, uo: ['Bloed zuiveren doen de nieren.', 'Klopt: het skelet geeft steun en vorm.', 'Zuurstof vervoeren doet het bloed.', 'Voedsel opslaan is geen skeletfunctie.'] },
      { v: 'Het oor en de neus zijn stevig maar buigzaam. Wat is dat?', o: ['Hard en stevig bot', 'Een trekkende spier', 'Kraakbeen', 'De beschermende huid'], c: 2, d: 3, uo: ['Bot is hard en niet buigzaam.', 'Een spier kan samentrekken.', 'Klopt: kraakbeen is stevig en buigzaam.', 'De huid is de bedekking.'] },
      { v: 'Welke laag onder de huid houdt de warmte vast?', o: ['De dunne dode opperhuid', 'De vetlaag', 'Een gladde talgklier', 'De buitenste hoornlaag'], c: 1, d: 2, uo: ['De opperhuid is dun en dood.', 'Klopt: de vetlaag houdt warmte vast.', 'Een talgklier geeft vet af.', 'De hoornlaag is de buitenkant.'] },
      { v: 'Waardoor blijft je huid soepel?', o: ['Door afkoelend zweet', 'Door voedend bloed', 'Door stevig kraakbeen', 'Door talg'], c: 3, d: 2, uo: ['Zweet koelt je juist af.', 'Bloed voedt de huid.', 'Kraakbeen zit in oor en neus.', 'Klopt: talg houdt de huid soepel.'] },
      { v: 'Alle botten samen noem je het...', o: ['spierstelsel', 'skelet', 'steunweefsel', 'zenuwstelsel'], c: 1, d: 1, uo: ['Het spierstelsel bestaat uit spieren.', 'Klopt: alle botten samen zijn het skelet.', 'Kraakbeen is steunweefsel.', 'Het zenuwstelsel geeft prikkels door.'] },
      { v: 'Wat doet een talgklier?', o: ['Zweet afgeven en koelen', 'Bloed door het lichaam pompen', 'Huidvet afgeven', 'Nieuwe botten aanmaken'], c: 2, d: 2, uo: ['Zweet afgeven doet de zweetklier.', 'Bloed pompen doet het hart.', 'Klopt: de talgklier geeft huidvet af.', 'Botten maakt het beenmerg.'] },
      { v: 'Wat is kraakbeen?', o: ['Buigzaam steunweefsel', 'Een samentrekkende spier', 'Een bedekkende huidlaag', 'Een vervoerend bloedvat'], c: 0, d: 1, uo: ['Klopt: kraakbeen is buigzaam steunweefsel.', 'Een spier kan samentrekken.', 'Een huidlaag beschermt.', 'Een bloedvat vervoert bloed.'] },
      { v: 'Bij een schaafwond raakt vooral de buitenste laag stuk. Welke?', o: ['De diepe lederhuid', 'Het onderhuids bindweefsel', 'Een hard bot', 'De opperhuid'], c: 3, d: 3, uo: ['De lederhuid ligt dieper.', 'Het bindweefsel ligt onderop.', 'Een bot zit veel dieper.', 'Klopt: de opperhuid is de buitenste laag.'] },
      { v: 'Wat beschermt je organen tegen stoten van buiten?', o: ['De koelende zweetklier', 'Het skelet', 'Het vloeibare cytoplasma', 'De grote vacuole'], c: 1, d: 2, uo: ['De zweetklier koelt af.', 'Klopt: het skelet beschermt de organen.', 'Cytoplasma zit in een cel.', 'De vacuole hoort bij een plantencel.'] },
      { v: 'Waartegen beschermt de huid vooral?', o: ['Tegen te veel eigen bloed', 'Tegen te veel botten', 'Tegen ziekteverwekkers', 'Tegen je eigen spieren'], c: 2, d: 2, uo: ['Bloed hoort juist in het lichaam.', 'Botten horen bij het skelet.', 'Klopt: tegen ziekteverwekkers en uitdroging.', 'Spieren horen bij beweging.'] },
      { v: 'Welke twee taken heeft het skelet vooral?', o: ['Voedsel verteren en ademhalen', 'Steun en bescherming', 'Zien en horen met zintuigen', 'Bloed pompen en koelen'], c: 1, d: 2, uo: ['Dat doen darmen en longen.', 'Klopt: steun geven en beschermen.', 'Dat doen de zintuigen.', 'Dat doen hart en huid.'] },
      { v: 'Spierweefsel bestaat uit cellen die op elkaar lijken. Wat is het?', o: ['Een groep samenwerkende organen', 'Een enkele losse lichaamscel', 'Een hard stuk bot', 'Een weefsel'], c: 3, d: 2, uo: ['Dat is een orgaanstelsel.', 'Het is niet één losse cel.', 'Een bot is iets anders.', 'Klopt: gelijke cellen vormen een weefsel.'] },
    ]),

  V('C', 'Planten, dieren en hun samenhang',
    `In een ecosysteem hangen organismen met elkaar samen. <strong>Producenten</strong> maken met <strong>fotosynthese</strong> zelf voedsel, <strong>consumenten</strong> eten anderen en <strong>reducenten</strong> breken dood materiaal af. Zo blijven stoffen in een <strong>kringloop</strong> rondgaan.`,
    [
      { h: '1. Voedselketens en voedselwebben', p: [
        `Een <strong>voedselketen</strong> laat zien wie wie eet, in een rechte lijn: van <strong>producent</strong> naar <strong>consument</strong>. In werkelijkheid eten veel dieren van meerdere soorten; als je die ketens met elkaar verbindt, krijg je een <strong>voedselweb</strong>.`,
        `Je onderscheidt eters naar hun voedsel: een <strong>herbivoor</strong> eet planten, een <strong>carnivoor</strong> eet dieren en een <strong>omnivoor</strong> eet beide.`] },
      { h: '2. Producenten, consumenten en reducenten', p: [
        `<strong>Producenten</strong> (groene planten) maken hun eigen voedsel met <strong>fotosynthese</strong>. <strong>Consumenten</strong> kunnen dat niet en eten daarom andere organismen. <strong>Reducenten</strong>, zoals schimmels en bacteriën, breken dode resten af tot stoffen die planten weer kunnen gebruiken.`] },
      { h: '3. Kringlopen', p: [
        `Doordat producenten, consumenten en reducenten samenwerken, blijven stoffen rondgaan. In de <strong>koolstofkringloop</strong> gaat koolstof via fotosynthese en verbranding tussen lucht en organismen rond. In de <strong>stikstofkringloop</strong> zorgen bacteriën dat stikstof beschikbaar blijft voor planten.`] },
    ],
    [
      { t: 'Voedselketen', d: 'een reeks organismen die elkaar opeten, van producent naar consument', k: 'wie eet wie, in een lijn', fout: ['Voedselweb'] },
      { t: 'Voedselweb', d: 'meerdere voedselketens die met elkaar verbonden zijn', k: 'verbonden voedselketens', fout: ['Voedselketen'] },
      { t: 'Producent', d: 'een organisme dat zelf voedsel maakt, meestal een plant', k: 'maakt zelf voedsel', fout: ['Consument', 'Reducent'] },
      { t: 'Consument', d: 'een organisme dat andere organismen eet', k: 'eet andere organismen', fout: ['Producent', 'Reducent'] },
      { t: 'Reducent', d: 'een organisme dat dood materiaal afbreekt, zoals een schimmel', k: 'breekt dood materiaal af', fout: ['Producent', 'Consument'] },
      { t: 'Fotosynthese', d: 'het maken van glucose uit koolstofdioxide en water met licht', k: 'suiker maken met licht', fout: ['Verbranding'] },
      { t: 'Verbranding', d: 'het vrijmaken van energie uit voedingsstoffen met zuurstof', k: 'energie vrijmaken met zuurstof', fout: ['Fotosynthese'] },
      { t: 'Koolstofkringloop', d: 'de kringloop waarin koolstof tussen organismen en lucht rondgaat', k: 'koolstof gaat rond', fout: ['Stikstofkringloop'] },
      { t: 'Stikstofkringloop', d: 'de kringloop waarin stikstof via bacteriën en planten rondgaat', k: 'stikstof gaat rond', fout: ['Koolstofkringloop'] },
      { t: 'Herbivoor', d: 'een dier dat alleen planten eet', k: 'planteneter', fout: ['Carnivoor', 'Omnivoor'] },
      { t: 'Carnivoor', d: 'een dier dat andere dieren eet', k: 'vleeseter', fout: ['Herbivoor', 'Omnivoor'] },
      { t: 'Omnivoor', d: 'een dier dat zowel planten als dieren eet', k: 'alleseter', fout: ['Herbivoor', 'Carnivoor'] },
      { t: 'Ecosysteem', d: 'een leefgebied met alle organismen en hun omgeving samen', k: 'organismen plus omgeving', fout: ['Voedselweb'] },
    ],
    [
      { v: 'Wat maakt een plant met fotosynthese?', o: ['Zuurstof en afval', 'Alleen schoon water', 'Glucose (suiker)', 'Stikstof uit de bodem'], c: 2, d: 2, uo: ['Zuurstof komt vrij, maar is niet het hoofdproduct.', 'Water is een grondstof, geen product.', 'Klopt: een plant maakt glucose.', 'Stikstof komt uit de bodem.'] },
      { v: 'Wat is een producent in een voedselketen?', o: ['Een plant', 'Een vleesetend dier', 'Een afbrekende schimmel', 'Een grazend hert'], c: 0, d: 1, uo: ['Klopt: een plant maakt zelf voedsel.', 'Dat is een consument.', 'Dat is een reducent.', 'Dat is een herbivoor.'] },
      { v: 'Een schimmel breekt dode bladeren af. Wat is de schimmel?', o: ['Een producent', 'Een reducent', 'Een herbivoor', 'Een carnivoor'], c: 1, d: 3, uo: ['Een producent maakt zelf voedsel.', 'Klopt: een reducent breekt dood materiaal af.', 'Een herbivoor eet planten.', 'Een carnivoor eet dieren.'] },
      { v: 'Een koe eet alleen gras. Wat voor eter is een koe?', o: ['Een carnivoor', 'Een reducent', 'Een producent', 'Een herbivoor'], c: 3, d: 2, uo: ['Een carnivoor eet vlees.', 'Een reducent breekt af.', 'Een producent maakt voedsel.', 'Klopt: een herbivoor eet planten.'] },
      { v: 'Wat gebeurt er in een voedselweb?', o: ['Eén rechte eetketen', 'Alleen planten groeien', 'Meerdere ketens zijn verbonden', 'Stoffen verdwijnen'], c: 2, d: 2, uo: ['Dat is een voedselketen.', 'Een web bevat ook dieren.', 'Klopt: meerdere ketens zijn met elkaar verbonden.', 'Stoffen gaan juist rond.'] },
      { v: 'Wat doen reducenten met dode resten?', o: ['Ze breken ze af', 'Ze eten levende dieren', 'Ze maken er licht van', 'Ze pompen bloed rond'], c: 0, d: 1, uo: ['Klopt: reducenten breken dode resten af.', 'Ze eten geen levende dieren.', 'Ze maken geen licht.', 'Bloed pompen doet een hart.'] },
      { v: 'Wat heeft een plant nodig voor fotosynthese?', o: ['Zuurstof uit de lucht', 'Licht, water en CO2', 'Suiker als brandstof', 'Vlees en eiwitten'], c: 1, d: 2, uo: ['Zuurstof komt juist vrij.', 'Klopt: licht, water en koolstofdioxide.', 'Suiker is het product.', 'Planten eten geen vlees.'] },
      { v: 'In welke kringloop gaat koolstof rond?', o: ['De waterkringloop', 'De stikstofkringloop', 'De voedselketen', 'De koolstofkringloop'], c: 3, d: 2, uo: ['Water gaat rond in de waterkringloop.', 'Stikstof in de stikstofkringloop.', 'Een keten is geen kringloop.', 'Klopt: koolstof in de koolstofkringloop.'] },
      { v: 'Een dier eet zowel planten als andere dieren. Wat is het?', o: ['Een herbivoor', 'Een producent', 'Een omnivoor', 'Een reducent'], c: 2, d: 3, uo: ['Een herbivoor eet alleen planten.', 'Een producent maakt voedsel.', 'Klopt: een omnivoor eet allebei.', 'Een reducent breekt af.'] },
      { v: 'Waarom noem je planten producenten?', o: ['Ze maken zelf hun voedsel', 'Ze eten andere dieren', 'Ze breken resten af', 'Ze pompen bloed rond'], c: 0, d: 2, uo: ['Klopt: planten maken zelf voedsel.', 'Dat doen consumenten.', 'Dat doen reducenten.', 'Bloed pompen doet een hart.'] },
      { v: 'Wat gebeurt er bij fotosynthese?', o: ['Suiker wordt juist verbrand', 'Er wordt suiker gemaakt', 'Er wordt bloed rondgepompt', 'Water verdampt in de lucht'], c: 1, d: 2, uo: ['Verbranden is het tegenovergestelde.', 'Klopt: er wordt suiker gemaakt.', 'Bloed pompen doet een hart.', 'Dat is verdamping.'] },
      { v: 'Wat is een reducent, bijvoorbeeld?', o: ['Een grasetend konijn', 'Een groene plant', 'Een jagende vos', 'Een schimmel'], c: 3, d: 3, uo: ['Dat is een herbivoor.', 'Dat is een producent.', 'Dat is een carnivoor.', 'Klopt: een schimmel is een reducent.'] },
      { v: 'Waardoor blijven stoffen in een ecosysteem rondgaan?', o: ['Door alleen de planten', 'Door alleen de dieren', 'Door kringlopen', 'Doordat ze verdwijnen'], c: 2, d: 2, uo: ['Planten alleen is niet genoeg.', 'Dieren alleen is niet genoeg.', 'Klopt: door kringlopen gaan stoffen rond.', 'Stoffen verdwijnen niet.'] },
      { v: 'Wat is een ecosysteem?', o: ['Organismen met hun omgeving', 'Alleen de dieren in een gebied', 'Alleen de groene planten', 'Alleen de kale bodem'], c: 0, d: 1, uo: ['Klopt: organismen samen met hun omgeving.', 'Dieren zijn maar een deel.', 'Planten zijn maar een deel.', 'De bodem is maar een deel.'] },
      { v: 'Een vos eet konijnen. Wat voor eter is de vos?', o: ['Een herbivoor', 'Een carnivoor', 'Een producent', 'Een reducent'], c: 1, d: 2, uo: ['Een herbivoor eet planten.', 'Klopt: een carnivoor eet dieren.', 'Een producent maakt voedsel.', 'Een reducent breekt af.'] },
      { v: 'Welke stof komt vrij bij fotosynthese?', o: ['Koolstofdioxide', 'Stikstof', 'Suiker', 'Zuurstof'], c: 3, d: 2, uo: ['CO2 is juist een grondstof.', 'Stikstof speelt hier geen rol.', 'Suiker blijft in de plant.', 'Klopt: er komt zuurstof vrij.'] },
    ]),

  V('D', 'Mensen beïnvloeden hun omgeving',
    `De mens gebruikt grondstoffen en veroorzaakt <strong>milieuvervuiling</strong>. Met <strong>duurzaamheid</strong> en <strong>kringloopdenken</strong> proberen we die invloed te verkleinen.`,
    [
      { h: '1. Vervuiling en klimaat', p: [
        `Bij <strong>milieuvervuiling</strong> komen schadelijke stoffen in lucht, water of bodem. Door het verbranden van <strong>fossiele brandstoffen</strong> komen <strong>broeikasgassen</strong> vrij die warmte vasthouden: het <strong>broeikaseffect</strong>, waardoor de aarde opwarmt.`] },
      { h: '2. Duurzaam met grondstoffen', p: [
        `<strong>Duurzaamheid</strong> betekent zo leven dat er ook voor de toekomst genoeg overblijft. Bij <strong>kringloopdenken</strong> gebruik je grondstoffen steeds opnieuw in plaats van ze weg te gooien; <strong>recycling</strong> en <strong>duurzame energie</strong> horen daarbij. Zo blijft de <strong>biodiversiteit</strong> beter behouden.`] },
    ],
    [
      { t: 'Milieuvervuiling', d: 'het toevoegen van schadelijke stoffen aan lucht, water of bodem', k: 'schadelijke stoffen lozen', fout: ['Broeikaseffect'] },
      { t: 'Broeikaseffect', d: 'het opwarmen van de aarde door broeikasgassen in de lucht', k: 'aarde warmt op', fout: ['Milieuvervuiling', 'Ozonlaag'] },
      { t: 'Broeikasgas', d: 'een gas zoals koolstofdioxide dat warmte vasthoudt', k: 'gas dat warmte vasthoudt', fout: ['Fijnstof'] },
      { t: 'Duurzaamheid', d: 'zo leven dat er ook voor de toekomst genoeg overblijft', k: 'toekomstbestendig leven', fout: ['Kringloopdenken'] },
      { t: 'Kringloopdenken', d: 'grondstoffen steeds opnieuw gebruiken in plaats van weggooien', k: 'grondstoffen hergebruiken', fout: ['Duurzaamheid', 'Recycling'] },
      { t: 'Recycling', d: 'afval verwerken tot nieuwe grondstoffen of producten', k: 'afval hergebruiken', fout: ['Kringloopdenken'] },
      { t: 'Duurzame energie', d: 'energie uit bronnen die niet opraken, zoals zon en wind', k: 'energie die niet opraakt', fout: ['Fossiele brandstof'] },
      { t: 'Fossiele brandstof', d: 'brandstof uit resten van organismen, zoals olie en gas', k: 'olie, gas en kolen', fout: ['Duurzame energie'] },
      { t: 'Biodiversiteit', d: 'de verscheidenheid aan soorten in een gebied', k: 'soortenrijkdom', fout: ['Ecosysteem'] },
      { t: 'Afbreekbaar', d: 'materiaal dat door reducenten wordt afgebroken', k: 'wordt afgebroken', fout: ['Recycling'] },
      { t: 'Fijnstof', d: 'kleine zwevende deeltjes in de lucht die schadelijk zijn', k: 'schadelijke luchtdeeltjes', fout: ['Broeikasgas'] },
      { t: 'Grondstof', d: 'een natuurlijke stof waarvan je iets maakt', k: 'basismateriaal', fout: ['Fossiele brandstof'] },
    ],
    [
      { v: 'Wat hoort bij milieuvervuiling?', o: ['Bomen planten langs de weg', 'Schadelijke stoffen lozen', 'Afval netjes scheiden', 'Zonnepanelen plaatsen'], c: 1, d: 2, uo: ['Bomen planten helpt juist.', 'Klopt: schadelijke stoffen in de omgeving brengen.', 'Scheiden is juist goed.', 'Zonnepanelen zijn schoon.'] },
      { v: 'Waardoor warmt de aarde op?', o: ['Door recycling', 'Door meer bomen', 'Door het broeikaseffect', 'Door schone lucht'], c: 2, d: 2, uo: ['Recycling helpt juist.', 'Bomen nemen CO2 op.', 'Klopt: door het broeikaseffect.', 'Schone lucht warmt niet op.'] },
      { v: 'Welke energiebron raakt op?', o: ['Zonne-energie', 'Windenergie', 'Waterkracht', 'Aardgas'], c: 3, d: 3, uo: ['De zon raakt niet op.', 'Wind raakt niet op.', 'Water raakt niet op.', 'Klopt: aardgas is een fossiele brandstof.'] },
      { v: 'Wat is duurzaam gedrag?', o: ['Grondstoffen hergebruiken', 'Alles meteen weggooien', 'Veel benzine blijven verbruiken', 'Oude bomen omkappen'], c: 0, d: 2, uo: ['Klopt: hergebruiken is duurzaam.', 'Weggooien is niet duurzaam.', 'Benzine vervuilt.', 'Bomen kappen schaadt de natuur.'] },
      { v: 'Wat is een broeikasgas?', o: ['Zuurstof', 'Koolstofdioxide', 'Stikstof', 'Waterstof'], c: 1, d: 1, uo: ['Zuurstof is geen broeikasgas.', 'Klopt: CO2 houdt warmte vast.', 'Stikstof is geen broeikasgas.', 'Waterstof speelt hier geen rol.'] },
      { v: 'Wat gebeurt er bij recycling?', o: ['Afval wordt verbrand', 'Afval blijft liggen', 'Afval wordt hergebruikt', 'Afval wordt begraven'], c: 2, d: 2, uo: ['Verbranden is geen recycling.', 'Blijven liggen helpt niet.', 'Klopt: afval wordt een nieuwe grondstof.', 'Begraven is geen hergebruik.'] },
      { v: 'Welke energiebron is duurzaam?', o: ['Aardolie', 'Steenkool', 'Aardgas', 'Windenergie'], c: 3, d: 3, uo: ['Aardolie raakt op.', 'Steenkool raakt op.', 'Aardgas raakt op.', 'Klopt: wind raakt niet op.'] },
      { v: 'Wat is kringloopdenken?', o: ['Grondstoffen opnieuw gebruiken', 'Steeds nieuwe grondstoffen kopen', 'Alles verbranden', 'Water verspillen'], c: 0, d: 2, uo: ['Klopt: grondstoffen opnieuw gebruiken.', 'Nieuw kopen is het tegenovergestelde.', 'Verbranden is geen kringloop.', 'Verspillen is niet duurzaam.'] },
      { v: 'Waarom is het broeikaseffect een probleem?', o: ['De aarde koelt af', 'De aarde warmt op', 'Er komt meer zuurstof', 'Er groeien meer bomen'], c: 1, d: 2, uo: ['De aarde koelt niet af.', 'Klopt: de aarde warmt op.', 'Zuurstof is niet het probleem.', 'Meer bomen zou juist helpen.'] },
      { v: 'Wat is een fossiele brandstof?', o: ['Zonlicht', 'Wind', 'Aardolie', 'Stromend water'], c: 2, d: 1, uo: ['Zonlicht is duurzaam.', 'Wind is duurzaam.', 'Klopt: aardolie is fossiel.', 'Water is duurzaam.'] },
      { v: 'Wat betekent duurzaamheid?', o: ['Alles snel opmaken', 'Zoveel mogelijk kopen', 'Grondstoffen uitputten', 'Genoeg overhouden voor later'], c: 3, d: 2, uo: ['Opmaken is niet duurzaam.', 'Veel kopen is niet duurzaam.', 'Uitputten is niet duurzaam.', 'Klopt: ook voor de toekomst genoeg overhouden.'] },
      { v: 'Wat helpt tegen het broeikaseffect?', o: ['Minder fossiele brandstof gebruiken', 'Steeds meer kolen verbranden', 'Veel meer met de auto rijden', 'Grote bossen kappen'], c: 0, d: 2, uo: ['Klopt: minder fossiele brandstof gebruiken.', 'Kolen verergeren het.', 'Auto rijden stoot CO2 uit.', 'Bossen kappen verergert het.'] },
      { v: 'Wat is fijnstof?', o: ['Heel schone lucht', 'Kleine schadelijke deeltjes', 'Gewone zuurstof', 'Schoon regenwater'], c: 1, d: 1, uo: ['Fijnstof maakt de lucht juist vuil.', 'Klopt: kleine schadelijke deeltjes in de lucht.', 'Zuurstof is geen fijnstof.', 'Water is geen fijnstof.'] },
      { v: 'Wat is biodiversiteit?', o: ['Eén enkele soort in een gebied', 'Helemaal geen leven', 'De verscheidenheid aan soorten', 'Alleen groene planten'], c: 2, d: 2, uo: ['Eén soort is juist weinig diversiteit.', 'Zonder leven is er geen diversiteit.', 'Klopt: de rijkdom aan verschillende soorten.', 'Alleen planten is te beperkt.'] },
      { v: 'Welke energiebron raakt niet op?', o: ['Aardgas', 'Steenkool', 'Aardolie', 'Zonne-energie'], c: 3, d: 3, uo: ['Aardgas raakt op.', 'Steenkool raakt op.', 'Aardolie raakt op.', 'Klopt: de zon raakt niet op.'] },
      { v: 'Waarom is recycling goed voor het milieu?', o: ['Er zijn minder grondstoffen nodig', 'Er ontstaat juist veel meer afval', 'Er wordt meer brandstof verstookt', 'Er komt meer vervuiling vrij'], c: 0, d: 2, uo: ['Klopt: er zijn minder nieuwe grondstoffen nodig.', 'Recycling geeft juist minder afval.', 'Recycling is geen verbranding.', 'Recycling vermindert vervuiling.'] },
    ]),

  V('E', 'Houding en beweging',
    `Het <strong>skelet</strong> en de <strong>spieren</strong> zorgen samen voor beweging. Botten zijn met elkaar verbonden in <strong>gewrichten</strong>, en spieren werken in paren omdat ze alleen kunnen trekken.`,
    [
      { h: '1. Gewrichten en verbindingen', p: [
        `Waar twee botten beweegbaar samenkomen, zit een <strong>gewricht</strong>. <strong>Gewrichtsbanden</strong> houden de botten bij elkaar, <strong>kraakbeen</strong> bedekt de uiteinden en <strong>gewrichtssmeer</strong> vermindert de wrijving. Een <strong>scharniergewricht</strong> (knie) buigt in één richting, een <strong>kogelgewricht</strong> (schouder) draait alle kanten op.`] },
      { h: '2. Spieren werken in paren', p: [
        `Een <strong>spier</strong> kan alleen trekken, niet duwen. Daarom werken spieren in paren: een <strong>buigspier</strong> buigt een gewricht en de <strong>strekspier</strong> strekt het weer. Zo\'n tegenwerkend paar heet een <strong>antagonist</strong>. Een <strong>pees</strong> verbindt de spier met het bot.`] },
    ],
    [
      { t: 'Gewricht', d: 'een beweegbare verbinding tussen twee botten', k: 'beweegbare botverbinding', fout: ['Gewrichtsband', 'Pees'] },
      { t: 'Gewrichtsband', d: 'stevig weefsel dat botten in een gewricht bij elkaar houdt', k: 'houdt botten bijeen', fout: ['Pees', 'Gewricht'] },
      { t: 'Pees', d: 'stevig weefsel dat een spier aan een bot vastmaakt', k: 'verbindt spier met bot', fout: ['Gewrichtsband'] },
      { t: 'Spier', d: 'een orgaan dat kan samentrekken en zo beweging maakt', k: 'trekt samen, beweegt', fout: ['Pees', 'Bot'] },
      { t: 'Buigspier', d: 'een spier die een gewricht buigt', k: 'buigt een gewricht', fout: ['Strekspier'] },
      { t: 'Strekspier', d: 'een spier die een gewricht strekt', k: 'strekt een gewricht', fout: ['Buigspier'] },
      { t: 'Antagonist', d: 'een spier die de tegengestelde beweging maakt', k: 'tegenwerkende spier', fout: ['Buigspier', 'Strekspier'] },
      { t: 'Gewrichtskapsel', d: 'het omhulsel om een gewricht met smeervloeistof', k: 'omhulsel met smeer', fout: ['Gewrichtsband'] },
      { t: 'Gewrichtssmeer', d: 'vloeistof die de wrijving in een gewricht verkleint', k: 'vermindert wrijving', fout: ['Kraakbeen'] },
      { t: 'Kraakbeen', d: 'buigzaam steunweefsel dat de botuiteinden bedekt', k: 'bedekt botuiteinden', fout: ['Bot', 'Gewrichtssmeer'] },
      { t: 'Scharniergewricht', d: 'een gewricht dat maar in één richting buigt, zoals de knie', k: 'buigt één richting', fout: ['Kogelgewricht'] },
      { t: 'Kogelgewricht', d: 'een gewricht dat in alle richtingen kan draaien, zoals de schouder', k: 'draait alle richtingen', fout: ['Scharniergewricht'] },
    ],
    [
      { v: 'Wat verbindt twee botten beweegbaar met elkaar?', o: ['Een spier', 'Een pees', 'Een gewricht', 'De huid'], c: 2, d: 2, uo: ['Een spier trekt samen.', 'Een pees verbindt spier en bot.', 'Klopt: een gewricht verbindt botten beweegbaar.', 'De huid bedekt het lichaam.'] },
      { v: 'Waarom werken spieren in paren?', o: ['Een spier kan alleen trekken', 'Een spier kan alleen maar duwen', 'Spieren zijn veel te zwak', 'Botten bewegen helemaal zelf'], c: 0, d: 3, uo: ['Klopt: een spier kan alleen trekken, dus je hebt er twee nodig.', 'Een spier duwt niet.', 'Kracht is niet het probleem.', 'Botten bewegen niet uit zichzelf.'] },
      { v: 'Welke spier buigt een gewricht?', o: ['De strekspier', 'De buigspier', 'De pees', 'Het gewrichtskapsel'], c: 1, d: 2, uo: ['De strekspier strekt juist.', 'Klopt: de buigspier buigt.', 'Een pees is geen spier.', 'Het kapsel omhult het gewricht.'] },
      { v: 'Wat verbindt een spier met een bot?', o: ['Een gewrichtsband', 'Kraakbeen', 'Een bloedvat', 'Een pees'], c: 3, d: 3, uo: ['Een band verbindt botten onderling.', 'Kraakbeen bedekt botuiteinden.', 'Een bloedvat vervoert bloed.', 'Klopt: een pees verbindt spier en bot.'] },
      { v: 'De knie buigt maar in één richting. Wat voor gewricht is dat?', o: ['Een kogelgewricht', 'Een vast gewricht', 'Een scharniergewricht', 'Een spiergewricht'], c: 2, d: 3, uo: ['Een kogelgewricht draait alle kanten op.', 'Een vast gewricht beweegt niet.', 'Klopt: een scharniergewricht buigt in één richting.', 'Een spiergewricht bestaat niet.'] },
      { v: 'De schouder kan alle kanten op draaien. Wat voor gewricht?', o: ['Een kogelgewricht', 'Een scharniergewricht', 'Een vast gewricht', 'Een pees'], c: 0, d: 3, uo: ['Klopt: een kogelgewricht draait alle kanten op.', 'Een scharnier buigt in één richting.', 'Een vast gewricht beweegt niet.', 'Een pees is geen gewricht.'] },
      { v: 'Wat houdt de botten in een gewricht bij elkaar?', o: ['Een spier', 'Een gewrichtsband', 'Een bloedvat', 'De opperhuid'], c: 1, d: 2, uo: ['Een spier zorgt voor beweging.', 'Klopt: een gewrichtsband houdt botten bijeen.', 'Een bloedvat vervoert bloed.', 'De opperhuid is een huidlaag.'] },
      { v: 'Wat doet de strekspier?', o: ['Een gewricht buigen', 'De huid koelen', 'Bloed pompen', 'Een gewricht strekken'], c: 3, d: 2, uo: ['Buigen doet de buigspier.', 'Koelen doet de huid.', 'Pompen doet het hart.', 'Klopt: de strekspier strekt een gewricht.'] },
      { v: 'Waarmee zijn de botuiteinden bedekt zodat ze soepel bewegen?', o: ['Met spierweefsel', 'Met huid', 'Met kraakbeen', 'Met bloed'], c: 2, d: 2, uo: ['Spierweefsel beweegt het bot.', 'Huid bedekt het lichaam.', 'Klopt: kraakbeen bedekt de botuiteinden.', 'Bloed voedt het weefsel.'] },
      { v: 'Wat vermindert de wrijving in een gewricht?', o: ['Gewrichtssmeer', 'Een pees', 'Een spier', 'Een bot'], c: 0, d: 2, uo: ['Klopt: gewrichtssmeer vermindert de wrijving.', 'Een pees verbindt spier en bot.', 'Een spier zorgt voor beweging.', 'Een bot geeft steun.'] },
      { v: 'Twee spieren die tegengesteld werken heten...', o: ['synergisten', 'antagonisten', 'pezen', 'banden'], c: 1, d: 1, uo: ['Synergisten werken juist samen.', 'Klopt: antagonisten werken tegengesteld.', 'Pezen verbinden spier en bot.', 'Banden verbinden botten.'] },
      { v: 'Waarom kun je je arm buigen én strekken?', o: ['Door één sterke spier', 'Door de huid', 'Door een bot', 'Door een buig- en strekspier'], c: 3, d: 3, uo: ['Eén spier kan alleen trekken.', 'De huid beweegt niet.', 'Een bot beweegt niet zelf.', 'Klopt: een buigspier en een strekspier samen.'] },
      { v: 'Wat is een pees?', o: ['Een gewricht in de knie', 'Buigzaam kraakbeen in het oor', 'Weefsel dat spier en bot verbindt', 'Een beschermende huidlaag'], c: 2, d: 2, uo: ['Dat is een gewricht.', 'Dat is kraakbeen.', 'Klopt: een pees verbindt spier en bot.', 'Dat is de huid.'] },
      { v: 'Welke twee delen zorgen samen voor beweging?', o: ['Skelet en spieren', 'Huid en haren', 'Hart en longen', 'Nieren en blaas'], c: 0, d: 1, uo: ['Klopt: het skelet en de spieren.', 'Huid en haren beschermen.', 'Hart en longen doen iets anders.', 'Nieren en blaas zuiveren.'] },
      { v: 'Wat gebeurt er als de buigspier samentrekt?', o: ['Het gewricht strekt', 'Het gewricht buigt', 'Het bot breekt', 'De huid koelt af'], c: 1, d: 2, uo: ['Strekken doet de strekspier.', 'Klopt: het gewricht buigt.', 'Er breekt niets.', 'De huid heeft hier geen rol.'] },
      { v: 'Waar zit kraakbeen onder andere?', o: ['In het hart', 'In de longen', 'In het bloed', 'In het oor'], c: 3, d: 2, uo: ['Het hart is een spier.', 'De longen doen gaswisseling.', 'Bloed is vloeibaar.', 'Klopt: kraakbeen zit in het oor en de neus.'] },
    ]),

  V('F', 'Het lichaam in werking',
    `Organen werken samen om je lichaam draaiende te houden: de <strong>vertering</strong> maakt voedsel klein, het <strong>bloed</strong> vervoert stoffen, de <strong>longen</strong> zorgen voor <strong>gaswisseling</strong> en het <strong>zenuwstelsel</strong> stuurt alles aan.`,
    [
      { h: '1. Vertering en opname', p: [
        `Bij de <strong>vertering</strong> wordt voedsel klein gemaakt zodat het in het bloed kan worden opgenomen. <strong>Enzymen</strong> versnellen dat proces. In de dunne darm nemen <strong>darmvlokken</strong> de voedingsstoffen op in het bloed.`] },
      { h: '2. Bloedsomloop', p: [
        `Het <strong>hart</strong> pompt het bloed rond. <strong>Slagaders</strong> voeren bloed van het hart af, <strong>aders</strong> voeren het naar het hart toe, en in de dunne <strong>haarvaten</strong> vindt de uitwisseling van stoffen met de cellen plaats.`] },
      { h: '3. Gaswisseling en regeling', p: [
        `In de <strong>longblaasjes</strong> vindt <strong>gaswisseling</strong> plaats: zuurstof gaat het bloed in, koolstofdioxide gaat eruit. De <strong>nieren</strong> filteren afvalstoffen uit het bloed. Het <strong>zenuwstelsel</strong> stuurt snel met prikkels, terwijl <strong>hormonen</strong> langzamer sturen via het bloed.`] },
    ],
    [
      { t: 'Vertering', d: 'het klein maken van voedsel zodat het opgenomen kan worden', k: 'voedsel klein maken', fout: ['Opname', 'Verbranding'] },
      { t: 'Enzym', d: 'een stof die een reactie zoals vertering versnelt', k: 'versnelt een reactie', fout: ['Hormoon'] },
      { t: 'Darmvlok', d: 'uitstulping in de dunne darm die voedingsstoffen opneemt', k: 'neemt voeding op', fout: ['Vertering'] },
      { t: 'Slagader', d: 'een bloedvat dat bloed van het hart af vervoert', k: 'bloed van het hart af', fout: ['Ader', 'Haarvat'] },
      { t: 'Ader', d: 'een bloedvat dat bloed naar het hart toe vervoert', k: 'bloed naar het hart toe', fout: ['Slagader', 'Haarvat'] },
      { t: 'Haarvat', d: 'een heel dun bloedvat waar uitwisseling van stoffen plaatsvindt', k: 'uitwisseling van stoffen', fout: ['Slagader', 'Ader'] },
      { t: 'Hart', d: 'de spier die het bloed rondpompt', k: 'pompt het bloed rond', fout: ['Long'] },
      { t: 'Gaswisseling', d: 'de opname van zuurstof en afgifte van koolstofdioxide', k: 'zuurstof in, CO2 uit', fout: ['Vertering'] },
      { t: 'Longblaasje', d: 'klein blaasje in de long waar gaswisseling plaatsvindt', k: 'plek van gaswisseling', fout: ['Haarvat'] },
      { t: 'Nier', d: 'een orgaan dat afvalstoffen uit het bloed filtert', k: 'filtert het bloed', fout: ['Blaas', 'Lever'] },
      { t: 'Zenuwstelsel', d: 'het stelsel dat prikkels doorgeeft en het lichaam stuurt', k: 'stuurt met prikkels', fout: ['Hormoonstelsel'] },
      { t: 'Hormoon', d: 'een stof die via het bloed processen in het lichaam regelt', k: 'regelt via het bloed', fout: ['Enzym', 'Zenuwstelsel'] },
      { t: 'Zintuig', d: 'een orgaan dat prikkels uit de omgeving opvangt', k: 'vangt prikkels op', fout: ['Zenuwstelsel'] },
    ],
    [
      { v: 'Wat gebeurt er bij de vertering?', o: ['Bloed wordt rondgepompt', 'Voedsel wordt klein gemaakt', 'Zuurstof wordt opgenomen', 'Afval wordt gefilterd'], c: 1, d: 2, uo: ['Pompen doet het hart.', 'Klopt: voedsel wordt klein gemaakt.', 'Zuurstof nemen de longen op.', 'Filteren doen de nieren.'] },
      { v: 'Welk bloedvat voert bloed van het hart af?', o: ['Een ader', 'Een haarvat', 'Een slagader', 'Een zenuw'], c: 2, d: 2, uo: ['Een ader voert bloed naar het hart toe.', 'In haarvaten wisselen stoffen uit.', 'Klopt: een slagader voert bloed van het hart af.', 'Een zenuw is geen bloedvat.'] },
      { v: 'Waar vindt de gaswisseling plaats?', o: ['In de longblaasjes', 'In de maag', 'In de nieren', 'In de botten'], c: 0, d: 2, uo: ['Klopt: in de longblaasjes.', 'De maag verteert voedsel.', 'De nieren filteren bloed.', 'Botten geven steun.'] },
      { v: 'Wat doet het hart?', o: ['Voedsel verteren', 'Zuurstof maken', 'Bloed filteren', 'Bloed rondpompen'], c: 3, d: 1, uo: ['Verteren doen de darmen.', 'Zuurstof maak je niet zelf aan.', 'Filteren doen de nieren.', 'Klopt: het hart pompt het bloed rond.'] },
      { v: 'Wat nemen de darmvlokken op?', o: ['Zuurstof', 'Voedingsstoffen', 'Afvalstoffen', 'Botten'], c: 1, d: 2, uo: ['Zuurstof nemen de longen op.', 'Klopt: darmvlokken nemen voedingsstoffen op.', 'Afval verlaat juist het lichaam.', 'Botten worden niet opgenomen.'] },
      { v: 'Welk bloedvat voert bloed naar het hart toe?', o: ['Een slagader', 'Een haarvat', 'Een ader', 'Een pees'], c: 2, d: 2, uo: ['Een slagader voert bloed van het hart af.', 'In haarvaten wisselen stoffen uit.', 'Klopt: een ader voert bloed naar het hart.', 'Een pees verbindt spier en bot.'] },
      { v: 'Wat filteren de nieren uit het bloed?', o: ['Afvalstoffen', 'Zuurstof', 'Voedingsstoffen', 'Botten'], c: 0, d: 2, uo: ['Klopt: de nieren filteren afvalstoffen.', 'Zuurstof blijft in het bloed.', 'Voedingsstoffen worden juist gebruikt.', 'Botten zitten niet in het bloed.'] },
      { v: 'Wat gebeurt er in de longblaasjes?', o: ['Voedsel verteren', 'Bloed filteren', 'Botten maken', 'Zuurstof en CO2 wisselen'], c: 3, d: 3, uo: ['Verteren gebeurt in de darmen.', 'Filteren doen de nieren.', 'Botten maakt het beenmerg.', 'Klopt: zuurstof erin, koolstofdioxide eruit.'] },
      { v: 'Wat versnelt de vertering van voedsel?', o: ['Botten', 'Enzymen', 'Zenuwen', 'Bloedvaten'], c: 1, d: 2, uo: ['Botten geven steun.', 'Klopt: enzymen versnellen de vertering.', 'Zenuwen geven prikkels door.', 'Bloedvaten vervoeren stoffen.'] },
      { v: 'Wat stuurt snel met prikkels door het lichaam?', o: ['Het bloed', 'De darmen', 'Het zenuwstelsel', 'De huid'], c: 2, d: 2, uo: ['Bloed vervoert stoffen.', 'De darmen verteren.', 'Klopt: het zenuwstelsel stuurt met prikkels.', 'De huid beschermt.'] },
      { v: 'Hoe regelt een hormoon iets in het lichaam?', o: ['Via het bloed', 'Via de botten', 'Via de huid', 'Via de nagels'], c: 0, d: 2, uo: ['Klopt: een hormoon werkt via het bloed.', 'Botten geven steun.', 'De huid beschermt.', 'Nagels spelen geen rol.'] },
      { v: 'Waar voert een slagader het bloed heen?', o: ['Naar het hart toe', 'Naar de nieren toe', 'Naar de longen', 'Van het hart af'], c: 3, d: 3, uo: ['Dat doet juist een ader.', 'Niet specifiek naar de nieren.', 'Niet specifiek naar de longen.', 'Klopt: een slagader voert bloed van het hart af.'] },
      { v: 'Waar worden voedingsstoffen in het bloed opgenomen?', o: ['In de longen', 'In de dunne darm', 'In het hart', 'In de nieren'], c: 1, d: 2, uo: ['In de longen gaat het om zuurstof.', 'Klopt: in de dunne darm via darmvlokken.', 'Het hart pompt alleen.', 'De nieren filteren.'] },
      { v: 'Wat is een haarvat?', o: ['Een dikke slagader', 'Een grote ader', 'Een heel dun bloedvat', 'Een zenuw'], c: 2, d: 2, uo: ['Een slagader is juist dik.', 'Een ader is groter.', 'Klopt: een haarvat is een heel dun bloedvat.', 'Een zenuw geeft prikkels door.'] },
      { v: 'Wat vervoert het bloed naar de cellen?', o: ['Zuurstof en voeding', 'Alleen botten', 'Alleen spieren', 'Alleen huid'], c: 0, d: 1, uo: ['Klopt: zuurstof en voedingsstoffen.', 'Botten worden niet vervoerd.', 'Spieren worden niet vervoerd.', 'Huid wordt niet vervoerd.'] },
      { v: 'Welk orgaan neemt zuurstof op uit de lucht?', o: ['De maag', 'De nieren', 'Het hart', 'De longen'], c: 3, d: 2, uo: ['De maag verteert.', 'De nieren filteren.', 'Het hart pompt.', 'Klopt: de longen nemen zuurstof op.'] },
    ]),

  V('G', 'Bio-wetenschappen en maatschappij',
    `Mensen zetten organismen aan het werk in de <strong>biotechnologie</strong>: <strong>gist</strong> en <strong>melkzuurbacteriën</strong> in voeding, <strong>schimmels</strong> voor <strong>antibiotica</strong> en <strong>genetische modificatie</strong> om stoffen zoals <strong>insuline</strong> te maken.`,
    [
      { h: '1. Micro-organismen in voeding', p: [
        `<strong>Biotechnologie</strong> is het gebruik van organismen om producten te maken. <strong>Gist</strong> is een schimmel die suiker omzet en deeg laat rijzen; <strong>melkzuurbacteriën</strong> maken van melk yoghurt en kaas. Dit omzetten zonder zuurstof heet <strong>gisting</strong>.`] },
      { h: '2. Medicijnen en modificatie', p: [
        `Sommige <strong>schimmels</strong> maken <strong>antibiotica</strong>, stoffen die bacteriën doden of hun groei remmen. Bij <strong>genetische modificatie</strong> verander je gericht het DNA van een organisme, bijvoorbeeld om bacteriën <strong>insuline</strong> te laten maken voor mensen met diabetes.`,
        `Genetische modificatie heeft voor- en nadelen. <strong>Gm-gewassen</strong> kunnen bijvoorbeeld beter tegen droogte, maar er zijn ook zorgen over gevolgen voor natuur en gezondheid. Overmatig antibioticagebruik leidt tot <strong>resistentie</strong>.`] },
    ],
    [
      { t: 'Biotechnologie', d: 'het gebruik van organismen om producten te maken', k: 'organismen als fabriekje', fout: ['Genetische modificatie'] },
      { t: 'Gist', d: 'een schimmel die suiker omzet en deeg laat rijzen', k: 'laat deeg rijzen', fout: ['Melkzuurbacterie', 'Schimmel'] },
      { t: 'Melkzuurbacterie', d: 'een bacterie die melk in yoghurt of kaas omzet', k: 'maakt yoghurt en kaas', fout: ['Gist'] },
      { t: 'Gisting', d: 'het omzetten van suiker door micro-organismen zonder zuurstof', k: 'suiker omzetten zonder zuurstof', fout: ['Verbranding'] },
      { t: 'Antibioticum', d: 'een stof die bacteriën doodt of hun groei remt', k: 'werkt tegen bacteriën', fout: ['Vaccin'] },
      { t: 'Schimmel', d: 'een organisme dat stoffen zoals antibiotica kan maken', k: 'maakt o.a. antibiotica', fout: ['Bacterie', 'Gist'] },
      { t: 'Genetische modificatie', d: 'het gericht veranderen van het DNA van een organisme', k: 'DNA gericht veranderen', fout: ['Biotechnologie', 'Natuurlijke selectie'] },
      { t: 'Insuline', d: 'een hormoon dat met gm-bacteriën gemaakt kan worden', k: 'hormoon uit gm-bacteriën', fout: ['Antibioticum'] },
      { t: 'Gm-gewas', d: 'een gewas met gericht veranderd DNA', k: 'gewas met veranderd DNA', fout: ['Genetische modificatie'] },
      { t: 'Resistentie', d: 'ongevoeligheid van bacteriën voor een antibioticum', k: 'ongevoelig voor antibiotica', fout: ['Antibioticum'] },
      { t: 'Vaccin', d: 'een middel dat je afweer traint tegen een ziekteverwekker', k: 'traint de afweer', fout: ['Antibioticum'] },
      { t: 'Bacterie', d: 'een eencellig organisme zonder celkern', k: 'eencellig, geen kern', fout: ['Schimmel', 'Gist'] },
    ],
    [
      { v: 'Wat is biotechnologie?', o: ['Het bestuderen van sterren', 'Organismen gebruiken om iets te maken', 'Het bouwen van machines', 'Het meten van het weer'], c: 1, d: 2, uo: ['Dat is sterrenkunde.', 'Klopt: organismen inzetten om producten te maken.', 'Dat is techniek.', 'Dat is het weerbericht.'] },
      { v: 'Wat doet gist in brood?', o: ['Het maakt het brood zout', 'Het kleurt het brood', 'Het laat het deeg rijzen', 'Het koelt het brood af'], c: 2, d: 2, uo: ['Gist maakt het niet zout.', 'Gist kleurt niet.', 'Klopt: gist laat het deeg rijzen.', 'Gist koelt niet.'] },
      { v: 'Welk micro-organisme maakt van melk yoghurt?', o: ['De melkzuurbacterie', 'Een schimmel', 'Een virus', 'Gist'], c: 0, d: 2, uo: ['Klopt: de melkzuurbacterie maakt yoghurt.', 'Een schimmel maakt o.a. antibiotica.', 'Een virus maakt ziek.', 'Gist laat deeg rijzen.'] },
      { v: 'Waar worden antibiotica onder andere van gemaakt?', o: ['Van gist', 'Van melk', 'Van virussen', 'Van schimmels'], c: 3, d: 3, uo: ['Gist laat deeg rijzen.', 'Melk wordt yoghurt.', 'Virussen maken juist ziek.', 'Klopt: sommige schimmels maken antibiotica.'] },
      { v: 'Waartegen werkt een antibioticum?', o: ['Tegen kou', 'Tegen bacteriën', 'Tegen honger', 'Tegen dorst'], c: 1, d: 1, uo: ['Niet tegen kou.', 'Klopt: een antibioticum doodt of remt bacteriën.', 'Niet tegen honger.', 'Niet tegen dorst.'] },
      { v: 'Wat is genetische modificatie?', o: ['Een dier goed voeren', 'Een plant water geven', 'Het DNA gericht veranderen', 'Een dier trainen'], c: 2, d: 2, uo: ['Voeren verandert het DNA niet.', 'Water geven ook niet.', 'Klopt: het DNA gericht veranderen.', 'Trainen verandert het DNA niet.'] },
      { v: 'Waarvoor gebruiken we gm-bacteriën onder andere?', o: ['Om insuline te maken', 'Om brood te bakken', 'Om te sporten', 'Om te rekenen'], c: 0, d: 3, uo: ['Klopt: gm-bacteriën maken insuline.', 'Bakken doet de bakker.', 'Bacteriën sporten niet.', 'Bacteriën rekenen niet.'] },
      { v: 'Wat is gisting?', o: ['Verbranden met zuurstof', 'Bevriezen van voedsel', 'Koken van water', 'Suiker omzetten zonder zuurstof'], c: 3, d: 3, uo: ['Verbranden gebruikt juist zuurstof.', 'Bevriezen is iets anders.', 'Koken is iets anders.', 'Klopt: suiker omzetten zonder zuurstof.'] },
      { v: 'Wat kan een schimmel maken?', o: ['Botten', 'Antibiotica', 'Bloed', 'Spieren'], c: 1, d: 2, uo: ['Botten maakt het beenmerg.', 'Klopt: sommige schimmels maken antibiotica.', 'Bloed maakt het beenmerg.', 'Spieren groeien door training.'] },
      { v: 'Wat is insuline?', o: ['Een soort bacterie', 'Een soort schimmel', 'Een hormoon voor de bloedsuiker', 'Een antibioticum'], c: 2, d: 2, uo: ['Insuline is geen bacterie.', 'Ook geen schimmel.', 'Klopt: insuline regelt de bloedsuiker.', 'Insuline is geen antibioticum.'] },
      { v: 'Wat is een voordeel van gm-gewassen?', o: ['Beter tegen droogte', 'Ze smaken heel zoet', 'Ze groeien niet meer', 'Ze worden zwaarder dan lood'], c: 0, d: 3, uo: ['Klopt: bijvoorbeeld beter tegen droogte.', 'Smaak is niet het doel.', 'Ze groeien juist wel.', 'Dat is onmogelijk.'] },
      { v: 'Wat gebeurt er met melk door melkzuurbacteriën?', o: ['De melk bevriest', 'De melk verdampt', 'De melk wordt gekookt', 'De melk wordt yoghurt of kaas'], c: 3, d: 2, uo: ['Bevriezen is iets anders.', 'Verdampen is iets anders.', 'Koken is iets anders.', 'Klopt: de melk wordt yoghurt of kaas.'] },
      { v: 'Wat betekent resistentie bij bacteriën?', o: ['Ze worden beter gevoed', 'Ze zijn ongevoelig voor antibiotica', 'Ze worden groter', 'Ze gaan sneller dood'], c: 1, d: 3, uo: ['Voeding is niet het punt.', 'Klopt: ongevoelig voor antibiotica.', 'Grootte is niet het punt.', 'Bij resistentie gaan ze juist niet dood.'] },
      { v: 'Wat doet een vaccin?', o: ['Het doodt bacteriën direct', 'Het geeft je energie', 'Het traint je afweer', 'Het maakt je ziek'], c: 2, d: 2, uo: ['Dat doet een antibioticum.', 'Een vaccin geeft geen energie.', 'Klopt: een vaccin traint de afweer.', 'Het maakt je juist niet ziek.'] },
      { v: 'Wat is een bacterie?', o: ['Eencellig, zonder kern', 'Een groot dier met botten', 'Een harde grijze steen', 'Een glanzend metaal'], c: 0, d: 1, uo: ['Klopt: eencellig, zonder celkern.', 'Een bacterie is geen groot dier.', 'Een bacterie leeft.', 'Een bacterie is geen metaal.'] },
      { v: 'Waarom is te veel antibiotica gebruiken een probleem?', o: ['Het voedt de bacteriën', 'Het maakt bacteriën groter', 'Het maakt bacteriën sneller', 'Bacteriën worden resistent'], c: 3, d: 3, uo: ['Het voedt ze niet.', 'Grootte is niet het punt.', 'Snelheid is niet het punt.', 'Klopt: bacteriën worden ongevoelig (resistent).'] },
    ]),
];
