// VMBO GL/TL - Aardrijkskunde. Gouden-stijl contentspec.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vmbo', vak: 'ak', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Weer en klimaat',
    `<strong>Weer</strong> is de toestand van de atmosfeer op een moment; <strong>klimaat</strong> is het gemiddelde weer over dertig jaar. Lucht stroomt van een <strong>hogedrukgebied</strong> naar een <strong>lagedrukgebied</strong>: dat is <strong>wind</strong>.`,
    [
      { h: '1. Weer en klimaat', p: [
        `<strong>Weer</strong> beschrijft de toestand van de lucht op één moment (nu regen, straks zon). <strong>Klimaat</strong> is het gemiddelde weer over een lange periode, meestal dertig jaar. Nederland heeft een <strong>zeeklimaat</strong>: milde winters en koele zomers door de invloed van de zee. Ver van zee heerst een <strong>landklimaat</strong> met koude winters en warme zomers.`] },
      { h: '2. Luchtdruk en wind', p: [
        `De <strong>luchtdruk</strong> is de druk die de lucht uitoefent. In een <strong>lagedrukgebied</strong> stijgt lucht op: vaak bewolkt en nat. In een <strong>hogedrukgebied</strong> daalt lucht: vaak droog en zonnig. Lucht stroomt van hoge naar lage druk, en die stroming is de <strong>wind</strong>. De <strong>wet van Buys Ballot</strong> beschrijft hoe de wind rond die gebieden draait.`,
        `Op een weerkaart verbindt een <strong>isobar</strong> punten met dezelfde luchtdruk, en een <strong>front</strong> is de grens tussen warme en koude lucht.`] },
      { h: '3. Een klimaatgrafiek lezen', p: [
        `Een <strong>klimaatgrafiek</strong> laat per maand de gemiddelde <strong>temperatuur</strong> (als lijn) en de <strong>neerslag</strong> (als staven) zien. Zo herken je bijvoorbeeld een natte winter en een droge zomer, of andersom.`] },
    ],
    [
      { t: 'Weer', d: 'de toestand van de atmosfeer op een bepaald moment', k: 'toestand van de lucht nu', fout: ['Klimaat'] },
      { t: 'Klimaat', d: 'het gemiddelde weer over een lange periode van dertig jaar', k: 'gemiddeld weer, lange termijn', fout: ['Weer'] },
      { t: 'Luchtdruk', d: 'de druk die de lucht op het aardoppervlak uitoefent', k: 'druk van de lucht', fout: ['Lagedrukgebied', 'Hogedrukgebied'] },
      { t: 'Lagedrukgebied', d: 'een gebied met lage luchtdruk, vaak bewolkt en nat', k: 'lage druk, nat weer', fout: ['Hogedrukgebied'] },
      { t: 'Hogedrukgebied', d: 'een gebied met hoge luchtdruk, vaak droog en zonnig', k: 'hoge druk, droog weer', fout: ['Lagedrukgebied'] },
      { t: 'Wind', d: 'bewegende lucht van een hogedruk- naar een lagedrukgebied', k: 'bewegende lucht', fout: ['Luchtdruk'] },
      { t: 'Wet van Buys Ballot', d: 'de regel die de windrichting rond hoge- en lagedrukgebieden beschrijft', k: 'regel voor windrichting', fout: ['Isobar'] },
      { t: 'Neerslag', d: 'water dat uit de lucht valt, zoals regen en sneeuw', k: 'regen en sneeuw', fout: ['Temperatuur', 'Verdamping'] },
      { t: 'Temperatuur', d: 'de mate van warmte, gemeten in graden', k: 'hoe warm het is', fout: ['Neerslag'] },
      { t: 'Klimaatgrafiek', d: 'een grafiek met de gemiddelde temperatuur en neerslag per maand', k: 'temperatuur en neerslag per maand', fout: ['Isobar'] },
      { t: 'Isobar', d: 'een lijn op een weerkaart die punten met gelijke luchtdruk verbindt', k: 'lijn van gelijke druk', fout: ['Klimaatgrafiek'] },
      { t: 'Front', d: 'de grens tussen warme en koude lucht', k: 'grens warme en koude lucht', fout: ['Isobar'] },
      { t: 'Zeeklimaat', d: 'een klimaat met milde winters en koele zomers door de zee', k: 'mild door de zee', fout: ['Landklimaat'] },
      { t: 'Landklimaat', d: 'een klimaat met koude winters en warme zomers, ver van zee', k: 'extreem, ver van zee', fout: ['Zeeklimaat'] },
    ],
    [
      { v: 'Wat is het verschil tussen weer en klimaat?', o: ['Ze zijn hetzelfde', 'Weer is nu, klimaat is gemiddeld over 30 jaar', 'Weer is gemiddeld', 'Klimaat is van vandaag'], c: 1, d: 2, uo: ['Nee.', 'Klopt: weer is nu, klimaat over lange tijd.', 'Nee, dat is klimaat.', 'Nee.'] },
      { v: 'Wat gebeurt er in een lagedrukgebied?', o: ['Droog en zonnig', 'De lucht daalt', 'Vaak bewolkt en nat', 'Geen wind'], c: 2, d: 2, uo: ['Dat is hogedruk.', 'De lucht stijgt juist.', 'Klopt: opstijgende lucht, vaak nat.', 'Er is juist wind.'] },
      { v: 'Wat is wind?', o: ['Bewegende lucht van hoge naar lage druk', 'Stilstaande lucht', 'Warme grond', 'Regen'], c: 0, d: 1, uo: ['Klopt: lucht stroomt van hoge naar lage druk.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat lees je af aan een klimaatgrafiek?', o: ['Alleen de wind', 'De hoogte', 'De bevolking', 'Temperatuur en neerslag per maand'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: gemiddelde temperatuur en neerslag per maand.'] },
      { v: 'Nederland heeft een...', o: ['woestijnklimaat', 'zeeklimaat', 'poolklimaat', 'landklimaat'], c: 1, d: 2, uo: ['Nee.', 'Klopt: mild door de zee.', 'Nee.', 'Dat is ver van zee.'] },
      { v: 'Wat is een hogedrukgebied?', o: ['Nat en bewolkt', 'Veel wind', 'Vaak droog en zonnig', 'Vol neerslag'], c: 2, d: 2, uo: ['Dat is lagedruk.', 'Nee.', 'Klopt: dalende lucht, droog weer.', 'Nee.'] },
      { v: 'Wat is neerslag?', o: ['Regen en sneeuw', 'Wind', 'Temperatuur', 'Luchtdruk'], c: 0, d: 1, uo: ['Klopt: water dat uit de lucht valt.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een isobar op een weerkaart?', o: ['Een grens tussen landen', 'Een rivier', 'Een weg', 'Een lijn van gelijke luchtdruk'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: verbindt punten met dezelfde luchtdruk.'] },
      { v: 'Wat is een landklimaat?', o: ['Mild door de zee', 'Koude winters en warme zomers', 'Altijd warm', 'Altijd nat'], c: 1, d: 2, uo: ['Dat is zeeklimaat.', 'Klopt: extreem, ver van zee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een front?', o: ['Een hogedrukgebied', 'Een isobar', 'De grens tussen warme en koude lucht', 'Een klimaatgrafiek'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: de grens tussen warme en koude lucht.', 'Nee.'] },
      { v: 'Waarom is het bij een zeeklimaat mild?', o: ['Door de invloed van de zee', 'Door de woestijn', 'Door bergen', 'Door de stad'], c: 0, d: 3, uo: ['Klopt: de zee zorgt voor milde temperaturen.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('B', 'Water',
    `In de <strong>waterkringloop</strong> verdampt water, valt het als <strong>neerslag</strong> en stroomt het via <strong>rivieren</strong> terug naar zee. Nederland ligt laag en beschermt zich met <strong>dijken</strong>, <strong>polders</strong> en <strong>gemalen</strong>.`,
    [
      { h: '1. De waterkringloop', p: [
        `Water is voortdurend in beweging. Door <strong>verdamping</strong> wordt zeewater waterdamp, die als <strong>neerslag</strong> weer valt. Een deel zakt weg als <strong>grondwater</strong>, een deel stroomt via een <strong>rivier</strong> naar zee, waar de rivier zich in een <strong>delta</strong> vertakt. Dit geheel heet de <strong>waterkringloop</strong>.`] },
      { h: '2. Nederland en het water', p: [
        `Grote delen van Nederland liggen onder zeeniveau. Een <strong>dijk</strong> houdt het water tegen, een <strong>polder</strong> is drooggelegd land en een <strong>gemaal</strong> pompt overtollig water weg. Het <strong>waterschap</strong> beheert de dijken en het waterpeil. Door <strong>zeespiegelstijging</strong> neemt het risico op <strong>overstroming</strong> toe.`] },
    ],
    [
      { t: 'Waterkringloop', d: 'de kringloop van verdamping, neerslag en afstroming van water', k: 'water gaat rond', fout: ['Verdamping'] },
      { t: 'Verdamping', d: 'het overgaan van water in waterdamp', k: 'water wordt damp', fout: ['Neerslag'] },
      { t: 'Neerslag', d: 'water dat uit de lucht valt, zoals regen en sneeuw', k: 'regen en sneeuw', fout: ['Verdamping'] },
      { t: 'Grondwater', d: 'water dat zich in de bodem bevindt', k: 'water in de bodem', fout: ['Rivier'] },
      { t: 'Rivier', d: 'stromend water dat richting de zee gaat', k: 'stromend water naar zee', fout: ['Delta', 'Grondwater'] },
      { t: 'Delta', d: 'het gebied waar een rivier zich vertakt en in zee uitmondt', k: 'riviermonding in zee', fout: ['Rivier'] },
      { t: 'Dijk', d: 'een verhoging die het land tegen water beschermt', k: 'waterkering', fout: ['Gemaal', 'Polder'] },
      { t: 'Polder', d: 'laaggelegen land dat door dijken en gemalen droog blijft', k: 'drooggelegd laagland', fout: ['Dijk', 'Gemaal'] },
      { t: 'Gemaal', d: 'een installatie die overtollig water wegpompt', k: 'pompt water weg', fout: ['Dijk'] },
      { t: 'Overstroming', d: 'het onderlopen van land met water', k: 'land loopt onder', fout: ['Zeespiegelstijging'] },
      { t: 'Zeespiegelstijging', d: 'het stijgen van het gemiddelde zeeniveau', k: 'zee komt hoger', fout: ['Overstroming'] },
      { t: 'Waterschap', d: 'het bestuur dat zorgt voor dijken en het waterpeil', k: 'bestuur voor water', fout: ['Gemaal'] },
    ],
    [
      { v: 'Wat is de waterkringloop?', o: ['Water dat verdwijnt', 'Verdamping, neerslag en afstroming', 'Alleen regen', 'Een rivier'], c: 1, d: 2, uo: ['Water verdwijnt niet.', 'Klopt: water gaat rond via verdamping en neerslag.', 'Nee, dat is één deel.', 'Nee.'] },
      { v: 'Wat is verdamping?', o: ['Regen die valt', 'Water dat bevriest', 'Water dat waterdamp wordt', 'Water in de bodem'], c: 2, d: 1, uo: ['Dat is neerslag.', 'Nee.', 'Klopt: water wordt waterdamp.', 'Dat is grondwater.'] },
      { v: 'Wat doet een dijk?', o: ['Houdt het water tegen', 'Pompt water weg', 'Maakt regen', 'Legt land droog'], c: 0, d: 1, uo: ['Klopt: een dijk houdt het water tegen.', 'Dat doet een gemaal.', 'Nee.', 'Dat doet een polder.'] },
      { v: 'Wat is een polder?', o: ['Een berg', 'Een woestijn', 'Een zee', 'Drooggelegd laaggelegen land'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: laag land dat door dijken en gemalen droog blijft.'] },
      { v: 'Wat doet een gemaal?', o: ['Water tegenhouden', 'Overtollig water wegpompen', 'Regen maken', 'Dijken bouwen'], c: 1, d: 2, uo: ['Dat doet een dijk.', 'Klopt: het pompt overtollig water weg.', 'Nee.', 'Nee.'] },
      { v: 'Wat is grondwater?', o: ['Water in de zee', 'Regen in de lucht', 'Water in de bodem', 'Water in een rivier'], c: 2, d: 1, uo: ['Nee.', 'Nee.', 'Klopt: water dat in de bodem zit.', 'Nee.'] },
      { v: 'Wat is een delta?', o: ['Waar een rivier in zee uitmondt', 'Een berg', 'Een woestijn', 'Een dijk'], c: 0, d: 2, uo: ['Klopt: waar een rivier zich vertakt en in zee uitmondt.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Waardoor neemt het overstromingsrisico toe?', o: ['Door minder regen', 'Door een lagere zeespiegel', 'Door meer dijken', 'Door zeespiegelstijging'], c: 3, d: 3, uo: ['Nee.', 'Juist andersom.', 'Dijken helpen juist.', 'Klopt: door de stijgende zeespiegel.'] },
      { v: 'Wat beheert het waterschap?', o: ['De wegen', 'De dijken en het waterpeil', 'De scholen', 'De belasting'], c: 1, d: 2, uo: ['Nee.', 'Klopt: het waterschap zorgt voor dijken en waterpeil.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een rivier?', o: ['Stilstaand water', 'Water in de bodem', 'Stromend water naar de zee', 'Regen'], c: 2, d: 1, uo: ['Nee.', 'Dat is grondwater.', 'Klopt: stromend water dat naar zee gaat.', 'Nee.'] },
      { v: 'Waarom is Nederland kwetsbaar voor water?', o: ['Grote delen liggen laag', 'Het ligt hoog', 'Er is geen zee', 'Er valt nooit regen'], c: 0, d: 3, uo: ['Klopt: veel land ligt onder zeeniveau.', 'Juist niet.', 'Er is wel zee.', 'Er valt wel regen.'] },
    ]),

  V('C', 'Bevolking en ruimte',
    `De <strong>bevolkingsgroei</strong> hangt af van het <strong>geboortecijfer</strong>, het <strong>sterftecijfer</strong> en <strong>migratie</strong>. Door <strong>verstedelijking</strong> trekken mensen naar de stad.`,
    [
      { h: '1. Waardoor groeit een bevolking?', p: [
        `Een bevolking groeit door geboorte en immigratie, en krimpt door sterfte en emigratie. Het <strong>geboortecijfer</strong> en het <strong>sterftecijfer</strong> geven het aantal geboorten en sterfgevallen per duizend inwoners. Het verschil is de <strong>natuurlijke aanwas</strong>. Daarnaast telt <strong>migratie</strong> mee: <strong>immigratie</strong> is een land binnenkomen, <strong>emigratie</strong> is vertrekken.`] },
      { h: '2. Steden en spreiding', p: [
        `Door <strong>verstedelijking</strong> groeien steden en neemt het aandeel stadsbewoners toe; het trekken van het platteland naar de stad heet <strong>urbanisatie</strong>. De <strong>bevolkingsdichtheid</strong> zegt hoeveel mensen er per vierkante kilometer wonen. In veel landen speelt ook <strong>vergrijzing</strong>: het aandeel ouderen stijgt.`] },
    ],
    [
      { t: 'Bevolkingsgroei', d: 'de toename van het aantal inwoners van een gebied', k: 'meer inwoners', fout: ['Natuurlijke aanwas'] },
      { t: 'Geboortecijfer', d: 'het aantal geboorten per duizend inwoners per jaar', k: 'geboorten per 1000', fout: ['Sterftecijfer'] },
      { t: 'Sterftecijfer', d: 'het aantal sterfgevallen per duizend inwoners per jaar', k: 'sterfgevallen per 1000', fout: ['Geboortecijfer'] },
      { t: 'Natuurlijke aanwas', d: 'het geboortecijfer min het sterftecijfer', k: 'geboorten min sterfte', fout: ['Bevolkingsgroei'] },
      { t: 'Migratie', d: 'het verhuizen van mensen naar een ander gebied', k: 'mensen verhuizen', fout: ['Verstedelijking'] },
      { t: 'Immigratie', d: 'het zich vestigen in een nieuw land', k: 'een land binnenkomen', fout: ['Emigratie'] },
      { t: 'Emigratie', d: 'het vertrekken uit je eigen land om elders te wonen', k: 'je land verlaten', fout: ['Immigratie'] },
      { t: 'Verstedelijking', d: 'de groei van steden en van het aandeel stadsbewoners', k: 'steden groeien', fout: ['Migratie'] },
      { t: 'Bevolkingsdichtheid', d: 'het aantal inwoners per vierkante kilometer', k: 'inwoners per km²', fout: ['Bevolkingsgroei'] },
      { t: 'Vergrijzing', d: 'de toename van het aandeel ouderen in de bevolking', k: 'meer ouderen', fout: ['Bevolkingsgroei'] },
      { t: 'Urbanisatie', d: 'het trekken van mensen van het platteland naar de stad', k: 'van platteland naar stad', fout: ['Verstedelijking'] },
      { t: 'Platteland', d: 'dunbevolkt gebied buiten de stad', k: 'buiten de stad', fout: ['Urbanisatie'] },
    ],
    [
      { v: 'Wat is het geboortecijfer?', o: ['Aantal doden per 1000', 'Aantal geboorten per 1000 inwoners', 'De bevolkingsdichtheid', 'Het aantal migranten'], c: 1, d: 2, uo: ['Dat is het sterftecijfer.', 'Klopt: geboorten per duizend inwoners.', 'Nee.', 'Nee.'] },
      { v: 'Wat is natuurlijke aanwas?', o: ['Migratie', 'Bevolkingsdichtheid', 'Geboortecijfer min sterftecijfer', 'Verstedelijking'], c: 2, d: 3, uo: ['Nee.', 'Nee.', 'Klopt: geboorten min sterfte.', 'Nee.'] },
      { v: 'Wat is immigratie?', o: ['Een land binnenkomen', 'Een land verlaten', 'In de stad wonen', 'Op het platteland wonen'], c: 0, d: 1, uo: ['Klopt: je vestigen in een nieuw land.', 'Dat is emigratie.', 'Nee.', 'Nee.'] },
      { v: 'Wat is emigratie?', o: ['Een land binnenkomen', 'In de stad gaan wonen', 'Kinderen krijgen', 'Je eigen land verlaten'], c: 3, d: 2, uo: ['Dat is immigratie.', 'Nee.', 'Nee.', 'Klopt: vertrekken uit je eigen land.'] },
      { v: 'Wat is verstedelijking?', o: ['Steden krimpen', 'Steden groeien', 'Minder mensen', 'Meer platteland'], c: 1, d: 2, uo: ['Juist niet.', 'Klopt: steden groeien, meer stadsbewoners.', 'Nee.', 'Nee.'] },
      { v: 'Wat is bevolkingsdichtheid?', o: ['Het aantal geboorten', 'Het aantal doden', 'Inwoners per vierkante kilometer', 'De migratie'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: inwoners per km².', 'Nee.'] },
      { v: 'Wat is vergrijzing?', o: ['Meer ouderen in de bevolking', 'Meer kinderen', 'Meer migranten', 'Meer steden'], c: 0, d: 2, uo: ['Klopt: het aandeel ouderen stijgt.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is urbanisatie?', o: ['Van stad naar platteland', 'Meer kinderen', 'Minder mensen', 'Van platteland naar de stad'], c: 3, d: 3, uo: ['Juist andersom.', 'Nee.', 'Nee.', 'Klopt: mensen trekken van het platteland naar de stad.'] },
      { v: 'Wat is het sterftecijfer?', o: ['Geboorten per 1000', 'Sterfgevallen per 1000 inwoners', 'De migratie', 'De dichtheid'], c: 1, d: 2, uo: ['Dat is het geboortecijfer.', 'Klopt: sterfgevallen per duizend inwoners.', 'Nee.', 'Nee.'] },
      { v: 'Wat is migratie?', o: ['Kinderen krijgen', 'In de stad wonen', 'Verhuizen naar een ander gebied', 'Sterven'], c: 2, d: 1, uo: ['Nee.', 'Nee.', 'Klopt: mensen verhuizen naar een ander gebied.', 'Nee.'] },
      { v: 'Wat is het platteland?', o: ['Dunbevolkt gebied buiten de stad', 'Het centrum van de stad', 'Een industriegebied', 'Een haven'], c: 0, d: 1, uo: ['Klopt: dunbevolkt gebied buiten de stad.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('D', 'Arm en rijk',
    `De <strong>welvaart</strong> verschilt sterk tussen landen; het <strong>bnp per inwoner</strong> is er een maat voor. Rijke <strong>centrumgebieden</strong> staan tegenover arme <strong>periferiegebieden</strong>.`,
    [
      { h: '1. Welvaart meten', p: [
        `<strong>Welvaart</strong> is de mate waarin mensen in hun behoeften kunnen voorzien. Je meet die onder meer met het <strong>bnp per inwoner</strong> (de gemiddelde productie per persoon), de <strong>levensverwachting</strong> en het <strong>analfabetisme</strong>. Landen met lage welvaart heten <strong>ontwikkelingslanden</strong>, landen met hoge welvaart <strong>ontwikkelde landen</strong>.`] },
      { h: '2. Centrum en periferie', p: [
        `Binnen en tussen landen zie je een rijk <strong>centrum</strong> met veel bedrijvigheid en een arme <strong>periferie</strong> aan de rand. Zulke <strong>welvaartsverschillen</strong> ontstaan door verschillen in <strong>grondstoffen</strong>, onderwijs, <strong>infrastructuur</strong> en handel. Met <strong>ontwikkelingssamenwerking</strong> worden armere landen geholpen.`] },
    ],
    [
      { t: 'Welvaart', d: 'de mate waarin mensen in hun behoeften kunnen voorzien', k: 'hoe goed men rondkomt', fout: ['Welvaartsverschil'] },
      { t: 'Bnp per inwoner', d: 'de gemiddelde productie per persoon in een land', k: 'productie per persoon', fout: ['Levensverwachting'] },
      { t: 'Ontwikkelingsland', d: 'een land met een lage welvaart', k: 'arm land', fout: ['Ontwikkeld land'] },
      { t: 'Ontwikkeld land', d: 'een land met een hoge welvaart', k: 'rijk land', fout: ['Ontwikkelingsland'] },
      { t: 'Centrum', d: 'een rijk en welvarend gebied met veel bedrijvigheid', k: 'rijk kerngebied', fout: ['Periferie'] },
      { t: 'Periferie', d: 'een arm en afgelegen gebied aan de rand', k: 'arm randgebied', fout: ['Centrum'] },
      { t: 'Welvaartsverschil', d: 'het verschil in rijkdom tussen gebieden of landen', k: 'verschil in rijkdom', fout: ['Welvaart'] },
      { t: 'Analfabetisme', d: 'het niet kunnen lezen en schrijven', k: 'niet kunnen lezen', fout: ['Levensverwachting'] },
      { t: 'Levensverwachting', d: 'het gemiddelde aantal jaren dat iemand naar verwachting leeft', k: 'gemiddelde levensduur', fout: ['Bnp per inwoner'] },
      { t: 'Grondstoffen', d: 'natuurlijke stoffen waarmee een land geld kan verdienen', k: 'natuurlijke rijkdommen', fout: ['Infrastructuur'] },
      { t: 'Infrastructuur', d: 'voorzieningen zoals wegen, havens en spoor', k: 'wegen en verbindingen', fout: ['Grondstoffen'] },
      { t: 'Ontwikkelingssamenwerking', d: 'hulp aan armere landen om zich te ontwikkelen', k: 'hulp aan arme landen', fout: ['Welvaartsverschil'] },
    ],
    [
      { v: 'Wat is welvaart?', o: ['Alleen geld', 'Hoe goed mensen in hun behoeften kunnen voorzien', 'Het weer', 'De bevolking'], c: 1, d: 2, uo: ['Het is meer dan alleen geld.', 'Klopt: hoe goed men kan rondkomen.', 'Nee.', 'Nee.'] },
      { v: 'Wat meet het bnp per inwoner?', o: ['De bevolking', 'Het weer', 'De gemiddelde productie per persoon', 'De oppervlakte'], c: 2, d: 3, uo: ['Nee.', 'Nee.', 'Klopt: de gemiddelde productie per persoon.', 'Nee.'] },
      { v: 'Wat is een ontwikkelingsland?', o: ['Een land met lage welvaart', 'Een rijk land', 'Een groot land', 'Een klein land'], c: 0, d: 1, uo: ['Klopt: een land met lage welvaart.', 'Dat is een ontwikkeld land.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een centrumgebied?', o: ['Een arm randgebied', 'Een leeg gebied', 'Een woestijn', 'Een rijk gebied met veel bedrijvigheid'], c: 3, d: 2, uo: ['Dat is de periferie.', 'Nee.', 'Nee.', 'Klopt: een rijk, welvarend kerngebied.'] },
      { v: 'Wat is de periferie?', o: ['Het rijke centrum', 'Een arm, afgelegen randgebied', 'De hoofdstad', 'Een fabriek'], c: 1, d: 2, uo: ['Juist het tegenovergestelde.', 'Klopt: arm gebied aan de rand.', 'Nee.', 'Nee.'] },
      { v: 'Wat is levensverwachting?', o: ['Het geboortecijfer', 'De bevolking', 'Het gemiddelde aantal jaren dat iemand leeft', 'De welvaart'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: de gemiddelde levensduur.', 'Nee.'] },
      { v: 'Wat is analfabetisme?', o: ['Niet kunnen lezen en schrijven', 'Rijk zijn', 'Ziek zijn', 'Werkloos zijn'], c: 0, d: 1, uo: ['Klopt: niet kunnen lezen en schrijven.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Waardoor ontstaan welvaartsverschillen?', o: ['Door het weer alleen', 'Door toeval', 'Door de kleur van de vlag', 'Door grondstoffen, onderwijs en handel'], c: 3, d: 3, uo: ['Niet alleen.', 'Nee.', 'Nee.', 'Klopt: verschillen in grondstoffen, onderwijs en handel.'] },
      { v: 'Wat is een ontwikkeld land?', o: ['Een land met lage welvaart', 'Een land met hoge welvaart', 'Een klein land', 'Een warm land'], c: 1, d: 1, uo: ['Dat is een ontwikkelingsland.', 'Klopt: een rijk land met hoge welvaart.', 'Nee.', 'Nee.'] },
      { v: 'Wat is ontwikkelingssamenwerking?', o: ['Handel met winst', 'Belasting', 'Hulp aan armere landen', 'Een oorlog'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: hulp aan armere landen.', 'Nee.'] },
      { v: 'Waarmee kan een land geld verdienen?', o: ['Met grondstoffen', 'Met het weer', 'Met de vlag', 'Met de tijd'], c: 0, d: 2, uo: ['Klopt: met grondstoffen kan een land geld verdienen.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('E', 'Ruimtelijke ordening',
    `<strong>Ruimtelijke ordening</strong> is het plannen van het gebruik van de ruimte. In een <strong>bestemmingsplan</strong> legt de overheid vast welke <strong>bestemming</strong> een gebied krijgt: wonen, werken of natuur.`,
    [
      { h: '1. De ruimte plannen', p: [
        `Nederland is klein en dichtbevolkt, dus de ruimte wordt zorgvuldig verdeeld: dat is <strong>ruimtelijke ordening</strong>. In een <strong>bestemmingsplan</strong> legt de gemeente vast waarvoor grond gebruikt mag worden. De <strong>bestemming</strong> is de functie die een gebied krijgt; de <strong>functie</strong> is het gebruik ervan, zoals wonen of natuur.`] },
      { h: '2. Belangen afwegen', p: [
        `Bij het inrichten van een gebied botsen vaak verschillende <strong>belangen</strong>. De overheid maakt dan een <strong>belangenafweging</strong>. Zo kies je tussen een <strong>woonfunctie</strong> en een <strong>recreatiefunctie</strong>, of tussen een <strong>industriegebied</strong> en een beschermd <strong>natuurgebied</strong>.`] },
    ],
    [
      { t: 'Ruimtelijke ordening', d: 'het indelen en plannen van het gebruik van de ruimte', k: 'de ruimte plannen', fout: ['Bestemmingsplan'] },
      { t: 'Bestemmingsplan', d: 'een plan dat vastlegt waarvoor grond gebruikt mag worden', k: 'plan voor grondgebruik', fout: ['Bestemming', 'Ruimtelijke ordening'] },
      { t: 'Bestemming', d: 'de functie die een gebied volgens het plan krijgt', k: 'toegewezen functie', fout: ['Functie'] },
      { t: 'Functie', d: 'het gebruik of doel van een gebied', k: 'gebruik van een gebied', fout: ['Bestemming'] },
      { t: 'Belang', d: 'het voordeel dat iemand bij iets heeft', k: 'wat iemand wil', fout: ['Belangenafweging'] },
      { t: 'Belangenafweging', d: 'het tegen elkaar afwegen van verschillende belangen', k: 'belangen afwegen', fout: ['Belang'] },
      { t: 'Woonfunctie', d: 'het gebruik van een gebied om te wonen', k: 'gebied om te wonen', fout: ['Recreatiefunctie'] },
      { t: 'Recreatiefunctie', d: 'het gebruik van een gebied voor ontspanning', k: 'gebied voor ontspanning', fout: ['Woonfunctie'] },
      { t: 'Industriegebied', d: 'een gebied bestemd voor bedrijven en fabrieken', k: 'gebied voor bedrijven', fout: ['Natuurgebied'] },
      { t: 'Natuurgebied', d: 'een gebied dat beschermd is voor planten en dieren', k: 'beschermde natuur', fout: ['Industriegebied'] },
      { t: 'Verstedelijking', d: 'de groei van steden en het stedelijk ruimtegebruik', k: 'steden groeien', fout: ['Woonfunctie'] },
      { t: 'Infrastructuur', d: 'voorzieningen zoals wegen en verbindingen in een gebied', k: 'wegen en verbindingen', fout: ['Industriegebied'] },
    ],
    [
      { v: 'Wat is ruimtelijke ordening?', o: ['De ruimte laten zoals hij is', 'Het plannen van het gebruik van de ruimte', 'Alleen bouwen', 'Alleen natuur'], c: 1, d: 2, uo: ['Nee.', 'Klopt: het indelen en plannen van de ruimte.', 'Nee.', 'Nee.'] },
      { v: 'Wat legt een bestemmingsplan vast?', o: ['De belasting', 'Het weer', 'Waarvoor grond gebruikt mag worden', 'De bevolking'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: waarvoor grond gebruikt mag worden.', 'Nee.'] },
      { v: 'Wat is de bestemming van een gebied?', o: ['De functie die het krijgt', 'De prijs', 'De bevolking', 'Het weer'], c: 0, d: 2, uo: ['Klopt: de functie, zoals wonen of natuur.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat doe je bij een belangenafweging?', o: ['Eén belang blind kiezen', 'Niets doen', 'Alles verbieden', 'Belangen tegen elkaar afwegen'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: verschillende belangen tegen elkaar afwegen.'] },
      { v: 'Wat is een woonfunctie?', o: ['Een gebied voor fabrieken', 'Een gebied om te wonen', 'Een natuurgebied', 'Een haven'], c: 1, d: 1, uo: ['Dat is industrie.', 'Klopt: een gebied om te wonen.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een natuurgebied?', o: ['Een industrieterrein', 'Een woonwijk', 'Beschermd gebied voor planten en dieren', 'Een haven'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: beschermde natuur.', 'Nee.'] },
      { v: 'Waarom is ruimtelijke ordening in Nederland belangrijk?', o: ['Het land is klein en dichtbevolkt', 'Er is veel lege ruimte', 'Er wonen weinig mensen', 'Er is geen water'], c: 0, d: 3, uo: ['Klopt: weinig ruimte, veel mensen.', 'Juist niet.', 'Er wonen juist veel mensen.', 'Er is juist veel water.'] },
      { v: 'Wat is een recreatiefunctie?', o: ['Wonen', 'Werken in een fabriek', 'Een haven', 'Een gebied voor ontspanning'], c: 3, d: 2, uo: ['Dat is wonen.', 'Dat is industrie.', 'Nee.', 'Klopt: een gebied voor ontspanning.'] },
      { v: 'Wat is een industriegebied?', o: ['Een natuurgebied', 'Een gebied voor bedrijven en fabrieken', 'Een woonwijk', 'Een park'], c: 1, d: 1, uo: ['Juist niet.', 'Klopt: een gebied voor bedrijven.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een belang?', o: ['Een gebouw', 'Een wet', 'Het voordeel dat iemand ergens bij heeft', 'Een straf'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: wat iemand ergens bij te winnen heeft.', 'Nee.'] },
      { v: 'Wie bepaalt mede de ruimtelijke ordening?', o: ['De overheid', 'Een winkel', 'Een school', 'Een sportclub'], c: 0, d: 2, uo: ['Klopt: de overheid bepaalt mede het ruimtegebruik.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),

  V('F', 'Grenzen en identiteit',
    `Een <strong>grens</strong> scheidt gebieden; soms valt hij samen met een rivier of gebergte. <strong>Migratiestromen</strong> verplaatsen mensen tussen <strong>cultuurgebieden</strong>, en gedeelde taal en gewoonten vormen een <strong>identiteit</strong>.`,
    [
      { h: '1. Grenzen en gebied', p: [
        `Een <strong>grens</strong> is de lijn die twee gebieden scheidt. Een <strong>natuurlijke grens</strong> valt samen met bijvoorbeeld een rivier of gebergte. Het gebied waarover een land zeggenschap heeft, is het <strong>territorium</strong>; over het bezit ervan ontstaat soms een <strong>territoriaal conflict</strong>.`] },
      { h: '2. Migratie, cultuur en identiteit', p: [
        `Door <strong>migratiestromen</strong> verhuizen grote groepen mensen, soms als <strong>vluchteling</strong>. Een <strong>cultuurgebied</strong> deelt taal en gewoonten (de <strong>cultuur</strong>) en soms een <strong>godsdienst</strong>. Dat gedeelde gevoel erbij te horen is de <strong>identiteit</strong>. <strong>Integratie</strong> is het meedoen van nieuwkomers in de samenleving.`] },
    ],
    [
      { t: 'Grens', d: 'de lijn die twee gebieden of landen van elkaar scheidt', k: 'scheidingslijn', fout: ['Natuurlijke grens'] },
      { t: 'Natuurlijke grens', d: 'een grens die samenvalt met een rivier of gebergte', k: 'grens langs de natuur', fout: ['Grens'] },
      { t: 'Migratiestroom', d: 'een grote verplaatsing van mensen tussen gebieden', k: 'grote verhuisstroom', fout: ['Vluchteling'] },
      { t: 'Cultuurgebied', d: 'een gebied met een gedeelde cultuur en taal', k: 'gebied met gedeelde cultuur', fout: ['Cultuur'] },
      { t: 'Identiteit', d: 'het gevoel bij een groep of gebied te horen', k: 'gevoel van erbij horen', fout: ['Cultuur'] },
      { t: 'Nationaliteit', d: 'het behoren tot een bepaald land', k: 'bij een land horen', fout: ['Identiteit'] },
      { t: 'Territorium', d: 'het gebied waarover een land zeggenschap heeft', k: 'grondgebied van een land', fout: ['Territoriaal conflict'] },
      { t: 'Territoriaal conflict', d: 'een conflict over het bezit van een gebied', k: 'ruzie over gebied', fout: ['Territorium'] },
      { t: 'Integratie', d: 'het opgaan van migranten in de samenleving', k: 'meedoen in de samenleving', fout: ['Migratiestroom'] },
      { t: 'Vluchteling', d: 'iemand die zijn land ontvlucht vanwege gevaar', k: 'ontvlucht gevaar', fout: ['Migratiestroom'] },
      { t: 'Cultuur', d: 'de gewoonten, taal en gebruiken van een groep', k: 'gewoonten en gebruiken', fout: ['Identiteit', 'Cultuurgebied'] },
      { t: 'Godsdienst', d: 'een gedeeld geloof binnen een cultuur', k: 'gedeeld geloof', fout: ['Cultuur'] },
    ],
    [
      { v: 'Wat is een grens?', o: ['Altijd een rivier', 'De lijn die twee gebieden scheidt', 'Een stad', 'Altijd een berg'], c: 1, d: 1, uo: ['Niet altijd.', 'Klopt: de scheidingslijn tussen gebieden.', 'Nee.', 'Niet altijd.'] },
      { v: 'Wat is een natuurlijke grens?', o: ['Een rechte lijn op de kaart', 'Een muur', 'Een grens langs een rivier of gebergte', 'Een stad'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: valt samen met een rivier of gebergte.', 'Nee.'] },
      { v: 'Wat is een migratiestroom?', o: ['Een grote verplaatsing van mensen', 'Een rivier', 'Een grens', 'Een cultuur'], c: 0, d: 2, uo: ['Klopt: een grote verhuizing van mensen tussen gebieden.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is identiteit?', o: ['Een grens', 'Een rivier', 'Een wet', 'Het gevoel bij een groep te horen'], c: 3, d: 2, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: het gevoel ergens bij te horen.'] },
      { v: 'Wat is een cultuurgebied?', o: ['Een leeg gebied', 'Een gebied met een gedeelde cultuur en taal', 'Een woestijn', 'Een zee'], c: 1, d: 2, uo: ['Nee.', 'Klopt: een gebied met een gedeelde cultuur.', 'Nee.', 'Nee.'] },
      { v: 'Wat is integratie?', o: ['Gescheiden leven', 'Vertrekken', 'Meedoen in de samenleving', 'Een grens'], c: 2, d: 2, uo: ['Dat is het tegenovergestelde.', 'Nee.', 'Klopt: nieuwkomers doen mee in de samenleving.', 'Nee.'] },
      { v: 'Wat is een vluchteling?', o: ['Iemand die zijn land ontvlucht', 'Een toerist', 'Een handelaar', 'Een ambtenaar'], c: 0, d: 1, uo: ['Klopt: ontvlucht gevaar.', 'Nee.', 'Nee.', 'Nee.'] },
      { v: 'Wat is een territoriaal conflict?', o: ['Een sportwedstrijd', 'Een verkiezing', 'Een handelsdeal', 'Een conflict over gebied'], c: 3, d: 3, uo: ['Nee.', 'Nee.', 'Nee.', 'Klopt: een conflict over het bezit van een gebied.'] },
      { v: 'Wat hoort bij cultuur?', o: ['Alleen het weer', 'Gewoonten, taal en gebruiken', 'Alleen de economie', 'Alleen grenzen'], c: 1, d: 2, uo: ['Nee.', 'Klopt: gewoonten, taal en gebruiken van een groep.', 'Nee.', 'Nee.'] },
      { v: 'Wat is nationaliteit?', o: ['Een cultuur', 'Een grens', 'Het behoren tot een bepaald land', 'Een rivier'], c: 2, d: 2, uo: ['Nee.', 'Nee.', 'Klopt: bij een bepaald land horen.', 'Nee.'] },
      { v: 'Wat is een territorium?', o: ['Het gebied waarover een land zeggenschap heeft', 'Een cultuur', 'Een migratiestroom', 'Een rivier'], c: 0, d: 2, uo: ['Klopt: het grondgebied van een land.', 'Nee.', 'Nee.', 'Nee.'] },
    ]),
];
