// VWO Frans - situaties per begrip.
export default {
  A: {
    Skimmen: ['Je leest snel de titel en eerste zinnen om te weten waar de tekst over gaat', 'Globaal lezen voor de grote lijn'],
    Scannen: ['Je zoekt gericht naar een jaartal in een lange tekst', 'Gericht zoeken naar een naam of getal'],
    cependant: ['Het was goedkoop; cependant, la qualité était mauvaise', 'Het Franse woord voor echter of maar'],
    pourtant: ['Il pleuvait; pourtant, nous sommes sortis', 'Het Franse woord voor toch of desondanks'],
    Context: ['Uit de rest van de zin raad je een onbekend Frans woord', 'De omringende woorden die de betekenis verduidelijken'],
    "d'une part... d'autre part": ['Enerzijds is het duur, anderzijds gaat het lang mee', 'De structuur die enerzijds tegenover anderzijds zet'],
    donc: ['Il pleuvait; donc le match a été annulé', 'Het Franse woord voor dus of daarom'],
    Hoofdgedachte: ['De belangrijkste boodschap van de tekst in één zin', 'De kern van waar de tekst over gaat'],
    toutefois: ['Les résultats sont bons; toutefois, il faut continuer', 'Het Franse woord voor toch of desondanks'],
    'ERK B2': ['Het niveau dat je aan het eind van VWO Frans moet halen', 'Het CE-niveau voor VWO Frans'],
  },
  B: {
    'en fait': ['De spreker zegt: en fait, ce n\'est pas si simple', 'Gesproken signaalwoord voor eigenlijk of in feite'],
    'quand même': ['Il fait froid, mais on y va quand même', 'Gesproken signaalwoord voor toch of desondanks'],
    Gist: ['Je hoort dat het fragment globaal over vakantie gaat', 'De grote lijn van wat gezegd wordt'],
    Detail: ['Je pikt het exacte tijdstip uit het fragment', 'Een specifiek gegeven in het fragment'],
    'Formeel register': ['In een officieel interview hoor je de vous-vorm en nette taal', 'Nette spreektaal met de vous-vorm'],
    Kernwoorden: ['Je noteert alleen de woorden die de betekenis dragen', 'De belangrijkste woorden in een fragment'],
    Voorspellen: ['Uit de titel en het beeld raad je vooraf het onderwerp', 'De inhoud vooraf inschatten'],
    'vous-vorm': ['Tegen een onbekende volwassene gebruik je vous', 'De beleefde aanspreekvorm in het Frans'],
    'tu-vorm': ['Tegen je vrienden gebruik je tu', 'De informele aanspreekvorm in het Frans'],
    Context: ['Je mist een woord, maar de situatie maakt het duidelijk', 'De situatie eromheen die helpt begrijpen'],
  },
  C: {
    'Passé composé': ['Hier, j\'ai mangé une pizza: een afgeronde handeling in de spreektaal', 'De tijd voor een afgeronde handeling'],
    Imparfait: ['Quand j\'étais petit, je jouais dehors: gewoonte in het verleden', 'De tijd voor achtergrond of gewoonte'],
    Conditionnel: ['Je lirais plus: de vorm die zou uitdrukt', 'De wijs die zou uitdrukt'],
    'parce que': ['Je reste chez moi parce que je suis malade: een nieuwe reden', 'Voegwoord dat een nieuwe reden geeft'],
    puisque: ['Puisque tu le sais déjà, je ne répète pas: een bekende reden', 'Voegwoord dat naar een bekende reden verwijst'],
    'de plus': ['C\'est bon marché; de plus, c\'est solide', 'De Franse connecteur voor bovendien'],
    donc: ['Il pleuvait; donc nous sommes restés', 'De Franse connecteur voor dus of daarom'],
    cependant: ['C\'était cher; cependant la qualité était bonne', 'De Franse connecteur voor echter'],
    'Formeel register': ['In een zakelijke brief gebruik je de vous-vorm en nette taal', 'Nette taal met de vous-vorm'],
    Connecteur: ['Het woord donc verbindt twee zinnen tot een gevolg', 'Een verbindingswoord tussen zinnen'],
  },
  D: {
    Fluency: ['Je praat vloeiend door zonder bij elke fout te stoppen', 'De vlotheid waarmee je spreekt'],
    Register: ['Tegen een leraar praat je formeler dan tegen je vrienden', 'De mate van formaliteit bij het spreken'],
    'Standpunt introduceren': ['Je zegt Par ailleurs... om een nieuw punt in te brengen', 'Je mening inbrengen in een gesprek'],
    Concessie: ['Je zegt: certes, il est vrai que... mais... om een punt toe te geven', 'Toegeven dat de ander deels gelijk heeft'],
    Omschrijven: ['Je kent het woord niet, dus je legt het met andere woorden uit', 'Een onbekend woord met andere woorden zeggen'],
    Instemmen: ['Je zegt je suis d\'accord om het eens te zijn', 'Aangeven dat je het eens bent'],
    Vulwoorden: ['Je zegt euh of ben terwijl je nadenkt', 'Woordjes die een pauze vullen'],
    Uitspraak: ['Je vormt de klanken duidelijk zodat men je verstaat', 'De manier waarop je de klanken vormt'],
    'Verduidelijking vragen': ['Je vraagt Qu\'est-ce que vous voulez dire? als je twijfelt', 'Vragen wat iemand precies bedoelt'],
    Doorvragen: ['Je stelt een extra vraag om meer te weten te komen', 'Extra vragen stellen in een gesprek'],
  },
  E: {
    Classicisme: ['Molière en Racine volgen strenge regels en de drie eenheden', 'De klassieke stroming van de 17e eeuw'],
    Romantisme: ['Een stroming vol subjectief gevoel en verheerlijking van de natuur', 'De romantische stroming van de 19e eeuw'],
    'Réalisme': ['Een stroming die de werkelijkheid nuchter en getrouw weergeeft', 'Het realisme van Flaubert'],
    Existentialisme: ['De mens moet in een absurde wereld zelf betekenis geven', 'De existentialistische stroming van Camus en Sartre'],
    'Madame Bovary': ['Flauberts roman uit 1857, hoogtepunt van het Réalisme', 'Het beroemdste werk van Flaubert'],
    "L'Étranger": ['Camus\' roman over Meursault die zonder emotie zijn moeder begraaft', 'Het bekende werk van Camus uit 1942'],
    Satire: ['Molière bespot maatschappelijke ondeugden via komische personages', 'Het bespotten van misstanden via humor'],
    'Narrateur omniscient': ['De verteller weet alles over alle personages', 'De alwetende verteller'],
    Lumières: ['Voltaire en Rousseau stellen rede, kritiek en vooruitgang centraal', 'De Verlichting in de Franse literatuur'],
    'Drie eenheden': ['Eén tijd, één plaats en één handeling in het klassieke toneel', 'De klassieke regel van eenheid'],
  },
};
