// VWO Duits - situaties per begrip.
export default {
  A: {
    Skimmen: ['Je leest snel de titel en eerste zinnen om te weten waar de tekst over gaat', 'Globaal lezen voor de grote lijn'],
    Scannen: ['Je zoekt gericht naar een jaartal in een lange tekst', 'Gericht zoeken naar een naam of getal'],
    jedoch: ['Het was goedkoop; jedoch was de kwaliteit slecht', 'Het Duitse woord voor echter of maar'],
    deshalb: ['Het regende hard; deshalb ging de wedstrijd niet door', 'Het Duitse woord voor daarom of dus'],
    Context: ['Uit de rest van de zin raad je een onbekend Duits woord', 'De omringende woorden die de betekenis verduidelijken'],
    Samenstelling: ['Handschuh bestaat uit Hand en Schuh, samen handschoen', 'Een Duits woord opgebouwd uit meerdere delen'],
    'außerdem': ['Het is goedkoop; außerdem gaat het lang mee', 'Het Duitse woord voor bovendien'],
    'nämlich': ['Ik blijf thuis; ich bin nämlich krank', 'Het Duitse woord voor namelijk of want'],
    trotzdem: ['Het was koud; trotzdem gingen we zwemmen', 'Het Duitse woord voor toch of desondanks'],
    'ERK B2': ['Het niveau dat je aan het eind van VWO Duits moet halen', 'Het CE-niveau voor VWO Duits'],
  },
  B: {
    'nämlich': ['De spreker zegt: ich komme nicht, ich bin nämlich müde', 'Gesproken signaalwoord voor namelijk of want'],
    also: ['De spreker vat samen: also, kurz gesagt...', 'Gesproken signaalwoord voor dus of kortom'],
    'Formeel register': ['In een officieel interview hoor je de Sie-vorm en nette taal', 'Nette spreektaal met de Sie-vorm'],
    Gist: ['Je hoort dat het fragment globaal over vakantie gaat', 'De grote lijn van wat gezegd wordt'],
    Detail: ['Je pikt het exacte tijdstip uit het fragment', 'Een specifiek gegeven in het fragment'],
    Kernwoorden: ['Je noteert alleen de woorden die de betekenis dragen', 'De belangrijkste woorden in een fragment'],
    Voorspellen: ['Uit de titel en het beeld raad je vooraf het onderwerp', 'De inhoud vooraf inschatten'],
    'Sie-vorm': ['Tegen een onbekende volwassene gebruik je Sie', 'De beleefde aanspreekvorm in het Duits'],
    'du-vorm': ['Tegen je vrienden gebruik je du', 'De informele aanspreekvorm in het Duits'],
    Context: ['Je mist een woord, maar de situatie maakt het duidelijk', 'De situatie eromheen die helpt begrijpen'],
  },
  C: {
    'außerdem': ['Je schrijft: es ist billig; außerdem ist es praktisch', 'Duitse Konnektor voor bovendien'],
    deshalb: ['Je schrijft: es regnete; deshalb blieben wir zu Hause', 'Duitse Konnektor voor daarom of bijgevolg'],
    Dativ: ['Na mit, aus, bei en von gebruik je deze naamval', 'De Wem-Fall, na mit/aus/bei/von'],
    Akkusativ: ['Na durch, für, ohne en gegen gebruik je deze naamval', 'De Wen-Fall, na durch/für/ohne/gegen'],
    'Formeel register': ['In een zakelijke brief gebruik je de Sie-vorm en nette taal', 'Nette taal met de Sie-vorm'],
    jedoch: ['Je schrijft: es war teuer; jedoch war die Qualität gut', 'Duitse Konnektor voor echter of maar'],
    Nominativ: ['De naamval van het onderwerp van de zin', 'De Wer-Fall, het onderwerp'],
    Genitiv: ['Das Auto des Vaters, de naamval die bezit uitdrukt', 'De Wessen-Fall, het bezit'],
    Wortstellung: ['In de Duitse hoofdzin staat de persoonsvorm op plaats twee', 'De vaste woordvolgorde van het Duits'],
    Konnektor: ['Het woord deshalb verbindt twee zinnen tot een gevolg', 'Een verbindingswoord tussen zinnen'],
  },
  D: {
    'Flüssigkeit': ['Je praat vloeiend door zonder bij elke fout te stoppen', 'De vlotheid waarmee je spreekt'],
    Register: ['Tegen een leraar praat je formeler dan tegen je vrienden', 'De mate van formaliteit bij het spreken'],
    'Standpunt introduceren': ['Je zegt Meiner Meinung nach... om je mening te geven', 'Je mening inbrengen in een gesprek'],
    Concessie: ['Je zegt: das stimmt, aber... om een punt toe te geven', 'Toegeven dat de ander deels gelijk heeft'],
    Omschrijven: ['Je kent het woord niet, dus je legt het met andere woorden uit', 'Een onbekend woord met andere woorden zeggen'],
    Instemmen: ['Je zegt da stimme ich zu om het eens te zijn', 'Aangeven dat je het eens bent'],
    Vulwoorden: ['Je zegt äh of naja terwijl je nadenkt', 'Woordjes die een pauze vullen'],
    Uitspraak: ['Je vormt de klanken duidelijk zodat men je verstaat', 'De manier waarop je de klanken vormt'],
    'Verduidelijking vragen': ['Je vraagt Wie meinen Sie das? als je twijfelt', 'Vragen wat iemand precies bedoelt'],
    Doorvragen: ['Je stelt een extra vraag om meer te weten te komen', 'Extra vragen stellen in een gesprek'],
  },
  E: {
    Verfremdungseffekt: ['Brecht haalt de toeschouwer bewust uit de illusie om na te denken', 'De techniek die de illusie doorbreekt'],
    Romantik: ['Een stroming vol Sehnsucht, verlangen en verheerlijking van de natuur', 'De romantische stroming rond 1800'],
    Faust: ['Goethes werk over een geleerde die zijn ziel aan de duivel verkoopt', 'Het beroemdste werk van Goethe'],
    'Allwissender Erzähler': ['De verteller weet alles over alle personages', 'De alwetende verteller'],
    'Sturm und Drang': ['Een stroming vol jeugdig gevoel en opstand tegen de regels', 'De stroming van gevoel en rebellie'],
    'Aufklärung': ['Een stroming die rede en verstand centraal stelt', 'De Verlichting in de Duitse literatuur'],
    Novelle: ['Een kort prozawerk dat om één opmerkelijke gebeurtenis draait', 'Een kort verhaal met een keerpunt'],
    'Ich-Erzähler': ['De verteller vertelt het verhaal in de ik-vorm', 'De ik-verteller'],
    Motiv: ['Een terugkerend element dat door het hele werk loopt', 'Een steeds terugkerend element'],
    Satire: ['Molière en Brecht bespotten misstanden met humor', 'Het bespotten van misstanden via humor'],
  },
};
