// VWO Wiskunde B - gouden-stijl contentspec. Vervangt crude generatorvragen
// door authored reken- en inzichtvragen met per-optie-uitleg + situatiebegrippen.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vwo', vak: 'wb', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Vaardigheden',
    `De algebraïsche basis van wiskunde B: <strong>ontbinden in factoren</strong>, <strong>merkwaardige producten</strong>, <strong>wortels vereenvoudigen</strong> en <strong>exact rekenen</strong> zonder afronden. De <strong>abc-formule</strong> lost tweedegraadsvergelijkingen op; een <strong>tegenvoorbeeld</strong> toont dat een bewering niet algemeen geldt.`,
    [
      { h: '1. Ontbinden en producten', p: [
        `<strong>Ontbinden in factoren</strong> is een som als product schrijven: x² − 9 = (x − 3)(x + 3). De <strong>merkwaardige producten</strong>: (a + b)² = a² + 2ab + b² en (a − b)(a + b) = a² − b². Bij machten geldt x⁵/x² = x³.`],
        formula: { label: 'Verschil van kwadraten', eq: 'a² − b² = (a − b)(a + b)', note: 'x² − 9 = (x − 3)(x + 3).' } },
      { h: '2. Wortels en exact rekenen', p: [
        `<strong>Wortels vereenvoudig</strong> je door een kwadraat eruit te halen: √8 = √(4·2) = 2√2. <strong>Exact rekenen</strong> betekent met breuken en wortels doorrekenen zonder tussendoor af te ronden. De <strong>abc-formule</strong> lost ax² + bx + c = 0 op.`] },
    ],
    [
      { t: 'Ontbinden in factoren', d: 'een som als product van factoren schrijven', k: 'som als product', fout: ['Merkwaardig product'] },
      { t: 'Merkwaardig product', d: 'een vaste vorm zoals (a + b)² of (a − b)(a + b)', k: 'vaste productvorm', fout: ['Ontbinden in factoren'] },
      { t: 'Wortel vereenvoudigen', d: 'een kwadraat onder de wortel eruit halen, √8 = 2√2', k: 'kwadraat eruit halen', fout: ['Exact rekenen'] },
      { t: 'abc-formule', d: 'de formule om een tweedegraadsvergelijking op te lossen', k: 'oplossing tweedegraads', fout: ['Discriminant'] },
      { t: 'Discriminant', d: 'D = b² − 4ac, bepaalt het aantal reële oplossingen', k: 'b² − 4ac', fout: ['abc-formule'] },
      { t: 'Exact rekenen', d: 'met breuken en wortels doorrekenen zonder af te ronden', k: 'niet afronden', fout: ['Wortel vereenvoudigen'] },
      { t: 'Tegenvoorbeeld', d: 'één geval dat aantoont dat een bewering niet algemeen geldt', k: 'weerlegt een bewering', fout: ['Bewijs'] },
      { t: 'Bewijs', d: 'een sluitende redenering die een bewering algemeen aantoont', k: 'toont algemeen aan', fout: ['Tegenvoorbeeld'] },
      { t: 'Kwadraatafsplitsen', d: 'ax² + bx + c schrijven als a(x − p)² + q', k: 'schrijven als kwadraat plus rest', fout: ['Ontbinden in factoren'] },
      { t: 'Grondtal', d: 'het getal dat je tot een macht verheft', k: 'basis van de macht', fout: ['Exponent'] },
    ],
    [
      { v: 'Ontbind in factoren: x² − 9.', o: ['(x − 3)(x + 3)', '(x − 3)²', '(x + 9)(x − 1)', '(x − 9)(x + 1)'], c: 0, d: 2, uo: ['Klopt: verschil van kwadraten, a² − b² = (a − b)(a + b).', 'Nee, dat geeft x² − 6x + 9.', 'Nee, dat geeft niet x² − 9.', 'Nee, uitwerken geeft x² − 8x − 9.'], uh: 'a² − b² = (a − b)(a + b).' },
      { v: 'Vereenvoudig √8.', o: ['2√2', '4√2', '2√4', '8'], c: 0, d: 2, uo: ['Klopt: √8 = √4 · √2 = 2√2.', 'Nee, √4 = 2, niet 4.', 'Nee, √4 = 2, dus dit is niet vereenvoudigd.', 'Nee, √8 is geen heel getal.'], uh: 'Haal een kwadraat uit de wortel: √8 = 2√2.' },
      { v: 'Werk uit: (a + b)².', o: ['a² + 2ab + b²', 'a² + b²', 'a² − 2ab + b²', '2a + 2b'], c: 0, d: 2, uo: ['Klopt: (a + b)² = a² + 2ab + b².', 'Nee, de dubbele term 2ab ontbreekt.', 'Nee, dat is (a − b)².', 'Nee, je moet kwadrateren.'], uh: '(a + b)² = a² + 2ab + b².' },
      { v: 'Los exact op: x² − 2 = 0.', o: ['x = ±√2', 'x = 2', 'x = ±2', 'x = √2'], c: 0, d: 2, uo: ['Klopt: x² = 2, dus x = ±√2.', 'Nee, je moet worteltrekken.', 'Nee, √2 is geen 2.', 'Nee, je mist de negatieve oplossing.'], uh: 'x² = a geeft x = ±√a.' },
      { v: 'Bereken x⁵ / x² (x ≠ 0).', o: ['x³', 'x⁷', 'x²·⁵', 'x'], c: 0, d: 1, uo: ['Klopt: bij delen trek je exponenten af: 5 − 2 = 3.', 'Nee, bij delen tel je niet op.', 'Nee, je deelt de exponenten niet.', 'Nee, 5 − 2 = 3.'], uh: 'Machten delen: exponenten aftrekken.' },
      { v: 'Wat toon je aan met een tegenvoorbeeld?', o: ['dat een bewering niet algemeen geldig is', 'dat een bewering altijd klopt', 'dat een getal priem is', 'dat twee lijnen snijden'], c: 0, d: 3, uo: ['Klopt: één tegenvoorbeeld weerlegt een algemene bewering.', 'Nee, dat vraagt juist een bewijs.', 'Nee, dat is een ander soort vraag.', 'Nee, dat is meetkunde.'], uh: 'Eén tegenvoorbeeld weerlegt een algemene bewering.' },
      { v: 'sin²α + cos²α = ...', o: ['1', '0', '2', 'sin(2α)'], c: 0, d: 2, uo: ['Klopt: de grondidentiteit geeft 1.', 'Nee, dat geldt niet.', 'Nee, de som is precies 1.', 'Nee, dat is een dubbele hoek.'], uh: 'Grondidentiteit: sin²α + cos²α = 1.' },
      { v: 'De abc-formule gebruik je om...', o: ['een tweedegraadsvergelijking op te lossen', 'een lijn te tekenen', 'een integraal te berekenen', 'een hoek te meten'], c: 0, d: 2, uo: ['Klopt: de abc-formule lost ax² + bx + c = 0 op.', 'Nee, daar heb je geen abc-formule voor nodig.', 'Nee, dat is integraalrekening.', 'Nee, dat is goniometrie.'], uh: 'abc-formule: oplossing van een tweedegraadsvergelijking.' },
      { v: 'Herleid: (x − 1)(x + 1).', o: ['x² − 1', 'x² + 1', 'x² − 2x + 1', 'x² − x − 1'], c: 0, d: 2, uo: ['Klopt: verschil van kwadraten, x² − 1.', 'Nee, het teken van b² is negatief.', 'Nee, dat is (x − 1)².', 'Nee, de kruistermen vallen weg.'], uh: '(a − b)(a + b) = a² − b².' },
      { v: 'Exact rekenen betekent...', o: ['met breuken en wortels doorrekenen zonder afronden', 'altijd op 2 decimalen afronden', 'de rekenmachine gebruiken', 'alleen met hele getallen werken'], c: 0, d: 2, uo: ['Klopt: exact betekent zonder afronden doorrekenen.', 'Nee, dat is juist afgerond.', 'Nee, dat geeft vaak een benadering.', 'Nee, breuken en wortels mogen juist.'], uh: 'Exact: doorrekenen met breuken en wortels, niet afronden.' },
      { v: 'Ontbind in factoren: x² + 5x + 6.', o: ['(x + 2)(x + 3)', '(x + 1)(x + 6)', '(x − 2)(x − 3)', '(x + 5)(x + 1)'], c: 0, d: 3, uo: ['Klopt: 2 en 3 hebben som 5 en product 6.', 'Nee, 1 + 6 = 7, niet 5.', 'Nee, dat geeft +6 maar −5x.', 'Nee, uitwerken geeft x² + 6x + 5.'], uh: 'Zoek twee getallen met de juiste som en product.' },
      { v: 'Vereenvoudig √50.', o: ['5√2', '2√5', '25√2', '√50'], c: 0, d: 2, uo: ['Klopt: √50 = √25 · √2 = 5√2.', 'Nee, √25 = 5, niet √5.', 'Nee, √25 = 5, geen 25.', 'Nee, dit kun je nog vereenvoudigen.'], uh: '√50 = 5√2.' },
      { v: 'Los op: x² − 5x = 0.', o: ['x = 0 of x = 5', 'x = 5', 'x = ±5', 'x = 0'], c: 0, d: 3, uo: ['Klopt: x(x − 5) = 0 geeft x = 0 of x = 5.', 'Nee, je mist de oplossing x = 0.', 'Nee, er is geen −5.', 'Nee, je mist x = 5.'], uh: 'Haal x buiten haakjes: x(x − 5) = 0.' },
      { v: 'Werk uit: (2x)³.', o: ['8x³', '6x³', '2x³', '8x'], c: 0, d: 2, uo: ['Klopt: 2³ · x³ = 8x³.', 'Nee, 2³ = 8, niet 6.', 'Nee, ook de 2 wordt tot de macht 3 verheven.', 'Nee, ook de x wordt tot de macht 3.'], uh: '(ab)ⁿ = aⁿbⁿ.' },
    ]),

  V('B', 'Functies, grafieken en vergelijkingen',
    `Een <strong>kwadratische functie</strong> heeft als grafiek een <strong>parabool</strong>. De <strong>discriminant</strong> D = b² − 4ac bepaalt het aantal <strong>nulpunten</strong>. Bij het oplossen van <strong>ongelijkheden</strong> klapt het teken om als je door een negatief getal deelt. Elke functie heeft een <strong>domein</strong> en een <strong>bereik</strong>.`,
    [
      { h: '1. Parabool en discriminant', p: [
        `De grafiek van een <strong>kwadratische functie</strong> is een <strong>parabool</strong> met een top en een symmetrieas x = −b/(2a). De <strong>discriminant</strong> D = b² − 4ac geeft het aantal reële nulpunten: D > 0 twee, D = 0 één (de grafiek raakt de x-as), D < 0 geen.`],
        formula: { label: 'Discriminant', eq: 'D = b² − 4ac', note: 'D > 0: twee nulpunten; D = 0: één; D < 0: geen reële nulpunten.' } },
      { h: '2. Ongelijkheden en functies', p: [
        `Bij een <strong>ongelijkheid</strong> klapt het teken om als je met een negatief getal vermenigvuldigt of deelt. De <strong>inverse</strong> functie ontstaat door te spiegelen in de lijn y = x. Het <strong>domein</strong> is de verzameling toegestane x-waarden, het <strong>bereik</strong> de mogelijke y-waarden.`] },
    ],
    [
      { t: 'Parabool', d: 'de grafiek van een kwadratische functie', k: 'grafiek van kwadratische functie', fout: ['Kwadratische functie'] },
      { t: 'Kwadratische functie', d: 'een functie met x² als hoogste macht, y = ax² + bx + c', k: 'hoogste macht x²', fout: ['Parabool'] },
      { t: 'Discriminant', d: 'D = b² − 4ac, bepaalt het aantal reële nulpunten', k: 'b² − 4ac', fout: ['Nulpunt'] },
      { t: 'Nulpunt', d: 'een x-waarde waar de grafiek de x-as snijdt', k: 'snijpunt met de x-as', fout: ['Top'] },
      { t: 'Symmetrieas', d: 'de verticale as x = −b/(2a) waarin de parabool spiegelt', k: 'x = −b/(2a)', fout: ['Top'] },
      { t: 'Top', d: 'het hoogste of laagste punt van de parabool', k: 'hoogste of laagste punt', fout: ['Nulpunt'] },
      { t: 'Ongelijkheid', d: 'een uitdrukking met <, >, ≤ of ≥ in plaats van =', k: 'met <, > in plaats van =', fout: ['Vergelijking'] },
      { t: 'Inverse functie', d: 'de functie die je krijgt door te spiegelen in de lijn y = x', k: 'spiegelen in y = x', fout: ['Parabool'] },
      { t: 'Domein', d: 'de verzameling toegestane x-waarden van een functie', k: 'toegestane x-waarden', fout: ['Bereik'] },
      { t: 'Bereik', d: 'de verzameling mogelijke y-waarden van een functie', k: 'mogelijke y-waarden', fout: ['Domein'] },
    ],
    [
      { v: 'Welke grafiek hoort bij een kwadratische functie?', o: ['een parabool', 'een rechte lijn', 'een cirkel', 'een sinusgolf'], c: 0, d: 1, uo: ['Klopt: een kwadratische functie geeft een parabool.', 'Nee, dat is een lineaire functie.', 'Nee, dat is geen functiegrafiek van y = ax² + bx + c.', 'Nee, dat is een goniometrische functie.'], uh: 'Kwadratische functie → parabool.' },
      { v: 'Wat bepaalt de discriminant D = b² − 4ac?', o: ['het aantal reële nulpunten', 'de top van de parabool', 'de richtingscoëfficiënt', 'de periode'], c: 0, d: 2, uo: ['Klopt: D bepaalt het aantal reële nulpunten.', 'Nee, de top volgt uit −b/(2a).', 'Nee, dat is bij een lijn.', 'Nee, dat hoort bij goniometrie.'], uh: 'Discriminant: aantal reële nulpunten.' },
      { v: 'Wat gebeurt met het teken als je een ongelijkheid door een negatief getal deelt?', o: ['het teken klapt om (van < naar >)', 'het teken blijft gelijk', 'de ongelijkheid wordt een gelijkheid', 'er zijn geen oplossingen meer'], c: 0, d: 2, uo: ['Klopt: delen door een negatief getal keert het teken om.', 'Nee, juist niet.', 'Nee, het blijft een ongelijkheid.', 'Nee, er zijn nog wel oplossingen.'], uh: 'Delen door een negatief getal: teken omklappen.' },
      { v: 'Wat betekent D > 0 voor een kwadratische vergelijking?', o: ['twee verschillende reële oplossingen', 'precies één oplossing', 'geen reële oplossingen', 'oneindig veel oplossingen'], c: 0, d: 3, uo: ['Klopt: D > 0 geeft twee reële nulpunten.', 'Nee, dat hoort bij D = 0.', 'Nee, dat hoort bij D < 0.', 'Nee, dat komt hier niet voor.'], uh: 'D > 0: twee reële oplossingen.' },
      { v: 'Wat betekent D = 0 meetkundig?', o: ['de parabool raakt de x-as in één punt', 'de parabool snijdt de x-as twee keer', 'de parabool ligt geheel boven de x-as', 'de parabool is een rechte lijn'], c: 0, d: 3, uo: ['Klopt: bij D = 0 raakt de top de x-as.', 'Nee, dat is D > 0.', 'Nee, dat is D < 0 (bij dalparabool: erboven).', 'Nee, een parabool is geen lijn.'], uh: 'D = 0: de grafiek raakt de x-as.' },
      { v: 'Wat betekent D < 0?', o: ['geen reële nulpunten', 'twee nulpunten', 'één nulpunt', 'de top ligt op de x-as'], c: 0, d: 3, uo: ['Klopt: bij D < 0 zijn er geen reële nulpunten.', 'Nee, dat is D > 0.', 'Nee, dat is D = 0.', 'Nee, dat is juist D = 0.'], uh: 'D < 0: geen reële nulpunten.' },
      { v: 'Wat is de symmetrieas van y = ax² + bx + c?', o: ['x = −b/(2a)', 'x = b/(2a)', 'x = −c/a', 'x = 0 altijd'], c: 0, d: 3, uo: ['Klopt: de symmetrieas is x = −b/(2a).', 'Nee, let op het minteken.', 'Nee, c hoort er niet in.', 'Nee, alleen als b = 0.'], uh: 'Symmetrieas parabool: x = −b/(2a).' },
      { v: 'Wat zijn de nulpunten van een functie?', o: ['de x-waarden waar de grafiek de x-as snijdt', 'de top van de grafiek', 'de y-waarde bij x = 0', 'de hoogste y-waarde'], c: 0, d: 2, uo: ['Klopt: nulpunten liggen op de x-as (y = 0).', 'Nee, dat is de top.', 'Nee, dat is het snijpunt met de y-as.', 'Nee, dat is een maximum.'], uh: 'Nulpunt: waar y = 0.' },
      { v: 'Hoe ontstaat de inverse van een functie?', o: ['door de grafiek te spiegelen in de lijn y = x', 'door te spiegelen in de x-as', 'door te verschuiven naar rechts', 'door met −1 te vermenigvuldigen'], c: 0, d: 3, uo: ['Klopt: de inverse is de spiegeling in y = x.', 'Nee, dat geeft −f(x).', 'Nee, dat is een translatie.', 'Nee, dat spiegelt in de x-as.'], uh: 'Inverse: spiegelen in de lijn y = x.' },
      { v: 'Wat is het domein van een functie?', o: ['de toegestane x-waarden', 'de mogelijke y-waarden', 'de nulpunten', 'de top'], c: 0, d: 2, uo: ['Klopt: het domein is de verzameling toegestane x-waarden.', 'Nee, dat is het bereik.', 'Nee, dat zijn losse punten.', 'Nee, dat is één punt.'], uh: 'Domein: toegestane x-waarden.' },
      { v: 'Wat is het bereik van een functie?', o: ['de mogelijke y-waarden', 'de toegestane x-waarden', 'het aantal nulpunten', 'de symmetrieas'], c: 0, d: 2, uo: ['Klopt: het bereik is de verzameling mogelijke y-waarden.', 'Nee, dat is het domein.', 'Nee, dat is een aantal.', 'Nee, dat is een lijn.'], uh: 'Bereik: mogelijke y-waarden.' },
      { v: 'De top van een dalparabool is het...', o: ['minimum van de functie', 'maximum van de functie', 'nulpunt', 'snijpunt met de y-as'], c: 0, d: 2, uo: ['Klopt: een dalparabool opent naar boven, de top is het minimum.', 'Nee, dat is een bergparabool.', 'Nee, de top hoeft niet op de x-as te liggen.', 'Nee, dat is het snijpunt met de y-as.'], uh: 'Dalparabool: top is het minimum.' },
      { v: 'Los op: x² = 16.', o: ['x = ±4', 'x = 4', 'x = 8', 'x = ±8'], c: 0, d: 2, uo: ['Klopt: zowel 4 als −4 in het kwadraat geeft 16.', 'Nee, je mist de negatieve oplossing.', 'Nee, 8² = 64.', 'Nee, √16 = 4, niet 8.'], uh: 'x² = a: x = ±√a.' },
    ]),

  V('C', 'Differentiaal- en integraalrekening',
    `<strong>Differentiëren</strong> geeft de helling: de afgeleide van eˣ is eˣ, van ln(x) is 1/x, van sin(x) is cos(x). Bij samengestelde functies gebruik je de <strong>kettingregel</strong>, bij producten de <strong>productregel</strong>. <strong>Integreren</strong> is het omgekeerde en geeft de <strong>oppervlakte</strong> onder de grafiek.`,
    [
      { h: '1. Differentiëren', p: [
        `Belangrijke afgeleiden: eˣ → eˣ, ln(x) → 1/x, sin(x) → cos(x), cos(x) → −sin(x). De <strong>kettingregel</strong>: [f(g(x))]' = f'(g(x))·g'(x), dus sin(x³) → cos(x³)·3x². Een <strong>stationair punt</strong> (f'(x) = 0) is noodzakelijk, maar niet voldoende, voor een extremum.`],
        formula: { label: 'Kettingregel', eq: '[f(g(x))]\' = f\'(g(x)) · g\'(x)', note: 'sin(x³) → cos(x³) · 3x².' } },
      { h: '2. Integreren en asymptoten', p: [
        `<strong>Integreren</strong> is de omgekeerde bewerking van differentiëren; de <strong>primitieve</strong> van 2x is x² + C, van 1/x is ln|x| + C. De <strong>bepaalde integraal</strong> geeft de oppervlakte onder de grafiek. De <strong>horizontale asymptoot</strong> van (3x² + 1)/(x² − 4) is y = 3 (verhouding van de kopcoëfficiënten).`] },
    ],
    [
      { t: 'Afgeleide', d: 'de functie die de helling van f in elk punt geeft', k: 'helling in elk punt', fout: ['Primitieve'] },
      { t: 'Kettingregel', d: 'de regel voor het differentiëren van een samengestelde functie', k: 'voor f(g(x))', fout: ['Productregel'] },
      { t: 'Productregel', d: 'de regel voor het differentiëren van een product van functies', k: 'voor f(x)·g(x)', fout: ['Kettingregel'] },
      { t: 'Quotiëntregel', d: 'de regel voor het differentiëren van een breuk van functies', k: 'voor f(x)/g(x)', fout: ['Productregel'] },
      { t: 'Primitieve', d: 'een functie waarvan de afgeleide f is, het omgekeerde van differentiëren', k: 'omgekeerde van afgeleide', fout: ['Afgeleide'] },
      { t: 'Integraal', d: 'de bewerking die de oppervlakte onder een grafiek geeft', k: 'oppervlakte onder de grafiek', fout: ['Afgeleide'] },
      { t: 'Horizontale asymptoot', d: 'de horizontale lijn die de grafiek voor grote x nadert', k: 'lijn voor grote x', fout: ['Stationair punt'] },
      { t: 'Stationair punt', d: 'een punt waar f\'(x) = 0, noodzakelijk voor een extremum', k: 'f\'(x) = 0', fout: ['Buigpunt'] },
      { t: 'Natuurlijke logaritme', d: 'de logaritme met grondtal e ≈ 2,718, genoteerd als ln', k: 'ln, grondtal e', fout: ['Horizontale asymptoot'] },
      { t: 'Buigpunt', d: 'een punt waar de grafiek van hol naar bol overgaat, f\'\'(x) = 0', k: 'f\'\'(x) = 0, holbol', fout: ['Stationair punt'] },
    ],
    [
      { v: 'Wat is de horizontale asymptoot van f(x) = (3x² + 1)/(x² − 4)?', o: ['y = 3', 'y = 0', 'y = −4', 'y = 1'], c: 0, d: 3, uo: ['Klopt: voor grote x telt de verhouding 3x²/x² = 3.', 'Nee, dat geldt als de teller een lagere graad heeft.', 'Nee, −4 is de constante in de noemer.', 'Nee, 1 is de constante in de teller.'], uh: 'Gelijke graad: asymptoot = verhouding kopcoëfficiënten.' },
      { v: 'Welke regel gebruik je voor de afgeleide van f(x) = sin(x³)?', o: ['de kettingregel: cos(x³)·3x²', 'de productregel', 'de quotiëntregel', 'geen regel nodig'], c: 0, d: 3, uo: ['Klopt: samengestelde functie, dus kettingregel.', 'Nee, er is geen product van twee functies.', 'Nee, er is geen breuk.', 'Nee, een regel is wel nodig.'], uh: 'Samengestelde functie: kettingregel.' },
      { v: 'Welke voorwaarde is noodzakelijk (maar niet voldoende) voor een extremum bij x = a?', o: ['f\'(a) = 0 (stationair punt)', 'f(a) = 0', 'f\'\'(a) = 0', 'f(a) > 0'], c: 0, d: 3, uo: ['Klopt: bij een extremum is de helling 0, maar dat kan ook een buigpunt zijn.', 'Nee, dat is een nulpunt van f.', 'Nee, dat hoort bij een buigpunt.', 'Nee, dat zegt niets over een extremum.'], uh: 'Extremum: f\'(a) = 0 (noodzakelijk, niet voldoende).' },
      { v: 'Wat is het verschil tussen ln(x) en log₁₀(x)?', o: ['ln heeft grondtal e ≈ 2,718; log₁₀ grondtal 10', 'ze zijn identiek', 'ln heeft grondtal 10', 'log₁₀ heeft grondtal e'], c: 0, d: 2, uo: ['Klopt: ln gebruikt grondtal e, log₁₀ grondtal 10.', 'Nee, de grondtallen verschillen.', 'Nee, ln heeft grondtal e.', 'Nee, dat is precies omgedraaid.'], uh: 'ln: grondtal e; log₁₀: grondtal 10.' },
      { v: 'Wat is de afgeleide van f(x) = eˣ?', o: ['eˣ', 'x·eˣ⁻¹', '1', 'ln(x)'], c: 0, d: 2, uo: ['Klopt: eˣ is zijn eigen afgeleide.', 'Nee, dat is de machtsregel, niet voor eˣ.', 'Nee, de afgeleide is niet constant.', 'Nee, dat is de omgekeerde functie.'], uh: 'De afgeleide van eˣ is eˣ.' },
      { v: 'Wat is de afgeleide van f(x) = ln(x)?', o: ['1/x', 'ln(x)', 'x', 'eˣ'], c: 0, d: 2, uo: ['Klopt: de afgeleide van ln(x) is 1/x.', 'Nee, dat is de functie zelf.', 'Nee, dat is een primitieve van 1.', 'Nee, dat is een andere functie.'], uh: 'Afgeleide van ln(x) is 1/x.' },
      { v: 'Wat is de primitieve van f(x) = 1/x?', o: ['ln|x| + C', '1/x² + C', '−1/x² + C', 'x + C'], c: 0, d: 3, uo: ['Klopt: de primitieve van 1/x is ln|x| + C.', 'Nee, dat is bijna de afgeleide van 1/x.', 'Nee, dat is de afgeleide van 1/x.', 'Nee, dat is de primitieve van 1.'], uh: 'Primitieve van 1/x is ln|x| + C.' },
      { v: 'Welke regel gebruik je voor de afgeleide van f(x) = x²·sin(x)?', o: ['de productregel', 'de kettingregel', 'de quotiëntregel', 'geen regel'], c: 0, d: 3, uo: ['Klopt: het is een product van twee functies, dus productregel.', 'Nee, er is geen samenstelling f(g(x)).', 'Nee, er is geen breuk.', 'Nee, er is wel een regel nodig.'], uh: 'Product van functies: productregel.' },
      { v: 'Wat geeft de bepaalde integraal meetkundig?', o: ['de oppervlakte onder de grafiek', 'de helling in een punt', 'de top van de grafiek', 'de periode'], c: 0, d: 2, uo: ['Klopt: de integraal geeft de oppervlakte onder de grafiek.', 'Nee, dat is de afgeleide.', 'Nee, dat is een extremum.', 'Nee, dat hoort bij goniometrie.'], uh: 'Integraal: oppervlakte onder de grafiek.' },
      { v: 'Wat is de primitieve van f(x) = 2x?', o: ['x² + C', '2 + C', 'x²', '2x² + C'], c: 0, d: 2, uo: ['Klopt: de afgeleide van x² + C is 2x.', 'Nee, dat is de afgeleide van 2x.', 'Nee, de integratieconstante ontbreekt.', 'Nee, dan zou de afgeleide 4x zijn.'], uh: 'Primitieve van 2x is x² + C.' },
      { v: 'Wat is de afgeleide van f(x) = sin(x)?', o: ['cos(x)', '−cos(x)', '−sin(x)', 'tan(x)'], c: 0, d: 2, uo: ['Klopt: de afgeleide van sin(x) is cos(x).', 'Nee, dat teken klopt niet.', 'Nee, dat is de afgeleide van cos(x) qua vorm.', 'Nee, dat is een andere functie.'], uh: 'sin(x) → cos(x).' },
      { v: 'Wat is de afgeleide van f(x) = cos(x)?', o: ['−sin(x)', 'sin(x)', 'cos(x)', '−cos(x)'], c: 0, d: 2, uo: ['Klopt: de afgeleide van cos(x) is −sin(x).', 'Nee, let op het minteken.', 'Nee, dat is de functie zelf.', 'Nee, dat teken en die functie kloppen niet.'], uh: 'cos(x) → −sin(x).' },
      { v: 'Wat geldt in een buigpunt van een grafiek?', o: ['f\'\'(x) = 0 en verandert van teken', 'f(x) = 0', 'f\'(x) is maximaal', 'de grafiek raakt de x-as'], c: 0, d: 3, uo: ['Klopt: in een buigpunt wisselt de kromming, f\'\'(x) = 0.', 'Nee, dat is een nulpunt.', 'Nee, dat is niet de definitie.', 'Nee, dat is een nulpunt.'], uh: 'Buigpunt: f\'\'(x) = 0 met tekenwissel.' },
    ]),

  V('D', 'Goniometrische functies',
    `Op de <strong>eenheidscirkel</strong> lees je exacte waarden af, zoals sin(30°) = ½ en sin(210°) = −½. De <strong>grondidentiteit</strong> sin²α + cos²α = 1 volgt uit Pythagoras. Met <strong>optellings-</strong> en <strong>dubbelehoekformules</strong> herleid je uitdrukkingen. De <strong>periode</strong> van sin(bx) is 2π/b.`,
    [
      { h: '1. Eenheidscirkel en identiteiten', p: [
        `Op de <strong>eenheidscirkel</strong> is cos de x- en sin de y-coördinaat. De <strong>grondidentiteit</strong> sin²α + cos²α = 1 volgt uit de stelling van Pythagoras. Een halve draai (180°) is π <strong>radialen</strong>. Exacte waarden: sin(30°) = ½, cos(0°) = 1, sin(90°) = 1.`],
        formula: { label: 'Grondidentiteit', eq: 'sin²α + cos²α = 1', note: 'Volgt uit Pythagoras op de eenheidscirkel (straal 1).' } },
      { h: '2. Formules en periode', p: [
        `De <strong>dubbelehoekformule</strong>: cos(2α) = 1 − 2sin²α en sin(2α) = 2 sin α cos α. Met <strong>optellingsformules</strong> bereken je bijvoorbeeld sin(75°) = (√6 + √2)/4. De <strong>periode</strong> van f(x) = sin(bx) is 2π/b; de <strong>amplitude</strong> van a·sin(x) is |a|.`] },
    ],
    [
      { t: 'Eenheidscirkel', d: 'de cirkel met straal 1 waarop cos en sin de coördinaten zijn', k: 'cirkel met straal 1', fout: ['Radiaal'] },
      { t: 'Radiaal', d: 'de hoekmaat waarbij een halve cirkel π is', k: 'halve cirkel = π', fout: ['Periode'] },
      { t: 'Periode', d: 'de lengte waarna een goniometrische grafiek zich herhaalt, 2π/b', k: '2π/b', fout: ['Amplitude'] },
      { t: 'Amplitude', d: 'de uitwijking van het midden, |a| bij a·sin(x)', k: 'uitwijking |a|', fout: ['Periode'] },
      { t: 'Grondidentiteit', d: 'sin²α + cos²α = 1, volgend uit Pythagoras', k: 'sin²α + cos²α = 1', fout: ['Dubbelehoekformule'] },
      { t: 'Dubbelehoekformule', d: 'formule voor sin(2α) of cos(2α)', k: 'voor de dubbele hoek', fout: ['Optellingsformule'] },
      { t: 'Optellingsformule', d: 'formule voor sin(α + β) of cos(α + β)', k: 'voor een som van hoeken', fout: ['Dubbelehoekformule'] },
      { t: 'Sinusfunctie', d: 'de functie die de y-coördinaat op de eenheidscirkel geeft', k: 'y op de eenheidscirkel', fout: ['Cosinusfunctie'] },
      { t: 'Cosinusfunctie', d: 'de functie die de x-coördinaat op de eenheidscirkel geeft', k: 'x op de eenheidscirkel', fout: ['Sinusfunctie'] },
      { t: 'Fase', d: 'de horizontale verschuiving van een goniometrische grafiek', k: 'horizontale verschuiving', fout: ['Amplitude'] },
    ],
    [
      { v: 'Wat is sin(210°)?', o: ['−½', '½', '−1', '√3/2'], c: 0, d: 3, uo: ['Klopt: 210° ligt in het derde kwadrant, sin is −½.', 'Nee, sin is daar negatief.', 'Nee, dat is de minimumwaarde bij 270°.', 'Nee, dat is |sin(60°)|.'], uh: 'Derde kwadrant: sin negatief; sin(210°) = −½.' },
      { v: 'Wat is sin(75°) met de optellingsformule?', o: ['(√6 + √2)/4', '(√6 − √2)/4', '½', '√2/2'], c: 0, d: 3, uo: ['Klopt: sin(45° + 30°) = (√6 + √2)/4.', 'Nee, dat is sin(15°).', 'Nee, dat is sin(30°).', 'Nee, dat is sin(45°).'], uh: 'sin(75°) = sin(45° + 30°) = (√6 + √2)/4.' },
      { v: 'Welke identiteit geldt altijd?', o: ['sin²α + cos²α = 1', 'sin α + cos α = 1', 'sin α · cos α = 1', 'sin²α − cos²α = 1'], c: 0, d: 2, uo: ['Klopt: dat is de grondidentiteit.', 'Nee, dat geldt niet in het algemeen.', 'Nee, dat klopt niet.', 'Nee, dat is niet de identiteit.'], uh: 'Grondidentiteit: sin²α + cos²α = 1.' },
      { v: 'Vereenvoudig: sin(2α)/cos α.', o: ['2 sin α', 'sin α', '2 cos α', 'tan α'], c: 0, d: 3, uo: ['Klopt: sin(2α) = 2 sin α cos α, gedeeld door cos α geeft 2 sin α.', 'Nee, de factor 2 valt niet weg.', 'Nee, de sin blijft, niet de cos.', 'Nee, dat is sin/cos.'], uh: 'sin(2α) = 2 sin α cos α.' },
      { v: 'Wat is de periode van f(x) = sin(2x)?', o: ['π', '2π', 'π/2', '4π'], c: 0, d: 2, uo: ['Klopt: periode = 2π/2 = π.', 'Nee, dat is de periode van sin(x).', 'Nee, deel 2π door 2.', 'Nee, dat is te groot.'], uh: 'Periode van sin(bx) = 2π/b.' },
      { v: 'Wat is de dubbelehoekformule voor cos(2α) uitgedrukt in sinus?', o: ['cos(2α) = 1 − 2sin²α', 'cos(2α) = 2sin²α − 1', 'cos(2α) = 2 sin α cos α', 'cos(2α) = 1 + 2sin²α'], c: 0, d: 3, uo: ['Klopt: cos(2α) = 1 − 2sin²α.', 'Nee, het teken klopt niet.', 'Nee, dat is sin(2α).', 'Nee, het teken is min.'], uh: 'cos(2α) = 1 − 2sin²α.' },
      { v: 'Uit welke stelling volgt sin²α + cos²α = 1?', o: ['de stelling van Pythagoras op de eenheidscirkel', 'de abc-formule', 'de kettingregel', 'de stelling van Thales'], c: 0, d: 2, uo: ['Klopt: op de eenheidscirkel met straal 1 geeft Pythagoras dit.', 'Nee, dat lost vergelijkingen op.', 'Nee, dat is een afgeleideregel.', 'Nee, dat gaat over rechte hoeken bij een cirkel.'], uh: 'Grondidentiteit volgt uit Pythagoras (straal 1).' },
      { v: 'Wat is sin(30°)?', o: ['½', '√3/2', '√2/2', '1'], c: 0, d: 2, uo: ['Klopt: sin(30°) = ½.', 'Nee, dat is sin(60°).', 'Nee, dat is sin(45°).', 'Nee, dat is sin(90°).'], uh: 'sin(30°) = ½.' },
      { v: 'Wat is cos(0°)?', o: ['1', '0', '−1', '½'], c: 0, d: 1, uo: ['Klopt: cos(0°) = 1.', 'Nee, dat is sin(0°).', 'Nee, dat is cos(180°).', 'Nee, dat is cos(60°).'], uh: 'cos(0°) = 1.' },
      { v: 'Hoeveel radialen is 180°?', o: ['π', '2π', 'π/2', '½'], c: 0, d: 2, uo: ['Klopt: een halve cirkel is π radialen.', 'Nee, dat is een hele cirkel (360°).', 'Nee, dat is 90°.', 'Nee, dat is geen hoekmaat.'], uh: '180° = π radialen.' },
      { v: 'Wat is de periode van f(x) = sin(x)?', o: ['2π', 'π', 'π/2', '1'], c: 0, d: 1, uo: ['Klopt: de sinus herhaalt zich na 2π.', 'Nee, dat is de periode van sin(2x).', 'Nee, dat is te klein.', 'Nee, dat is geen hoek.'], uh: 'Periode van sin(x) = 2π.' },
      { v: 'Wat is sin(90°)?', o: ['1', '0', '½', '−1'], c: 0, d: 1, uo: ['Klopt: sin(90°) = 1, de top.', 'Nee, dat is sin(0°).', 'Nee, dat is sin(30°).', 'Nee, dat is sin(270°).'], uh: 'sin(90°) = 1.' },
      { v: 'Wat is de amplitude van f(x) = 3·sin(x)?', o: ['3', '1', '2π', '½'], c: 0, d: 2, uo: ['Klopt: de factor 3 is de amplitude.', 'Nee, dat is de amplitude van sin(x).', 'Nee, dat is de periode.', 'Nee, dat klopt niet.'], uh: 'Amplitude van a·sin(x) = |a|.' },
    ]),

  V('E', 'Meetkunde met coördinaten',
    `Met <strong>vectoren</strong> reken je in 2D en 3D. Het <strong>inproduct</strong> a⃗·b⃗ is 0 als de vectoren loodrecht staan, en levert via a⃗·b⃗/(|a⃗||b⃗|) de cosinus van de <strong>hoek</strong>. Een <strong>lijn</strong> schrijf je als r⃗ = a⃗ + t·d⃗ met richtingsvector d⃗. Een <strong>normaalvector</strong> staat loodrecht op een vlak.`,
    [
      { h: '1. Inproduct en hoek', p: [
        `Het <strong>inproduct</strong> van (a₁, a₂, a₃) en (b₁, b₂, b₃) is a₁b₁ + a₂b₂ + a₃b₃. Twee vectoren staan <strong>loodrecht</strong> als hun inproduct 0 is. De <strong>hoek</strong> θ volgt uit cos θ = a⃗·b⃗/(|a⃗|·|b⃗|). De <strong>norm</strong> |a⃗| is de lengte; een <strong>eenheidsvector</strong> heeft lengte 1.`],
        formula: { label: 'Hoek tussen vectoren', eq: 'cos θ = (a⃗·b⃗) / (|a⃗|·|b⃗|)', note: 'Inproduct 0 → θ = 90° (loodrecht).' } },
      { h: '2. Lijnen en vlakken', p: [
        `Een <strong>lijn</strong> in 3D: r⃗ = a⃗ + t·d⃗, met a⃗ een punt en d⃗ de <strong>richtingsvector</strong>. Twee lijnen zijn <strong>parallel</strong> als hun richtingsvectoren veelvouden van elkaar zijn. In 3D zijn lijnen <strong>snijdend</strong> (één punt) of <strong>kruisend</strong> (geen punt, niet parallel). Een <strong>normaalvector</strong> staat loodrecht op een vlak.`] },
    ],
    [
      { t: 'Inproduct', d: 'a₁b₁ + a₂b₂ + a₃b₃; is 0 bij loodrechte vectoren', k: 'som van producten van kentallen', fout: ['Norm'] },
      { t: 'Normaalvector', d: 'een vector die loodrecht op een vlak staat', k: 'loodrecht op het vlak', fout: ['Richtingsvector'] },
      { t: 'Richtingsvector', d: 'de vector die de richting van een lijn aangeeft', k: 'richting van de lijn', fout: ['Normaalvector'] },
      { t: 'Eenheidsvector', d: 'een vector met lengte (norm) 1', k: 'lengte 1', fout: ['Norm'] },
      { t: 'Norm', d: 'de lengte van een vector, |a⃗|', k: 'lengte van een vector', fout: ['Inproduct'] },
      { t: 'Parameterrepresentatie', d: 'r⃗ = a⃗ + t·d⃗, de vergelijking van een lijn met parameter t', k: 'r⃗ = a⃗ + t·d⃗', fout: ['Normaalvector'] },
      { t: 'Loodrecht', d: 'twee vectoren met inproduct 0', k: 'inproduct 0', fout: ['Parallel'] },
      { t: 'Parallel', d: 'twee vectoren die veelvouden van elkaar zijn', k: 'veelvoud van elkaar', fout: ['Loodrecht'] },
      { t: 'Kruisende lijnen', d: 'lijnen zonder gemeenschappelijk punt die niet parallel zijn', k: 'geen snijpunt, niet parallel', fout: ['Snijdende lijnen'] },
      { t: 'Snijdende lijnen', d: 'lijnen met precies één gemeenschappelijk punt', k: 'één gemeenschappelijk punt', fout: ['Kruisende lijnen'] },
    ],
    [
      { v: 'Wat is het inproduct van a⃗ = (2, −1, 3) en b⃗ = (1, 4, −2)?', o: ['−8', '8', '0', '5'], c: 0, d: 3, uo: ['Klopt: 2·1 + (−1)·4 + 3·(−2) = 2 − 4 − 6 = −8.', 'Nee, let op de mintekens.', 'Nee, ze staan niet loodrecht.', 'Nee, tel de producten opnieuw op.'], uh: 'Inproduct: a₁b₁ + a₂b₂ + a₃b₃.' },
      { v: 'Wat is de hoek θ tussen a⃗ = (1, 0, 1) en b⃗ = (1, 1, 0)?', o: ['60°', '90°', '45°', '30°'], c: 0, d: 3, uo: ['Klopt: cos θ = 1/(√2·√2) = ½, dus θ = 60°.', 'Nee, het inproduct is 1, niet 0.', 'Nee, cos θ = ½ geeft 60°.', 'Nee, reken cos θ = ½ uit.'], uh: 'cos θ = a⃗·b⃗/(|a⃗||b⃗|).' },
      { v: 'Welke voorwaarde geldt voor twee loodrechte vectoren?', o: ['het inproduct is 0', 'ze zijn veelvouden van elkaar', 'ze hebben dezelfde lengte', 'hun som is 0'], c: 0, d: 2, uo: ['Klopt: loodrecht betekent inproduct 0.', 'Nee, dat is parallel.', 'Nee, gelijke lengte zegt niets over de hoek.', 'Nee, dat betekent tegengesteld.'], uh: 'Loodrecht: a⃗·b⃗ = 0.' },
      { v: 'Lijnen met richtingsvectoren d₁ = (1, 2, 3) en d₂ = (2, 4, 6) zijn...', o: ['parallel (d₂ = 2·d₁)', 'loodrecht', 'kruisend', 'snijdend onder 45°'], c: 0, d: 3, uo: ['Klopt: d₂ is een veelvoud van d₁, dus parallel.', 'Nee, loodrecht zou inproduct 0 zijn.', 'Nee, ze hebben dezelfde richting.', 'Nee, de richtingen zijn gelijk.'], uh: 'Richtingsvectoren veelvoud van elkaar: parallel.' },
      { v: 'Wat geeft a⃗·b⃗/(|a⃗|·|b⃗|)?', o: ['cos θ, de cosinus van de hoek tussen a⃗ en b⃗', 'de lengte van a⃗', 'het inproduct', 'de normaalvector'], c: 0, d: 3, uo: ['Klopt: deze uitdrukking geeft de cosinus van de hoek.', 'Nee, dat is |a⃗|.', 'Nee, dat is alleen de teller.', 'Nee, dat is een vector.'], uh: 'cos θ = a⃗·b⃗/(|a⃗||b⃗|).' },
      { v: 'Wat is de meetkundige betekenis van de normaalvector n⃗ van een vlak?', o: ['n⃗ staat loodrecht op het vlak', 'n⃗ ligt in het vlak', 'n⃗ is een punt van het vlak', 'n⃗ is evenwijdig aan het vlak'], c: 0, d: 2, uo: ['Klopt: de normaalvector staat loodrecht op het vlak.', 'Nee, dan zou het een richtingsvector zijn.', 'Nee, een vector is geen punt.', 'Nee, hij staat er juist loodrecht op.'], uh: 'Normaalvector: loodrecht op het vlak.' },
      { v: 'Wat beschrijft r⃗ = a⃗ + t·d⃗ in 3D?', o: ['a⃗ is een punt op de lijn, d⃗ de richtingsvector, t ∈ ℝ', 'een vlak', 'een cirkel', 'een normaalvector'], c: 0, d: 3, uo: ['Klopt: dit is de parametervoorstelling van een lijn.', 'Nee, een vlak heeft twee parameters.', 'Nee, dit is recht, geen cirkel.', 'Nee, dat is één vector.'], uh: 'Lijn: r⃗ = a⃗ + t·d⃗.' },
      { v: 'Wat is het verschil tussen snijdende en kruisende lijnen in 3D?', o: ['snijdend: één gemeenschappelijk punt; kruisend: geen punt, niet parallel', 'ze zijn hetzelfde', 'snijdend: geen punt; kruisend: één punt', 'beide zijn parallel'], c: 0, d: 3, uo: ['Klopt: snijdend heeft een snijpunt, kruisend niet en is niet parallel.', 'Nee, ze verschillen.', 'Nee, dat is precies omgedraaid.', 'Nee, kruisende lijnen zijn juist niet parallel.'], uh: 'Snijdend: één punt; kruisend: geen punt, niet parallel.' },
      { v: 'Welke eigenschap heeft een eenheidsvector?', o: ['de lengte (norm) is 1', 'het inproduct met zichzelf is 0', 'hij staat loodrecht op alles', 'hij is altijd (1, 0, 0)'], c: 0, d: 2, uo: ['Klopt: een eenheidsvector heeft lengte 1.', 'Nee, dat inproduct is juist 1.', 'Nee, dat geldt niet.', 'Nee, richting mag variëren.'], uh: 'Eenheidsvector: norm 1.' },
      { v: 'Wat is de norm (lengte) van de vector (3, 4)?', o: ['5', '7', '12', '25'], c: 0, d: 2, uo: ['Klopt: √(3² + 4²) = √25 = 5.', 'Nee, je telt de kentallen niet op.', 'Nee, dat is 3·4.', 'Nee, dat is onder de wortel, √25 = 5.'], uh: 'Norm: |a⃗| = √(a₁² + a₂²).' },
      { v: 'Wat is het inproduct van (1, 0) en (0, 1)?', o: ['0 (ze staan loodrecht)', '1', '2', '−1'], c: 0, d: 2, uo: ['Klopt: 1·0 + 0·1 = 0, dus loodrecht.', 'Nee, reken het inproduct uit.', 'Nee, dat klopt niet.', 'Nee, het is 0.'], uh: 'Inproduct 0: loodrechte vectoren.' },
      { v: 'Wat is de norm van een vector?', o: ['de lengte van de vector', 'de richting van de vector', 'het inproduct', 'de hoek'], c: 0, d: 1, uo: ['Klopt: de norm is de lengte.', 'Nee, dat is de richtingsvector.', 'Nee, dat is een getal uit twee vectoren.', 'Nee, dat is θ.'], uh: 'Norm = lengte van een vector.' },
      { v: 'Twee vectoren zijn parallel als...', o: ['de een een veelvoud van de ander is', 'hun inproduct 0 is', 'ze even lang zijn', 'hun som 0 is'], c: 0, d: 3, uo: ['Klopt: parallel betekent veelvoud van elkaar.', 'Nee, dat is loodrecht.', 'Nee, gelijke lengte zegt niets over richting.', 'Nee, dat betekent tegengesteld.'], uh: 'Parallel: veelvoud van elkaar.' },
    ]),

  V('F', 'Keuzeonderwerpen',
    `Een <strong>differentievergelijking</strong> beschrijft hoe een grootheid per stap verandert. Een <strong>evenwichtswaarde</strong> verandert bij een volgende stap niet meer. De <strong>afgeleide</strong> geeft de veranderingssnelheid; bij <strong>exponentiële groei</strong> is die evenredig met de aanwezige hoeveelheid. Het <strong>langetermijngedrag</strong> beschrijft het model op de lange duur.`,
    [
      { h: '1. Dynamische modellen', p: [
        `Een <strong>differentievergelijking</strong> geeft de verandering per stap. Een <strong>evenwichtswaarde</strong> is een waarde die bij een volgende stap niet meer verandert. Een <strong>stabiel evenwicht</strong> keert na een kleine verstoring terug. Je toetst een keuzeonderwerp door een <strong>model</strong> op te stellen, door te rekenen en te interpreteren.`] },
      { h: '2. Groei en gedrag', p: [
        `De <strong>afgeleide</strong> geeft de <strong>veranderingssnelheid</strong> in een punt. Bij <strong>exponentiële groei</strong> is de groeisnelheid evenredig met de aanwezige hoeveelheid. Het <strong>langetermijngedrag</strong> beschrijft waar het model op de lange duur naartoe gaat, bijvoorbeeld naar een evenwicht.`] },
    ],
    [
      { t: 'Differentievergelijking', d: 'een vergelijking die de verandering van een grootheid per stap beschrijft', k: 'verandering per stap', fout: ['Evenwichtswaarde'] },
      { t: 'Evenwichtswaarde', d: 'een waarde die bij een volgende stap niet meer verandert', k: 'verandert niet meer', fout: ['Langetermijngedrag'] },
      { t: 'Afgeleide', d: 'de veranderingssnelheid (helling) van een functie in een punt', k: 'veranderingssnelheid', fout: ['Groeisnelheid'] },
      { t: 'Exponentiële groei', d: 'groei waarvan de snelheid evenredig is met de aanwezige hoeveelheid', k: 'snelheid evenredig met hoeveelheid', fout: ['Lineaire groei'] },
      { t: 'Model', d: 'een wiskundige beschrijving van een situatie', k: 'wiskundige beschrijving', fout: ['Langetermijngedrag'] },
      { t: 'Langetermijngedrag', d: 'het gedrag van een model op de lange duur', k: 'gedrag op lange duur', fout: ['Evenwichtswaarde'] },
      { t: 'Recursie', d: 'het berekenen van de volgende waarde uit de vorige', k: 'volgende uit vorige', fout: ['Differentievergelijking'] },
      { t: 'Stabiel evenwicht', d: 'een evenwicht waar het model na een kleine verstoring naar terugkeert', k: 'keert terug na verstoring', fout: ['Evenwichtswaarde'] },
      { t: 'Groeisnelheid', d: 'hoe snel een grootheid per tijdseenheid verandert', k: 'snelheid van verandering', fout: ['Afgeleide'] },
      { t: 'Numerieke benadering', d: 'een uitkomst bij benadering uitrekenen met kleine stapjes', k: 'bij benadering met stapjes', fout: ['Exponentiële groei'] },
    ],
    [
      { v: 'Een differentievergelijking beschrijft...', o: ['hoe een grootheid per stap verandert', 'de oppervlakte onder een grafiek', 'een vaste eindwaarde', 'een rechte lijn'], c: 0, d: 2, uo: ['Klopt: het beschrijft de verandering per stap.', 'Nee, dat is een integraal.', 'Nee, de waarde verandert juist per stap.', 'Nee, dat is een lineaire functie.'], uh: 'Differentievergelijking: verandering per stap.' },
      { v: 'Een evenwichtswaarde van een dynamisch model is een waarde die...', o: ['niet meer verandert bij een volgende stap', 'steeds groter wordt', 'oscilleert', 'naar oneindig gaat'], c: 0, d: 3, uo: ['Klopt: in een evenwicht blijft de waarde gelijk.', 'Nee, dan is het geen evenwicht.', 'Nee, dan is er geen stabiel evenwicht.', 'Nee, dan groeit het onbeperkt.'], uh: 'Evenwicht: verandert niet meer.' },
      { v: 'De afgeleide van een functie geeft in een punt...', o: ['de helling (veranderingssnelheid)', 'de oppervlakte', 'de functiewaarde', 'de startwaarde'], c: 0, d: 2, uo: ['Klopt: de afgeleide is de helling in dat punt.', 'Nee, dat is de integraal.', 'Nee, dat is f(x) zelf.', 'Nee, dat is een constante.'], uh: 'Afgeleide: helling/veranderingssnelheid.' },
      { v: 'Bij exponentiële groei is de groeisnelheid...', o: ['evenredig met de aanwezige hoeveelheid', 'constant', 'evenredig met de tijd', 'nul'], c: 0, d: 3, uo: ['Klopt: hoe meer er is, hoe sneller het groeit.', 'Nee, constant is lineaire groei.', 'Nee, dat is niet exponentieel.', 'Nee, dan is er geen groei.'], uh: 'Exponentieel: snelheid evenredig met de hoeveelheid.' },
      { v: 'Een keuzeonderwerp toets je vaak door een model te...', o: ['opstellen, doorrekenen en interpreteren', 'alleen uit het hoofd te leren', 'te negeren', 'op te zoeken'], c: 0, d: 2, uo: ['Klopt: je stelt een model op, rekent het door en duidt de uitkomst.', 'Nee, het gaat om toepassen.', 'Nee, dat is geen toets.', 'Nee, je moet het zelf uitwerken.'], uh: 'Model: opstellen, doorrekenen, interpreteren.' },
      { v: 'Het gedrag van een dynamisch model op de lange termijn noem je het...', o: ['langetermijngedrag', 'startgedrag', 'differentiequotiënt', 'domein'], c: 0, d: 3, uo: ['Klopt: dat is het langetermijngedrag.', 'Nee, dat is juist het begin.', 'Nee, dat is een gemiddelde verandering.', 'Nee, dat zijn de toegestane x-waarden.'], uh: 'Langetermijngedrag: gedrag op lange duur.' },
      { v: 'Wat doet recursie in een model?', o: ['de volgende waarde uit de vorige berekenen', 'de oppervlakte berekenen', 'de inverse bepalen', 'de hoek meten'], c: 0, d: 2, uo: ['Klopt: recursie rekent stap voor stap door.', 'Nee, dat is integreren.', 'Nee, dat is spiegelen in y = x.', 'Nee, dat is goniometrie.'], uh: 'Recursie: volgende waarde uit de vorige.' },
      { v: 'Wat betekent een model opstellen?', o: ['de situatie in wiskunde vertalen', 'het antwoord opzoeken', 'de grafiek uitgummen', 'afronden op hele getallen'], c: 0, d: 2, uo: ['Klopt: je vertaalt de situatie naar wiskundige taal.', 'Nee, je maakt het zelf.', 'Nee, dat hoort er niet bij.', 'Nee, dat is iets anders.'], uh: 'Model opstellen: situatie naar wiskunde vertalen.' },
      { v: 'Wat is de groeisnelheid?', o: ['hoe snel een grootheid per tijdseenheid verandert', 'de startwaarde', 'de eindwaarde', 'het aantal stappen'], c: 0, d: 2, uo: ['Klopt: de groeisnelheid is de verandering per tijdseenheid.', 'Nee, dat is de beginwaarde.', 'Nee, dat is de eindwaarde.', 'Nee, dat is een aantal.'], uh: 'Groeisnelheid: verandering per tijd.' },
      { v: 'Wat kenmerkt een stabiel evenwicht?', o: ['het model keert na een kleine verstoring terug', 'het model loopt weg na een verstoring', 'de waarde groeit exponentieel', 'er is geen evenwicht'], c: 0, d: 3, uo: ['Klopt: bij een stabiel evenwicht keert het systeem terug.', 'Nee, dat is juist instabiel.', 'Nee, dan is er geen evenwicht.', 'Nee, er is wel een evenwicht.'], uh: 'Stabiel evenwicht: keert terug na verstoring.' },
      { v: 'Wat betekent numeriek benaderen?', o: ['een uitkomst bij benadering uitrekenen met kleine stapjes', 'exact met wortels doorrekenen', 'de grafiek spiegelen', 'de periode berekenen'], c: 0, d: 3, uo: ['Klopt: numeriek betekent stapsgewijs benaderen.', 'Nee, dat is juist exact rekenen.', 'Nee, dat is een transformatie.', 'Nee, dat hoort bij goniometrie.'], uh: 'Numeriek: bij benadering met stapjes.' },
      { v: 'In het evenwicht van een continu model is de verandering...', o: ['nul', 'maximaal', 'negatief', 'exponentieel'], c: 0, d: 3, uo: ['Klopt: in evenwicht verandert er niets, de snelheid is 0.', 'Nee, juist niet.', 'Nee, er is geen verandering.', 'Nee, er is geen groei.'], uh: 'Evenwicht: veranderingssnelheid 0.' },
    ]),
];
