// VWO Maatschappijwetenschappen - gouden-stijl contentspec. Vervangt crude
// generatorvragen door authored inzichtvragen met per-optie-uitleg + situaties.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vwo', vak: 'mw', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Vaardigheden',
    `Sociaalwetenschappelijk onderzoek beoordeel je op <strong>betrouwbaarheid</strong> (herhaalbaarheid) en <strong>validiteit</strong> (meet je wat je bedoelt). Je kent het verschil tussen <strong>kwalitatief</strong> en <strong>kwantitatief</strong> onderzoek en tussen <strong>correlatie</strong> en <strong>causaliteit</strong>, en let bij bronnen op <strong>belanghebbendheid</strong>.`,
    [
      { h: '1. Kwaliteit van onderzoek', p: [
        `<strong>Betrouwbaarheid</strong> gaat over of herhaling dezelfde uitkomst geeft; <strong>validiteit</strong> over of je meet wat je bedoelt te meten. Een <strong>representatieve steekproef</strong> lijkt in samenstelling op de hele populatie. <strong>Kwalitatief</strong> onderzoek gebruikt open interviews en observaties, <strong>kwantitatief</strong> onderzoek cijfers en enquêtes.`] },
      { h: '2. Verbanden en bronnen', p: [
        `Een <strong>correlatie</strong> is samenhang tussen A en B, maar niet per se een oorzaak; <strong>causaliteit</strong> is een echt oorzaak-gevolg-verband. Een <strong>gesloten vraag</strong> geeft antwoorden uit vaste categorieën, een <strong>open vraag</strong> antwoorden in eigen woorden. Bij een bron let je op <strong>belanghebbendheid</strong>: een belanghebbende partij kan gekleurd rapporteren.`] },
    ],
    [
      { t: 'Betrouwbaarheid', d: 'of herhaling van het onderzoek dezelfde uitkomst geeft', k: 'herhaalbaarheid', fout: ['Validiteit'] },
      { t: 'Validiteit', d: 'of je meet wat je bedoelt te meten', k: 'meten wat je bedoelt', fout: ['Betrouwbaarheid'] },
      { t: 'Representatieve steekproef', d: 'een steekproef die in samenstelling op de populatie lijkt', k: 'lijkt op de populatie', fout: ['Correlatie'] },
      { t: 'Kwalitatief onderzoek', d: 'onderzoek met open interviews en observaties', k: 'open interviews, observaties', fout: ['Kwantitatief onderzoek'] },
      { t: 'Kwantitatief onderzoek', d: 'onderzoek met cijfers, grote aantallen en enquêtes', k: 'cijfers en enquêtes', fout: ['Kwalitatief onderzoek'] },
      { t: 'Correlatie', d: 'samenhang tussen twee variabelen, niet per se een oorzaak', k: 'samenhang zonder oorzaak', fout: ['Causaliteit'] },
      { t: 'Causaliteit', d: 'een echt oorzaak-gevolg-verband tussen variabelen', k: 'oorzaak-gevolg', fout: ['Correlatie'] },
      { t: 'Gesloten vraag', d: 'een vraag met antwoorden uit vaste categorieën', k: 'vaste antwoordcategorieën', fout: ['Open vraag'] },
      { t: 'Open vraag', d: 'een vraag waarop je in eigen woorden antwoordt', k: 'eigen woorden', fout: ['Gesloten vraag'] },
      { t: 'Belanghebbendheid', d: 'dat een belanghebbende partij gekleurd kan rapporteren', k: 'gekleurd door belang', fout: ['Validiteit'] },
    ],
    [
      { v: 'De betrouwbaarheid van een onderzoek gaat over...', o: ['of herhaling dezelfde uitkomst geeft', 'of je meet wat je bedoelt', 'of de steekproef groot is', 'of de vragen open zijn'], c: 0, d: 2, uo: ['Klopt: betrouwbaarheid is herhaalbaarheid.', 'Nee, dat is validiteit.', 'Nee, grootte alleen zegt het niet.', 'Nee, dat is een vraagtype.'], uh: 'Betrouwbaarheid: herhaling geeft dezelfde uitkomst.' },
      { v: 'De validiteit van een onderzoek gaat over...', o: ['of je meet wat je bedoelt te meten', 'of herhaling hetzelfde geeft', 'of de bron belanghebbend is', 'of de vraag gesloten is'], c: 0, d: 2, uo: ['Klopt: validiteit is meten wat je bedoelt.', 'Nee, dat is betrouwbaarheid.', 'Nee, dat is bronkritiek.', 'Nee, dat is een vraagtype.'], uh: 'Validiteit: meet je wat je bedoelt.' },
      { v: 'Een representatieve steekproef...', o: ['lijkt in samenstelling op de hele populatie', 'bestaat uit alleen vrijwilligers', 'is altijd heel klein', 'bevat alleen jongeren'], c: 0, d: 2, uo: ['Klopt: representatief betekent lijkend op de populatie.', 'Nee, dat is juist scheef.', 'Nee, grootte is niet de kern.', 'Nee, dat is niet representatief.'], uh: 'Representatief: lijkt op de populatie.' },
      { v: 'Kwalitatief onderzoek gebruikt vooral...', o: ['open interviews en observaties', 'grote enquêtes met cijfers', 'alleen bestaande statistieken', 'gesloten meerkeuzevragen'], c: 0, d: 2, uo: ['Klopt: kwalitatief werkt met diepte-informatie.', 'Nee, dat is kwantitatief.', 'Nee, dat is kwantitatief.', 'Nee, dat is kwantitatief.'], uh: 'Kwalitatief: open interviews en observaties.' },
      { v: 'Een correlatie tussen A en B betekent...', o: ['er is samenhang, niet per se een oorzaak', 'A veroorzaakt altijd B', 'B veroorzaakt altijd A', 'er is geen enkel verband'], c: 0, d: 3, uo: ['Klopt: samenhang is nog geen oorzaak.', 'Nee, correlatie bewijst geen oorzaak.', 'Nee, ook dat volgt niet.', 'Nee, er is juist samenhang.'], uh: 'Correlatie: samenhang, geen bewijs van oorzaak.' },
      { v: 'Een gesloten vraag levert op...', o: ['antwoorden uit vaste categorieën', 'antwoorden in eigen woorden', 'een diepte-interview', 'een observatie'], c: 0, d: 2, uo: ['Klopt: gesloten vragen hebben vaste opties.', 'Nee, dat is een open vraag.', 'Nee, dat is kwalitatief.', 'Nee, dat is een methode.'], uh: 'Gesloten vraag: vaste antwoordcategorieën.' },
      { v: 'Twee sociaalwetenschappelijke benaderingen zijn de...', o: ['sociologische en politicologische', 'chemische en fysische', 'literaire en taalkundige', 'wiskundige en statistische'], c: 0, d: 2, uo: ['Klopt: sociologie en politicologie zijn kernbenaderingen.', 'Nee, dat is bèta.', 'Nee, dat is taal.', 'Nee, dat zijn hulpmiddelen.'], uh: 'Benaderingen: sociologisch en politicologisch.' },
      { v: 'Bij een bron let je op belanghebbendheid omdat...', o: ['een belanghebbende partij gekleurd kan rapporteren', 'oude bronnen altijd fout zijn', 'lange teksten betrouwbaarder zijn', 'de kleur van de bron telt'], c: 0, d: 3, uo: ['Klopt: eigen belang kan de informatie kleuren.', 'Nee, ouderdom bepaalt dat niet.', 'Nee, lengte zegt niets.', 'Nee, dat is letterlijke kleur.'], uh: 'Belanghebbendheid: eigen belang kleurt de rapportage.' },
      { v: 'Kwantitatief onderzoek gebruikt vooral...', o: ['cijfers, grote aantallen en enquêtes', 'open diepte-interviews', 'losse observaties', 'één casus in detail'], c: 0, d: 2, uo: ['Klopt: kwantitatief werkt met cijfers en aantallen.', 'Nee, dat is kwalitatief.', 'Nee, dat is kwalitatief.', 'Nee, dat is een casestudy.'], uh: 'Kwantitatief: cijfers en enquêtes.' },
      { v: 'Wat is causaliteit?', o: ['een echt oorzaak-gevolg-verband', 'toevallige samenhang', 'een vraagtype', 'een steekproef'], c: 0, d: 3, uo: ['Klopt: causaliteit is oorzaak en gevolg.', 'Nee, dat is correlatie.', 'Nee, dat is iets anders.', 'Nee, dat is een selectie.'], uh: 'Causaliteit: oorzaak-gevolg-verband.' },
      { v: 'Een open vraag levert op...', o: ['antwoorden in eigen woorden', 'antwoorden uit vaste categorieën', 'alleen ja of nee', 'een getal'], c: 0, d: 2, uo: ['Klopt: bij een open vraag antwoord je vrij.', 'Nee, dat is een gesloten vraag.', 'Nee, dat is heel gesloten.', 'Nee, dat is kwantitatief.'], uh: 'Open vraag: eigen woorden.' },
    ]),

  V('B', 'Vorming',
    `Mensen worden gevormd door <strong>socialisatie</strong>: primair in het gezin, secundair op school en werk. <strong>Cultuur</strong> (gedeelde waarden en normen) en <strong>sociale controle</strong> (beloning en straf) sturen gedrag. Theorieën als de <strong>labelingtheorie</strong>, <strong>anomie</strong> en <strong>sociale reproductie</strong> verklaren afwijkend gedrag en ongelijkheid.`,
    [
      { h: '1. Socialisatie en cultuur', p: [
        `<strong>Primaire socialisatie</strong> vindt plaats in het gezin in de vroege kinderjaren; <strong>secundaire socialisatie</strong> op school, werk en via media. <strong>Cultuur</strong> is het geheel van gedeelde waarden, normen en gedragspatronen. Bij <strong>anticiperende socialisatie</strong> pas je je alvast aan een nieuwe rol aan.`] },
      { h: '2. Controle, afwijking en ongelijkheid', p: [
        `<strong>Sociale controle</strong> stuurt gedrag via <strong>formele</strong> (wetten) en <strong>informele</strong> (ongeschreven) normen. De <strong>labelingtheorie</strong> (Becker) stelt dat deviantie in de reactie van de samenleving zit; <strong>anomie</strong> (Durkheim) is normloosheid. <strong>Sociale reproductie</strong> (Bourdieu) draagt ongelijke kansen over via cultureel en sociaal kapitaal.`] },
    ],
    [
      { t: 'Primaire socialisatie', d: 'de vorming in het gezin tijdens de vroege kinderjaren', k: 'vorming in het gezin', fout: ['Secundaire socialisatie'] },
      { t: 'Secundaire socialisatie', d: 'de vorming op school, werk en via media', k: 'vorming buiten het gezin', fout: ['Primaire socialisatie'] },
      { t: 'Cultuur', d: 'de gedeelde waarden, normen en gedragspatronen van een groep', k: 'gedeelde waarden en normen', fout: ['Sociale controle'] },
      { t: 'Sociale controle', d: 'het sturen van gedrag via beloningen en straffen', k: 'beloning en straf', fout: ['Cultuur'] },
      { t: 'Labelingtheorie', d: 'de theorie dat deviantie in de reactie van de samenleving zit', k: 'deviantie is de reactie', fout: ['Anomie'] },
      { t: 'Anomie', d: 'normloosheid door gebrek aan maatschappelijke samenhang (Durkheim)', k: 'normloosheid', fout: ['Labelingtheorie'] },
      { t: 'Sociale reproductie', d: 'de overdracht van ongelijke kansen via cultureel en sociaal kapitaal', k: 'ongelijkheid van ouders op kinderen', fout: ['Anticiperende socialisatie'] },
      { t: 'Formele normen', d: 'in wetten en regels vastgelegde gedragsregels', k: 'vastgelegd in wet', fout: ['Informele normen'] },
      { t: 'Informele normen', d: 'ongeschreven maar sociaal afgedwongen gedragsregels', k: 'ongeschreven regels', fout: ['Formele normen'] },
      { t: 'Anticiperende socialisatie', d: 'je alvast aanpassen aan de verwachtingen van een nieuwe rol', k: 'vooraf aanpassen aan een rol', fout: ['Primaire socialisatie'] },
    ],
    [
      { v: 'Welk type socialisatie vindt plaats in het gezin tijdens de vroege kinderjaren?', o: ['primaire socialisatie', 'secundaire socialisatie', 'anticiperende socialisatie', 'resocialisatie'], c: 0, d: 2, uo: ['Klopt: het gezin verzorgt de primaire socialisatie.', 'Nee, dat is op school en werk.', 'Nee, dat is vooruitlopen op een rol.', 'Nee, dat is opnieuw socialiseren.'], uh: 'Primaire socialisatie: in het gezin.' },
      { v: 'Welke theorie stelt dat deviantie niet in de daad zit maar in de reactie van de samenleving?', o: ['de labelingtheorie (Becker)', 'de anomietheorie', 'het pluralisme', 'de sociale reproductie'], c: 0, d: 3, uo: ['Klopt: labeling legt de nadruk op de reactie.', 'Nee, dat gaat over normloosheid.', 'Nee, dat is politicologie.', 'Nee, dat gaat over kansenoverdracht.'], uh: 'Labelingtheorie: deviantie zit in de reactie.' },
      { v: 'Welke term omschrijft gedeelde waarden, normen en gedragspatronen die een groep bijeenhouden?', o: ['cultuur', 'sociale controle', 'anomie', 'validiteit'], c: 0, d: 2, uo: ['Klopt: dat is cultuur.', 'Nee, dat stuurt gedrag via beloning en straf.', 'Nee, dat is normloosheid.', 'Nee, dat is onderzoeksterm.'], uh: 'Cultuur: gedeelde waarden, normen en gedrag.' },
      { v: 'Welk mechanisme stuurt gedrag via beloningen en straffen, formeel en informeel?', o: ['sociale controle', 'anomie', 'modernisering', 'correlatie'], c: 0, d: 2, uo: ['Klopt: sociale controle beloont en straft.', 'Nee, dat is normloosheid.', 'Nee, dat is maatschappelijke verandering.', 'Nee, dat is een onderzoeksterm.'], uh: 'Sociale controle: beloning en straf.' },
      { v: 'Welke term beschrijft Durkheims concept van normloosheid door ontbrekende samenhang?', o: ['anomie', 'anticiperende socialisatie', 'legitimiteit', 'cultuur'], c: 0, d: 3, uo: ['Klopt: anomie is normloosheid.', 'Nee, dat is vooruitlopen op een rol.', 'Nee, dat is erkende macht.', 'Nee, dat zijn gedeelde normen.'], uh: 'Anomie: normloosheid (Durkheim).' },
      { v: 'Welke term beschrijft de overdracht van ongelijke kansen via cultureel en sociaal kapitaal?', o: ['sociale reproductie (Bourdieu)', 'sociale controle', 'primaire socialisatie', 'pluralisme'], c: 0, d: 3, uo: ['Klopt: sociale reproductie draagt ongelijkheid over.', 'Nee, dat is beloning en straf.', 'Nee, dat is vorming in het gezin.', 'Nee, dat is politicologie.'], uh: 'Sociale reproductie: ongelijkheid van ouders op kinderen.' },
      { v: 'Wat onderscheidt formele van informele normen?', o: ['formeel is vastgelegd in wet, informeel is ongeschreven maar afgedwongen', 'ze zijn hetzelfde', 'formeel is ongeschreven', 'informeel staat in de wet'], c: 0, d: 3, uo: ['Klopt: vastgelegd versus ongeschreven.', 'Nee, ze verschillen.', 'Nee, dat is omgedraaid.', 'Nee, dat is omgedraaid.'], uh: 'Formeel: in de wet; informeel: ongeschreven.' },
      { v: 'Welk concept beschrijft je aanpassen aan de verwachtingen van een nieuwe sociale positie?', o: ['anticiperende socialisatie', 'primaire socialisatie', 'anomie', 'labeling'], c: 0, d: 3, uo: ['Klopt: je loopt vooruit op de nieuwe rol.', 'Nee, dat is de vorming in het gezin.', 'Nee, dat is normloosheid.', 'Nee, dat gaat over deviantie.'], uh: 'Anticiperende socialisatie: vooraf aanpassen aan een rol.' },
      { v: 'Wat is de kern van Bourdieus "symbolisch geweld"?', o: ['ongelijkheid wordt door de gedomineerden zelf als natuurlijk aanvaard', 'fysiek geweld tussen klassen', 'straf door de overheid', 'een onderzoeksmethode'], c: 0, d: 3, uo: ['Klopt: de ongelijkheid wordt onzichtbaar geaccepteerd.', 'Nee, het is juist niet fysiek.', 'Nee, dat is formele sanctie.', 'Nee, dat is geen methode.'], uh: 'Symbolisch geweld: ongelijkheid als vanzelfsprekend aanvaard.' },
      { v: 'Waar vindt secundaire socialisatie vooral plaats?', o: ['op school, werk en via media', 'alleen in het gezin', 'alleen voor de geboorte', 'nergens'], c: 0, d: 2, uo: ['Klopt: buiten het gezin socialiseer je verder.', 'Nee, dat is primair.', 'Nee, dat kan niet.', 'Nee, ze vindt wel plaats.'], uh: 'Secundaire socialisatie: school, werk, media.' },
      { v: 'Wat is een norm?', o: ['een gedragsregel voor wat hoort', 'een nastrevenswaardig ideaal', 'een onderzoeksmethode', 'een machtsvorm'], c: 0, d: 1, uo: ['Klopt: een norm is een concrete gedragsregel.', 'Nee, dat is een waarde.', 'Nee, dat is een methode.', 'Nee, dat is macht.'], uh: 'Norm: een gedragsregel.' },
      { v: 'Wat is een waarde?', o: ['een nastrevenswaardig ideaal', 'een concrete gedragsregel', 'een steekproef', 'een sanctie'], c: 0, d: 2, uo: ['Klopt: een waarde is een ideaal.', 'Nee, dat is een norm.', 'Nee, dat is onderzoek.', 'Nee, dat is een straf.'], uh: 'Waarde: een nastrevenswaardig ideaal.' },
      { v: 'Welke drie kerntaken vervult de verzorgingsstaat?', o: ['herverdeling, risicospreiding en bevordering van gelijke kansen', 'productie, handel en export', 'controle, straf en toezicht', 'onderzoek, onderwijs en advies'], c: 0, d: 3, uo: ['Klopt: dat zijn de kerntaken via AOW, WW en Zvw.', 'Nee, dat is economie.', 'Nee, dat is handhaving.', 'Nee, dat is de kennissector.'], uh: 'Verzorgingsstaat: herverdeling, risicospreiding, gelijke kansen.' },
    ]),

  V('C', 'Verhouding',
    `Machtsverhoudingen bepalen wie beslist. In een <strong>directe democratie</strong> stemmen burgers zelf; in een <strong>representatieve democratie</strong> via gekozenen. <strong>Politieke partijen</strong> aggregeren belangen, het <strong>kiesstelsel</strong> bepaalt de vertegenwoordiging, en <strong>legitimiteit</strong> maakt macht rechtmatig. In de EU geldt <strong>supranationalisme</strong>.`,
    [
      { h: '1. Democratie en macht', p: [
        `Bij <strong>directe democratie</strong> stemmen burgers zelf over besluiten (referendum); bij <strong>representatieve democratie</strong> kiezen ze vertegenwoordigers. <strong>Formele democratie</strong> gaat over procedures, <strong>materiële democratie</strong> over uitkomsten. <strong>Legitimiteit</strong> is macht die de bevolking als rechtmatig erkent.`] },
      { h: '2. Partijen, stelsel en EU', p: [
        `<strong>Politieke partijen</strong> articuleren standpunten en aggregeren belangen. Nederland kent <strong>evenredige vertegenwoordiging</strong>, wat leidt tot veel partijen en coalitieregeringen. Alleen de Tweede Kamer heeft het <strong>recht van amendement</strong>. In de EU geldt <strong>supranationalisme</strong>: EU-recht heeft voorrang op nationaal recht.`] },
    ],
    [
      { t: 'Directe democratie', d: 'een stelsel waarin burgers zelf direct over besluiten stemmen', k: 'burgers stemmen zelf', fout: ['Representatieve democratie'] },
      { t: 'Representatieve democratie', d: 'een stelsel waarin gekozen vertegenwoordigers beslissen', k: 'gekozenen beslissen', fout: ['Directe democratie'] },
      { t: 'Supranationalisme', d: 'dat EU-recht voorrang heeft op nationaal recht', k: 'EU-recht boven nationaal recht', fout: ['Pluralisme'] },
      { t: 'Evenredige vertegenwoordiging', d: 'zetels naar rato van de stemmen, met veel partijen en coalities', k: 'zetels naar rato', fout: ['Legitimiteit'] },
      { t: 'Legitimiteit', d: 'macht die door de bevolking als rechtmatig wordt erkend', k: 'als rechtmatig erkend', fout: ['Macht'] },
      { t: 'Pluralisme', d: 'de theorie dat beleid ontstaat uit strijd tussen georganiseerde belangen', k: 'strijd tussen belangen', fout: ['Supranationalisme'] },
      { t: 'Recht van amendement', d: 'het recht om wetten aan te passen, in Nederland bij de Tweede Kamer', k: 'wetten aanpassen', fout: ['Legitimiteit'] },
      { t: 'Lobby', d: 'het beïnvloeden van beleid door belangengroepen', k: 'beleid beïnvloeden', fout: ['Pluralisme'] },
      { t: 'Participatiedemocratie', d: 'burgers participeren actief in beleid buiten verkiezingen om', k: 'meedoen buiten verkiezingen', fout: ['Directe democratie'] },
      { t: 'Macht', d: 'het vermogen om het gedrag van anderen te beïnvloeden', k: 'gedrag beïnvloeden', fout: ['Legitimiteit'] },
    ],
    [
      { v: 'Welke democratievorm laat burgers zelf direct over besluiten stemmen?', o: ['directe democratie', 'representatieve democratie', 'constitutionele monarchie', 'pluralisme'], c: 0, d: 2, uo: ['Klopt: via bijvoorbeeld een referendum stemmen burgers zelf.', 'Nee, daar beslissen gekozenen.', 'Nee, dat gaat over de vorst.', 'Nee, dat is een beleidsttheorie.'], uh: 'Directe democratie: burgers stemmen zelf.' },
      { v: 'Welke rol vervullen politieke partijen naast het leveren van kandidaten?', o: ['standpunten articuleren en belangen aggregeren', 'wetten uitvoeren', 'recht spreken', 'belasting innen'], c: 0, d: 3, uo: ['Klopt: partijen bundelen en verwoorden belangen.', 'Nee, dat doet de uitvoerende macht.', 'Nee, dat doet de rechter.', 'Nee, dat doet de fiscus.'], uh: 'Partijen: belangen articuleren en aggregeren.' },
      { v: 'Welke bevoegdheid mag de Eerste Kamer NIET uitoefenen op wetgeving?', o: ['amendementen indienen', 'een wet verwerpen', 'debatteren', 'stemmen'], c: 0, d: 3, uo: ['Klopt: amenderen mag alleen de Tweede Kamer.', 'Nee, verwerpen mag de Eerste Kamer wel.', 'Nee, debatteren mag.', 'Nee, stemmen mag.'], uh: 'Eerste Kamer: geen recht van amendement.' },
      { v: 'Welk begrip beschrijft dat EU-recht voorrang heeft op nationaal recht?', o: ['supranationalisme', 'pluralisme', 'legitimiteit', 'federalisme'], c: 0, d: 3, uo: ['Klopt: bij supranationalisme gaat EU-recht voor.', 'Nee, dat is een beleidsttheorie.', 'Nee, dat is rechtmatige macht.', 'Nee, dat is een staatsvorm.'], uh: 'Supranationalisme: EU-recht boven nationaal recht.' },
      { v: 'Welk democratisch bezwaar kleeft aan lobbyen door grote bedrijven?', o: ['ongelijke politieke invloed', 'te veel transparantie', 'te weinig partijen', 'te veel referenda'], c: 0, d: 3, uo: ['Klopt: rijke belangen wegen zwaarder dan zwakkere.', 'Nee, lobby is juist vaak ondoorzichtig.', 'Nee, dat is geen lobbybezwaar.', 'Nee, dat gaat over directe democratie.'], uh: 'Lobbybezwaar: ongelijke politieke invloed.' },
      { v: 'Welke macht heeft in Nederland het recht van amendement?', o: ['de Tweede Kamer', 'de Eerste Kamer', 'de rechterlijke macht', 'de koning'], c: 0, d: 3, uo: ['Klopt: alleen de Tweede Kamer mag wetten aanpassen.', 'Nee, die mag alleen aannemen of verwerpen.', 'Nee, die spreekt recht.', 'Nee, die tekent slechts.'], uh: 'Recht van amendement: Tweede Kamer.' },
      { v: 'Wat is het verschil tussen formele en materiële democratie?', o: ['formeel gaat over procedures, materieel over uitkomsten', 'ze zijn hetzelfde', 'formeel gaat over uitkomsten', 'materieel gaat over procedures'], c: 0, d: 3, uo: ['Klopt: procedures versus uitkomsten.', 'Nee, ze verschillen.', 'Nee, dat is omgedraaid.', 'Nee, dat is omgedraaid.'], uh: 'Formeel: procedures; materieel: uitkomsten.' },
      { v: 'Welke theorie ziet beleid als resultaat van strijd tussen georganiseerde belangen?', o: ['pluralisme', 'supranationalisme', 'labeling', 'anomie'], c: 0, d: 3, uo: ['Klopt: pluralisme benadrukt de strijd tussen belangen.', 'Nee, dat gaat over EU-recht.', 'Nee, dat gaat over deviantie.', 'Nee, dat is normloosheid.'], uh: 'Pluralisme: beleid uit strijd tussen belangen.' },
      { v: 'Welk kiesstelsel gebruikt Nederland en wat is een gevolg?', o: ['evenredige vertegenwoordiging, met veel partijen en coalities', 'districtenstelsel, met twee partijen', 'een koning die kiest', 'geen verkiezingen'], c: 0, d: 3, uo: ['Klopt: evenredige vertegenwoordiging geeft veel partijen.', 'Nee, dat past bij een districtenstelsel.', 'Nee, dat is geen democratie.', 'Nee, er zijn juist verkiezingen.'], uh: 'NL: evenredige vertegenwoordiging → coalities.' },
      { v: 'Welke term beschrijft macht die de bevolking als rechtmatig erkent?', o: ['legitimiteit', 'lobby', 'anomie', 'correlatie'], c: 0, d: 2, uo: ['Klopt: legitimiteit is erkende, rechtmatige macht.', 'Nee, dat is belangenbehartiging.', 'Nee, dat is normloosheid.', 'Nee, dat is een onderzoeksterm.'], uh: 'Legitimiteit: als rechtmatig erkende macht.' },
      { v: 'Welk begrip beschrijft actieve burgerparticipatie in beleid buiten verkiezingen om?', o: ['participatiedemocratie', 'representatieve democratie', 'supranationalisme', 'anomie'], c: 0, d: 3, uo: ['Klopt: participatiedemocratie is meedoen tussen verkiezingen door.', 'Nee, dat is via gekozenen.', 'Nee, dat gaat over EU-recht.', 'Nee, dat is normloosheid.'], uh: 'Participatiedemocratie: meedoen buiten verkiezingen.' },
      { v: 'Wat is macht?', o: ['het vermogen om het gedrag van anderen te beïnvloeden', 'het bezit van geld', 'de leeftijd van een leider', 'een onderzoeksmethode'], c: 0, d: 2, uo: ['Klopt: macht is invloed op gedrag.', 'Nee, geld is hooguit een bron van macht.', 'Nee, leeftijd is niet de definitie.', 'Nee, dat is methodologie.'], uh: 'Macht: gedrag van anderen beïnvloeden.' },
    ]),

  V('D', 'Binding',
    `Wat houdt een samenleving bijeen? <strong>Sociale cohesie</strong> ontstaat door <strong>binding</strong>: via instituties (school, kerk, staat), via <strong>solidariteit</strong> en via gedeelde cultuur. De <strong>verzorgingsstaat</strong> versterkt de cohesie, maar staat door <strong>vergrijzing</strong> en <strong>individualisering</strong> onder druk.`,
    [
      { h: '1. Cohesie en binding', p: [
        `<strong>Sociale cohesie</strong> is de samenhang in een samenleving. <strong>Institutionele binding</strong> verloopt via school, kerk en staat; <strong>affectieve binding</strong> via gevoelsrelaties. <strong>Solidariteit</strong> is de bereidheid elkaar te steunen. Tegenover <strong>sociale integratie</strong> staat <strong>segregatie</strong>: het gescheiden leven van groepen.`] },
      { h: '2. Verzorgingsstaat onder druk', p: [
        `De <strong>verzorgingsstaat</strong> versterkt de cohesie door bestaanszekerheid en solidariteit te bieden. Maar <strong>vergrijzing</strong>, stijgende kosten en <strong>individualisering</strong> (mensen worden onafhankelijker van vaste groepen) zetten hem onder druk.`] },
    ],
    [
      { t: 'Sociale cohesie', d: 'de mate van samenhang in een samenleving', k: 'samenhang in de samenleving', fout: ['Segregatie'] },
      { t: 'Institutionele binding', d: 'binding via instituties zoals school, kerk en staat', k: 'binding via instituties', fout: ['Affectieve binding'] },
      { t: 'Verzorgingsstaat', d: 'de staat die bestaanszekerheid en collectieve voorzieningen biedt', k: 'biedt bestaanszekerheid', fout: ['Solidariteit'] },
      { t: 'Solidariteit', d: 'de bereidheid om elkaar te steunen', k: 'elkaar steunen', fout: ['Segregatie'] },
      { t: 'Sociale integratie', d: 'het opgenomen worden in de samenleving', k: 'opgenomen worden', fout: ['Segregatie'] },
      { t: 'Segregatie', d: 'het gescheiden leven van groepen in de samenleving', k: 'groepen leven gescheiden', fout: ['Sociale integratie'] },
      { t: 'Individualisering', d: 'dat mensen onafhankelijker worden van vaste groepen', k: 'losser van groepen', fout: ['Solidariteit'] },
      { t: 'Affectieve binding', d: 'binding via gevoelsrelaties met anderen', k: 'binding via gevoel', fout: ['Institutionele binding'] },
      { t: 'Vergrijzing', d: 'de toename van het aandeel ouderen in de bevolking', k: 'meer ouderen', fout: ['Individualisering'] },
      { t: 'Gemeenschap', d: 'een groep met een sterke onderlinge band', k: 'sterke onderlinge band', fout: ['Sociale cohesie'] },
    ],
    [
      { v: 'Wat is een voorbeeld van institutionele binding?', o: ['binding via school, kerk of de staat', 'binding via een liefdesrelatie', 'binding via toeval', 'binding via het weer'], c: 0, d: 2, uo: ['Klopt: instituties als school en staat binden mensen.', 'Nee, dat is affectieve binding.', 'Nee, toeval bindt niet structureel.', 'Nee, dat is geen binding.'], uh: 'Institutionele binding: via school, kerk, staat.' },
      { v: 'Hoe kan de verzorgingsstaat de sociale cohesie versterken?', o: ['door bestaanszekerheid en solidariteit te bieden', 'door groepen te scheiden', 'door belasting af te schaffen', 'door verkiezingen te verbieden'], c: 0, d: 3, uo: ['Klopt: zekerheid en solidariteit binden mensen.', 'Nee, dat is juist segregatie.', 'Nee, dan verdwijnt de financiering.', 'Nee, dat schaadt de democratie.'], uh: 'Verzorgingsstaat: bestaanszekerheid en solidariteit.' },
      { v: 'Welke ontwikkeling zet de verzorgingsstaat onder druk?', o: ['vergrijzing en stijgende kosten', 'meer jonge werkenden', 'dalende zorgvraag', 'lagere levensverwachting'], c: 0, d: 2, uo: ['Klopt: meer ouderen en kosten drukken op het stelsel.', 'Nee, dat zou juist verlichten.', 'Nee, de zorgvraag stijgt.', 'Nee, die stijgt juist.'], uh: 'Onder druk: vergrijzing en kosten.' },
      { v: 'Wat is sociale cohesie?', o: ['de mate van samenhang in een samenleving', 'het aantal inwoners', 'de hoogte van de belasting', 'de grootte van het land'], c: 0, d: 2, uo: ['Klopt: cohesie is samenhang.', 'Nee, dat is bevolkingsomvang.', 'Nee, dat is fiscaal.', 'Nee, dat is oppervlakte.'], uh: 'Sociale cohesie: samenhang in de samenleving.' },
      { v: 'Wat is solidariteit?', o: ['de bereidheid om elkaar te steunen', 'het scheiden van groepen', 'het innen van belasting', 'het meten van onderzoek'], c: 0, d: 2, uo: ['Klopt: solidariteit is elkaar steunen.', 'Nee, dat is segregatie.', 'Nee, dat is fiscaal.', 'Nee, dat is methodologie.'], uh: 'Solidariteit: elkaar steunen.' },
      { v: 'Wat is segregatie?', o: ['het gescheiden leven van groepen in de samenleving', 'het samenkomen van groepen', 'de groei van de economie', 'het houden van verkiezingen'], c: 0, d: 3, uo: ['Klopt: bij segregatie leven groepen apart.', 'Nee, dat is juist integratie.', 'Nee, dat is economisch.', 'Nee, dat is politiek.'], uh: 'Segregatie: groepen leven gescheiden.' },
      { v: 'Wat is sociale integratie?', o: ['het opgenomen worden in de samenleving', 'het gescheiden leven van groepen', 'het verlaten van een land', 'het meten van cohesie'], c: 0, d: 2, uo: ['Klopt: integratie is opgenomen worden.', 'Nee, dat is segregatie.', 'Nee, dat is emigratie.', 'Nee, dat is onderzoek.'], uh: 'Sociale integratie: opgenomen worden.' },
      { v: 'Wat is individualisering?', o: ['dat mensen onafhankelijker worden van vaste groepen', 'dat mensen zich sterker binden aan de kerk', 'dat groepen samensmelten', 'dat de bevolking krimpt'], c: 0, d: 3, uo: ['Klopt: mensen komen losser te staan van groepen.', 'Nee, dat is juist het tegenovergestelde.', 'Nee, dat is collectivisering.', 'Nee, dat is demografie.'], uh: 'Individualisering: losser van vaste groepen.' },
      { v: 'Wat is een gemeenschap?', o: ['een groep met een sterke onderlinge band', 'een willekeurige verzameling vreemden', 'een enkele persoon', 'een overheidsdienst'], c: 0, d: 2, uo: ['Klopt: een gemeenschap heeft sterke banden.', 'Nee, dan is er geen band.', 'Nee, een gemeenschap is een groep.', 'Nee, dat is een instituut.'], uh: 'Gemeenschap: groep met sterke band.' },
      { v: 'Wat is affectieve binding?', o: ['binding via gevoelsrelaties met anderen', 'binding via school en staat', 'binding via belasting', 'binding via het weer'], c: 0, d: 3, uo: ['Klopt: affectieve binding loopt via gevoel.', 'Nee, dat is institutioneel.', 'Nee, dat is geen binding.', 'Nee, dat is geen binding.'], uh: 'Affectieve binding: via gevoel en relaties.' },
      { v: 'Wat betekent vergrijzing?', o: ['de toename van het aandeel ouderen in de bevolking', 'de toename van jongeren', 'de daling van de bevolking', 'de groei van steden'], c: 0, d: 2, uo: ['Klopt: vergrijzing is meer ouderen.', 'Nee, dat is het tegenovergestelde.', 'Nee, dat is krimp.', 'Nee, dat is verstedelijking.'], uh: 'Vergrijzing: meer ouderen.' },
    ]),

  V('E', 'Verandering',
    `Samenlevingen veranderen door <strong>modernisering</strong>: de langdurige overgang van een traditionele naar een moderne samenleving, met <strong>industrialisatie</strong>, <strong>rationalisering</strong>, <strong>secularisering</strong> en <strong>individualisering</strong>. <strong>Globalisering</strong> versterkt deze processen en zet de verzorgingsstaat onder druk.`,
    [
      { h: '1. Modernisering', p: [
        `<strong>Modernisering</strong> is de overgang van gemeenschap en geloof naar wetenschap en industrie. Kenmerken zijn <strong>industrialisatie</strong> (machinale productie), <strong>rationalisering</strong> (beslissen op basis van efficiëntie) en <strong>differentiatie</strong> (uitsplitsing in gespecialiseerde delen).`] },
      { h: '2. Gevolgen', p: [
        `Modernisering voedt de <strong>individualisering</strong> en gaat samen met <strong>secularisering</strong> (afnemende rol van religie) en <strong>urbanisatie</strong>. <strong>Globalisering</strong> (wereldwijde verwevenheid) versterkt dit alles en zet, samen met individualisering, de verzorgingsstaat onder druk.`] },
    ],
    [
      { t: 'Modernisering', d: 'de langdurige overgang van een traditionele naar een moderne samenleving', k: 'traditioneel naar modern', fout: ['Individualisering'] },
      { t: 'Individualisering', d: 'dat mensen onafhankelijker worden van vaste groepen', k: 'losser van groepen', fout: ['Modernisering'] },
      { t: 'Rationalisering', d: 'beslissen op basis van efficiëntie en verstand in plaats van traditie', k: 'op basis van efficiëntie', fout: ['Secularisering'] },
      { t: 'Industrialisatie', d: 'de overgang naar machinale, grootschalige productie', k: 'machinale productie', fout: ['Urbanisatie'] },
      { t: 'Globalisering', d: 'de toename van wereldwijde verwevenheid', k: 'wereldwijde verwevenheid', fout: ['Modernisering'] },
      { t: 'Secularisering', d: 'de afnemende rol van religie in de samenleving', k: 'minder religie', fout: ['Rationalisering'] },
      { t: 'Differentiatie', d: 'de uitsplitsing van de samenleving in gespecialiseerde delen', k: 'uitsplitsing in delen', fout: ['Modernisering'] },
      { t: 'Sociale verandering', d: 'de verandering van een samenleving door de tijd', k: 'de samenleving verandert', fout: ['Modernisering'] },
      { t: 'Urbanisatie', d: 'de trek van mensen naar de steden', k: 'trek naar de stad', fout: ['Industrialisatie'] },
      { t: 'Emancipatie', d: 'het opeisen van gelijke rechten door achtergestelde groepen', k: 'gelijke rechten opeisen', fout: ['Individualisering'] },
    ],
    [
      { v: 'Wat is modernisering?', o: ['de langdurige overgang van een traditionele naar een moderne samenleving', 'een korte economische crisis', 'het scheiden van groepen', 'het houden van een referendum'], c: 0, d: 2, uo: ['Klopt: modernisering is die lange overgang.', 'Nee, dat is iets tijdelijks.', 'Nee, dat is segregatie.', 'Nee, dat is directe democratie.'], uh: 'Modernisering: traditioneel naar modern.' },
      { v: 'Welk kenmerk hoort bij een moderne samenleving?', o: ['industrialisatie en rationalisering', 'geloof en traditie boven alles', 'zelfvoorzienende dorpen', 'afwezigheid van instituties'], c: 0, d: 3, uo: ['Klopt: industrie en rationeel denken kenmerken de moderne samenleving.', 'Nee, dat is traditioneel.', 'Nee, dat is premodern.', 'Nee, moderne samenlevingen kennen juist veel instituties.'], uh: 'Modern: industrialisatie en rationalisering.' },
      { v: 'Hoe hangen modernisering en individualisering samen?', o: ['modernisering voedt de individualisering', 'ze hebben niets met elkaar te maken', 'individualisering stopt de modernisering', 'ze zijn identiek'], c: 0, d: 3, uo: ['Klopt: modernisering versterkt de individualisering.', 'Nee, ze hangen juist samen.', 'Nee, dat klopt niet.', 'Nee, het zijn verschillende processen.'], uh: 'Modernisering voedt individualisering.' },
      { v: 'Welk begrip beschrijft de verschuiving van gemeenschap en geloof naar wetenschap en industrie?', o: ['modernisering', 'segregatie', 'legitimiteit', 'anomie'], c: 0, d: 3, uo: ['Klopt: dat is modernisering.', 'Nee, dat is groepen scheiden.', 'Nee, dat is rechtmatige macht.', 'Nee, dat is normloosheid.'], uh: 'Modernisering: van geloof naar wetenschap en industrie.' },
      { v: 'Wat is een gevolg van globalisering én individualisering voor de verzorgingsstaat?', o: ['die komt onder druk te staan', 'die wordt overbodig', 'die groeit onbeperkt', 'die verdwijnt meteen'], c: 0, d: 2, uo: ['Klopt: beide processen zetten de verzorgingsstaat onder druk.', 'Nee, hij blijft nodig.', 'Nee, juist niet onbeperkt.', 'Nee, hij verdwijnt niet meteen.'], uh: 'Verzorgingsstaat: onder druk door globalisering en individualisering.' },
      { v: 'Wat is individualisering?', o: ['dat mensen onafhankelijker worden van vaste groepen', 'dat mensen sterker in groepen leven', 'dat de bevolking krimpt', 'dat steden leeglopen'], c: 0, d: 2, uo: ['Klopt: mensen komen losser van vaste groepen.', 'Nee, dat is het tegenovergestelde.', 'Nee, dat is demografie.', 'Nee, dat is het tegendeel van urbanisatie.'], uh: 'Individualisering: losser van vaste groepen.' },
      { v: 'Wat is rationalisering?', o: ['beslissen op basis van efficiëntie en verstand', 'beslissen op basis van traditie', 'het scheiden van groepen', 'het innen van belasting'], c: 0, d: 3, uo: ['Klopt: rationalisering vervangt traditie door doelmatig denken.', 'Nee, dat is juist traditioneel.', 'Nee, dat is segregatie.', 'Nee, dat is fiscaal.'], uh: 'Rationalisering: op basis van efficiëntie.' },
      { v: 'Wat is secularisering?', o: ['de afnemende rol van religie in de samenleving', 'de groei van de kerk', 'de trek naar de stad', 'de toename van ouderen'], c: 0, d: 3, uo: ['Klopt: secularisering is minder religie.', 'Nee, dat is het tegenovergestelde.', 'Nee, dat is urbanisatie.', 'Nee, dat is vergrijzing.'], uh: 'Secularisering: afnemende rol van religie.' },
      { v: 'Wat is globalisering?', o: ['de toename van wereldwijde verwevenheid', 'de scheiding van landen', 'het afsluiten van grenzen', 'de daling van handel'], c: 0, d: 2, uo: ['Klopt: globalisering verweeft de wereld.', 'Nee, dat is het tegenovergestelde.', 'Nee, juist meer verkeer.', 'Nee, de handel stijgt juist.'], uh: 'Globalisering: wereldwijde verwevenheid.' },
      { v: 'Wat is differentiatie in een samenleving?', o: ['de uitsplitsing in gespecialiseerde delen', 'het samensmelten van groepen', 'de afname van beroepen', 'de groei van religie'], c: 0, d: 3, uo: ['Klopt: differentiatie splitst de samenleving in gespecialiseerde onderdelen.', 'Nee, dat is juist het tegenovergestelde.', 'Nee, er komen juist meer beroepen.', 'Nee, dat is niet differentiatie.'], uh: 'Differentiatie: uitsplitsing in gespecialiseerde delen.' },
      { v: 'Wat is sociale verandering?', o: ['de verandering van een samenleving door de tijd', 'een wisseling van regering', 'een economische winst', 'een steekproef'], c: 0, d: 2, uo: ['Klopt: sociale verandering betreft de samenleving over tijd.', 'Nee, dat is één gebeurtenis.', 'Nee, dat is economisch.', 'Nee, dat is onderzoek.'], uh: 'Sociale verandering: de samenleving verandert door de tijd.' },
    ]),
];
