// VWO Aardrijkskunde - gouden-stijl contentspec. Vervangt crude generatorvragen
// door authored inzichtvragen met per-optie-uitleg + situatiebegrippen.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vwo', vak: 'ak', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Vaardigheden',
    `Geografen werken met <strong>kaarten</strong> en <strong>schaal</strong>, geven een <strong>absolute</strong> of <strong>relatieve locatie</strong>, en lezen <strong>hoogtelijnen</strong>. Ze passen <strong>bronkritiek</strong> toe en <strong>redeneren geografisch</strong>: waar speelt iets, en waarom juist daar?`,
    [
      { h: '1. Schaal en kaarten', p: [
        `De <strong>schaal</strong> 1 : 100 000 betekent dat 1 cm op de kaart 1 km in werkelijkheid is. Een <strong>grotere schaal</strong> (bijv. 1 : 10 000) toont minder gebied met meer detail. Een <strong>topografische kaart</strong> toont het landschap, een <strong>thematische kaart</strong> de verdeling van één verschijnsel. Dicht opeen liggende <strong>hoogtelijnen</strong> wijzen op een steile helling.`] },
      { h: '2. Locatie en redeneren', p: [
        `Een <strong>absolute locatie</strong> geef je met coördinaten (lengte- en breedtegraad); een <strong>relatieve locatie</strong> beschrijft de ligging ten opzichte van andere plaatsen. Bij <strong>bronkritiek</strong> let je op betrouwbaarheid en herkomst. <strong>Geografisch redeneren</strong> begint met "waar en waarom daar", en bekijkt een verschijnsel op meerdere <strong>schaalniveaus</strong> (schaalvergelijking).`] },
    ],
    [
      { t: 'Schaal', d: 'de verhouding tussen afstand op de kaart en in werkelijkheid', k: 'kaartafstand : echte afstand', fout: ['Schaalvergelijking'] },
      { t: 'Absolute locatie', d: 'de exacte ligging met lengte- en breedtegraad', k: 'coördinaten', fout: ['Relatieve locatie'] },
      { t: 'Relatieve locatie', d: 'de ligging ten opzichte van andere plaatsen', k: 'ligging t.o.v. andere plaatsen', fout: ['Absolute locatie'] },
      { t: 'Thematische kaart', d: 'een kaart die de verdeling van één verschijnsel toont', k: 'één verschijnsel', fout: ['Topografische kaart'] },
      { t: 'Topografische kaart', d: 'een kaart die het landschap toont: hoogte, wegen en plaatsen', k: 'het landschap', fout: ['Thematische kaart'] },
      { t: 'Bronkritiek', d: 'het beoordelen van de betrouwbaarheid en herkomst van een bron', k: 'betrouwbaarheid en herkomst', fout: ['Geografisch redeneren'] },
      { t: 'Geografisch redeneren', d: 'nadenken over waar iets speelt en waarom juist daar', k: 'waar en waarom daar', fout: ['Bronkritiek'] },
      { t: 'Hoogtelijnen', d: 'lijnen die punten van gelijke hoogte verbinden', k: 'gelijke hoogte', fout: ['Schaal'] },
      { t: 'Schaalvergelijking', d: 'een verschijnsel op meerdere schaalniveaus bekijken', k: 'lokaal tot mondiaal', fout: ['Schaal'] },
      { t: 'Schaalniveau', d: 'het niveau van lokaal tot mondiaal waarop je iets bekijkt', k: 'lokaal tot mondiaal', fout: ['Schaalvergelijking'] },
    ],
    [
      { v: 'Bij een schaal van 1 : 100 000 komt 1 cm op de kaart overeen met...', o: ['1 km', '100 m', '10 km', '100 km'], c: 0, d: 2, uo: ['Klopt: 100 000 cm = 1000 m = 1 km.', 'Nee, dat zou 1 : 10 000 zijn.', 'Nee, dat is tien keer te veel.', 'Nee, dat is honderd keer te veel.'], uh: '1 : 100 000 → 1 cm = 1 km.' },
      { v: 'Een absolute locatie geef je met...', o: ['coördinaten (lengte- en breedtegraad)', 'de ligging naast een rivier', 'de afstand tot de stad', 'een windrichting'], c: 0, d: 2, uo: ['Klopt: absolute locatie is een exact coördinaat.', 'Nee, dat is relatief.', 'Nee, dat is relatief.', 'Nee, dat is relatief.'], uh: 'Absolute locatie: coördinaten.' },
      { v: 'Een thematische kaart laat vooral zien...', o: ['de verdeling van één verschijnsel', 'alle wegen en plaatsen', 'de hoogte van het land', 'de coördinaten'], c: 0, d: 2, uo: ['Klopt: een thematische kaart toont één thema.', 'Nee, dat is topografisch.', 'Nee, dat is een hoogtekaart.', 'Nee, dat is een gradennet.'], uh: 'Thematische kaart: één verschijnsel.' },
      { v: 'Bij bronkritiek let je op...', o: ['de betrouwbaarheid en herkomst', 'de kleur van de kaart', 'de schaal alleen', 'de titel alleen'], c: 0, d: 2, uo: ['Klopt: je beoordeelt hoe betrouwbaar de bron is.', 'Nee, kleur zegt niets over betrouwbaarheid.', 'Nee, schaal is een detail.', 'Nee, de titel is te weinig.'], uh: 'Bronkritiek: betrouwbaarheid en herkomst.' },
      { v: 'Geografisch redeneren begint vaak met de vraag...', o: ['waar en waarom daar', 'hoe laat het is', 'wie het heeft gemaakt', 'hoeveel het kost'], c: 0, d: 2, uo: ['Klopt: locatie en verklaring staan centraal.', 'Nee, tijd is geen geografische startvraag.', 'Nee, dat is bronkritiek.', 'Nee, dat is economie.'], uh: 'Geografisch redeneren: waar en waarom daar.' },
      { v: 'Een grotere schaal (bijvoorbeeld 1 : 10 000) betekent...', o: ['minder gebied, meer detail', 'meer gebied, minder detail', 'geen verschil', 'altijd een wereldkaart'], c: 0, d: 3, uo: ['Klopt: een grotere schaal zoomt in.', 'Nee, dat is een kleinere schaal.', 'Nee, er is wel verschil.', 'Nee, juist een klein gebied.'], uh: 'Grotere schaal: minder gebied, meer detail.' },
      { v: 'Hoogtelijnen die dicht bij elkaar liggen betekenen...', o: ['een steile helling', 'een vlak gebied', 'water', 'een weg'], c: 0, d: 2, uo: ['Klopt: dicht opeen betekent snel hoogteverschil, dus steil.', 'Nee, dan liggen ze juist ver uiteen.', 'Nee, dat toont een andere symboliek.', 'Nee, wegen zijn aparte lijnen.'], uh: 'Hoogtelijnen dicht opeen: steile helling.' },
      { v: 'Een verschijnsel op meerdere schaalniveaus bekijken (lokaal tot mondiaal) heet...', o: ['schaalvergelijking', 'bronkritiek', 'absolute locatie', 'kaartprojectie'], c: 0, d: 3, uo: ['Klopt: je vergelijkt over schaalniveaus.', 'Nee, dat gaat over bronnen.', 'Nee, dat is een coördinaat.', 'Nee, dat is een kaarttechniek.'], uh: 'Schaalvergelijking: lokaal tot mondiaal.' },
      { v: 'Een relatieve locatie beschrijft...', o: ['de ligging ten opzichte van andere plaatsen', 'de exacte coördinaten', 'de hoogte boven zeeniveau', 'de schaal van de kaart'], c: 0, d: 2, uo: ['Klopt: relatief is ten opzichte van iets anders.', 'Nee, dat is absoluut.', 'Nee, dat is hoogte.', 'Nee, dat is schaal.'], uh: 'Relatieve locatie: ligging t.o.v. andere plaatsen.' },
      { v: 'Welke schaal is het kleinschaligst?', o: ['1 : 1 000 000', '1 : 10 000', '1 : 1 000', '1 : 100'], c: 0, d: 3, uo: ['Klopt: hoe groter het getal, hoe kleiner de schaal.', 'Nee, die is grootschaliger.', 'Nee, die is grootschaliger.', 'Nee, die is het grootschaligst.'], uh: 'Groter schaalgetal = kleinere schaal.' },
      { v: 'Wat toont een topografische kaart vooral?', o: ['het landschap: hoogte, wegen en plaatsen', 'de verdeling van één verschijnsel', 'alleen de coördinaten', 'alleen de bevolkingsdichtheid'], c: 0, d: 2, uo: ['Klopt: topografie toont het landschap.', 'Nee, dat is thematisch.', 'Nee, dat is een gradennet.', 'Nee, dat is een thematische kaart.'], uh: 'Topografische kaart: het landschap.' },
    ]),

  V('B', 'Wereld',
    `Op wereldschaal bestudeer je <strong>migratie</strong> (push- en pullfactoren), <strong>bevolkingsgroei</strong> (demografische transitie) en <strong>ontwikkeling</strong> (HDI, Gini). <strong>Globalisering</strong> verweeft economieën via handel, investeringen en <strong>offshoring</strong>, met effecten als <strong>brain drain</strong> en de <strong>resource curse</strong>.`,
    [
      { h: '1. Bevolking en migratie', p: [
        `<strong>Pushfactoren</strong> drijven mensen weg uit hun herkomstgebied; <strong>pullfactoren</strong> trekken hen aan. In de <strong>demografische transitie</strong> is de groei het sterkst in fase 2: de sterfte daalt terwijl de geboortecijfers nog hoog zijn. <strong>Brain drain</strong> is het vertrek van hoogopgeleiden uit een ontwikkelingsland.`] },
      { h: '2. Ontwikkeling en globalisering', p: [
        `De <strong>HDI</strong> combineert levensverwachting, onderwijs en inkomen per hoofd; de <strong>Gini-coëfficiënt</strong> meet inkomensongelijkheid (0 = gelijk, 1 = maximaal ongelijk). <strong>Globalisering</strong> vergroot de mondiale afhankelijkheid; <strong>offshoring</strong> verplaatst productie naar lagelonenlanden. De <strong>resource curse</strong> is dat grondstofrijkdom tot zwak bestuur en onderontwikkeling leidt.`] },
    ],
    [
      { t: 'Pushfactor', d: 'een factor die mensen wegdrijft uit hun herkomstgebied', k: 'drijft weg', fout: ['Pullfactor'] },
      { t: 'Pullfactor', d: 'een factor die mensen naar een gebied toe trekt', k: 'trekt aan', fout: ['Pushfactor'] },
      { t: 'Demografische transitie', d: 'het model van bevolkingsgroei via geboorte- en sterftecijfers', k: 'model van bevolkingsgroei', fout: ['HDI'] },
      { t: 'HDI', d: 'index van levensverwachting, onderwijs en inkomen per hoofd', k: 'welvaart en welzijn', fout: ['Gini-coëfficiënt'] },
      { t: 'Brain drain', d: 'het vertrek van hoogopgeleiden uit een ontwikkelingsland', k: 'hoogopgeleiden vertrekken', fout: ['Offshoring'] },
      { t: 'Globalisering', d: 'de toename van mondiale onderlinge afhankelijkheid', k: 'mondiale afhankelijkheid', fout: ['Offshoring'] },
      { t: 'Offshoring', d: 'het verplaatsen van productie naar lagelonenlanden', k: 'productie naar lage lonen', fout: ['Brain drain'] },
      { t: 'Overurbanisatie', d: 'te snelle stadsgroei waar voorzieningen niet meekomen', k: 'te snelle stadsgroei', fout: ['Globalisering'] },
      { t: 'Race to the bottom', d: 'landen verlagen normen om bedrijven aan te trekken', k: 'normen verlagen', fout: ['Resource curse'] },
      { t: 'Resource curse', d: 'grondstofrijkdom die tot zwak bestuur en onderontwikkeling leidt', k: 'grondstoffenvloek', fout: ['Race to the bottom'] },
    ],
    [
      { v: 'Welke factoren drijven mensen weg uit hun land van herkomst?', o: ['pushfactoren', 'pullfactoren', 'trekfactoren', 'HDI-factoren'], c: 0, d: 2, uo: ['Klopt: pushfactoren duwen mensen weg.', 'Nee, die trekken juist aan.', 'Nee, dat is geen vakterm hiervoor.', 'Nee, dat is een ontwikkelingsindex.'], uh: 'Pushfactoren: drijven weg.' },
      { v: 'In welke fase van de demografische transitie is de groei het sterkst?', o: ['fase 2: sterfte daalt, geboorte nog hoog', 'fase 1: beide hoog', 'fase 4: beide laag', 'fase 5: krimp'], c: 0, d: 3, uo: ['Klopt: in fase 2 daalt de sterfte terwijl de geboorte hoog blijft.', 'Nee, in fase 1 is de groei laag.', 'Nee, in fase 4 is de groei laag.', 'Nee, dan krimpt de bevolking.'], uh: 'Sterkste groei: fase 2.' },
      { v: 'Welke drie dimensies combineert de HDI?', o: ['levensverwachting, onderwijs en inkomen per hoofd', 'geboorte, sterfte en migratie', 'handel, investeringen en export', 'klimaat, reliëf en bodem'], c: 0, d: 3, uo: ['Klopt: de HDI vat gezondheid, kennis en welvaart samen.', 'Nee, dat is demografie.', 'Nee, dat is economie.', 'Nee, dat is fysische geografie.'], uh: 'HDI: levensverwachting, onderwijs, inkomen.' },
      { v: 'Welk begrip beschrijft het bewust verlagen van arbeids- en milieunormen om bedrijven aan te trekken?', o: ['race to the bottom', 'brain drain', 'mitigatie', 'demografische transitie'], c: 0, d: 3, uo: ['Klopt: landen onderbieden elkaar in normen.', 'Nee, dat is het vertrek van talent.', 'Nee, dat is klimaatbeleid.', 'Nee, dat is bevolkingsgroei.'], uh: 'Race to the bottom: normen verlagen om bedrijven te lokken.' },
      { v: 'Welk begrip beschrijft te snelle stadsgroei waar voorzieningen niet meekomen?', o: ['overurbanisatie', 'globalisering', 'suburbanisatie', 'mitigatie'], c: 0, d: 3, uo: ['Klopt: de stad groeit sneller dan werk en voorzieningen.', 'Nee, dat is mondiale verwevenheid.', 'Nee, dat is de trek naar de rand.', 'Nee, dat is klimaatbeleid.'], uh: 'Overurbanisatie: te snelle stadsgroei.' },
      { v: 'Hoogopgeleiden verlaten een ontwikkelingsland voor betere kansen elders. Dit heet...', o: ['brain drain', 'offshoring', 'pushmigratie', 'resource curse'], c: 0, d: 2, uo: ['Klopt: het land verliest zijn talent.', 'Nee, dat gaat over productie verplaatsen.', 'Nee, dat is een migratiefactor, geen naam.', 'Nee, dat gaat over grondstoffen.'], uh: 'Brain drain: talent vertrekt.' },
      { v: 'Welke theorie stelt dat landen zich specialiseren waar ze een relatief kostenvoordeel hebben?', o: ['comparatief voordeel (Ricardo)', 'demografische transitie', 'resource curse', 'race to the bottom'], c: 0, d: 3, uo: ['Klopt: het comparatief voordeel stuurt specialisatie.', 'Nee, dat gaat over bevolking.', 'Nee, dat gaat over grondstoffen.', 'Nee, dat gaat over normen.'], uh: 'Comparatief voordeel: specialiseren waar je relatief het sterkst bent.' },
      { v: 'Welk begrip beschrijft de toename van mondiale afhankelijkheid door handel, migratie en digitale communicatie?', o: ['globalisering', 'overurbanisatie', 'mitigatie', 'subductie'], c: 0, d: 2, uo: ['Klopt: globalisering verweeft de wereld.', 'Nee, dat gaat over steden.', 'Nee, dat is klimaatbeleid.', 'Nee, dat is een aardproces.'], uh: 'Globalisering: mondiale verwevenheid.' },
      { v: 'Wat meet de Gini-coëfficiënt?', o: ['inkomensongelijkheid (0 = gelijk, 1 = maximaal ongelijk)', 'de bevolkingsgroei', 'de levensverwachting', 'de handelsbalans'], c: 0, d: 3, uo: ['Klopt: de Gini meet inkomensongelijkheid.', 'Nee, dat is demografie.', 'Nee, dat zit in de HDI.', 'Nee, dat is economie.'], uh: 'Gini: inkomensongelijkheid, dichter bij 1 = ongelijker.' },
      { v: 'Het verplaatsen van productie naar lagelonenlanden heet...', o: ['offshoring', 'brain drain', 'mitigatie', 'suburbanisatie'], c: 0, d: 2, uo: ['Klopt: offshoring verplaatst productie.', 'Nee, dat gaat over talent.', 'Nee, dat is klimaatbeleid.', 'Nee, dat is stedelijke spreiding.'], uh: 'Offshoring: productie naar lage lonen.' },
      { v: 'Wat is de resource curse (grondstoffenvloek)?', o: ['grondstofrijkdom leidt tot zwak bestuur, corruptie en onderontwikkeling', 'grondstofrijkdom leidt altijd tot welvaart', 'een tekort aan grondstoffen', 'een klimaatprobleem'], c: 0, d: 3, uo: ['Klopt: rijkdom aan grondstoffen kan bestuur en ontwikkeling ondermijnen.', 'Nee, juist het tegenovergestelde vaak.', 'Nee, het gaat om rijkdom, niet tekort.', 'Nee, het is een bestuurlijk-economisch probleem.'], uh: 'Resource curse: rijkdom → zwak bestuur en onderontwikkeling.' },
      { v: 'Welke factoren trekken mensen juist naar een gebied toe?', o: ['pullfactoren', 'pushfactoren', 'resource curse', 'mitigatiefactoren'], c: 0, d: 2, uo: ['Klopt: pullfactoren trekken aan.', 'Nee, die drijven weg.', 'Nee, dat is de grondstoffenvloek.', 'Nee, dat is klimaatbeleid.'], uh: 'Pullfactoren: trekken aan.' },
      { v: 'Mensen worden door droogte en klimaatverandering gedwongen te migreren. Dit heet...', o: ['klimaatvluchteling', 'brain drain', 'offshoring', 'suburbanisatie'], c: 0, d: 2, uo: ['Klopt: klimaat dwingt tot migratie.', 'Nee, dat gaat over talent.', 'Nee, dat gaat over productie.', 'Nee, dat is stedelijke spreiding.'], uh: 'Klimaatvluchteling: gedwongen migratie door klimaat.' },
    ]),

  V('C', 'Aarde',
    `Het aardsysteem kent processen als het <strong>versterkt broeikaseffect</strong>, <strong>platentektoniek</strong> met <strong>subductie</strong>, en de <strong>koolstofkringloop</strong>. Klimaatbeleid onderscheidt <strong>mitigatie</strong> (oorzaak aanpakken) van <strong>adaptatie</strong> (gevolgen opvangen); bij een <strong>kantelpunt</strong> verandert een systeem onomkeerbaar.`,
    [
      { h: '1. Klimaat en kringlopen', p: [
        `Het <strong>versterkt broeikaseffect</strong> is de extra opwarming door menselijke uitstoot bovenop het natuurlijke effect. De <strong>koolstofkringloop</strong> wisselt koolstof uit via fotosynthese, ademhaling, verbranding en verwering. Een <strong>mediterraan klimaat</strong> heeft droge, hete zomers en milde, natte winters. Het <strong>altitudinaal effect</strong> is de invloed van hoogte op het klimaat.`] },
      { h: '2. Aardprocessen en beleid', p: [
        `Bij <strong>platentektoniek</strong> bewegen platen; bij een convergente rand duikt een oceaanplaat onder een continentale plaat (<strong>subductie</strong>). <strong>Verwering</strong> breekt gesteente af aan het oppervlak. <strong>Mitigatie</strong> pakt de oorzaak aan (minder uitstoot), <strong>adaptatie</strong> vangt de gevolgen op. Een <strong>kantelpunt</strong> is de grens waarna een ecosysteem onomkeerbaar verandert.`] },
    ],
    [
      { t: 'Versterkt broeikaseffect', d: 'extra opwarming door menselijke uitstoot bovenop het natuurlijke effect', k: 'extra opwarming door de mens', fout: ['Mitigatie'] },
      { t: 'Subductie', d: 'het wegduiken van een oceaanplaat onder een continentale plaat', k: 'plaat duikt onder', fout: ['Platentektoniek'] },
      { t: 'Koolstofkringloop', d: 'de uitwisseling van koolstof via fotosynthese, ademhaling en verbranding', k: 'kringloop van koolstof', fout: ['Versterkt broeikaseffect'] },
      { t: 'Mitigatie', d: 'de oorzaak aanpakken door de uitstoot te verminderen', k: 'oorzaak aanpakken', fout: ['Adaptatie'] },
      { t: 'Adaptatie', d: 'je aanpassen aan de gevolgen van klimaatverandering', k: 'gevolgen opvangen', fout: ['Mitigatie'] },
      { t: 'Kantelpunt', d: 'de grens waarna een ecosysteem onomkeerbaar verandert', k: 'onomkeerbare verandering', fout: ['Koolstofkringloop'] },
      { t: 'Platentektoniek', d: 'de beweging van de aardplaten', k: 'beweging van de platen', fout: ['Subductie'] },
      { t: 'Mediterraan klimaat', d: 'een klimaat met droge hete zomers en milde natte winters', k: 'droge zomer, natte winter', fout: ['Altitudinaal effect'] },
      { t: 'Altitudinaal effect', d: 'de invloed van de hoogte boven zeeniveau op het klimaat', k: 'hoogte bepaalt klimaat', fout: ['Mediterraan klimaat'] },
      { t: 'Verwering', d: 'de afbraak van gesteente aan het aardoppervlak', k: 'afbraak van gesteente', fout: ['Subductie'] },
    ],
    [
      { v: 'Welk begrip beschrijft de extra opwarming door menselijke uitstoot bovenop het natuurlijke broeikaseffect?', o: ['versterkt broeikaseffect', 'natuurlijk broeikaseffect', 'mitigatie', 'subductie'], c: 0, d: 3, uo: ['Klopt: de mens versterkt het effect.', 'Nee, dat is het effect zonder de mens.', 'Nee, dat is beleid.', 'Nee, dat is een aardproces.'], uh: 'Versterkt broeikaseffect: extra opwarming door de mens.' },
      { v: 'Wat gebeurt er bij een convergente plaatrand waar een oceaanplaat onder een continentale plaat duikt?', o: ['subductie', 'verwering', 'sedimentatie', 'mitigatie'], c: 0, d: 3, uo: ['Klopt: het wegduiken heet subductie.', 'Nee, dat is afbraak van gesteente.', 'Nee, dat is afzetting.', 'Nee, dat is klimaatbeleid.'], uh: 'Subductie: plaat duikt onder een andere.' },
      { v: 'Welk klimaattype kenmerkt de mediterrane zone?', o: ['droge hete zomers en milde natte winters', 'natte zomers en droge winters', 'het hele jaar nat', 'het hele jaar droog'], c: 0, d: 3, uo: ['Klopt: dat is het mediterrane patroon.', 'Nee, dat is een moesson.', 'Nee, dat is tropisch regenwoud.', 'Nee, dat is woestijn.'], uh: 'Mediterraan: droge zomer, natte winter.' },
      { v: 'Welke kringloop beschrijft de uitwisseling van koolstof via fotosynthese, ademhaling en verbranding?', o: ['de koolstofkringloop', 'de waterkringloop', 'de stikstofkringloop', 'de gesteentekringloop'], c: 0, d: 3, uo: ['Klopt: dat is de koolstofkringloop.', 'Nee, die gaat over water.', 'Nee, die gaat over stikstof.', 'Nee, die gaat over gesteente.'], uh: 'Koolstofkringloop: fotosynthese, ademhaling, verbranding.' },
      { v: 'Welk klimaatbeleidsbegrip pakt de oorzaak aan door uitstoot te verminderen?', o: ['mitigatie', 'adaptatie', 'subductie', 'verwering'], c: 0, d: 3, uo: ['Klopt: mitigatie vermindert de uitstoot.', 'Nee, dat vangt de gevolgen op.', 'Nee, dat is een aardproces.', 'Nee, dat is afbraak van gesteente.'], uh: 'Mitigatie: oorzaak aanpakken.' },
      { v: 'Welke term beschrijft de grens waarna een ecosysteem onomkeerbaar verandert?', o: ['kantelpunt', 'evenwicht', 'mitigatie', 'schaalniveau'], c: 0, d: 3, uo: ['Klopt: voorbij het kantelpunt is er geen weg terug.', 'Nee, dat is juist stabiel.', 'Nee, dat is beleid.', 'Nee, dat is een kaartbegrip.'], uh: 'Kantelpunt: onomkeerbare verandering.' },
      { v: 'Welk begrip beschrijft de hoogte boven zeeniveau als klimaatbepalende factor?', o: ['altitudinaal effect', 'mediterraan klimaat', 'subductie', 'mitigatie'], c: 0, d: 3, uo: ['Klopt: hoger betekent kouder, het altitudinaal effect.', 'Nee, dat is een klimaattype.', 'Nee, dat is een aardproces.', 'Nee, dat is beleid.'], uh: 'Altitudinaal effect: hoogte bepaalt klimaat.' },
      { v: 'Wat is adaptatie in het klimaatbeleid?', o: ['je aanpassen aan de gevolgen van klimaatverandering', 'de uitstoot verminderen', 'de oorzaak wegnemen', 'gesteente afbreken'], c: 0, d: 2, uo: ['Klopt: adaptatie vangt de gevolgen op.', 'Nee, dat is mitigatie.', 'Nee, dat is mitigatie.', 'Nee, dat is verwering.'], uh: 'Adaptatie: gevolgen opvangen.' },
      { v: 'Wat is platentektoniek?', o: ['de beweging van de aardplaten', 'de opwarming van de aarde', 'de kringloop van water', 'de afbraak van gesteente'], c: 0, d: 2, uo: ['Klopt: platentektoniek is de beweging van de platen.', 'Nee, dat is het broeikaseffect.', 'Nee, dat is de waterkringloop.', 'Nee, dat is verwering.'], uh: 'Platentektoniek: beweging van de platen.' },
      { v: 'Wat is verwering?', o: ['de afbraak van gesteente aan het oppervlak', 'het wegduiken van een plaat', 'de opwarming van de aarde', 'de afzetting van sediment'], c: 0, d: 2, uo: ['Klopt: verwering breekt gesteente af.', 'Nee, dat is subductie.', 'Nee, dat is het broeikaseffect.', 'Nee, dat is sedimentatie.'], uh: 'Verwering: afbraak van gesteente.' },
      { v: 'Wat is het verschil tussen mitigatie en adaptatie?', o: ['mitigatie pakt de oorzaak aan, adaptatie vangt de gevolgen op', 'ze zijn hetzelfde', 'mitigatie vangt de gevolgen op', 'adaptatie vermindert de uitstoot'], c: 0, d: 3, uo: ['Klopt: oorzaak versus gevolg.', 'Nee, ze verschillen.', 'Nee, dat is omgedraaid.', 'Nee, dat is omgedraaid.'], uh: 'Mitigatie: oorzaak; adaptatie: gevolg.' },
    ]),

  V('D', 'Gebied (ontwikkelingsregio)',
    `Een <strong>gebiedsanalyse</strong> bekijkt een regio vanuit twee lagen: de <strong>fysische geografie</strong> (natuurlijke omgeving) en de <strong>sociale geografie</strong> (de mens in de ruimte). Zo begrijp je een <strong>ontwikkelingsregio</strong> vanuit klimaat en reliëf én vanuit bevolking en economie.`,
    [
      { h: '1. Twee lagen', p: [
        `Een <strong>gebiedsanalyse</strong> combineert de <strong>fysische geografie</strong> (klimaat, reliëf, bodem, water) met de <strong>sociale geografie</strong> (bevolking, economie, cultuur). Samen verklaren ze hoe een gebied functioneert.`] },
      { h: '2. Ruimte en regio', p: [
        `Een <strong>regio</strong> is een gebied met gemeenschappelijke kenmerken. De <strong>ruimtelijke spreiding</strong> beschrijft hoe een verschijnsel over een gebied verdeeld is. Een <strong>ontwikkelingsregio</strong> kent vaak een lager inkomen en minder voorzieningen.`] },
    ],
    [
      { t: 'Fysische geografie', d: 'de studie van de natuurlijke omgeving: klimaat, reliëf en bodem', k: 'natuurlijke omgeving', fout: ['Sociale geografie'] },
      { t: 'Sociale geografie', d: 'de studie van de mens in de ruimte: bevolking en economie', k: 'de mens in de ruimte', fout: ['Fysische geografie'] },
      { t: 'Gebiedsanalyse', d: 'een gebied bekijken via de fysische en de sociale laag', k: 'twee lagen samen', fout: ['Regio'] },
      { t: 'Klimaat', d: 'het gemiddelde weer over lange tijd, een fysisch kenmerk', k: 'gemiddeld weer', fout: ['Reliëf'] },
      { t: 'Reliëf', d: 'de hoogteverschillen in een gebied, een fysisch kenmerk', k: 'hoogteverschillen', fout: ['Klimaat'] },
      { t: 'Bevolking', d: 'de mensen in een gebied, een sociaal-geografisch kenmerk', k: 'de mensen', fout: ['Economie'] },
      { t: 'Economie', d: 'de productie en handel in een gebied, een sociaal-geografisch kenmerk', k: 'productie en handel', fout: ['Bevolking'] },
      { t: 'Ontwikkelingsregio', d: 'een gebied met vaak een lager inkomen en minder voorzieningen', k: 'lager inkomen, minder voorzieningen', fout: ['Regio'] },
      { t: 'Ruimtelijke spreiding', d: 'hoe een verschijnsel over een gebied verdeeld is', k: 'verdeling over een gebied', fout: ['Gebiedsanalyse'] },
      { t: 'Regio', d: 'een gebied met gemeenschappelijke kenmerken', k: 'gebied met gemeenschappelijke kenmerken', fout: ['Ontwikkelingsregio'] },
    ],
    [
      { v: 'Uit welke twee lagen bestaat een geografische gebiedsanalyse?', o: ['fysische en sociale geografie', 'lokale en mondiale geografie', 'klimaat en bodem', 'bevolking en economie'], c: 0, d: 2, uo: ['Klopt: de fysische en de sociale laag samen.', 'Nee, dat zijn schaalniveaus.', 'Nee, dat is alleen fysisch.', 'Nee, dat is alleen sociaal.'], uh: 'Gebiedsanalyse: fysische + sociale geografie.' },
      { v: 'Welke van deze hoort bij de fysische geografie?', o: ['klimaat en reliëf', 'bevolking en economie', 'cultuur en politiek', 'handel en migratie'], c: 0, d: 2, uo: ['Klopt: klimaat en reliëf zijn natuurlijk.', 'Nee, dat is sociaal.', 'Nee, dat is sociaal.', 'Nee, dat is sociaal-economisch.'], uh: 'Fysisch: klimaat, reliëf, bodem.' },
      { v: 'Welk aspect hoort bij de sociale geografie?', o: ['bevolking en economie', 'klimaat en reliëf', 'bodem en water', 'gesteente en verwering'], c: 0, d: 2, uo: ['Klopt: bevolking en economie zijn sociaal.', 'Nee, dat is fysisch.', 'Nee, dat is fysisch.', 'Nee, dat is fysisch.'], uh: 'Sociaal: bevolking, economie, cultuur.' },
      { v: 'Wat is een gebiedsanalyse?', o: ['een gebied bekijken via de fysische en de sociale laag', 'alleen de hoogtekaart bestuderen', 'alleen de bevolking tellen', 'de coördinaten opzoeken'], c: 0, d: 2, uo: ['Klopt: je combineert beide lagen.', 'Nee, dat is maar één laag.', 'Nee, dat is maar één laag.', 'Nee, dat is een locatiebepaling.'], uh: 'Gebiedsanalyse: fysisch én sociaal.' },
      { v: 'Wat betekent reliëf?', o: ['de hoogteverschillen in een gebied', 'het gemiddelde weer', 'de bevolkingsdichtheid', 'de economie'], c: 0, d: 2, uo: ['Klopt: reliëf zijn de hoogteverschillen.', 'Nee, dat is klimaat.', 'Nee, dat is sociaal.', 'Nee, dat is sociaal.'], uh: 'Reliëf: hoogteverschillen.' },
      { v: 'Wat is een regio?', o: ['een gebied met gemeenschappelijke kenmerken', 'een exact coördinaat', 'een enkele stad', 'een kaartschaal'], c: 0, d: 2, uo: ['Klopt: een regio deelt bepaalde kenmerken.', 'Nee, dat is een locatie.', 'Nee, een regio is groter dan één stad.', 'Nee, dat is schaal.'], uh: 'Regio: gebied met gemeenschappelijke kenmerken.' },
      { v: 'Wat kenmerkt een ontwikkelingsregio vaak?', o: ['een lager inkomen en minder voorzieningen', 'een hoog inkomen en veel voorzieningen', 'een koud klimaat', 'veel hoogteverschil'], c: 0, d: 2, uo: ['Klopt: ontwikkelingsregio\'s hebben vaak minder welvaart en voorzieningen.', 'Nee, dat past bij een rijk gebied.', 'Nee, dat is een fysisch kenmerk.', 'Nee, dat is fysisch.'], uh: 'Ontwikkelingsregio: lager inkomen, minder voorzieningen.' },
      { v: 'Wat beschrijft de ruimtelijke spreiding?', o: ['hoe een verschijnsel over een gebied verdeeld is', 'de hoogte van het land', 'het gemiddelde weer', 'de coördinaten'], c: 0, d: 3, uo: ['Klopt: het gaat om de verdeling over de ruimte.', 'Nee, dat is reliëf.', 'Nee, dat is klimaat.', 'Nee, dat is locatie.'], uh: 'Ruimtelijke spreiding: verdeling over een gebied.' },
      { v: 'Wat bestudeert de fysische geografie?', o: ['de natuurlijke omgeving', 'de mens in de ruimte', 'de economie', 'de cultuur'], c: 0, d: 2, uo: ['Klopt: fysische geografie gaat over de natuur.', 'Nee, dat is sociaal.', 'Nee, dat is sociaal.', 'Nee, dat is sociaal.'], uh: 'Fysische geografie: de natuurlijke omgeving.' },
      { v: 'Wat bestudeert de sociale geografie?', o: ['de mens in de ruimte', 'het klimaat', 'het reliëf', 'de bodem'], c: 0, d: 2, uo: ['Klopt: sociale geografie gaat over de mens.', 'Nee, dat is fysisch.', 'Nee, dat is fysisch.', 'Nee, dat is fysisch.'], uh: 'Sociale geografie: de mens in de ruimte.' },
      { v: 'Bij welke laag hoort het reliëf van een gebied?', o: ['de fysische geografie', 'de sociale geografie', 'de economische laag', 'de culturele laag'], c: 0, d: 3, uo: ['Klopt: reliëf is een natuurlijk, fysisch kenmerk.', 'Nee, dat is de menselijke laag.', 'Nee, dat is sociaal.', 'Nee, dat is sociaal.'], uh: 'Reliëf hoort bij de fysische geografie.' },
    ]),

  V('E', 'Leefomgeving (Nederland)',
    `Nederland is een <strong>deltaland</strong>: ongeveer een kwart ligt onder <strong>NAP</strong>. Via <strong>waterbeheer</strong>, <strong>dijken</strong> en <strong>ruimtelijke ordening</strong> beheersen we het <strong>overstromingsrisico</strong> (kans maal gevolg). Door <strong>zeespiegelstijging</strong> en <strong>bodemdaling</strong> is <strong>klimaatadaptatie</strong> nodig.`,
    [
      { h: '1. Water en risico', p: [
        `Ongeveer een kwart van Nederland ligt onder <strong>NAP</strong> (het referentiepeil). Het <strong>overstromingsrisico</strong> is de <strong>kans</strong> maal de <strong>gevolgen</strong>. Je verlaagt het risico door de kans te verkleinen (sterkere <strong>dijken</strong>) én de gevolgen te beperken (evacuatieplannen).`] },
      { h: '2. Ruimte en klimaat', p: [
        `Via <strong>ruimtelijke ordening</strong> deelt de overheid de schaarse ruimte in, met de dichtbevolkte <strong>Randstad</strong> in het westen. <strong>Zeespiegelstijging</strong> en <strong>bodemdaling</strong> (vooral in veengebieden) vergroten de druk, waardoor <strong>klimaatadaptatie</strong> tegen hitte en wateroverlast nodig is.`] },
    ],
    [
      { t: 'NAP', d: 'het referentiepeil voor hoogte in Nederland', k: 'referentiepeil hoogte', fout: ['Zeespiegelstijging'] },
      { t: 'Overstromingsrisico', d: 'de kans op overstroming maal de gevolgen ervan', k: 'kans maal gevolg', fout: ['Waterbeheer'] },
      { t: 'Waterbeheer', d: 'het beschermen tegen water en het regelen van het waterpeil', k: 'water beheersen', fout: ['Ruimtelijke ordening'] },
      { t: 'Ruimtelijke ordening', d: 'het indelen van de schaarse ruimte door de overheid', k: 'de ruimte indelen', fout: ['Waterbeheer'] },
      { t: 'Randstad', d: 'het dichtbevolkte, verstedelijkte westen van Nederland', k: 'verstedelijkt westen', fout: ['Ruimtelijke ordening'] },
      { t: 'Bodemdaling', d: 'het zakken van de grond, vooral in veengebieden', k: 'grond zakt', fout: ['Zeespiegelstijging'] },
      { t: 'Zeespiegelstijging', d: 'het stijgen van de zeespiegel dat laaggelegen gebieden bedreigt', k: 'zee stijgt', fout: ['Bodemdaling'] },
      { t: 'Dijk', d: 'een waterkering die het land tegen water beschermt', k: 'houdt water tegen', fout: ['NAP'] },
      { t: 'Klimaatadaptatie', d: 'het aanpassen van de leefomgeving aan hitte en wateroverlast', k: 'aanpassen aan klimaat', fout: ['Waterbeheer'] },
      { t: 'Verstedelijking', d: 'de groei van steden en het aandeel stadsbewoners', k: 'groei van steden', fout: ['Randstad'] },
    ],
    [
      { v: 'Ongeveer welk deel van Nederland ligt onder NAP?', o: ['ongeveer een kwart', 'ongeveer de helft', 'bijna het hele land', 'vrijwel niets'], c: 0, d: 2, uo: ['Klopt: ongeveer een kwart ligt onder NAP.', 'Nee, dat is te veel.', 'Nee, dat is te veel.', 'Nee, dat is te weinig.'], uh: 'Ongeveer een kwart van NL ligt onder NAP.' },
      { v: 'Hoe verlaag je naast een kleinere kans ook het overstromingsrisico?', o: ['door de gevolgen te beperken, bijvoorbeeld met evacuatieplannen', 'door alleen hogere dijken te bouwen', 'door niets te doen', 'door de zeespiegel te meten'], c: 0, d: 3, uo: ['Klopt: risico = kans maal gevolg, dus ook de gevolgen aanpakken.', 'Nee, dat verlaagt alleen de kans.', 'Nee, dan blijft het risico gelijk.', 'Nee, meten verlaagt geen risico.'], uh: 'Risico = kans × gevolg; pak beide aan.' },
      { v: 'Wat is NAP?', o: ['het referentiepeil voor hoogte in Nederland', 'de hoogste dijk van Nederland', 'de gemiddelde zeespiegel wereldwijd', 'een waterschap'], c: 0, d: 2, uo: ['Klopt: NAP is het referentiepeil.', 'Nee, dat is geen dijk.', 'Nee, het is een Nederlands referentiepeil.', 'Nee, dat is een organisatie.'], uh: 'NAP: het referentiepeil voor hoogte.' },
      { v: 'Hoe bereken je het overstromingsrisico?', o: ['kans maal gevolg', 'kans plus gevolg', 'alleen de kans', 'alleen het gevolg'], c: 0, d: 3, uo: ['Klopt: risico is kans maal gevolg.', 'Nee, het is een product, geen som.', 'Nee, ook de gevolgen tellen mee.', 'Nee, ook de kans telt mee.'], uh: 'Overstromingsrisico = kans × gevolg.' },
      { v: 'Wat houdt waterbeheer in Nederland in?', o: ['beschermen tegen water en het waterpeil regelen', 'alleen drinkwater maken', 'de zeespiegel verhogen', 'de ruimte indelen'], c: 0, d: 2, uo: ['Klopt: waterbeheer beschermt en regelt het peil.', 'Nee, dat is maar een deel.', 'Nee, dat is niet het doel.', 'Nee, dat is ruimtelijke ordening.'], uh: 'Waterbeheer: beschermen en peil regelen.' },
      { v: 'Wat is de Randstad?', o: ['het dichtbevolkte, verstedelijkte westen van Nederland', 'de rand van een dijk', 'het noorden van Nederland', 'een natuurgebied'], c: 0, d: 2, uo: ['Klopt: de Randstad is het verstedelijkte westen.', 'Nee, dat is iets anders.', 'Nee, de Randstad ligt in het westen.', 'Nee, het is juist stedelijk.'], uh: 'Randstad: verstedelijkt westen van NL.' },
      { v: 'Wat gebeurt er bij bodemdaling in veengebieden?', o: ['de grond zakt langzaam weg', 'de grond komt omhoog', 'het klimaat verandert', 'de zeespiegel daalt'], c: 0, d: 3, uo: ['Klopt: veen klinkt in en de bodem zakt.', 'Nee, de grond zakt juist.', 'Nee, dat is iets anders.', 'Nee, de zee stijgt juist.'], uh: 'Bodemdaling: de grond zakt.' },
      { v: 'Wat is ruimtelijke ordening?', o: ['het indelen van de schaarse ruimte door de overheid', 'het bouwen van dijken', 'het meten van hoogte', 'het beheren van water'], c: 0, d: 2, uo: ['Klopt: ruimtelijke ordening verdeelt de ruimte.', 'Nee, dat is waterbeheer.', 'Nee, dat is met NAP.', 'Nee, dat is waterbeheer.'], uh: 'Ruimtelijke ordening: de ruimte indelen.' },
      { v: 'Wat is klimaatadaptatie in Nederland?', o: ['de leefomgeving aanpassen aan hitte en wateroverlast', 'de uitstoot van CO₂ verminderen', 'de zeespiegel verlagen', 'de bevolking tellen'], c: 0, d: 2, uo: ['Klopt: adaptatie past de omgeving aan de gevolgen aan.', 'Nee, dat is mitigatie.', 'Nee, dat kunnen we niet.', 'Nee, dat is demografie.'], uh: 'Klimaatadaptatie: aanpassen aan hitte en water.' },
      { v: 'Wat bedreigt zeespiegelstijging vooral?', o: ['laaggelegen gebieden', 'de hoge Alpen', 'de woestijn', 'de bergen'], c: 0, d: 2, uo: ['Klopt: laaggelegen land loopt het meeste risico.', 'Nee, die liggen juist hoog.', 'Nee, die ligt niet aan zee.', 'Nee, die liggen hoog.'], uh: 'Zeespiegelstijging bedreigt laaggelegen gebieden.' },
      { v: 'Waar dient een dijk voor?', o: ['om water tegen te houden', 'om de ruimte in te delen', 'om hoogte te meten', 'om steden te laten groeien'], c: 0, d: 1, uo: ['Klopt: een dijk is een waterkering.', 'Nee, dat is ruimtelijke ordening.', 'Nee, dat doet NAP.', 'Nee, dat is verstedelijking.'], uh: 'Dijk: houdt water tegen.' },
    ]),
];
