// VWO Nederlands - gouden-stijl contentspec. Vervangt crude generatorvragen
// door authored inzichtvragen met per-optie-uitleg + situatiebegrippen.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vwo', vak: 'nl', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Leesvaardigheid',
    `Bij leesvaardigheid herken je het <strong>tekstdoel</strong> (informeren, overtuigen, beschouwen) en de <strong>tekstrelaties</strong> tussen zinnen, zoals oorzaak-gevolg en doel-middel. Je let op <strong>verwijzingen</strong>, <strong>presupposities</strong> en het verschil tussen <strong>denotatie</strong> en <strong>connotatie</strong>.`,
    [
      { h: '1. Tekstdoelen en tekstsoorten', p: [
        `Een <strong>betogende</strong> tekst wil de lezer van één standpunt overtuigen; een <strong>beschouwende</strong> tekst biedt een kwestie ter overweging zonder één standpunt op te leggen; een <strong>uiteenzettende</strong> tekst informeert. Het herken je aan de aanwezigheid van een expliciet standpunt en argumenten.`] },
      { h: '2. Tekstrelaties en betekenis', p: [
        `Veelvoorkomende <strong>tekstrelaties</strong>: <strong>oorzaak-gevolg</strong> ("doordat … smolt het ijs"), <strong>doel-middel</strong>, <strong>algemene uitspraak-toelichting</strong> en de <strong>verwijzingsrelatie</strong> (een voornaamwoord verwijst terug). Een <strong>presuppositie</strong> is kennis die de tekst veronderstelt. <strong>Denotatief</strong> is de letterlijke betekenis, <strong>connotatief</strong> de gevoelswaarde.`] },
    ],
    [
      { t: 'Betogende tekst', d: 'een tekst die de lezer van één standpunt wil overtuigen', k: 'wil overtuigen', fout: ['Beschouwende tekst'] },
      { t: 'Beschouwende tekst', d: 'een tekst die een kwestie ter overweging biedt zonder één standpunt op te leggen', k: 'kwestie ter overweging', fout: ['Betogende tekst'] },
      { t: 'Uiteenzettende tekst', d: 'een tekst die vooral informeert en uitlegt', k: 'informeert', fout: ['Betogende tekst'] },
      { t: 'Oorzaak-gevolgrelatie', d: 'een relatie waarin het ene het andere veroorzaakt', k: 'het een veroorzaakt het ander', fout: ['Doel-middelrelatie'] },
      { t: 'Doel-middelrelatie', d: 'een relatie waarin een middel dient om een doel te bereiken', k: 'middel om een doel te bereiken', fout: ['Oorzaak-gevolgrelatie'] },
      { t: 'Verwijzingsrelatie', d: 'een relatie waarin een woord terugverwijst naar iets eerders', k: 'terugverwijzen', fout: ['Presuppositie'] },
      { t: 'Presuppositie', d: 'kennis die de tekst veronderstelt zonder die te benoemen', k: 'veronderstelde kennis', fout: ['Verwijzingsrelatie'] },
      { t: 'Denotatie', d: 'de letterlijke, neutrale betekenis van een woord', k: 'letterlijke betekenis', fout: ['Connotatie'] },
      { t: 'Connotatie', d: 'de bijbetekenis met gevoelswaarde van een woord', k: 'gevoelswaarde', fout: ['Denotatie'] },
      { t: 'Algemene uitspraak-toelichting', d: 'een relatie waarin een zin een algemene uitspraak concretiseert', k: 'algemeen dan concreet', fout: ['Oorzaak-gevolgrelatie'] },
    ],
    [
      { v: 'Wat is het kenmerkende doel van een betogende tekst?', o: ['de lezer van een standpunt overtuigen', 'de lezer neutraal informeren', 'de lezer laten meedenken zonder standpunt', 'de lezer amuseren'], c: 0, d: 2, uo: ['Klopt: een betoog wil overtuigen van één standpunt.', 'Nee, dat is een uiteenzetting.', 'Nee, dat is een beschouwing.', 'Nee, dat is een amuserende tekst.'], uh: 'Betoog: de lezer overtuigen.' },
      { v: 'Welke relatie zit in "Doordat de temperatuur steeg, smolt het ijs snel"?', o: ['oorzaak-gevolgrelatie', 'doel-middelrelatie', 'tegenstelling', 'opsomming'], c: 0, d: 2, uo: ['Klopt: de stijging is de oorzaak, het smelten het gevolg.', 'Nee, er is geen middel om een doel te bereiken.', 'Nee, er wordt niets tegenover elkaar gezet.', 'Nee, er wordt niets opgesomd.'], uh: '"Doordat" markeert een oorzaak-gevolgrelatie.' },
      { v: 'De ene zin is een algemene uitspraak, de volgende concretiseert die. Welke relatie?', o: ['algemene uitspraak-toelichting', 'oorzaak-gevolg', 'tegenstelling', 'verwijzing'], c: 0, d: 3, uo: ['Klopt: de tweede zin licht de algemene uitspraak toe.', 'Nee, er is geen oorzaak.', 'Nee, er is geen contrast.', 'Nee, er wordt niet terugverwezen.'], uh: 'Algemeen dan concreet: uitspraak-toelichting.' },
      { v: 'Een tekst veronderstelt kennis bij de lezer zonder die te benoemen. Wat is dat?', o: ['een presuppositie', 'een connotatie', 'een verwijzing', 'een argument'], c: 0, d: 3, uo: ['Klopt: veronderstelde, onbenoemde kennis is een presuppositie.', 'Nee, dat is gevoelswaarde van een woord.', 'Nee, dat verwijst naar iets eerders.', 'Nee, dat onderbouwt een standpunt.'], uh: 'Presuppositie: veronderstelde kennis.' },
      { v: 'Wat is het verschil tussen denotatieve en connotatieve betekenis?', o: ['denotatief is letterlijk, connotatief is de gevoelswaarde', 'ze zijn hetzelfde', 'denotatief is de gevoelswaarde', 'connotatief is de letterlijke betekenis'], c: 0, d: 3, uo: ['Klopt: denotatie is neutraal-letterlijk, connotatie draagt gevoel.', 'Nee, ze verschillen.', 'Nee, dat is precies omgedraaid.', 'Nee, dat is precies omgedraaid.'], uh: 'Denotatie: letterlijk; connotatie: gevoelswaarde.' },
      { v: 'Een zin verwijst met een voornaamwoord naar een eerder genoemde persoon. Welke relatie?', o: ['verwijzingsrelatie', 'oorzaak-gevolg', 'doel-middel', 'tegenstelling'], c: 0, d: 2, uo: ['Klopt: een voornaamwoord dat terugwijst geeft een verwijzingsrelatie.', 'Nee, er is geen oorzaak.', 'Nee, er is geen middel.', 'Nee, er is geen contrast.'], uh: 'Voornaamwoord terug: verwijzingsrelatie.' },
      { v: 'Wat zijn de kenmerken van een betogend tekstfragment?', o: ['een expliciet standpunt, argumenten en het doel om te overtuigen', 'alleen neutrale feiten', 'een terugblik in de tijd', 'een opsomming zonder mening'], c: 0, d: 2, uo: ['Klopt: standpunt plus argumenten met overtuigingsdoel.', 'Nee, dat is een uiteenzetting.', 'Nee, dat is een verteltechniek.', 'Nee, een betoog heeft juist een mening.'], uh: 'Betoog: standpunt + argumenten, wil overtuigen.' },
      { v: 'Welke tekstsoort biedt een kwestie ter overweging zonder één standpunt op te leggen?', o: ['een beschouwende tekst', 'een betogende tekst', 'een instructie', 'een verhaal'], c: 0, d: 3, uo: ['Klopt: een beschouwing weegt af zonder één standpunt op te dringen.', 'Nee, een betoog kiest juist partij.', 'Nee, dat legt stappen uit.', 'Nee, dat is fictie.'], uh: 'Beschouwing: kwestie ter overweging.' },
      { v: 'Wat is een doel-middelrelatie in een tekst?', o: ['een zin beschrijft een middel om een doel te bereiken', 'een zin geeft de oorzaak van iets', 'een zin verwijst terug', 'een zin somt op'], c: 0, d: 3, uo: ['Klopt: het middel dient om een doel te bereiken.', 'Nee, dat is oorzaak-gevolg.', 'Nee, dat is verwijzing.', 'Nee, dat is opsomming.'], uh: 'Doel-middel: middel om een doel te bereiken.' },
      { v: 'Het signaalwoord "daarom" markeert meestal een...', o: ['gevolg', 'tegenstelling', 'voorbeeld', 'opsomming'], c: 0, d: 2, uo: ['Klopt: "daarom" leidt een gevolg in.', 'Nee, dat is "maar" of "echter".', 'Nee, dat is "bijvoorbeeld".', 'Nee, dat is "ten eerste".'], uh: '"Daarom": gevolg.' },
      { v: 'Wat is de hoofdgedachte van een tekst?', o: ['de belangrijkste boodschap in één zin', 'het eerste woord', 'een willekeurig detail', 'de titel letterlijk'], c: 0, d: 1, uo: ['Klopt: de hoofdgedachte vat de kern samen.', 'Nee, dat zegt weinig over de inhoud.', 'Nee, een detail is bijzaak.', 'Nee, de titel is niet altijd de hoofdgedachte.'], uh: 'Hoofdgedachte: de kern in één zin.' },
      { v: 'Een tekst die vooral informatie geeft en uitlegt, is...', o: ['uiteenzettend', 'betogend', 'beschouwend', 'amuserend'], c: 0, d: 2, uo: ['Klopt: informeren en uitleggen is uiteenzettend.', 'Nee, een betoog wil overtuigen.', 'Nee, een beschouwing weegt af.', 'Nee, amuseren is vermaken.'], uh: 'Uiteenzetting: informeert.' },
    ]),

  V('B', 'Mondeling',
    `Bij mondelinge taalvaardigheid houd je rekening met je <strong>publiek</strong> en <strong>doel</strong>: je varieert je <strong>intonatie</strong>, houdt <strong>oogcontact</strong> en past je <strong>register</strong> aan. In een <strong>debat</strong> luister je actief en doe je een <strong>concessie</strong> om een tegenargument serieus te nemen.`,
    [
      { h: '1. Presenteren', p: [
        `Overtuigend <strong>presenteren</strong> vraagt om <strong>oogcontact</strong>, een rustig tempo en variatie in <strong>intonatie</strong>. Ook <strong>non-verbale communicatie</strong> (houding, gebaren) telt mee. Een goede inleiding kondigt het onderwerp aan en trekt de aandacht.`] },
      { h: '2. Luisteren en debat', p: [
        `Bij <strong>actief luisteren</strong> noteer je de kernzin per alinea en denk je mee. In een <strong>debat</strong> toon je met een <strong>concessie</strong> ("Je hebt gelijk dat X, maar…") dat je het tegenargument serieus neemt. Je past je <strong>register</strong> aan: formeel, informeel of spreektaal.`] },
    ],
    [
      { t: 'Intonatie', d: 'de variatie in toonhoogte waarmee je spreekt', k: 'variatie in toonhoogte', fout: ['Register'] },
      { t: 'Oogcontact', d: 'het aankijken van je publiek om contact te houden', k: 'publiek aankijken', fout: ['Intonatie'] },
      { t: 'Concessie', d: 'toegeven dat de ander op een punt gelijk heeft', k: 'een punt toegeven', fout: ['Weerlegging'] },
      { t: 'Actief luisteren', d: 'meedenken en de kern noteren terwijl je luistert', k: 'meedenkend luisteren', fout: ['Register'] },
      { t: 'Register', d: 'de mate van formaliteit van je taalgebruik', k: 'mate van formaliteit', fout: ['Intonatie'] },
      { t: 'Debat', d: 'een gestructureerde discussie waarin standpunten botsen', k: 'gestructureerde discussie', fout: ['Presentatie'] },
      { t: 'Non-verbale communicatie', d: 'communicatie via houding, gebaren en mimiek', k: 'lichaamstaal', fout: ['Intonatie'] },
      { t: 'Presentatie', d: 'een mondelinge uiteenzetting voor een publiek', k: 'mondelinge uiteenzetting', fout: ['Debat'] },
      { t: 'Formeel taalgebruik', d: 'nette, zakelijke taal voor onbekenden of officiële situaties', k: 'nette, zakelijke taal', fout: ['Informeel taalgebruik'] },
      { t: 'Informeel taalgebruik', d: 'losse, alledaagse taal onder bekenden', k: 'losse alledaagse taal', fout: ['Formeel taalgebruik'] },
    ],
    [
      { v: 'Welke spreektechniek verbetert de overtuigingskracht van een presentatie het meest?', o: ['oogcontact houden en variëren in intonatie', 'zo snel mogelijk praten', 'monotoon voorlezen', 'naar de grond kijken'], c: 0, d: 2, uo: ['Klopt: contact en levendige intonatie overtuigen.', 'Nee, te snel praten verliest het publiek.', 'Nee, monotoon werkt juist saai.', 'Nee, wegkijken verzwakt de band.'], uh: 'Overtuigen: oogcontact en intonatievariatie.' },
      { v: 'Welke luisterstrategie past bij een informatieve presentatie?', o: ['de kernzin per alinea en sleutelinformatie noteren', 'alles woord voor woord opschrijven', 'alleen naar de intonatie luisteren', 'meteen tegenargumenten bedenken'], c: 0, d: 2, uo: ['Klopt: kernzinnen vangen de hoofdzaken.', 'Nee, dat is niet vol te houden.', 'Nee, dan mis je de inhoud.', 'Nee, dat hoort bij een debat.'], uh: 'Actief luisteren: kernzinnen noteren.' },
      { v: 'Hoe toon je in een debat dat je een tegenargument serieus neemt?', o: ['door een concessie te doen: "Je hebt gelijk dat X, maar…"', 'door de ander te onderbreken', 'door het argument te negeren', 'door harder te praten'], c: 0, d: 3, uo: ['Klopt: een concessie erkent het punt voordat je het weerlegt.', 'Nee, onderbreken is juist onbeleefd.', 'Nee, negeren toont geen respect.', 'Nee, volume is geen argument.'], uh: 'Concessie: eerst toegeven, dan weerleggen.' },
      { v: 'Welke niveaus van formaliteit bestaan er in gesproken Nederlands?', o: ['formeel, informeel en dialect/spreektaal', 'alleen formeel', 'alleen schrijftaal', 'alleen dialect'], c: 0, d: 2, uo: ['Klopt: er zijn meerdere registers.', 'Nee, er is meer dan formeel.', 'Nee, het gaat om spreektaal.', 'Nee, dialect is er één van.'], uh: 'Registers: formeel, informeel, spreektaal.' },
      { v: 'Wat is een concessie in een discussie?', o: ['toegeven dat de ander op een punt gelijk heeft', 'de ander volledig gelijk geven', 'het onderwerp veranderen', 'de ander aanvallen'], c: 0, d: 3, uo: ['Klopt: je erkent één punt zonder je standpunt op te geven.', 'Nee, je geeft niet alles toe.', 'Nee, dat ontwijkt de discussie.', 'Nee, dat is een persoonlijke aanval.'], uh: 'Concessie: één punt toegeven.' },
      { v: 'Wat is intonatie?', o: ['de variatie in toonhoogte van je stem', 'de snelheid van praten', 'je woordkeuze', 'je lichaamshouding'], c: 0, d: 2, uo: ['Klopt: intonatie is de melodie in je stem.', 'Nee, dat is spreektempo.', 'Nee, dat is register.', 'Nee, dat is non-verbaal.'], uh: 'Intonatie: variatie in toonhoogte.' },
      { v: 'Wat doe je bij actief luisteren?', o: ['meedenken en de kern noteren', 'wachten tot je aan de beurt bent', 'alleen knikken', 'meteen je mening geven'], c: 0, d: 2, uo: ['Klopt: je verwerkt actief wat de ander zegt.', 'Nee, dat is passief.', 'Nee, knikken alleen is niet actief.', 'Nee, eerst luisteren.'], uh: 'Actief luisteren: meedenken en verwerken.' },
      { v: 'Wat is een debat?', o: ['een gestructureerde discussie waarin standpunten botsen', 'een presentatie zonder publiek', 'een gesprek zonder regels', 'een monoloog'], c: 0, d: 2, uo: ['Klopt: een debat is een geregelde meningsstrijd.', 'Nee, een debat heeft juist publiek.', 'Nee, er zijn spelregels.', 'Nee, er zijn meerdere sprekers.'], uh: 'Debat: gestructureerde meningsstrijd.' },
      { v: 'Wat is non-verbale communicatie?', o: ['communicatie via houding, gebaren en mimiek', 'de woorden die je kiest', 'de toonhoogte van je stem', 'de lengte van je zinnen'], c: 0, d: 2, uo: ['Klopt: lichaamstaal is non-verbaal.', 'Nee, woorden zijn verbaal.', 'Nee, dat is intonatie.', 'Nee, dat is zinsbouw.'], uh: 'Non-verbaal: lichaamstaal.' },
      { v: 'Wanneer gebruik je formeel taalgebruik?', o: ['bij onbekenden of officiële situaties', 'alleen bij vrienden', 'nooit', 'alleen in een dagboek'], c: 0, d: 1, uo: ['Klopt: formeel past bij afstand en officiële situaties.', 'Nee, bij vrienden is informeel gepast.', 'Nee, het heeft wel degelijk nut.', 'Nee, een dagboek is juist informeel.'], uh: 'Formeel: bij onbekenden en officiële situaties.' },
    ]),

  V('C', 'Schrijfvaardigheid',
    `Een goede tekst is <strong>coherent</strong> (inhoudelijk samenhangend) en <strong>cohesief</strong> (met verbindende <strong>signaalwoorden</strong>). Je kiest een <strong>tekstsoort</strong> en <strong>register</strong> dat past bij doel en publiek, en bouwt de tekst op met inleiding, kern en slot.`,
    [
      { h: '1. Samenhang', p: [
        `<strong>Coherentie</strong> is de betekenissamenhang (de tekst klopt inhoudelijk); <strong>cohesie</strong> is de tekstuele samenhang via <strong>signaalwoorden</strong> en verwijzingen. Signaalwoorden markeren een verband: "echter" (tegenstelling), "immers/want/namelijk" (reden), "daardoor/dus" (gevolg), "bovendien" (opsomming).`] },
      { h: '2. Opbouw en register', p: [
        `Een tekst heeft een <strong>inleiding</strong> (onderwerp aankondigen), een <strong>kern</strong> (uitwerking) en een <strong>slot</strong> (conclusie). Elke <strong>alinea</strong> behandelt één deelonderwerp met een <strong>kernzin</strong>. Je kiest een passend <strong>register</strong>: een brief aan een krantenredactie is formeel.`] },
    ],
    [
      { t: 'Coherentie', d: 'de betekenissamenhang: de tekst klopt inhoudelijk', k: 'betekenissamenhang', fout: ['Cohesie'] },
      { t: 'Cohesie', d: 'de tekstuele samenhang via signaalwoorden en verwijzingen', k: 'tekstuele samenhang', fout: ['Coherentie'] },
      { t: 'Signaalwoord', d: 'een woord dat het verband tussen zinnen aangeeft', k: 'geeft verband aan', fout: ['Kernzin'] },
      { t: 'Betoog', d: 'een tekst die de lezer van een standpunt wil overtuigen', k: 'wil overtuigen', fout: ['Uiteenzetting'] },
      { t: 'Register', d: 'de mate van formaliteit die past bij doel en publiek', k: 'mate van formaliteit', fout: ['Signaalwoord'] },
      { t: 'Alinea', d: 'een tekstdeel over één deelonderwerp', k: 'één deelonderwerp', fout: ['Kernzin'] },
      { t: 'Kernzin', d: 'de zin met de hoofdgedachte van een alinea', k: 'hoofdgedachte van een alinea', fout: ['Alinea'] },
      { t: 'Inleiding', d: 'het begin van de tekst dat het onderwerp aankondigt', k: 'kondigt het onderwerp aan', fout: ['Slot'] },
      { t: 'Kern', d: 'het middendeel waarin het onderwerp wordt uitgewerkt', k: 'uitwerking van het onderwerp', fout: ['Inleiding'] },
      { t: 'Slot', d: 'het einde van de tekst met de conclusie', k: 'conclusie', fout: ['Inleiding'] },
    ],
    [
      { v: 'Wat is het verschil tussen coherentie en cohesie?', o: ['coherentie is betekenissamenhang, cohesie is tekstuele samenhang', 'ze zijn hetzelfde', 'coherentie is tekstuele samenhang', 'cohesie is de inhoud'], c: 0, d: 3, uo: ['Klopt: coherentie = inhoud klopt, cohesie = verbindende middelen.', 'Nee, ze verschillen.', 'Nee, dat is precies omgedraaid.', 'Nee, cohesie gaat over de vorm.'], uh: 'Coherentie: inhoud; cohesie: verbindende middelen.' },
      { v: 'Welk signaalwoord geeft een tegenstelling aan?', o: ['echter', 'daardoor', 'bovendien', 'namelijk'], c: 0, d: 2, uo: ['Klopt: "echter" markeert een tegenstelling.', 'Nee, dat is een gevolg.', 'Nee, dat is een opsomming.', 'Nee, dat is een reden.'], uh: '"Echter": tegenstelling.' },
      { v: 'Welk type tekst schrijf je om de lezer van een standpunt te overtuigen?', o: ['een betoog', 'een uiteenzetting', 'een verslag', 'een verhaal'], c: 0, d: 2, uo: ['Klopt: een betoog wil overtuigen.', 'Nee, dat informeert.', 'Nee, dat doet neutraal verslag.', 'Nee, dat is fictie.'], uh: 'Overtuigen: betoog.' },
      { v: 'Welk signaalwoord geeft een redengeving aan?', o: ['immers / want / namelijk', 'echter', 'daardoor', 'ten slotte'], c: 0, d: 2, uo: ['Klopt: deze woorden leiden een reden in.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een gevolg.', 'Nee, dat markeert een afsluiting.'], uh: '"Want/immers/namelijk": reden.' },
      { v: 'Welk register gebruik je voor een brief aan de redactie van een krant?', o: ['formeel register', 'straattaal', 'dialect', 'sms-taal'], c: 0, d: 2, uo: ['Klopt: een brief aan een redactie is formeel.', 'Nee, dat is te informeel.', 'Nee, dat past niet bij een officiële brief.', 'Nee, afkortingen horen er niet.'], uh: 'Officiële brief: formeel register.' },
      { v: 'Wat is een signaalwoord?', o: ['een woord dat het verband tussen zinnen aangeeft', 'het eerste woord van een alinea', 'een moeilijk woord', 'een werkwoord'], c: 0, d: 2, uo: ['Klopt: een signaalwoord markeert een tekstverband.', 'Nee, dat is niet de definitie.', 'Nee, moeilijkheid doet er niet toe.', 'Nee, het hoeft geen werkwoord te zijn.'], uh: 'Signaalwoord: markeert een verband.' },
      { v: 'Wat gebeurt er in de kern van een tekst?', o: ['het onderwerp wordt uitgewerkt', 'het onderwerp wordt aangekondigd', 'de tekst wordt afgesloten', 'de titel wordt gekozen'], c: 0, d: 2, uo: ['Klopt: de kern werkt het onderwerp uit.', 'Nee, dat is de inleiding.', 'Nee, dat is het slot.', 'Nee, dat is geen tekstdeel.'], uh: 'Kern: uitwerking van het onderwerp.' },
      { v: 'Wat is een alinea?', o: ['een tekstdeel over één deelonderwerp', 'één enkele zin', 'de titel', 'een opsomming'], c: 0, d: 1, uo: ['Klopt: een alinea behandelt één deelonderwerp.', 'Nee, een alinea heeft meerdere zinnen.', 'Nee, dat is de kop.', 'Nee, dat is een lijstje.'], uh: 'Alinea: één deelonderwerp.' },
      { v: 'Welk signaalwoord geeft een opsomming aan?', o: ['bovendien / ten eerste', 'echter', 'doordat', 'kortom'], c: 0, d: 2, uo: ['Klopt: deze woorden voegen iets toe in een reeks.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een oorzaak.', 'Nee, dat is een samenvatting.'], uh: '"Bovendien/ten eerste": opsomming.' },
      { v: 'Wat is een kernzin?', o: ['de zin met de hoofdgedachte van een alinea', 'de langste zin', 'de laatste zin van de tekst', 'de titel'], c: 0, d: 2, uo: ['Klopt: de kernzin draagt de hoofdgedachte.', 'Nee, lengte bepaalt het niet.', 'Nee, dat kan, maar hoeft niet.', 'Nee, dat is de kop.'], uh: 'Kernzin: hoofdgedachte van een alinea.' },
      { v: 'Welk signaalwoord geeft een gevolg aan?', o: ['daardoor / dus', 'maar', 'want', 'bijvoorbeeld'], c: 0, d: 2, uo: ['Klopt: "daardoor/dus" leidt een gevolg in.', 'Nee, dat is een tegenstelling.', 'Nee, dat is een reden.', 'Nee, dat is een voorbeeld.'], uh: '"Daardoor/dus": gevolg.' },
    ]),

  V('D', 'Argumentatieve vaardigheden',
    `Je analyseert <strong>argumentatie</strong>: het <strong>standpunt</strong>, de <strong>argumenten</strong> en de <strong>structuur</strong> (nevenschikkend of onderschikkend). Je herkent <strong>drogredenen</strong> zoals de persoonlijke aanval, het valse dilemma, de cirkelredenering en de overhaaste generalisatie.`,
    [
      { h: '1. Structuur', p: [
        `Een <strong>argument</strong> ondersteunt het standpunt direct; een <strong>subargument</strong> ondersteunt een argument (onderschikkend). Bij <strong>nevenschikkende</strong> argumentatie steunen twee onafhankelijke argumenten elk het standpunt. Een <strong>syllogisme</strong> heeft twee premissen en een conclusie die logisch volgt.`] },
      { h: '2. Drogredenen', p: [
        `Veelvoorkomende <strong>drogredenen</strong>: de <strong>persoonlijke aanval</strong> (de persoon in plaats van het argument aanvallen), het <strong>valse dilemma</strong> (maar twee opties terwijl er meer zijn), de <strong>cirkelredenering</strong> (het standpunt bewijst zichzelf), <strong>post hoc</strong> (na elkaar dus door elkaar) en de <strong>overhaaste generalisatie</strong>.`] },
    ],
    [
      { t: 'Standpunt', d: 'de mening die iemand met argumenten verdedigt', k: 'de verdedigde mening', fout: ['Argument'] },
      { t: 'Argument', d: 'een reden die het standpunt direct ondersteunt', k: 'ondersteunt het standpunt', fout: ['Subargument'] },
      { t: 'Subargument', d: 'een reden die een argument ondersteunt (onderschikkend)', k: 'ondersteunt een argument', fout: ['Argument'] },
      { t: 'Nevenschikkende argumentatie', d: 'twee onafhankelijke argumenten die elk het standpunt steunen', k: 'onafhankelijke argumenten', fout: ['Onderschikkende argumentatie'] },
      { t: 'Persoonlijke aanval', d: 'de drogreden waarbij je de persoon aanvalt in plaats van het argument', k: 'man in plaats van bal', fout: ['Vals dilemma'] },
      { t: 'Vals dilemma', d: 'de drogreden die maar twee opties toont terwijl er meer zijn', k: 'maar twee opties', fout: ['Cirkelredenering'] },
      { t: 'Cirkelredenering', d: 'de drogreden waarbij het standpunt zichzelf bewijst', k: 'bewijst zichzelf', fout: ['Vals dilemma'] },
      { t: 'Post hoc', d: 'de drogreden dat iets de oorzaak is puur omdat het eraan voorafging', k: 'na elkaar dus door elkaar', fout: ['Overhaaste generalisatie'] },
      { t: 'Overhaaste generalisatie', d: 'de drogreden die uit te weinig gevallen een algemene conclusie trekt', k: 'te snelle algemene conclusie', fout: ['Post hoc'] },
      { t: 'Syllogisme', d: 'een redenering met twee premissen en een logisch volgende conclusie', k: 'twee premissen, één conclusie', fout: ['Cirkelredenering'] },
    ],
    [
      { v: 'Een politicus zegt: "Als we X invoeren, volgt Y zeker." Welke drogreden speelt hier?', o: ['een oorzaak-gevolgdrogreden: Y kan ook andere oorzaken hebben', 'een persoonlijke aanval', 'een vals dilemma', 'een cirkelredenering'], c: 0, d: 3, uo: ['Klopt: het gestelde gevolg is niet zeker, er zijn andere oorzaken.', 'Nee, er wordt geen persoon aangevallen.', 'Nee, er worden geen twee opties opgedrongen.', 'Nee, het standpunt bewijst zichzelf niet.'], uh: 'Onterecht zeker gevolg: oorzaak-gevolgdrogreden.' },
      { v: '"Fietspaden bevorderen de gezondheid én verminderen CO₂." Welke structuur?', o: ['nevenschikkende argumentatie', 'onderschikkende argumentatie', 'cirkelredenering', 'vals dilemma'], c: 0, d: 3, uo: ['Klopt: twee onafhankelijke argumenten steunen het standpunt.', 'Nee, het ene argument steunt niet het andere.', 'Nee, er is geen cirkel.', 'Nee, er worden geen opties opgedrongen.'], uh: 'Twee losse argumenten: nevenschikkend.' },
      { v: '"Jij kunt mij niets over eerlijkheid vertellen, jij liegt zelf!" Welke drogreden?', o: ['persoonlijke aanval', 'vals dilemma', 'cirkelredenering', 'overhaaste generalisatie'], c: 0, d: 2, uo: ['Klopt: de persoon wordt aangevallen, niet het argument.', 'Nee, er zijn geen twee opties.', 'Nee, er is geen cirkel.', 'Nee, er wordt niet gegeneraliseerd.'], uh: 'Man in plaats van bal: persoonlijke aanval.' },
      { v: 'Wanneer is een argument "feitelijk" volgens het CE?', o: ['als de spreker claimt dat het waar, aannemelijk of controleerbaar is', 'als het over gevoelens gaat', 'als het een bevel is', 'als het een vraag is'], c: 0, d: 3, uo: ['Klopt: een feitelijk argument doet een controleerbare claim.', 'Nee, dat is een waarderend argument.', 'Nee, een bevel is geen argument.', 'Nee, een vraag onderbouwt niets.'], uh: 'Feitelijk argument: controleerbare claim.' },
      { v: 'Wat is een vals dilemma?', o: ['maar twee opties presenteren terwijl er meer zijn', 'de persoon aanvallen', 'iets bewijzen met zichzelf', 'te snel generaliseren'], c: 0, d: 2, uo: ['Klopt: een vals dilemma verzwijgt de andere mogelijkheden.', 'Nee, dat is een persoonlijke aanval.', 'Nee, dat is een cirkelredenering.', 'Nee, dat is een overhaaste generalisatie.'], uh: 'Vals dilemma: maar twee opties.' },
      { v: 'Wat is een cirkelredenering?', o: ['het standpunt wordt gebruikt om zichzelf te bewijzen', 'twee opties opdringen', 'de persoon aanvallen', 'na elkaar dus door elkaar'], c: 0, d: 3, uo: ['Klopt: de conclusie zit al in de premisse.', 'Nee, dat is een vals dilemma.', 'Nee, dat is een persoonlijke aanval.', 'Nee, dat is post hoc.'], uh: 'Cirkelredenering: bewijst zichzelf.' },
      { v: 'Wat is het verschil tussen een argument en een subargument?', o: ['een argument steunt het standpunt, een subargument steunt een argument', 'ze zijn hetzelfde', 'een subargument steunt het standpunt direct', 'een argument is altijd fout'], c: 0, d: 3, uo: ['Klopt: een subargument onderbouwt een argument (onderschikkend).', 'Nee, ze verschillen.', 'Nee, dat doet het argument juist.', 'Nee, een argument kan geldig zijn.'], uh: 'Subargument steunt een argument.' },
      { v: 'Iemand legt een oorzaak-verband puur omdat B ná A gebeurde. Welke drogreden?', o: ['post hoc ergo propter hoc', 'vals dilemma', 'persoonlijke aanval', 'cirkelredenering'], c: 0, d: 3, uo: ['Klopt: opeenvolging is geen oorzaak, dat is post hoc.', 'Nee, er zijn geen twee opties.', 'Nee, er wordt geen persoon aangevallen.', 'Nee, er is geen cirkel.'], uh: 'Na elkaar dus door elkaar: post hoc.' },
      { v: 'Wat is een syllogisme?', o: ['een redenering met twee premissen en een logisch volgende conclusie', 'een drogreden', 'een terugblik', 'een opsomming'], c: 0, d: 3, uo: ['Klopt: uit twee premissen volgt de conclusie logisch.', 'Nee, een syllogisme kan juist geldig zijn.', 'Nee, dat is een verteltechniek.', 'Nee, dat is geen redenering.'], uh: 'Syllogisme: twee premissen, één conclusie.' },
      { v: '"Alle tieners in mijn klas zijn lui, dus alle tieners zijn lui." Welke drogreden?', o: ['overhaaste generalisatie', 'persoonlijke aanval', 'vals dilemma', 'cirkelredenering'], c: 0, d: 2, uo: ['Klopt: uit één klas volgt geen conclusie over alle tieners.', 'Nee, er wordt geen persoon aangevallen.', 'Nee, er zijn geen twee opties.', 'Nee, er is geen cirkel.'], uh: 'Te weinig gevallen: overhaaste generalisatie.' },
      { v: 'Wat is een standpunt?', o: ['de mening die iemand met argumenten verdedigt', 'een controleerbaar feit', 'een terugblik', 'een signaalwoord'], c: 0, d: 1, uo: ['Klopt: een standpunt is de te verdedigen mening.', 'Nee, een feit is controleerbaar, geen mening.', 'Nee, dat is een verteltechniek.', 'Nee, dat markeert een verband.'], uh: 'Standpunt: de verdedigde mening.' },
      { v: 'Wat is een drogreden?', o: ['een argument dat schijnbaar geldig is maar niet klopt', 'een sterk onderbouwd argument', 'een feit', 'een kernzin'], c: 0, d: 2, uo: ['Klopt: een drogreden lijkt te kloppen maar is onjuist.', 'Nee, dat is juist een goed argument.', 'Nee, een feit is controleerbaar.', 'Nee, dat is een tekstbegrip.'], uh: 'Drogreden: schijnbaar geldig, maar onjuist.' },
    ]),

  V('E', 'Literatuur',
    `Bij literatuur herken je <strong>verteltechnieken</strong> (analepse, chronologie, perspectief), <strong>structuurbegrippen</strong> (climax, motief, thema) en <strong>stromingen</strong> zoals het <strong>modernisme</strong> en <strong>postmodernisme</strong>. Je kent kernwerken zoals Multatuli's Max Havelaar.`,
    [
      { h: '1. Verteltechniek en structuur', p: [
        `Een <strong>analepse</strong> is een terugblik (flashback); een <strong>chronologische</strong> vertelling loopt van vroeg naar laat. De <strong>climax</strong> is het spanningshoogtepunt. Een <strong>motief</strong> is een terugkerend concreet element met symbolische betekenis; het <strong>thema</strong> is de centrale gedachte.`] },
      { h: '2. Stromingen', p: [
        `Het <strong>modernisme</strong> experimenteert met vorm, bijvoorbeeld de <strong>stream of consciousness</strong> (ongeordende gedachtestroom). Het <strong>postmodernisme</strong> bevraagt de grens tussen fictie en werkelijkheid via metafictie, ironie en intertekstualiteit. <strong>Multatuli</strong> schreef Max Havelaar (1860) over koloniale uitbuiting.`] },
    ],
    [
      { t: 'Analepse', d: 'een terugblik op een eerdere gebeurtenis, een flashback', k: 'terugblik/flashback', fout: ['Chronologische vertelling'] },
      { t: 'Chronologische vertelling', d: 'een verhaal dat van de vroegste naar de laatste gebeurtenis loopt', k: 'van vroeg naar laat', fout: ['Analepse'] },
      { t: 'Climax', d: 'het punt in de plot waar de spanning het hoogst is', k: 'spanningshoogtepunt', fout: ['Motief'] },
      { t: 'Motief', d: 'een terugkerend concreet element dat iets abstracts symboliseert', k: 'terugkerend symbolisch element', fout: ['Thema'] },
      { t: 'Thema', d: 'de centrale gedachte of boodschap van een werk', k: 'centrale gedachte', fout: ['Motief'] },
      { t: 'Perspectief', d: 'het standpunt van waaruit het verhaal wordt verteld', k: 'vertelstandpunt', fout: ['Thema'] },
      { t: 'Modernisme', d: 'een stroming die met vorm experimenteert, zoals stream of consciousness', k: 'vormexperiment, gedachtestroom', fout: ['Postmodernisme'] },
      { t: 'Postmodernisme', d: 'een stroming die fictie en werkelijkheid bevraagt via metafictie en ironie', k: 'metafictie en ironie', fout: ['Modernisme'] },
      { t: 'Ironie', d: 'het tegenovergestelde bedoelen van wat je letterlijk zegt', k: 'tegenovergestelde bedoelen', fout: ['Motief'] },
      { t: 'Raamvertelling', d: 'een verhaal waarin een ander verhaal is ingebed', k: 'verhaal binnen een verhaal', fout: ['Analepse'] },
    ],
    [
      { v: 'Wat is een analepse?', o: ['een terugblik op een eerdere gebeurtenis (flashback)', 'een vooruitblik', 'het spanningshoogtepunt', 'de centrale gedachte'], c: 0, d: 2, uo: ['Klopt: een analepse is een terugblik.', 'Nee, dat is een prolepse.', 'Nee, dat is de climax.', 'Nee, dat is het thema.'], uh: 'Analepse: terugblik/flashback.' },
      { v: 'Welk kenmerk hoort bij het modernisme?', o: ['stream of consciousness: de ongeordende gedachtestroom', 'strikte rijmschema\'s', 'een moraal aan het eind', 'uitsluitend chronologie'], c: 0, d: 3, uo: ['Klopt: het modernisme geeft de gedachtestroom direct weer.', 'Nee, dat is klassieker.', 'Nee, een expliciete moraal past er niet bij.', 'Nee, het modernisme breekt juist met chronologie.'], uh: 'Modernisme: stream of consciousness.' },
      { v: 'Wat is postmodernisme in de literatuur?', o: ['een stroming die fictie en werkelijkheid bevraagt via metafictie en ironie', 'realistische romans met een duidelijke moraal', 'poëzie met vaste versvormen', 'toneel uit de oudheid'], c: 0, d: 3, uo: ['Klopt: het postmodernisme speelt met fictie en werkelijkheid.', 'Nee, dat is realisme.', 'Nee, dat is klassieke poëzie.', 'Nee, dat is antiek theater.'], uh: 'Postmodernisme: metafictie, ironie, intertekstualiteit.' },
      { v: 'Welk begrip beschrijft een verhaal dat van de vroegste tot de laatste gebeurtenis loopt?', o: ['chronologische vertelling', 'analepse', 'raamvertelling', 'climax'], c: 0, d: 2, uo: ['Klopt: chronologisch is op tijdsvolgorde.', 'Nee, dat is een terugblik.', 'Nee, dat is een verhaal in een verhaal.', 'Nee, dat is het spanningshoogtepunt.'], uh: 'Chronologisch: van vroeg naar laat.' },
      { v: 'Welk begrip beschrijft het punt waar de spanning het hoogst is?', o: ['climax', 'expositie', 'motief', 'perspectief'], c: 0, d: 2, uo: ['Klopt: de climax is het spanningshoogtepunt.', 'Nee, dat is de inleidende situatie.', 'Nee, dat is een terugkerend element.', 'Nee, dat is het vertelstandpunt.'], uh: 'Climax: hoogtepunt van de spanning.' },
      { v: 'Welke Nederlandse auteur schreef Max Havelaar (1860)?', o: ['Multatuli', 'Willem Frederik Hermans', 'Harry Mulisch', 'Joost van den Vondel'], c: 0, d: 2, uo: ['Klopt: Multatuli schreef Max Havelaar over koloniale uitbuiting.', 'Nee, die schreef later, in de 20e eeuw.', 'Nee, ook een 20e-eeuwse auteur.', 'Nee, die schreef in de 17e eeuw.'], uh: 'Max Havelaar (1860): Multatuli.' },
      { v: 'Welk begrip beschrijft een terugkerend concreet element met symbolische betekenis?', o: ['motief', 'thema', 'climax', 'analepse'], c: 0, d: 3, uo: ['Klopt: een motief keert terug en verwijst naar iets abstracts.', 'Nee, het thema is de centrale gedachte zelf.', 'Nee, dat is het spanningshoogtepunt.', 'Nee, dat is een terugblik.'], uh: 'Motief: terugkerend symbolisch element.' },
      { v: 'Wat is het thema van een literair werk?', o: ['de centrale gedachte of boodschap', 'de eerste zin', 'de naam van de hoofdpersoon', 'het aantal hoofdstukken'], c: 0, d: 2, uo: ['Klopt: het thema is de kerngedachte.', 'Nee, dat is de opening.', 'Nee, dat is een personage.', 'Nee, dat is de omvang.'], uh: 'Thema: centrale gedachte.' },
      { v: 'Wat bepaalt het perspectief (vertelstandpunt) in een verhaal?', o: ['vanuit wiens ogen het verhaal wordt verteld', 'hoe lang het verhaal is', 'in welk jaar het speelt', 'hoeveel personages er zijn'], c: 0, d: 2, uo: ['Klopt: het perspectief is het standpunt van vertellen.', 'Nee, dat is de lengte.', 'Nee, dat is de tijd.', 'Nee, dat is het aantal personages.'], uh: 'Perspectief: vanuit wiens ogen verteld wordt.' },
      { v: 'Wat is een raamvertelling?', o: ['een verhaal waarin een ander verhaal is ingebed', 'een verhaal zonder einde', 'een gedicht met vaste vorm', 'een terugblik'], c: 0, d: 3, uo: ['Klopt: een raamverhaal omlijst een binnenverhaal.', 'Nee, dat is iets anders.', 'Nee, dat is poëzie.', 'Nee, dat is een analepse.'], uh: 'Raamvertelling: verhaal binnen een verhaal.' },
      { v: 'Wat is ironie?', o: ['het tegenovergestelde bedoelen van wat je letterlijk zegt', 'een terugblik in de tijd', 'het spanningshoogtepunt', 'een vaste versvorm'], c: 0, d: 2, uo: ['Klopt: bij ironie zeg je het omgekeerde van wat je bedoelt.', 'Nee, dat is een analepse.', 'Nee, dat is de climax.', 'Nee, dat is een dichtvorm.'], uh: 'Ironie: het omgekeerde bedoelen.' },
    ]),
];
