// VWO Economie - situaties per begrip.
export default {
  A: {
    Nominaal: ['Het bedrag in euro\'s van dat jaar, niet gecorrigeerd voor inflatie', 'Het loon dat op je loonstrook staat, zonder correctie'],
    Reëel: ['Het bedrag gecorrigeerd voor de prijsstijging, de echte koopkracht', 'Je loon steeg, maar door inflatie kun je er niet meer van kopen'],
    Indexcijfer: ['Het getal 120 ten opzichte van het basisjaar 100', 'Een getal dat een verandering ten opzichte van een basisjaar toont'],
    'Procentuele verandering': ['Een prijs gaat van 80 naar 100, dat is een kwart erbij', 'De toename gedeeld door de oude waarde, maal honderd'],
    'Ceteris paribus': ['Je bekijkt het effect van de prijs terwijl al het andere gelijk blijft', 'De aanname dat de overige omstandigheden constant zijn'],
    'Marginale kosten': ['De extra kosten om één product meer te maken', 'Wat de laatst geproduceerde eenheid kost'],
    Prijselasticiteit: ['Hoe sterk de vraag reageert als de prijs verandert', 'Bij luxe daalt de vraag sterk als de prijs stijgt'],
    Bruto: ['Het loon vóór er belasting en premies af gaan', 'Het volledige bedrag voor aftrek'],
    Netto: ['Het bedrag dat overblijft nadat de aftrek eraf is', 'Wat er uiteindelijk op je rekening komt'],
    'Vraag-en-aanbodgrafiek': ['Een grafiek met de prijs op de verticale en de hoeveelheid op de horizontale as', 'De dalende vraaglijn en de stijgende aanbodlijn kruisen bij de evenwichtsprijs'],
  },
  B: {
    Schaarste: ['Er is minder van iets dan mensen willen hebben', 'Beperkte middelen tegenover onbeperkte behoeften'],
    Opofferingskosten: ['Kies je voor studeren, dan mis je het loon van werken', 'De waarde van het beste alternatief dat je opgeeft'],
    PMC: ['De curve die de maximale combinaties laat zien die je kunt maken', 'Op de grens produceer je zoveel mogelijk met je middelen'],
    'Productiefactor natuur': ['De grond en grondstoffen waarmee je produceert, beloond met pacht', 'Vruchtbare landbouwgrond die een boer verpacht'],
    'Productiefactor arbeid': ['Het werk dat mensen leveren, beloond met loon', 'De uren die een medewerker maakt tegen salaris'],
    'Productiefactor kapitaal': ['De machines en gebouwen van een bedrijf, beloond met rente', 'De fabriekshal en de robots waarmee wordt geproduceerd'],
    Ondernemerschap: ['Iemand combineert de productiefactoren en draagt het risico, voor winst', 'De ondernemer die zijn bedrijf opzet en er winst uit haalt'],
    'Economische groei': ['De productiecapaciteit neemt toe en de PMC verschuift naar buiten', 'Een land kan volgend jaar meer produceren dan dit jaar'],
    Behoefte: ['Iets wat een mens wil hebben of gebruiken', 'De wens naar eten, kleding of ontspanning'],
    Welvaart: ['De mate waarin behoeften met schaarse middelen bevredigd worden', 'Hoe goed mensen in hun behoeften kunnen voorzien'],
  },
  C: {
    'Comparatief voordeel': ['Je maakt een goed met de laagste opofferingskosten', 'Je bent relatief het beste in taarten bakken'],
    'Absoluut voordeel': ['Je maakt met dezelfde middelen simpelweg meer dan een ander', 'Een land dat per uur meer auto\'s produceert'],
    Specialisatie: ['Je legt je toe op het goed waarin je het beste bent', 'De bakker bakt brood, de boer verbouwt graan'],
    'Geld als ruilmiddel': ['Je betaalt met geld in plaats van goederen te ruilen', 'Met munten hoef je niet je koe tegen brood te ruilen'],
    'Geld als rekenmiddel': ['Met prijzen in euro\'s kun je waarden onderling vergelijken', 'Je ziet meteen dat een fiets meer waard is dan een boek'],
    'Geld als oppotmiddel': ['Je bewaart koopkracht voor later door geld op te potten', 'Je spaart nu om er over een jaar iets van te kopen'],
    Ruilhandel: ['Je ruilt goederen direct tegen goederen zonder geld', 'Een boer ruilt graan tegen de schoenen van de schoenmaker'],
    Transactiekosten: ['De moeite en kosten om een ruil rond te krijgen', 'Zoeken, onderhandelen en een contract opstellen kost tijd'],
    Arbeidsverdeling: ['Het werk wordt opgesplitst in deeltaken', 'Aan de lopende band doet ieder één handeling'],
    'Onderlinge afhankelijkheid': ['Doordat iedereen zich specialiseert, heeft men elkaar nodig', 'De bakker heeft de boer nodig voor graan en andersom'],
  },
  D: {
    'Volledige mededinging': ['Heel veel aanbieders met een identiek product en vrije toetreding', 'Op een groentemarkt verkoopt iedereen dezelfde appels'],
    Monopolie: ['Eén aanbieder zonder concurrenten', 'De enige waterleverancier in een land'],
    Oligopolie: ['Een kleine groep grote aanbieders die op elkaar reageren', 'Een paar grote telecombedrijven die elkaar in de gaten houden'],
    'Negatief extern effect': ['Fabrieksrook schaadt omwonenden die er niets mee te maken hebben', 'Schade voor derden buiten de transactie'],
    'Publiek goed': ['Iedereen profiteert van dijken, niemand kun je uitsluiten', 'Een goed dat niet-rivaliserend en niet-uitsluitbaar is'],
    Informatieasymmetrie: ['De verkoper weet meer over de auto dan de koper', 'De ene partij weet meer over de kwaliteit dan de andere'],
    Consumentensurplus: ['Je betaalt minder dan je maximaal had willen betalen', 'De extra welvaart doordat de prijs onder je grens ligt'],
    Winstmaximum: ['Het bedrijf produceert tot de marginale opbrengst gelijk is aan de marginale kosten', 'Bij MO = MK is de winst het hoogst'],
    Maximumprijs: ['De overheid stelt een bovengrens onder de evenwichtsprijs in', 'Een prijsplafond dat een tekort veroorzaakt'],
    Kruisprijselasticiteit: ['Hoe de vraag naar boter reageert op de prijs van margarine', 'De reactie van de vraag op de prijs van een ander goed'],
  },
  E: {
    Rente: ['De beloning die je krijgt als je spaart in plaats van uitgeeft', 'De prijs die je betaalt als je geld leent'],
    'Contante waarde': ['Wat een bedrag dat je pas later krijgt nu waard is', 'Een toekomstig bedrag teruggerekend naar vandaag'],
    Eindwaarde: ['Wat je spaargeld na een aantal jaren met rente waard is', 'Het bedrag inclusief alle opgebouwde rente'],
    'Samengestelde rente': ['Je krijgt ook rente over de rente van vorige jaren', 'Rente over rente laat je spaarpot sneller groeien'],
    Inflatie: ['De prijzen stijgen algemeen, je geld wordt minder waard', 'Een algemene stijging van het prijspeil'],
    Koopkracht: ['Hoeveel je met een bedrag geld kunt kopen', 'Door inflatie kun je met hetzelfde geld minder kopen'],
    'Reële rente': ['De rente nadat je de inflatie eraf haalt', 'Rente 2% bij inflatie 3% geeft ongeveer −1%'],
    'Nominale rente': ['Het rentepercentage dat de bank noemt, zonder inflatiecorrectie', 'De 2% die op je spaarrekening staat'],
    Sparen: ['Je geeft geld nu niet uit maar bewaart het voor later', 'Je zet elke maand wat opzij voor de toekomst'],
    Lenen: ['Je gebruikt nu geld van een ander en betaalt er rente voor', 'Met een lening haal je een aankoop naar voren'],
  },
  F: {
    Gevangenendilemma: ['Ieder kiest voor zichzelf en samen komen ze slechter uit', 'Beide verdachten bekennen en krijgen allebei straf'],
    Meelifterprobleem: ['Je profiteert van een goed zonder eraan mee te betalen', 'Iedereen wil schoon vuurwerk, maar niemand wil betalen'],
    'Collectief goed': ['Een goed waarvan iedereen profiteert en uitsluiten lastig is', 'Straatverlichting die de hele buurt gebruikt'],
    Vakbond: ['Werknemers verenigen zich om samen sterker te staan', 'De organisatie die opkomt voor de belangen van werknemers'],
    Onderhandelingsmacht: ['De mate waarin je een gunstige afspraak kunt afdwingen', 'Samen sta je sterker dan ieder apart'],
    CAO: ['In dit akkoord staan loon en arbeidsvoorwaarden voor een hele sector', 'Collectieve afspraken tussen werkgevers en vakbonden'],
    Kartel: ['Aanbieders spreken stiekem af de prijs hoog te houden', 'Een verboden prijsafspraak tussen concurrenten'],
    Speltheorie: ['Je bestudeert keuzes die van elkaars gedrag afhangen', 'Wat de een doet, hangt af van wat de ander doet'],
    'Sociaal dilemma': ['Wat goed is voor jou alleen, is slecht voor de groep', 'Eigenbelang botst met het algemeen belang'],
    Coöperatie: ['Door samen te werken is iedereen beter af', 'Boeren bundelen krachten in een gezamenlijke vereniging'],
  },
  G: {
    'Asymmetrische informatie': ['De verkoper weet meer over het product dan de koper', 'De ene partij weet meer dan de andere'],
    'Averechtse selectie': ['Bij een vaste premie melden vooral de slechte risico\'s zich aan', 'Vooral zieke mensen sluiten een dure zorgverzekering af'],
    'Moreel wangedrag': ['Wie verzekerd is, gedraagt zich roekelozer', 'Met een fietsverzekering zet je hem minder goed op slot'],
    'Eigen risico': ['Het deel van de schade dat je zelf moet betalen', 'De eerste paar honderd euro betaal je uit eigen zak'],
    Premie: ['Het bedrag dat je maandelijks voor je verzekering betaalt', 'Wat je betaalt in ruil voor dekking'],
    Verzekeren: ['Met een groep samen een onzeker risico delen', 'Velen betalen premie zodat de enkele pechvogel wordt gedekt'],
    Signaleren: ['De goede partij toont haar kwaliteit, bijvoorbeeld met een diploma', 'Met een keurmerk laat je zien dat je product deugt'],
    Screening: ['De onwetende partij zoekt zelf informatie op', 'De verzekeraar vraagt naar je medische verleden'],
    Schaderisico: ['De kans dat er schade optreedt', 'Een oude auto heeft een grotere kans op pech'],
    Risicoaversie: ['Je verkiest zekerheid boven een gok met dezelfde verwachte waarde', 'Liever een vast bedrag dan een onzekere loterij'],
  },
  H: {
    Lorenzcurve: ['Een curve die laat zien hoe scheef de inkomens verdeeld zijn', 'Hoe verder van de diagonaal, hoe ongelijker'],
    'Gini-coëfficiënt': ['Een getal tussen 0 en 1 voor de inkomensongelijkheid', 'Dichter bij 1 betekent een ongelijkere verdeling'],
    'Reële groei': ['De bbp-groei nadat je de inflatie eraf haalt', '5% groei bij 2% inflatie is ongeveer 3% reëel'],
    'Nominale groei': ['De bbp-groei in lopende prijzen, zonder inflatiecorrectie', 'De groei voordat je voor prijsstijging corrigeert'],
    Bbp: ['De waarde van alles wat een land in een jaar produceert', 'De totale productie van goederen en diensten'],
    'Bbp per hoofd': ['Het bbp gedeeld door het aantal inwoners', 'Een gemiddelde dat de verdeling verbergt'],
    Inkomensverdeling: ['Hoe de inkomens over de bevolking zijn verdeeld', 'Een klein deel verdient veel, een groot deel weinig'],
    Nivellering: ['De inkomensverschillen worden kleiner gemaakt', 'Meer belasting voor de rijken, meer toeslag voor de armen'],
    Denivellering: ['De inkomensverschillen worden groter gemaakt', 'De kloof tussen arm en rijk neemt toe'],
    'Brede welvaart': ['Welvaart inclusief milieu, gezondheid en vrije tijd', 'Niet alleen geld telt mee, ook je leefomgeving'],
  },
  I: {
    Conjunctuur: ['De op- en neergang van de economie in de tijd', 'Afwisselend goede en slechte economische jaren'],
    'Conjuncturele werkloosheid': ['Werkloosheid doordat de vraag in een recessie te laag is', 'In slechte tijden ontslaan bedrijven personeel'],
    Phillipscurve: ['Bij lage werkloosheid hoort op korte termijn hogere inflatie', 'Een negatief verband tussen inflatie en werkloosheid'],
    'Automatische stabilisator': ['Uitkeringen lopen vanzelf op in een recessie en dempen de klap', 'Een mechanisme dat de economie dempt zonder nieuw besluit'],
    'Restrictief monetair beleid': ['De ECB verhoogt de rente om de inflatie te remmen', 'Duurder lenen zorgt voor minder bestedingen'],
    Multiplier: ['Een euro extra overheidsuitgave leidt tot meer dan een euro bbp', 'Het versterkte effect van bestedingen op het bbp'],
    'Crowding out': ['Veel overheidslenen jaagt de rente op en verdringt private investeringen', 'De overheid duwt bedrijven van de kapitaalmarkt'],
    Hoogconjunctuur: ['Lage werkloosheid en hoge inflatie, de economie draait op volle toeren', 'In de hausse is er bijna geen werkloosheid'],
    Recessie: ['Een periode waarin het bbp krimpt', 'Twee kwartalen achtereen daalt de productie'],
    'Lopende rekening': ['Het deel van de betalingsbalans met goederen, diensten en inkomens', 'Hier staat de handel met het buitenland geregistreerd'],
  },
};
