// VWO Wiskunde A - situaties per begrip.
export default {
  A: {
    Groeifactor: ['Een prijs stijgt 20%, dan vermenigvuldig je met 1,20', 'Het getal waarmee je vermenigvuldigt om de nieuwe waarde te krijgen', 'Van 200 naar 250 hoort bij de factor 1,25'],
    Groeipercentage: ['De prijs neemt met 15% af per stap', 'De procentuele toename of afname per periode'],
    Macht: ['x tot de derde betekent x keer x keer x', 'Herhaald vermenigvuldigen met hetzelfde grondtal'],
    Wortel: ['De wortel van 9 is 3, want 3 in het kwadraat is 9', 'De bewerking die kwadrateren ongedaan maakt'],
    Herleiden: ['Je werkt de haakjes weg en telt gelijksoortige termen op', 'Een uitdrukking zo eenvoudig mogelijk schrijven'],
    'Vergelijking oplossen': ['Je zoekt de x waarvoor 2x + 6 = 0 klopt', 'De onbekende vinden waarvoor de gelijkheid geldt'],
    Procent: ['Je berekent 5% van 240 als 240 keer 0,05', 'Een deel per honderd'],
    'Wetenschappelijke notatie': ['Het getal 0,003 schrijf je als 3 keer tien tot de min drie', 'Een getal als a keer een macht van tien'],
    Verhouding: ['Twee stukken in de verhouding 3 staat tot 4', 'De onderlinge grootte van twee getallen'],
    Intersect: ['Op de grafische rekenmachine zoek je zo het snijpunt van twee grafieken', 'De functie waarmee je een snijpunt berekent'],
  },
  B: {
    Faculteit: ['Het aantal volgordes van 4 personen op een rij is 4 keer 3 keer 2 keer 1', 'Het product van alle getallen tot en met n'],
    Permutatie: ['Je zet mensen in een bepaalde volgorde op een podium', 'Een greep waarbij de volgorde wél meetelt'],
    Combinatie: ['Je kiest een groepje waarbij de volgorde niet uitmaakt', 'Twee vrienden uit een groep kiezen, wie eerst maakt niet uit'],
    Somregel: ['Je kiest een shirt OF een broek, dan tel je de mogelijkheden op', 'Bij een of-keuze tel je de aantallen op'],
    Productregel: ['Je kiest een shirt EN een broek, dan vermenigvuldig je', 'Bij een en-keuze vermenigvuldig je de aantallen'],
    Logaritme: ['Het antwoord op de vraag: tot welke macht moet ik 2 verheffen om 8 te krijgen', 'De exponent waarmee je een grondtal tot een getal maakt'],
    Grondtal: ['In tweelog is 2 het getal dat je tot een macht verheft', 'De basis van een macht of logaritme'],
    'Exponentiële vergelijking': ['In 2 tot de macht x is 16 staat de onbekende in de exponent', 'Een vergelijking met de onbekende in de exponent'],
    Machtsvergelijking: ['In x tot de derde is 8 staat de onbekende in het grondtal', 'Een vergelijking met de onbekende in het grondtal'],
    'Natuurlijke logaritme': ['De logaritme met grondtal e, ongeveer 2,718, schrijf je als ln', 'De ln-knop op je rekenmachine'],
  },
  C: {
    'Lineair verband': ['Elke maand komt er hetzelfde bedrag bij op je rekening', 'Een verband met een vaste toename per stap'],
    'Exponentieel verband': ['Een bacteriekolonie verdubbelt elk uur', 'Een verband met een vaste vermenigvuldigingsfactor per stap'],
    Machtsverband: ['De oppervlakte hangt af van de straal in het kwadraat', 'Een verband y is a keer x tot een vaste macht'],
    Richtingscoëfficiënt: ['De steilheid van de lijn: hoeveel y stijgt per stap in x', 'De a in y is ax plus b'],
    Startwaarde: ['De waarde van y op het moment dat x nul is', 'De b in y is ax plus b'],
    'Recht evenredig': ['Twee keer zoveel benzine kost twee keer zoveel geld', 'Als x verdubbelt, verdubbelt y'],
    'Omgekeerd evenredig': ['Met twee keer zoveel mensen is de klus in de helft van de tijd klaar', 'Als x verdubbelt, halveert y'],
    Periode: ['Na hoeveel tijd herhaalt een golfpatroon zich', 'De lengte waarna een periodieke grafiek zich herhaalt'],
    Amplitude: ['Hoe ver een golf maximaal van zijn evenwicht uitwijkt', 'De halve afstand tussen top en dal'],
    Asymptoot: ['De grafiek nadert deze lijn steeds dichter zonder hem te raken', 'Een lijn die de grafiek nadert maar nooit bereikt'],
  },
  D: {
    Afgeleide: ['De functie die in elk punt de helling van de grafiek geeft', 'Van x kwadraat is dit 2x'],
    Differentiequotiënt: ['De gemiddelde verandering van y gedeeld door de verandering van x', 'De gemiddelde snelheid over een heel interval'],
    Helling: ['Hoe steil de grafiek in een punt loopt', 'De steilheid van de raaklijn'],
    Raaklijn: ['De lijn die de grafiek in precies één punt raakt', 'De rechte lijn met de afgeleide als richtingscoëfficiënt'],
    'Momentane verandering': ['De snelheid op precies één moment', 'De verandering op een enkel tijdstip, de afgeleide'],
    'Gemiddelde verandering': ['De gemiddelde snelheid over de hele rit', 'De verandering over een heel interval'],
    Maximum: ['De top van de grafiek, waar de helling van stijgen naar dalen omslaat', 'Waar de afgeleide nul is en van plus naar min gaat'],
    Minimum: ['Het dal van de grafiek, waar de helling van dalen naar stijgen omslaat', 'Waar de afgeleide nul is en van min naar plus gaat'],
    Snelheid: ['De verandering van de plaats per tijdseenheid', 'De afgeleide van de plaats naar de tijd'],
    Toenamediagram: ['Een staafdiagram dat per stap de toename laat zien', 'Staven die de veranderingen per periode weergeven'],
  },
  E: {
    Verwachtingswaarde: ['Het gemiddelde aantal zessen dat je op de lange duur verwacht', 'Bij binomiaal reken je dit als n keer p'],
    Standaardafwijking: ['Hoe ver de waarden gemiddeld van het gemiddelde af liggen', 'Een maat voor de spreiding van de data'],
    'Binomiale verdeling': ['Het aantal keer kop bij twintig muntworpen', 'De discrete verdeling van het aantal successen bij n pogingen'],
    'Normale verdeling': ['De klokvormige kromme rond het gemiddelde, zoals bij lengtes', 'De continue verdeling waar 95 procent binnen twee sigma valt'],
    Nulhypothese: ['De aanname dat een nieuw medicijn geen effect heeft', 'De aanname dat er geen effect of verschil is'],
    Correlatiecoëfficiënt: ['Een getal tussen min een en een dat de samenhang van twee variabelen meet', 'De sterkte en richting van een lineair verband'],
    Mediaan: ['De middelste waarde als je alle metingen op volgorde zet', 'De middenmaat die niet meebeweegt met een uitschieter'],
    Gemiddelde: ['De som van alle waarden gedeeld door hun aantal', 'De middenmaat die wel gevoelig is voor uitschieters'],
    Steekproef: ['Je ondervraagt duizend kiezers in plaats van het hele land', 'Een deel van de populatie dat je onderzoekt'],
    Significantieniveau: ['De grens, vaak 5 procent, waaronder je de nulhypothese verwerpt', 'De afgesproken verwerpingsgrens van een toets'],
  },
  F: {
    'Recursieve formule': ['Elke term reken je uit de vorige, zoals u volgende is u plus drie', 'Een formule die de volgende term uit de vorige geeft'],
    'Directe formule': ['Je vult n meteen in om de n-de term te krijgen', 'Een formule die u-n rechtstreeks uit n berekent'],
    Beginwaarde: ['De startterm u-nul waarmee de rij begint', 'De waarde waar het model mee start'],
    'Discreet dynamisch model': ['Een model dat een grootheid stap voor stap laat veranderen', 'Elke stap reken je de nieuwe waarde uit de oude'],
    Evenwicht: ['Een waarde die bij de volgende stap niet meer verandert', 'De stationaire toestand van het model'],
    'Lineaire groei': ['Er komt elke stap hetzelfde vaste getal bij', 'Groei met een vaste toename per stap'],
    'Exponentiële groei': ['Elke stap vermenigvuldig je met dezelfde factor', 'Een populatie die telkens verdubbelt'],
    'Logistische groei': ['Eerst snelle groei, daarna afvlakken naar een grens', 'Groei die de draagkracht nadert'],
    Draagkracht: ['Het maximale aantal dieren dat een gebied kan voeden', 'De maximale omvang die de omgeving toelaat'],
    Convergentie: ['De rij nadert steeds dichter een grenswaarde', 'Het naderen van een vaste eindwaarde'],
  },
};
