// VWO Geschiedenis - situaties per begrip.
export default {
  A: {
    Aanleiding: ['De moord op Franz Ferdinand was de directe trigger van WO I', 'De directe, concrete trigger van een gebeurtenis'],
    Oorzaak: ['De dieperliggende spanningen tussen de grootmachten', 'Een dieperliggende reden waardoor iets gebeurt'],
    Bronkritiek: ['Je vraagt wie de bron maakte, met welk doel en wanneer', 'Het kritisch beoordelen van een bron'],
    'Continuïteit': ['Ondanks alle veranderingen bleef de kerk eeuwenlang machtig', 'Elementen die door de tijd gelijk blijven'],
    Verandering: ['Door de industrialisatie veranderde het dagelijks leven ingrijpend', 'Elementen die door de tijd anders worden'],
    'Primaire bron': ['Een dagboek, foto of verdrag uit de onderzochte periode', 'Materiaal uit de tijd zelf'],
    'Secundaire bron': ['Een geschiedenisboek dat het verleden achteraf analyseert', 'Een latere analyse van het verleden'],
    Periodisering: ['Je deelt de geschiedenis in tijdvakken met eigen kenmerken', 'Het indelen van de geschiedenis in tijdvakken'],
    Anachronisme: ['Een ridder met een horloge in een film: uit de verkeerde tijd', 'Iets in de verkeerde tijd plaatsen'],
    'Historische context': ['Je plaatst een pamflet in de tijd waarin het geschreven werd', 'De omstandigheden van de tijd waarin een bron ontstond'],
  },
  B: {
    'Koude Oorlog': ['VS en USSR stonden 1947 tot 1991 tegenover elkaar zonder directe oorlog', 'Het ideologische conflict tussen VS en USSR'],
    Dekolonisatie: ['Na 1945 werden veel Aziatische en Afrikaanse landen onafhankelijk', 'Het onafhankelijk worden van kolonies'],
    Totalitarisme: ['De staat controleert politiek, economie, media en het hele leven', 'Volledige overheidscontrole over alles'],
    Holocaust: ['De nazi\'s vermoordden systematisch miljoenen Joden', 'De genocide door het nazi-regime'],
    'Bipolaire wereldorde': ['De wereld was na WO II verdeeld in twee blokken', 'Twee machtsblokken rond VS en USSR'],
    'Verenigde Naties': ['In 1945 opgericht voor de vrede, opvolger van de Volkenbond', 'De VN voor internationale vrede'],
    Nationalisme: ['Een sterk gevoel van eenheid en trots op de eigen natie', 'Nationale eenheid en eigen superioriteit'],
    Imperialisme: ['Europese landen veroverden koloniën om hun macht uit te breiden', 'Het streven naar koloniën en machtsuitbreiding'],
    'Beurskrach 1929': ['De aandelenmarkt van Wall Street stortte in en de wereldcrisis begon', 'De instorting van Wall Street in 1929'],
    'Berlijnse Muur': ['De muur van 1961 tot 1989 werd het symbool van de Koude Oorlog', 'Het symbool van de Koude Oorlog'],
  },
  C: {
    'Continuïteit': ['Ondanks de eeuwen bleven bepaalde tradities hetzelfde', 'Wat door de tijd heen gelijk blijft'],
    Verandering: ['In korte tijd veranderde de samenleving ingrijpend', 'Wat door de tijd heen anders wordt'],
    'Lange lijn': ['De groei van de democratie loopt door de hele moderne tijd', 'Een ontwikkeling over een lange periode'],
    Thema: ['Je volgt het thema migratie door alle tijdvakken heen', 'Eén onderwerp dat je door de tijd volgt'],
    'Oorzaak-gevolg': ['Je legt uit waarom een oorlog uitbrak en wat eruit voortkwam', 'De relatie tussen waarom en wat eruit volgt'],
    Keerpunt: ['De val van de Muur was een moment van ingrijpende verandering', 'Een moment van ingrijpende verandering'],
    Ontwikkeling: ['De geleidelijke groei van de industrie door de eeuwen', 'Een geleidelijke verandering door de tijd'],
    Trend: ['Een langlopende richting, zoals de toenemende verstedelijking', 'Een langlopende richting van verandering'],
    Periodisering: ['Je deelt de tijd in overzichtelijke tijdvakken', 'Het indelen van de tijd in tijdvakken'],
    Vergelijking: ['Je gaat na wat bleef en wat veranderde tussen twee tijden', 'Nagaan wat bleef en wat veranderde'],
  },
  D: {
    Rechtsstaat: ['Ook de overheid moet zich aan de wet houden', 'Een staat waarin de macht aan wetten gebonden is'],
    'Trias politica': ['De wetgevende, uitvoerende en rechterlijke macht zijn gescheiden', 'De scheiding der machten'],
    Grondwet: ['De hoogste wet met de spelregels van de staat', 'De wet die boven alle andere wetten staat'],
    'Algemeen kiesrecht': ['Elke volwassene mag stemmen, ongeacht bezit', 'Het recht van iedereen om te stemmen'],
    'Parlementaire democratie': ['Het volk kiest een parlement dat de regering controleert', 'Een gekozen parlement dat de regering controleert'],
    Grondrechten: ['De vrijheid van meningsuiting en het recht op een eerlijk proces', 'De fundamentele rechten van burgers'],
    'Ministeriële verantwoordelijkheid': ['Een minister moet zich in het parlement verantwoorden', 'Ministers leggen verantwoording af aan het parlement'],
    Censuskiesrecht: ['Vroeger mocht alleen wie genoeg belasting betaalde stemmen', 'Kiesrecht alleen voor belastingbetalers'],
    'Constitutionele monarchie': ['Er is een koning, maar de grondwet beperkt zijn macht', 'Een koningschap beperkt door de grondwet'],
    'Scheiding kerk en staat': ['De overheid bemoeit zich niet met het geloof en andersom', 'Religie en overheid worden gescheiden gehouden'],
  },
  E: {
    'Primaire bron': ['Een originele brief of foto uit de onderzochte tijd', 'Materiaal uit de tijd zelf'],
    'Secundaire bron': ['Een geschiedenisboek dat het verleden achteraf beschrijft', 'Een latere analyse van het verleden'],
    Representativiteit: ['Je vraagt of deze ene bron typisch is voor het geheel', 'In hoeverre een bron typisch is'],
    Betrouwbaarheid: ['Je gaat na of de informatie in de bron klopt', 'In hoeverre de informatie waar is'],
    Anachronisme: ['Een fout waarbij iets uit de verkeerde tijd wordt geplaatst', 'Iets in de verkeerde tijd plaatsen'],
    'Standplaatsgebonden bron': ['De schrijver kleurt het verhaal vanuit zijn eigen gezichtspunt', 'Een bron gekleurd door het gezichtspunt van de maker'],
    Oorzaak: ['De reden waardoor een gebeurtenis plaatsvond', 'De reden waardoor iets gebeurt'],
    Gevolg: ['Wat er na een gebeurtenis uit voortkwam', 'Wat uit een gebeurtenis voortvloeit'],
    Historicus: ['Iemand die het verleden onderzoekt en beschrijft', 'Een onderzoeker van het verleden'],
    Archivaris: ['Iemand die oude documenten bewaart en ordent', 'Een beheerder van historische stukken'],
  },
};
