// VWO Natuurkunde - situaties per begrip.
export default {
  A: {
    'Significante cijfers': ['De betekenisvolle cijfers in een meetwaarde zoals 0,04070', 'Ze laten zien hoe nauwkeurig een meting is'],
    Snelheid: ['De helling van een (x,t)-grafiek geeft deze grootheid', 'Hoeveel meter je per seconde aflegt'],
    Versnelling: ['De helling van een (v,t)-grafiek geeft deze grootheid', 'Hoe snel de snelheid per seconde verandert'],
    '(x,t)-diagram': ['Een grafiek van de plaats tegen de tijd, met de snelheid als helling', 'Hieruit lees je waar iets is op elk moment'],
    '(v,t)-diagram': ['Een grafiek van de snelheid tegen de tijd; de oppervlakte eronder is de afstand', 'De helling geeft de versnelling, het oppervlak de afstand'],
    'Recht evenredig verband': ['De grafiek is een rechte lijn door de oorsprong', 'Twee keer zo groot geeft twee keer zo veel'],
    'Omgekeerd evenredig verband': ['De grafiek is een hyperbool: y wordt kleiner als x groter wordt', 'Twee keer zo groot geeft de helft'],
    Meetonzekerheid: ['Je verkleint deze door vaker te meten en te middelen', 'De marge waarbinnen de echte waarde ligt'],
    Newton: ['De SI-eenheid van kracht', 'Een kracht van 1 kilogram maal 1 meter per seconde in het kwadraat'],
    Watt: ['De SI-eenheid van vermogen, joule per seconde', 'Hoeveel energie een apparaat per seconde gebruikt'],
    'Numeriek model': ['Je berekent de beweging stap voor stap in kleine tijdstapjes', 'Een computer rekent de baan uit met kleine stapjes tijd'],
  },
  B: {
    Golflengte: ['De afstand tussen twee opeenvolgende golftoppen', 'Uit v = f·λ bereken je deze bij bekende snelheid en frequentie'],
    Frequentie: ['Het aantal trillingen per seconde, in hertz', 'Een hogere waarde geeft een hogere toon'],
    'Transversale golf': ['De trilling staat loodrecht op de richting waarin de golf gaat, zoals bij licht', 'Een golf op het water, en alleen deze soort kun je polariseren'],
    'Longitudinale golf': ['De trilling gaat in dezelfde richting als de golf, zoals bij geluid', 'Een drukgolf van samengeperste en uitgerekte lucht'],
    'Staande golf': ['Twee tegengestelde golven vormen een patroon met stilstaande punten', 'Op een snaar ontstaan vaste knopen en buiken'],
    Knoop: ['Een punt in een staande golf dat helemaal stilstaat', 'Aan de uiteinden van een trillende snaar zitten deze punten'],
    Buik: ['Een punt in een staande golf met de grootste uitwijking', 'Precies tussen twee stilstaande punten trilt het maximaal'],
    Interferentie: ['Twee golven versterken of doven elkaar afhankelijk van hun fase', 'In fase geeft versterking, in tegenfase uitdoving'],
    Diffractie: ['Golven buigen om een obstakel of door een smalle opening heen', 'Licht dat door een spleet gaat, waaiert uit'],
    Breking: ['Licht verandert van richting als het van lucht naar glas gaat', 'De straal buigt naar de normaal toe in een dichter medium'],
    'Doppler-effect': ['De sirene klinkt hoger bij nadering en lager na het passeren', 'Beweegt de bron naar je toe, dan hoor je een hogere toon'],
    Resonantie: ['De amplitude loopt sterk op als je op de eigenfrequentie aandrijft', 'Een brug die op zijn eigen trilling wordt aangedreven, kan bezwijken'],
  },
  C: {
    Kracht: ['Een duw of trek die een voorwerp versnelt of vervormt', 'Volgens F = m·a bepaalt hij de versnelling'],
    Arbeid: ['Een kracht verplaatst een kist over een afstand', 'W = F·s: kracht maal weg in de richting van de kracht'],
    'Kinetische energie': ['De bewegingsenergie van een rijdende auto, ½mv²', 'Verdubbel je de snelheid, dan wordt deze vier keer zo groot'],
    'Potentiële energie': ['De hoogte-energie van een steen boven de grond', 'Hoe hoger je iets tilt, hoe meer je hiervan opslaat'],
    Energiebehoud: ['Zonder wrijving blijft de som van beweging- en hoogte-energie gelijk', 'Bij het vallen wordt hoogte-energie omgezet in bewegingsenergie'],
    Impuls: ['Het product van massa en snelheid van een voorwerp', 'Een zware, snelle vrachtwagen heeft er veel van'],
    Impulsbehoud: ['Twee schaatsers duwen elkaar af, samen blijft de impuls nul', 'Zonder externe kracht verandert de totale impuls niet'],
    Vermogen: ['Hoeveel arbeid een motor per seconde levert, in watt', 'P = W/t: energie gedeeld door de tijd'],
    Veerkracht: ['Een uitgerekte veer trekt terug naar zijn evenwichtsstand', 'F = −kx: de kracht wijst tegengesteld aan de uitrekking'],
    'Middelpuntzoekende kracht': ['De kracht die een voorwerp in een cirkelbaan houdt, naar het midden gericht', 'Ze staat loodrecht op de beweging en verricht geen arbeid'],
    'Tweede wet van Newton': ['De nettokracht is massa maal versnelling', 'Meer kracht op dezelfde massa geeft meer versnelling'],
    'Derde wet van Newton': ['Duw je tegen een muur, dan duwt de muur even hard terug', 'Actie en reactie zijn even groot en tegengesteld gericht'],
  },
};
