// VWO Natuurkunde - situaties per begrip.
export default {
  A: {
    'Significante cijfers': ['De betekenisvolle cijfers in een meetwaarde zoals 0,04070', 'Ze laten zien hoe nauwkeurig een meting is'],
    Snelheid: ['De helling van een (x,t)-grafiek geeft deze grootheid', 'Hoeveel meter je per seconde aflegt'],
    Versnelling: ['De helling van een (v,t)-grafiek geeft deze grootheid', 'Hoe snel de snelheid per seconde verandert'],
    '(x,t)-diagram': ['Een grafiek van de plaats tegen de tijd, met de snelheid als helling', 'Hieruit lees je waar iets is op elk moment'],
    '(v,t)-diagram': ['Een grafiek van de snelheid tegen de tijd; de oppervlakte eronder is de afstand', 'De helling geeft de versnelling, het oppervlak de afstand'],
    'Recht evenredig verband': ['De grafiek is een rechte lijn door de oorsprong', 'Twee keer zo groot geeft twee keer zo veel'],
    'Omgekeerd evenredig verband': ['De grafiek is een hyperbool: y wordt kleiner als x groter wordt', 'Twee keer zo groot geeft de helft'],
    Meetonzekerheid: ['Je verkleint deze door vaker te meten en te middelen', 'De marge waarbinnen de echte waarde ligt'],
    Newton: ['De SI-eenheid van kracht', 'Een kracht van 1 kilogram maal 1 meter per seconde in het kwadraat'],
    Watt: ['De SI-eenheid van vermogen, joule per seconde', 'Hoeveel energie een apparaat per seconde gebruikt'],
    'Numeriek model': ['Je berekent de beweging stap voor stap in kleine tijdstapjes', 'Een computer rekent de baan uit met kleine stapjes tijd'],
  },
  B: {
    Golflengte: ['De afstand tussen twee opeenvolgende golftoppen', 'Uit v = f·λ bereken je deze bij bekende snelheid en frequentie'],
    Frequentie: ['Het aantal trillingen per seconde, in hertz', 'Een hogere waarde geeft een hogere toon'],
    'Transversale golf': ['De trilling staat loodrecht op de richting waarin de golf gaat, zoals bij licht', 'Een golf op het water, en alleen deze soort kun je polariseren'],
    'Longitudinale golf': ['De trilling gaat in dezelfde richting als de golf, zoals bij geluid', 'Een drukgolf van samengeperste en uitgerekte lucht'],
    'Staande golf': ['Twee tegengestelde golven vormen een patroon met stilstaande punten', 'Op een snaar ontstaan vaste knopen en buiken'],
    Knoop: ['Een punt in een staande golf dat helemaal stilstaat', 'Aan de uiteinden van een trillende snaar zitten deze punten'],
    Buik: ['Een punt in een staande golf met de grootste uitwijking', 'Precies tussen twee stilstaande punten trilt het maximaal'],
    Interferentie: ['Twee golven versterken of doven elkaar afhankelijk van hun fase', 'In fase geeft versterking, in tegenfase uitdoving'],
    Diffractie: ['Golven buigen om een obstakel of door een smalle opening heen', 'Licht dat door een spleet gaat, waaiert uit'],
    Breking: ['Licht verandert van richting als het van lucht naar glas gaat', 'De straal buigt naar de normaal toe in een dichter medium'],
    'Doppler-effect': ['De sirene klinkt hoger bij nadering en lager na het passeren', 'Beweegt de bron naar je toe, dan hoor je een hogere toon'],
    Resonantie: ['De amplitude loopt sterk op als je op de eigenfrequentie aandrijft', 'Een brug die op zijn eigen trilling wordt aangedreven, kan bezwijken'],
  },
  C: {
    Kracht: ['Een duw of trek die een voorwerp versnelt of vervormt', 'Volgens F = m·a bepaalt hij de versnelling'],
    Arbeid: ['Een kracht verplaatst een kist over een afstand', 'W = F·s: kracht maal weg in de richting van de kracht'],
    'Kinetische energie': ['De bewegingsenergie van een rijdende auto, ½mv²', 'Verdubbel je de snelheid, dan wordt deze vier keer zo groot'],
    'Potentiële energie': ['De hoogte-energie van een steen boven de grond', 'Hoe hoger je iets tilt, hoe meer je hiervan opslaat'],
    Energiebehoud: ['Zonder wrijving blijft de som van beweging- en hoogte-energie gelijk', 'Bij het vallen wordt hoogte-energie omgezet in bewegingsenergie'],
    Impuls: ['Het product van massa en snelheid van een voorwerp', 'Een zware, snelle vrachtwagen heeft er veel van'],
    Impulsbehoud: ['Twee schaatsers duwen elkaar af, samen blijft de impuls nul', 'Zonder externe kracht verandert de totale impuls niet'],
    Vermogen: ['Hoeveel arbeid een motor per seconde levert, in watt', 'P = W/t: energie gedeeld door de tijd'],
    Veerkracht: ['Een uitgerekte veer trekt terug naar zijn evenwichtsstand', 'F = −kx: de kracht wijst tegengesteld aan de uitrekking'],
    'Middelpuntzoekende kracht': ['De kracht die een voorwerp in een cirkelbaan houdt, naar het midden gericht', 'Ze staat loodrecht op de beweging en verricht geen arbeid'],
    'Tweede wet van Newton': ['De nettokracht is massa maal versnelling', 'Meer kracht op dezelfde massa geeft meer versnelling'],
    'Derde wet van Newton': ['Duw je tegen een muur, dan duwt de muur even hard terug', 'Actie en reactie zijn even groot en tegengesteld gericht'],
  },
  D: {
    Stroomsterkte: ['De hoeveelheid lading die per seconde door de draad gaat, in ampère', 'I = U/R: uit de spanning en de weerstand bereken je deze'],
    Spanning: ['De elektrische duw die de stroom aandrijft, in volt', 'De batterij levert dit verschil in energie per lading'],
    Weerstand: ['Iets dat de stroom tegenwerkt, in ohm', 'Een dunne of lange draad heeft er meer van'],
    'Wet van Ohm': ['Het verband U = I·R tussen spanning, stroom en weerstand', 'Bij 12 V en 220 Ω volgt de stroom uit deze wet'],
    Serieschakeling: ['De componenten staan achter elkaar en de stroom is overal gelijk', 'De spanningen over de onderdelen tellen op'],
    Parallelschakeling: ['De componenten staan naast elkaar en de spanning is overal gelijk', 'De stromen door de takken tellen op'],
    'Elektrisch veld': ['Rond een lading heerst een gebied dat kracht op andere ladingen uitoefent', 'E = kQ/r²: het veld neemt af met het kwadraat van de afstand'],
    'Magnetisch veld': ['Rond een stroomdraad ontstaat een gebied dat op een kompas werkt', 'Een bewegende lading wekt dit op'],
    'Wet van Faraday': ['Een veranderende magnetische flux wekt een spanning op', 'Beweeg een magneet in een spoel en er ontstaat stroom'],
    'Wet van Lenz': ['De geïnduceerde stroom werkt de verandering die hem veroorzaakt tegen', 'De opgewekte stroom remt de fluxverandering af'],
    Zelfinductie: ['Een spoel verzet zich tegen een verandering van de stroom', 'Bij het inschakelen loopt de stroom door een spoel traag op'],
    Condensator: ['Een component die lading en een elektrisch veld opslaat', 'Na de tijd RC is hij tot 63 procent opgeladen'],
  },
  E: {
    Alfastraling: ['Straling van heliumkernen die al door een vel papier wordt gestopt', 'Zware, geladen deeltjes die weinig doordringen', 'Radon in huis zendt deze straling uit'],
    Bètastraling: ['Straling van snelle elektronen, die verder doordringt dan alfa', 'Deze straling wordt door een dun laagje aluminium tegengehouden', 'Koolstof-14 vervalt onder uitzending van deze straling'],
    Gammastraling: ['Straling zonder massa of lading die zelfs door lood dringt', 'De meest doordringende soort straling, een foton', 'Bij het bestralen van tumoren gebruikt men deze straling'],
    Halveringstijd: ['De tijd waarin de helft van de kernen vervalt', 'Na deze tijd is nog de helft van de stof over', 'Bij koolstofdatering gebruik je deze eigenschap van C-14'],
    Activiteit: ['Het aantal vervallen kernen per seconde, dat exponentieel daalt', 'Hoe minder onvervallen kernen, hoe kleiner deze wordt', 'Een geigerteller meet deze grootheid, in becquerel'],
    'Ioniserende straling': ['Straling die elektronen losslaat en zo ionen maakt', 'Deze straling kan cellen beschadigen'],
    Isotoop: ['Een atoomsoort met evenveel protonen maar een ander aantal neutronen', 'Koolstof-12 en koolstof-14 zijn hiervan voorbeelden'],
    'Radioactief verval': ['Een onstabiele kern valt uiteen en zendt straling uit', 'Het spontane uiteenvallen van een atoomkern', 'Uranium verandert zo langzaam in lood'],
  },
  F: {
    'Foto-elektrisch effect': ['Licht slaat pas elektronen los als de frequentie hoog genoeg is', 'Meer intensiteit onder de drempelfrequentie helpt niet'],
    Foton: ['Een pakketje licht-energie met E = h·f', 'Licht bestaat uit deze energiepakketjes'],
    Uittreedarbeid: ['De minimale energie om een elektron uit een metaal te maken', 'De drempel bij het foto-elektrisch effect'],
    'De-Broglie-golflengte': ['De golflengte die een bewegend deeltje heeft: λ = h/p', 'Hoe groter de impuls, hoe kleiner deze golflengte'],
    Alfaverval: ['Een kern zendt een heliumkern uit', 'Het atoomnummer daalt hierbij met twee'],
    Bètaverval: ['Een neutron wordt een proton onder uitzending van een elektron', 'Het atoomnummer stijgt hierbij met één'],
    Kernsplitsing: ['Een zware kern valt uiteen in lichtere kernen met energie', 'In een kerncentrale splijt uranium'],
    Kernfusie: ['Lichte kernen smelten samen tot een zwaardere met energie', 'In de zon versmelten waterstofkernen tot helium'],
    Tijddilatatie: ['Een bewegende klok loopt langzamer bij zeer hoge snelheid', 'Astronauten verouderen minutieus langzamer op hoge snelheid'],
    Relativiteitstheorie: ['De theorie die geldt bij snelheden dicht bij de lichtsnelheid', 'Hier vervangt ze de klassieke mechanica'],
  },
  G: {
    Spectrum: ['De verdeling van sterlicht over kleuren die temperatuur en samenstelling verraadt', 'Uit de kleurlijnen lees je af waaruit een ster bestaat', 'Donkere lijnen in het licht verraden welke stoffen in de ster zitten'],
    Roodverschuiving: ['Het licht van een wegbewegend sterrenstelsel verschuift naar rood', 'Een teken dat een bron zich van ons af beweegt', 'Hoe verder een sterrenstelsel, hoe groter deze verschuiving'],
    'Uitdijend heelal': ['Verre sterrenstelsels bewegen allemaal van ons af', 'Het heelal wordt steeds groter', 'De ontdekking van Hubble dat alles uit elkaar beweegt'],
    Lichtjaar: ['De afstand die het licht in één jaar aflegt', 'Een maat voor de enorme afstanden in het heelal'],
    Röntgenstraling: ['Doordringende straling waarmee een arts je botten in beeld brengt', 'Op de foto van een gebroken arm zie je deze straling gebruikt', 'Op het vliegveld scant men bagage met deze straling'],
    Echografie: ['Een beeld van een ongeboren baby, gemaakt met ultrageluid', 'Deze techniek gebruikt geluidsgolven, geen straling', 'De hartslag van een baby wordt hiermee zichtbaar gemaakt'],
    MRI: ['Een scan met sterke magneten en radiogolven', 'Zonder straling maakt deze techniek de weke delen zichtbaar', 'Voor een blik in de hersenen kies je deze scan'],
    Gammastraling: ['De straling met de hoogste energie per foton', 'Van alle straling heeft deze de kortste golflengte'],
  },
  H: {
    'Behoud van energie': ['Energie verandert van vorm maar de totale hoeveelheid blijft gelijk', 'Bij het vallen wordt hoogte-energie bewegingsenergie, samen constant', 'Een slinger wisselt hoogte- en bewegingsenergie steeds uit'],
    'Behoud van impuls': ['Bij een botsing zonder externe kracht blijft de totale m·v gelijk', 'De som van de impulsen is vóór en na de botsing gelijk', 'De terugslag van een geweer volgt uit deze wet'],
    'Behoud van lading': ['De totale elektrische lading in een gesloten systeem blijft constant', 'Er komt evenveel positieve als negatieve lading bij', 'Bij wrijven verplaatst lading, maar de totale hoeveelheid blijft gelijk'],
    Model: ['Een vereenvoudigde voorstelling die binnen grenzen klopt', 'Het bolletjesmodel van het atoom is er een voorbeeld van', 'Een weersverwachting komt uit een rekenmodel'],
    Geldigheidsgebied: ['Het bereik waarbinnen een model de werkelijkheid goed beschrijft', 'Buiten dit bereik gaat een model mank', 'De klassieke mechanica geldt niet meer bij de lichtsnelheid'],
    'Deeltjesmodel van licht': ['Licht als fotonen, waarmee je het foto-elektrisch effect verklaart', 'In dit model draagt licht energie in pakketjes', 'Zonnecellen werken dankzij dit karakter van licht'],
    'Golfmodel van licht': ['Licht als golf, waarmee je interferentie en diffractie verklaart', 'In dit model buigt en versterkt licht zich als een golf', 'Een zeepbel toont kleuren door interferentie, dat is golfgedrag'],
    Relativiteitstheorie: ['De theorie die je gebruikt bij snelheden dicht bij die van het licht', 'Hier vervangt ze de klassieke mechanica'],
  },
  I: {
    Meetonzekerheid: ['De marge waarbinnen de echte waarde ligt, met een plus-minteken', 'Je noteert een meting als een waarde met een foutmarge', 'Een resultaat schrijf je als 3,2 plus of min 0,1 seconde'],
    'Systematische fout': ['De meting wijkt telkens dezelfde kant op af, bijvoorbeeld door een verkeerd ijkpunt', 'Een balans die altijd 2 gram te veel aangeeft', 'Een thermometer die overal één graad te laag wijst'],
    'Toevallige fout': ['De meting schommelt willekeurig rond de echte waarde', 'Je verkleint deze door vaker te meten en te middelen', 'De ene keer 12,1 s, de andere 12,3 s bij dezelfde meting'],
    Variabele: ['De grootheid die je in een onderzoek verandert of juist constant houdt', 'Om het effect te zien laat je er één variëren en houd je de rest gelijk', 'De temperatuur die je stap voor stap verhoogt in een proef'],
    'Programma van eisen': ['De lijst met eisen waarmee je een ontwerpopdracht begint', 'Voordat je iets bouwt, zet je op wat het moet kunnen', 'De brug moet honderd kilo dragen en twee meter breed zijn, dat staat vooraf vast'],
    Afleesnauwkeurigheid: ['Hoe nauwkeurig je een schaal kunt aflezen, bij een mm-liniaal ongeveer een halve mm', 'De fijnheid waarmee je een meetinstrument afleest', 'Met een digitale weegschaal op 0,1 gram lees je fijner af'],
    Betrouwbaarheid: ['De mate waarin een meting herhaalbaar is en te vertrouwen', 'Meer meetpunten maken een resultaat betrouwbaarder'],
    Hypothese: ['Een toetsbare verwachting die je vóór het experiment opstelt', 'Je gok van tevoren over de uitkomst'],
  },
};
