// VWO Scheikunde - gouden-stijl contentspec. Vervangt de crude generatorvragen
// door authored bereken-/inzichtvragen met per-optie-uitleg + situaties.
const V = (domein, naam, intro, secties, concepten, vragen) => ({ niveau: 'vwo', vak: 'sk', domein, naam, intro, secties, concepten, vragen });

export default [
  V('A', 'Vaardigheden',
    `Bij de <strong>rekenvaardigheden</strong> werk je met de <strong>mol</strong> als eenheid van hoeveelheid stof. Met de <strong>molaire massa</strong> reken je tussen gram en mol, met de <strong>concentratie</strong> tussen mol en volume, en de <strong>coëfficiënten</strong> van een reactievergelijking geven de <strong>molverhouding</strong>.`,
    [
      { h: '1. Rekenen met mol', p: [
        `De <strong>mol</strong> is de eenheid voor hoeveelheid stof: één mol bevat <strong>6,022·10²³</strong> deeltjes (de <strong>constante van Avogadro</strong>). Met de <strong>molaire massa</strong> M (in g/mol) reken je tussen massa en aantal mol.`],
        formula: { label: 'Massa en mol', eq: 'm = n · M   ⟺   n = m / M', note: 'n = aantal mol, m = massa (g), M = molaire massa (g/mol).' },
        worked: { q: 'Hoeveel mol is 36 g water? (M = 18 g/mol)', steps: ['Gebruik n = m / M', 'n = 36 / 18 = 2 mol'], ans: '2 mol' } },
      { h: '2. Concentratie', p: [
        `De <strong>concentratie</strong> geeft het aantal mol opgeloste stof per liter oplossing, in mol/L.`],
        formula: { label: 'Concentratie', eq: 'c = n / V', note: 'c in mol/L, n in mol, V in liter.' },
        worked: { q: 'Wat is de concentratie van 0,2 mol in 0,5 L?', steps: ['Gebruik c = n / V', 'c = 0,2 / 0,5 = 0,4 mol/L'], ans: '0,4 mol/L' } },
      { h: '3. Molverhouding en behoud van massa', p: [
        `De <strong>coëfficiënten</strong> in een kloppende reactievergelijking geven de <strong>molverhouding</strong>. In 2 H₂ + O₂ → 2 H₂O reageert waterstof en zuurstof in de verhouding 2 : 1. Volgens de <strong>wet van behoud van massa</strong> (Lavoisier) blijft de totale massa in een afgesloten systeem gelijk: atomen worden alleen herschikt.`] },
      { h: '4. Veilig werken', p: [
        `<strong>GHS-pictogrammen</strong> waarschuwen voor gevaar: een vlam betekent brandbaar, een doodshoofd giftig. Een sterk zuur verdun je door het <strong>zuur voorzichtig bij het water</strong> te gieten (nooit andersom), zodat de vrijkomende warmte zich veilig verdeelt.`] },
    ],
    [
      { t: 'Mol', d: 'de eenheid voor hoeveelheid stof; één mol bevat 6,022·10²³ deeltjes', k: 'eenheid voor hoeveelheid stof', fout: ['Molaire massa', 'Concentratie'] },
      { t: 'Constante van Avogadro', d: 'het aantal deeltjes in één mol: 6,022·10²³ per mol', k: '6,022·10²³ deeltjes per mol', fout: ['Mol'] },
      { t: 'Molaire massa', d: 'de massa van één mol van een stof, in gram per mol', k: 'massa van één mol in g/mol', fout: ['Mol', 'Molverhouding'] },
      { t: 'Concentratie', d: 'de hoeveelheid opgeloste stof per liter oplossing, in mol/L', k: 'mol opgeloste stof per liter', fout: ['Molaire massa'] },
      { t: 'Molverhouding', d: 'de verhouding tussen de aantallen mol, af te lezen uit de coëfficiënten', k: 'verhouding uit de coëfficiënten', fout: ['Molaire massa'] },
      { t: 'Significante cijfers', d: 'de betekenisvolle cijfers in een meetwaarde', k: 'betekenisvolle cijfers', fout: ['Molaire massa'] },
      { t: 'Wet van behoud van massa', d: 'in een afgesloten reactie blijft de totale massa gelijk', k: 'massa blijft behouden', fout: ['Molverhouding'] },
      { t: 'GHS-pictogram', d: 'een symbool dat waarschuwt voor het gevaar van een stof', k: 'waarschuwt voor gevaar', fout: ['Significante cijfers'] },
    ],
    [
      { v: 'Hoeveel deeltjes zitten er in 1 mol?', o: ['6,022·10²³', '3,00·10⁸', '9,81', '1,60·10⁻¹⁹'], c: 0, d: 1, uo: ['Klopt: de constante van Avogadro, 6,022·10²³ deeltjes per mol.', 'Nee, 3,00·10⁸ m/s is de lichtsnelheid.', 'Nee, 9,81 m/s² is de valversnelling g.', 'Nee, 1,60·10⁻¹⁹ C is de elementaire lading.'], uh: '1 mol = 6,022·10²³ deeltjes (constante van Avogadro).' },
      { v: 'Hoe bereken je de massa m uit het aantal mol n en de molaire massa M?', o: ['m = n / M', 'm = n · M', 'm = M / n', 'm = n + M'], c: 1, d: 2, uo: ['Nee, delen door M klopt niet met de eenheden.', 'Klopt: m = n · M (mol × g/mol = gram).', 'Nee, dat is omgekeerd.', 'Nee, optellen kan niet, de eenheden verschillen.'], uh: 'm = n · M, en dus n = m / M.' },
      { v: 'In 2 H₂ + O₂ → 2 H₂O is de molverhouding H₂ : O₂ gelijk aan', o: ['1 : 1', '2 : 1', '1 : 2', '2 : 2'], c: 1, d: 2, uo: ['Nee, de coëfficiënten zijn niet gelijk.', 'Klopt: de coëfficiënten 2 en 1 geven 2 : 1.', 'Nee, dat is de omgekeerde verhouding.', 'Nee, 2 : 2 vereenvoudig je tot 1 : 1.'], uh: 'De coëfficiënten geven de molverhouding.' },
      { v: 'Wat is de molaire massa van water H₂O? (H = 1, O = 16)', o: ['16 g/mol', '18 g/mol', '17 g/mol', '20 g/mol'], c: 1, d: 2, uo: ['Nee, dat is alleen de zuurstof; de twee H tellen ook mee.', 'Klopt: 2·1 + 16 = 18 g/mol.', 'Nee, je telde maar één H mee.', 'Nee, 2·1 + 16 = 18, niet 20.'], uh: 'Molaire massa = som van de atoommassa\'s.' },
      { v: 'Hoeveel mol is 36 g water? (M = 18 g/mol)', o: ['1 mol', '2 mol', '0,5 mol', '18 mol'], c: 1, d: 2, uo: ['Nee, 1 mol zou 18 g zijn.', 'Klopt: n = m/M = 36/18 = 2 mol.', 'Nee, 0,5 mol is 9 g.', 'Nee, 18 is de molaire massa, niet het aantal mol.'], uh: 'n = m / M.' },
      { v: 'Welk gevaar hoort bij het GHS-pictogram met een vlam?', o: ['giftig', 'bijtend', 'brandbaar', 'oxiderend'], c: 2, d: 1, uo: ['Nee, giftig heeft een doodshoofd.', 'Nee, bijtend toont aantasting van hand en materiaal.', 'Klopt: de vlam staat voor brandbaar/ontvlambaar.', 'Nee, oxiderend toont een vlam boven een cirkel.'], uh: 'Vlam-pictogram betekent brandbaar.' },
      { v: 'Waarom draag je een veiligheidsbril tijdens practicum?', o: ['om beter te zien', 'om je ogen te beschermen tegen spatten', 'tegen het geluid', 'voor de sfeer'], c: 1, d: 1, uo: ['Nee, het is geen leesbril.', 'Klopt: hij beschermt je ogen tegen wegspattende stoffen.', 'Nee, geluid speelt geen rol.', 'Nee, veiligheid is de reden.'], uh: 'Bescherming tegen spatten.' },
      { v: 'Hoe verdun je een sterk zuur veilig?', o: ['giet water bij het zuur', 'giet het zuur voorzichtig bij het water', 'het maakt niet uit', 'verwarm het eerst'], c: 1, d: 2, uo: ['Nee, water bij zuur kan gevaarlijk opspatten door de warmte.', 'Klopt: zuur voorzichtig bij het water, zo verdeelt de warmte zich veilig.', 'Nee, de volgorde is wel degelijk belangrijk.', 'Nee, verwarmen maakt het juist gevaarlijker.'], uh: 'Zuur bij water, nooit water bij zuur.' },
      { v: 'Hoe bereken je de concentratie in mol/L?', o: ['mol × liter', 'mol / liter', 'liter / mol', 'gram / liter'], c: 1, d: 1, uo: ['Nee, vermenigvuldigen geeft niet de eenheid mol/L.', 'Klopt: c = n / V, mol per liter.', 'Nee, dat is omgekeerd.', 'Nee, gram/liter is een massaconcentratie, niet in mol.'], uh: 'c = n / V, in mol/L.' },
      { v: 'Welke wet zegt dat de totale massa in een afgesloten reactie gelijk blijft?', o: ['de wet van Avogadro', 'de wet van behoud van massa', 'de wet van Boyle', 'de wet van Ohm'], c: 1, d: 2, uo: ['Nee, Avogadro gaat over gelijke gasvolumes met gelijke aantallen deeltjes.', 'Klopt: de wet van behoud van massa (Lavoisier).', 'Nee, Boyle gaat over druk en volume van een gas.', 'Nee, Ohm hoort bij elektriciteit.'], uh: 'Massa vooraf = massa achteraf.' },
      { v: 'Hoeveel gram is 0,5 mol NaCl? (M = 58,5 g/mol)', o: ['29,25 g', '117 g', '58,5 g', '11,7 g'], c: 0, d: 2, uo: ['Klopt: m = n·M = 0,5·58,5 = 29,25 g.', 'Nee, 117 g is 2 mol.', 'Nee, 58,5 g is 1 mol.', 'Nee, reken 0,5·58,5.'], uh: 'm = n · M.' },
      { v: 'Hoeveel deeltjes zitten er in 2 mol?', o: ['1,2·10²⁴', '6,0·10²³', '3,0·10²³', '2·10²³'], c: 0, d: 2, uo: ['Klopt: 2·6,022·10²³ ≈ 1,2·10²⁴.', 'Nee, dat is 1 mol.', 'Nee, dat is 0,5 mol.', 'Nee, veel te weinig.'], uh: 'aantal deeltjes = n · 6,022·10²³.' },
      { v: 'Wat is de concentratie als je 0,2 mol oplost in 0,5 L?', o: ['0,1 mol/L', '0,4 mol/L', '2,5 mol/L', '1,0 mol/L'], c: 1, d: 2, uo: ['Nee, dat is n maal V.', 'Klopt: c = n/V = 0,2/0,5 = 0,4 mol/L.', 'Nee, dat is V/n.', 'Nee, reken 0,2/0,5.'], uh: 'c = n / V.' },
      { v: 'Hoeveel significante cijfers heeft 0,0450?', o: ['2', '3', '4', '5'], c: 1, d: 3, uo: ['Nee, de nul achteraan telt ook mee.', 'Klopt: 4, 5 en de nul erachter zijn significant; de voorloopnullen niet, dus 3.', 'Nee, voorloopnullen tellen niet mee.', 'Nee, er zijn er drie significant.'], uh: 'Voorloopnullen tellen niet, nullen achter een cijfer wel.' },
      { v: 'In N₂ + 3 H₂ → 2 NH₃ reageert met 1 mol N₂ hoeveel mol H₂?', o: ['1 mol', '2 mol', '3 mol', '6 mol'], c: 2, d: 2, uo: ['Nee, kijk naar de coëfficiënt van H₂.', 'Nee, 2 is de coëfficiënt van NH₃.', 'Klopt: de coëfficiënt van H₂ is 3, dus 3 mol.', 'Nee, dat is dubbel geteld.'], uh: 'De molverhouding volgt uit de coëfficiënten.' },
    ]),

  V('B', 'Stoffen en materialen in de chemie',
    `Atomen binden op drie manieren: door <strong>overdracht</strong> van elektronen (<strong>ionbinding</strong>), door <strong>delen</strong> van elektronen (<strong>covalente binding</strong>) of via een <strong>elektronenwolk</strong> (<strong>metaalbinding</strong>). Tussen moleculen werken <strong>intermoleculaire krachten</strong> die de stofeigenschappen bepalen.`,
    [
      { h: '1. Bindingstypen', p: [
        `Een <strong>ionbinding</strong> ontstaat als een metaalatoom elektronen afstaat aan een niet-metaalatoom: er vormen zich ionen die elkaar aantrekken in een <strong>ionrooster</strong>. Bij een <strong>covalente binding</strong> delen niet-metaalatomen een elektronenpaar. Bij een <strong>metaalbinding</strong> zitten positieve kernen in een wolk van vrije elektronen (daardoor geleiden metalen).`],
        formula: { label: 'Bindingstype uit elektronegativiteitsverschil', eq: 'ΔEN > 1,7 → ionbinding · 0,4–1,7 → polair covalent · < 0,4 → apolair covalent', note: 'Hoe groter het verschil in elektronegativiteit, hoe polairder de binding.' } },
      { h: '2. Intermoleculaire krachten', p: [
        `Tussen moleculen werken krachten die oplopen in sterkte: <strong>vanderwaalskrachten</strong> (zwak, tussen alle moleculen), <strong>dipool-dipoolkrachten</strong> (tussen polaire moleculen) en de <strong>waterstofbrug</strong> (sterk, met H aan N, O of F). De waterstofbrug verklaart het hoge kookpunt van water.`] },
      { h: '3. Roostertypen', p: [
        `De structuur bepaalt de eigenschappen. Een <strong>ionrooster</strong> (zout) heeft een hoog smeltpunt en geleidt alleen gesmolten of opgelost. Een <strong>atomair rooster</strong> (diamant, kwarts) is een covalent netwerk met een extreem hoog smeltpunt. Een <strong>molecuulrooster</strong> (ijs, jood) wordt door zwakke krachten bijeengehouden en heeft een laag smeltpunt.`] },
    ],
    [
      { t: 'Ionbinding', d: 'binding door overdracht van elektronen tussen een metaal en een niet-metaal', k: 'overdracht van elektronen', fout: ['Covalente binding', 'Metaalbinding'] },
      { t: 'Covalente binding', d: 'binding door het delen van een elektronenpaar tussen niet-metaalatomen', k: 'delen van elektronen', fout: ['Ionbinding'] },
      { t: 'Metaalbinding', d: 'binding tussen positieve metaalkernen in een wolk van vrije elektronen', k: 'kernen in een elektronenwolk', fout: ['Ionbinding', 'Covalente binding'] },
      { t: 'Elektronegativiteit', d: 'de mate waarin een atoom elektronen in een binding naar zich toe trekt', k: 'aantrekking van elektronen', fout: ['Polariteit'] },
      { t: 'Polariteit', d: 'de ongelijke ladingsverdeling in een binding door verschil in elektronegativiteit', k: 'ongelijke ladingsverdeling', fout: ['Elektronegativiteit'] },
      { t: 'Waterstofbrug', d: 'sterke intermoleculaire kracht met waterstof aan N, O of F', k: 'H aan N, O of F', fout: ['Vanderwaalskracht', 'Dipool-dipoolkracht'] },
      { t: 'Vanderwaalskracht', d: 'de zwakste intermoleculaire kracht, werkt tussen alle moleculen', k: 'zwakste intermoleculaire kracht', fout: ['Waterstofbrug'] },
      { t: 'Dipool-dipoolkracht', d: 'aantrekking tussen de permanente dipolen van polaire moleculen', k: 'tussen polaire moleculen', fout: ['Waterstofbrug'] },
      { t: 'Atomair rooster', d: 'een covalent netwerk van atomen, zoals diamant, met zeer hoog smeltpunt', k: 'covalent netwerk', fout: ['Ionrooster', 'Molecuulrooster'] },
      { t: 'Ionrooster', d: 'een regelmatig rooster van positieve en negatieve ionen', k: 'rooster van ionen', fout: ['Metaalbinding', 'Atomair rooster'] },
      { t: 'Molecuulrooster', d: 'rooster van moleculen bijeengehouden door zwakke krachten', k: 'moleculen met zwakke krachten', fout: ['Atomair rooster'] },
    ],
    [
      { v: 'Welk type binding ontstaat door overdracht van elektronen van een metaal- naar een niet-metaalatoom?', o: ['Ionbinding', 'Covalente binding', 'Metaalbinding', 'Polaire covalente binding'], c: 0, d: 2, uo: ['Klopt: overdracht van elektronen geeft ionen en dus een ionbinding.', 'Nee, bij een covalente binding worden elektronen gedeeld, niet overgedragen.', 'Nee, metaalbinding is tussen metaalatomen onderling.', 'Nee, bij polair covalent worden elektronen ongelijk gedeeld, niet overgedragen.'], uh: 'Overdracht → ionbinding; delen → covalent.' },
      { v: 'Welke intermoleculaire kracht is het sterkst en vereist H aan N, O of F?', o: ['Waterstofbrug', 'Vanderwaalskracht', 'Dipool-dipoolkracht', 'Iondipoolkracht'], c: 0, d: 2, uo: ['Klopt: de waterstofbrug is de sterkste en vereist H aan N, O of F.', 'Nee, vanderwaalskrachten zijn juist de zwakste.', 'Nee, dipool-dipool is zwakker dan een waterstofbrug.', 'Nee, iondipool speelt bij ionen in oplossing.'], uh: 'Sterkte: vanderwaals < dipool-dipool < waterstofbrug.' },
      { v: 'Wat is de relatie tussen elektronegativiteit en de polariteit van een binding?', o: ['Groter EN-verschil geeft een polairdere binding', 'Electropositiviteit bepaalt de polariteit', 'Alle bindingen zijn even polair', 'EN-verschil telt alleen bij ionbinding'], c: 0, d: 2, uo: ['Klopt: hoe groter het verschil in elektronegativiteit, hoe polairder de binding.', 'Nee, het gaat om elektronegativiteit, niet electropositiviteit.', 'Nee, de polariteit hangt af van het EN-verschil.', 'Nee, ook of een covalente binding polair is hangt van het EN-verschil af.'], uh: 'ΔEN groter → polairder; ΔEN > 1,7 → ionbinding.' },
      { v: 'Welk rooster beschrijft atomen die covalent gebonden zijn in een uitgebreid netwerk (zoals diamant)?', o: ['Atomair rooster', 'Ionrooster', 'Metaalrooster', 'Molecuulrooster'], c: 0, d: 3, uo: ['Klopt: een covalent netwerk (diamant, kwarts) met extreem hoog smeltpunt.', 'Nee, een ionrooster bestaat uit ionen.', 'Nee, een metaalrooster heeft kernen in een elektronenwolk.', 'Nee, een molecuulrooster wordt door zwakke krachten bijeengehouden.'], uh: 'Atomair rooster = covalent netwerk, zeer hoog smeltpunt.' },
      { v: 'Welke functionele groep bevat een carbonzuur?', o: ['–COOH', '–OH', '–NH₂', '–CHO'], c: 0, d: 2, uo: ['Klopt: de carboxylgroep –COOH kenmerkt een carbonzuur.', 'Nee, –OH is een hydroxylgroep (alcohol).', 'Nee, –NH₂ is een aminogroep (amine).', 'Nee, –CHO is een aldehydegroep.'], uh: 'Carbonzuur = –COOH.' },
      { v: 'Welk reactietype voegt atomen toe aan een C=C dubbele binding?', o: ['Additie', 'Substitutie', 'Eliminatie', 'Condensatie'], c: 0, d: 2, uo: ['Klopt: bij additie wordt de dubbele binding benut om atomen toe te voegen.', 'Nee, bij substitutie wordt een atoom vervangen.', 'Nee, bij eliminatie worden atomen juist afgesplitst.', 'Nee, condensatie voegt twee moleculen samen met een bijproduct.'], uh: 'Additie benut de dubbele binding.' },
      { v: 'Welk reactietype koppelt twee moleculen en splitst een klein molecuul (zoals water) af?', o: ['Condensatiereactie', 'Additiereactie', 'Hydrolyse', 'Oxidatiereactie'], c: 0, d: 3, uo: ['Klopt: bij condensatie koppelen twee moleculen met afsplitsing van bijvoorbeeld water.', 'Nee, additie voegt toe aan een dubbele binding.', 'Nee, hydrolyse is juist de splitsing mét water (tegenreactie).', 'Nee, oxidatie is toevoeging van zuurstof.'], uh: 'Condensatie koppelt en splitst H₂O af; hydrolyse is de tegenreactie.' },
      { v: 'Welke stereoisomeren zijn elkaars niet-samenvallende spiegelbeelden (chiraal)?', o: ['Enantiomeren', 'Constitutie-isomeren', 'Conformatie-isomeren', 'Diastereomeren'], c: 0, d: 3, uo: ['Klopt: enantiomeren zijn niet-samenvallende spiegelbeelden.', 'Nee, constitutie-isomeren hebben een andere bindingsvolgorde.', 'Nee, conformatie-isomeren verschillen door rotatie om een C-C binding.', 'Nee, diastereomeren zijn stereoisomeren die geen spiegelbeeld zijn.'], uh: 'Enantiomeren = spiegelbeeld-isomeren (chiraal).' },
      { v: 'Welk polymerisatietype koppelt monomeren zonder bijproduct (zoals polyetheen)?', o: ['Additiepolymerisatie', 'Condensatiepolymerisatie', 'Ringopening-polymerisatie', 'Zuur-basepolymerisatie'], c: 0, d: 3, uo: ['Klopt: bij additiepolymerisatie breekt de C=C open zonder bijproduct.', 'Nee, condensatiepolymerisatie vormt juist een bijproduct (H₂O of HCl).', 'Nee, ringopening opent een cyclisch monomeer.', 'Nee, dat is geen polymerisatietype.'], uh: 'Additie: geen bijproduct; condensatie: bijproduct.' },
      { v: 'Wat is het verschil tussen alkynen en alkenen?', o: ['Alkynen hebben C≡C, alkenen C=C', 'Alkynen hebben C=C, alkenen C–C', 'Alkynen zijn cyclisch, alkenen lineair', 'Ze zijn identiek qua bindingen'], c: 0, d: 2, uo: ['Klopt: alkynen hebben een drievoudige C≡C, alkenen een dubbele C=C.', 'Nee, een C=C is juist een alkeen.', 'Nee, alkynen zijn niet per definitie cyclisch.', 'Nee, de bindingen verschillen wel degelijk.'], uh: 'Alkaan C–C, alkeen C=C, alkyn C≡C.' },
      { v: 'Welke eigenschap maakt een benzeenring bijzonder stabiel?', o: ['Gedelokaliseerde π-elektronen over de ring', 'Alternerende bindingen zonder elektronendeling', 'Volledige verzadiging', 'Positieve lading op alle koolstofatomen'], c: 0, d: 3, uo: ['Klopt: gedelokaliseerde π-elektronen (aromaticiteit) maken benzeen stabiel.', 'Nee, de elektronen zijn juist gedelokaliseerd.', 'Nee, benzeen is niet volledig verzadigd.', 'Nee, de koolstofatomen dragen geen positieve lading.'], uh: 'Aromaticiteit = gedelokaliseerde π-elektronen.' },
      { v: 'Wat is het verschil tussen een alcohol en een fenol?', o: ['Alcohol: –OH aan koolstofketen; fenol: –OH aan benzeenring', 'Alcohol: –OH aan benzeenring; fenol: –OH aan keten', 'Ze zijn identiek', 'Fenol is sterker alkalisch dan alcohol'], c: 0, d: 3, uo: ['Klopt: bij een alcohol zit –OH aan een koolstofketen, bij een fenol aan de benzeenring.', 'Nee, dat is precies omgekeerd.', 'Nee, ze verschillen in waar de –OH zit.', 'Nee, fenol is juist zuurder, niet alkalisch.'], uh: 'Fenol: –OH aan de benzeenring en zuurder dan een alcohol.' },
      { v: 'Welke groep en eigenschap horen bij een amine?', o: ['–NH₂ en werkt als base', '–COOH en werkt als zuur', 'neutraal en reageert niet met zuren', '–OH en gedraagt zich als alcohol'], c: 0, d: 2, uo: ['Klopt: een amine bevat –NH₂ en accepteert H⁺, dus het is een base.', 'Nee, –COOH hoort bij een carbonzuur.', 'Nee, een amine reageert wel degelijk met zuren.', 'Nee, –OH hoort bij een alcohol.'], uh: 'Amine = –NH₂, basisch.' },
      { v: 'Welk reactietype zet een alcohol om in een alkeen door verwijdering van water?', o: ['Eliminatie (dehydratatie)', 'Substitutie', 'Additie', 'Condensatie'], c: 0, d: 3, uo: ['Klopt: bij eliminatie (dehydratatie) verdwijnt water en ontstaat een C=C.', 'Nee, bij substitutie wordt –OH vervangen door een ander atoom.', 'Nee, additie voegt juist toe aan een dubbele binding.', 'Nee, condensatie koppelt twee moleculen met een bijproduct.'], uh: 'Dehydratatie: alcohol → alkeen + water (eliminatie).' },
      { v: 'Welke aminozuren keren naar de waterloze kern van een opgevouwen eiwit?', o: ['Aminozuren met apolaire zijketens', 'Aminozuren met geladen zijketens', 'Aminozuren met OH-groepen', 'Aminozuren met S-S bruggen'], c: 0, d: 3, uo: ['Klopt: apolaire (hydrofobe) zijketens keren naar de waterloze kern.', 'Nee, geladen zijketens zijn hydrofiel en zitten aan de buitenkant.', 'Nee, OH-groepen zijn polair (hydrofiel).', 'Nee, S-S bruggen zijn verbindingen, geen hydrofobe zijketens.'], uh: 'Hydrofobe zijketens naar binnen, hydrofiele naar buiten.' },
    ]),
];
