// VWO Biologie - situaties per begrip.
export default {
  A: {
    'Onafhankelijke variabele': ['De grootheid die je zelf instelt of verandert in de proef', 'De hoeveelheid mest die je per plantje varieert'],
    'Afhankelijke variabele': ['De grootheid die je meet als resultaat van de proef', 'De hoogte van de plant die je aan het eind meet'],
    Controlevariabele: ['Een grootheid die je bewust constant houdt', 'Alle planten krijgen evenveel licht en water, alleen de mest verschilt'],
    Controlegroep: ['De groep zonder behandeling waarmee je vergelijkt', 'De planten die geen mest krijgen, als vergelijking'],
    Hypothese: ['Een toetsbare verwachting die je vooraf opstelt', 'Je gok van tevoren over de uitkomst'],
    Betrouwbaarheid: ['De mate waarin herhaling hetzelfde resultaat geeft', 'Meer metingen maken een resultaat hiervan beter'],
    'Dubbelblind onderzoek': ['Noch de proefpersoon noch de onderzoeker weet wie wat krijgt', 'Zo voorkom je dat verwachtingen de uitkomst kleuren'],
    Placebo: ['Een nepmiddel zonder werkzame stof, gebruikt als controle', 'De groep die een pil zonder medicijn krijgt'],
    Vergroting: ['Hoeveel groter je een preparaat onder de microscoop ziet', 'Objectief maal oculair geeft de totale waarde'],
    'Biologische tekening': ['Een nette potloodtekening met scherpe lijnen, bijschriften en vergroting', 'Zo leg je een waarneming onder de microscoop vast'],
  },
  B: {
    Homeostase: ['Je lichaam houdt de temperatuur rond 37 graden, ongeacht buiten', 'Het constant houden van het inwendige milieu'],
    'Negatieve terugkoppeling': ['Stijgt de bloedsuiker, dan komt insuline vrij die hem weer verlaagt', 'Een afwijking van het setpoint wordt automatisch gecorrigeerd'],
    Insuline: ['Na een maaltijd daalt de bloedsuiker doordat dit hormoon vrijkomt', 'Het hormoon dat glucose de cellen in laat gaan'],
    Glucagon: ['Bij honger breekt dit hormoon glycogeen in de lever af', 'Het hormoon dat de bloedsuiker verhoogt'],
    ADH: ['Als je weinig drinkt, houdt dit hormoon meer water vast in de nier', 'Het hormoon dat de waterhuishouding regelt'],
    Actiepotentiaal: ['Een korte elektrische puls schiet langs de zenuwcel door instromend natrium', 'De prikkel die als een golf over het axon loopt'],
    Synaps: ['Aan het uiteinde springt de prikkel via neurotransmitters over naar de volgende cel', 'De ruimte tussen twee zenuwcellen met chemische overdracht'],
    'Sympathisch zenuwstelsel': ['Bij schrik gaat je hart sneller en verwijden je pupillen', 'Het deel dat je klaarmaakt om te vechten of te vluchten'],
    'Parasympathisch zenuwstelsel': ['Na het eten komt de spijsvertering op gang en kalmeert je hart', 'Het deel dat zorgt voor rust en vertering'],
    Antigeen: ['Een lichaamsvreemde stof op een virus die je afweer aanzet', 'Iets wat een afweerreactie oproept'],
    Antilichaam: ['Een eiwit dat precies op een ziekteverwekker past en hem onschadelijk maakt', 'Door B-cellen gemaakt om een antigeen te binden'],
    Vaccinatie: ['Een prikje met een onschadelijk antigeen leert je afweer een ziekte kennen', 'Zo bouw je zelf antilichamen en geheugen op'],
    Fotosynthese: ['Een blad maakt met zonlicht suiker uit koolstofdioxide en water', 'In de chloroplast ontstaat glucose en zuurstof'],
    Celademhaling: ['In de mitochondriën wordt glucose met zuurstof omgezet in energie', 'De afbraak van glucose die ATP oplevert'],
  },
  C: {
    Mitose: ['Uit één huidcel ontstaan twee genetisch identieke cellen', 'De celdeling waarmee een wond geneest'],
    Meiose: ['Er ontstaan vier geslachtscellen met de helft van de chromosomen', 'De deling die eicellen en zaadcellen maakt'],
    Differentiatie: ['Een stamcel wordt een spiercel of een zenuwcel', 'Cellen krijgen een gespecialiseerde vorm en taak'],
    Stamcel: ['Een cel die zich nog tot van alles kan ontwikkelen', 'In het beenmerg zitten deze nog niet gespecialiseerde cellen'],
    Successie: ['Op kaal zand komen eerst mossen, dan grassen, dan struiken', 'De geleidelijke opeenvolging van levensgemeenschappen'],
    Pioniersoort: ['Korstmossen die als eerste een kale rots koloniseren', 'De eerste soort die de bodem geschikt maakt'],
    Climaxstadium: ['Een oud, stabiel bos in evenwicht', 'Het stabiele eindstadium van de successie'],
    Biodiversiteit: ['Het aantal verschillende soorten in een gebied', 'In een tropisch regenwoud is deze heel hoog'],
    'Emergente eigenschap': ['Bewustzijn ontstaat uit losse hersencellen die het zelf niet hebben', 'Een eigenschap die pas in het geheel verschijnt'],
    Genexpressie: ['In een levercel zijn andere genen actief dan in een huidcel', 'Welke genen in een cel worden afgelezen'],
  },
  D: {
    'Abiotische factor': ['De temperatuur en het licht in een sloot', 'Een niet-levende invloed op organismen', 'De zuurgraad van de bodem waarin een plant groeit'],
    'Biotische factor': ['De roofdieren en planten in een gebied', 'Een levende invloed op organismen'],
    Producent: ['Een plant die met licht zijn eigen voedsel maakt', 'Het organisme onderaan de energiepiramide', 'Gras dat door fotosynthese zijn eigen suiker maakt'],
    Reducent: ['Schimmels die dode bladeren afbreken', 'Het organisme dat dood materiaal opruimt'],
    Energiepiramide: ['Een schema waarin elke laag maar ongeveer tien procent doorgeeft', 'Onderaan veel producenten, bovenaan weinig toppredatoren'],
    Mutualisme: ['De bij bestuift de bloem en krijgt er nectar voor terug', 'Een relatie waarin beide soorten winnen', 'De clownvis en de zeeanemoon beschermen elkaar'],
    Competitie: ['Twee vogelsoorten strijden om dezelfde nestplekken', 'De strijd om een beperkte hulpbron', 'Twee leeuwengroepen betwisten hetzelfde jachtgebied'],
    Parasitisme: ['Een lintworm leeft in de darm ten koste van de gastheer', 'De één profiteert, de ander lijdt'],
  },
  E: {
    Transcriptie: ['De DNA-code wordt in de kern overgeschreven naar mRNA', 'De eerste stap van de eiwitsynthese'],
    Translatie: ['Op het ribosoom wordt uit mRNA een eiwit gebouwd', 'tRNA voert de aminozuren aan'],
    'DNA-replicatie': ['Vóór een celdeling wordt het DNA gekopieerd', 'Elke nieuwe helix krijgt één oude en één nieuwe streng'],
    'Dominant allel': ['Deze genvariant is altijd zichtbaar als hij aanwezig is', 'Bruine ogen overheersen blauwe'],
    'Recessief allel': ['Deze genvariant zie je pas bij twee kopieën', 'Blauwe ogen komen alleen bij een dubbele aanleg voor'],
    Genotype: ['De genen die iemand van zijn ouders kreeg', 'De erfelijke samenstelling, of je ze nu ziet of niet'],
    Fenotype: ['De kleur van je ogen die je echt kunt zien', 'De waarneembare eigenschappen van een organisme'],
    Mutatie: ['Een verandering in de volgorde van het DNA', 'Een fout bij het kopiëren van het erfelijk materiaal'],
    PCR: ['In het lab maak je van weinig DNA heel veel kopieën', 'De techniek die een DNA-fragment vermenigvuldigt'],
    'CRISPR-Cas9': ['Met een gids-RNA knip je het DNA op een precieze plek', 'De techniek waarmee je gericht genen kunt bewerken'],
    Pleiotropie: ['Eén gen beïnvloedt zowel de vachtkleur als de gezondheid', 'Eén gen met meerdere zichtbare effecten'],
    Geslachtschromosomen: ['De X- en Y-chromosomen die het geslacht bepalen', 'Een man heeft XY, een vrouw XX'],
  },
  F: {
    'Natuurlijke selectie': ['De snelste hazen ontsnappen en krijgen meer jongen', 'De best aangepaste individuen planten zich meer voort'],
    Overproductie: ['Een vis legt duizenden eitjes waarvan er weinig overleven', 'Er komen meer nakomelingen dan er kunnen overleven'],
    Variatie: ['Binnen een soort verschillen de individuen erfelijk van elkaar', 'De erfelijke verschillen waarop selectie kan werken'],
    'Genetische drift': ['In een klein groepje verandert de kleurverdeling puur door toeval', 'Toevallige verandering van allelfrequenties'],
    Flessenhalseffect: ['Na een ramp blijft een kleine groep met weinig variatie over', 'De diversiteit stort in door een sterke inkrimping'],
    Stichtingseffect: ['Een paar vogels bereiken een eiland en stichten een nieuwe populatie', 'Een kleine groep verlaat de populatie en begint elders opnieuw'],
    'Sympatrische speciatie': ['Nieuwe soorten ontstaan zonder dat er een berg of rivier tussen zit', 'Soortvorming zonder geografische scheiding'],
    'Allopatrische speciatie': ['Een rivier splitst een populatie en er ontstaan twee soorten', 'Soortvorming door een geografische barrière'],
    'Homologe structuren': ['De arm van een mens en de vleugel van een vogel hebben dezelfde bouw', 'Zelfde oorsprong, wat op verwantschap wijst'],
    'Analoge structuren': ['De vleugel van een vlinder en van een vleermuis: zelfde functie, andere bouw', 'Zelfde functie maar een andere oorsprong'],
    'Hardy-Weinberg-evenwicht': ['Onder ideale omstandigheden blijven de allelfrequenties gelijk', 'Geen evolutie: de verhoudingen veranderen niet'],
  },
};
