// VWO Scheikunde - situaties per begrip (voedt de situatie-vraaggenerator).
export default {
  A: {
    Mol: ['In deze eenheid druk je uit hoeveel deeltjes je hebt: 6,022·10²³ per stuk', 'Je rekent met hoeveelheid stof in plaats van met losse deeltjes'],
    'Constante van Avogadro': ['Het getal 6,022·10²³ geeft het aantal deeltjes per mol', 'Zo veel deeltjes zitten er in precies één mol'],
    'Molaire massa': ['De massa van één mol van een stof, af te lezen in gram per mol', 'Voor water is deze grootheid 18 g/mol'],
    Concentratie: ['Hoeveel mol opgeloste stof er per liter oplossing zit', 'Een oplossing van 0,1 mol/L is verdund, 5 mol/L is geconcentreerd'],
    Molverhouding: ['De verhouding tussen de aantallen mol volgt uit de coëfficiënten van de reactie', 'In 2 H₂ + O₂ reageert twee keer zoveel waterstof als zuurstof'],
    'Significante cijfers': ['De betekenisvolle cijfers in een meetwaarde, zoals bij 0,0450', 'Hiermee geef je aan hoe nauwkeurig je meting is'],
    'Wet van behoud van massa': ['De totale massa vóór en na een reactie in een afgesloten systeem is gelijk', 'Er gaat geen massa verloren, atomen worden alleen herschikt'],
    'GHS-pictogram': ['Een teken op de verpakking waarschuwt voor het gevaar van een stof', 'Een vlam, doodshoofd of bijtend symbool op een fles'],
  },
  B: {
    Ionbinding: ['Natrium geeft een elektron af aan chloor; de geladen deeltjes trekken elkaar aan', 'De binding in keukenzout, tussen een metaal- en een niet-metaalion'],
    'Covalente binding': ['Twee niet-metaalatomen delen samen een elektronenpaar', 'In een watermolecuul houden O en H elkaar vast door elektronen te delen'],
    Metaalbinding: ['Positieve metaalkernen zitten in een zee van vrije elektronen', 'Deze binding verklaart waarom metalen stroom en warmte geleiden'],
    Elektronegativiteit: ['De mate waarin een atoom de gedeelde elektronen naar zich toe trekt', 'Fluor heeft hiervan de hoogste waarde, waterstof een lage'],
    Polariteit: ['Doordat O de elektronen sterker aantrekt, is de O-H binding aan één kant negatiever', 'Een ongelijke ladingsverdeling binnen een binding'],
    Waterstofbrug: ['De sterke aantrekking die het hoge kookpunt van water verklaart', 'Ontstaat als waterstof gebonden is aan stikstof, zuurstof of fluor'],
    Vanderwaalskracht: ['De zwakke aantrekking die tussen alle moleculen werkt, ook apolaire', 'De enige intermoleculaire kracht tussen onpolaire alkanen'],
    'Dipool-dipoolkracht': ['De aantrekking tussen de plus- en de minkant van permanente dipolen', 'Werkt tussen polaire moleculen, sterker dan vanderwaals maar zwakker dan een waterstofbrug'],
    'Atomair rooster': ['Diamant: elk koolstofatoom covalent gebonden in een enorm netwerk, extreem hard', 'Een netwerk van atomen met een zeer hoog smeltpunt, zoals kwarts'],
    Ionrooster: ['Een regelmatige stapeling van positieve en negatieve ionen, zoals in zout', 'Hoog smeltpunt en bros, geleidt alleen gesmolten of opgelost'],
    Molecuulrooster: ['Losse moleculen bijeengehouden door zwakke krachten, laag smeltpunt', 'Vast jood: moleculen in een rooster door zwakke vanderwaalskrachten'],
  },
  C: {
    Evenwichtsconstante: ['Een groot getal K vertelt dat er in evenwicht vooral product is', 'Deze constante geeft de verhouding tussen product en reactant'],
    'Dynamisch evenwicht': ['De concentraties blijven gelijk terwijl de reactie heen en terug doorgaat', 'Heen- en teruggaande reactie verlopen precies even snel'],
    'Le Chatelier': ['Verhoog je de druk, dan wijkt het evenwicht uit naar minder gasmoleculen', 'Voeg je product toe, dan verschuift het evenwicht naar de reactanten'],
    pH: ['Een oplossing van 0,01 mol/L zoutzuur heeft hiervan de waarde 2', 'Deze maat daalt naarmate een oplossing zuurder wordt'],
    pOH: ['Bij een pH van 9 is deze waarde 5, want samen zijn ze 14', 'De tegenhanger van de pH voor de basiciteit'],
    Zuur: ['Zoutzuur staat een proton af aan het water', 'Volgens Brønsted het deeltje dat een H⁺ afgeeft'],
    Base: ['Ammoniak neemt een proton op uit het water', 'Volgens Brønsted het deeltje dat een H⁺ opneemt'],
    Oxidatie: ['Bij deze halfreactie staat een deeltje elektronen af', 'IJzer dat roest staat elektronen af'],
    Reductie: ['Bij deze halfreactie neemt een deeltje elektronen op', 'Aan de kathode worden elektronen opgenomen'],
    'Galvanische cel': ['Een batterij levert stroom uit een spontane redoxreactie', 'Twee halfcellen leveren samen een elektrische spanning'],
    Elektrolyse: ['Met een stroombron splits je water in waterstof en zuurstof', 'Elektrische energie drijft een reactie die vanzelf niet verloopt'],
  },
};
