  gs: [
    {
      id: 'gs_havo_2025_1', vakId: 'gs', titel: 'Geschiedenis',
      niveau: 'havo', jaar: 2025, tijdvak: 1,
      duur_minuten: 150, max_punten: 64,
      bron: 'HA-3850-a-25-1-o',
      vragen: [
        { nr: 1, opgave: 1, punten: 1, type: 'mc',
          context: 'De Industriele Revolutie begon in Engeland rond 1760.',
          vraag: 'Welk gevolg had de stoommachine van Watt voor de industrie?',
          options: ['A) Ambachtelijke productie nam toe', 'B) Fabrieken konden op elke locatie worden gebouwd', 'C) De landbouw werd de belangrijkste sector', 'D) Kinderarbeid werd afgeschaft'],
          correct_option: 1,
          antwoord: 'B) Fabrieken waren niet langer afhankelijk van waterloop of wind en konden overal worden gebouwd.',
          antwoord_rubric: '1 pt: B.' },
        { nr: 2, opgave: 1, punten: 2, type: 'open',
          context: 'De Industriele Revolutie leidde tot grote sociale veranderingen in de 19e eeuw.',
          vraag: 'Beschrijf twee sociale gevolgen van de industrialisatie voor arbeiders.',
          antwoord: '(1) Slechte arbeidsomstandigheden: lange werkdagen (12-16 uur), gevaarlijk werk in fabrieken.\n(2) Urbanisatie: trek van platteland naar steden, overbevolkte woonwijken, armoede.',
          antwoord_rubric: '1 pt per correct sociaal gevolg.' },
        { nr: 3, opgave: 2, punten: 1, type: 'mc',
          context: 'De Eerste Wereldoorlog (1914-1918).',
          vraag: 'Welke directe aanleiding leidde tot het uitbreken van WO1?',
          options: ['A) De Russische Revolutie', 'B) De aanslag op Franz Ferdinand in Sarajevo', 'C) De annexatie van Elzas-Lotharingen', 'D) Het Verdrag van Versailles'],
          correct_option: 1,
          antwoord: 'B) De aanslag op kroonprins Franz Ferdinand in Sarajevo (28 juni 1914).',
          antwoord_rubric: '1 pt: B.' },
        { nr: 4, opgave: 2, punten: 2, type: 'open',
          context: 'Het Verdrag van Versailles (1919) legde zware voorwaarden op aan Duitsland.',
          vraag: 'Noem twee bepalingen van het Verdrag van Versailles en leg uit waarom ze bijdroegen aan de opkomst van het nationaalsocialisme.',
          antwoord: '(1) Schuldclausule (art.231): Duitsland erkende volledige schuld voor WO1 -> nationaal vernedering.\n(2) Zware herstelbetalingen -> economische ellende en inflatie -> vruchtbare bodem voor extremistische bewegingen.',
          antwoord_rubric: '1 pt per bepaling + uitleg.' },
        { nr: 5, opgave: 3, punten: 2, type: 'open',
          context: 'De Tweede Wereldoorlog. De Jodenvervolging.',
          vraag: 'Beschrijf de drie fasen van de Jodenvervolging door de nazi\'s (1933-1945).',
          antwoord: '(1) Discriminatie en uitsluiting (1933-1938): Neurenberger wetten, boycot Joodse winkels.\n(2) Pogingen en deportatie (1938-1942): Kristallnacht, getto\'s, massa-deportaties.\n(3) Systematische massamoord (1942-1945): vernietigingskampen (Auschwitz), Endlosung -- ca. 6 miljoen Joden vermoord.',
          antwoord_rubric: '2 pt: drie fasen correct beschreven.' },
        { nr: 6, opgave: 3, punten: 1, type: 'mc',
          context: 'De Koude Oorlog (1947-1991).',
          vraag: 'Wat was de Truman-doctrine (1947)?',
          options: ['A) Amerika\'s belofte om Europa economisch te steunen (Marshallplan)', 'B) Amerika\'s belofte om landen te steunen die bedreigd werden door communisme', 'C) De NAVO-oprichtingsverdrag', 'D) Het plan voor de Berlijnse Luchtbrug'],
          correct_option: 1,
          antwoord: 'B) De VS beloofde vrije volkeren te steunen die weerstand boden aan communistische druk (containment-beleid).',
          antwoord_rubric: '1 pt: B.' },
        { nr: 7, opgave: 4, punten: 2, type: 'open',
          context: 'Dekolonisatie. Na WO2 verloren Europese mogendheden hun kolonien.',
          vraag: 'Beschrijf twee redenen waarom Europese landen hun kolonien niet konden vasthouden na 1945.',
          antwoord: '(1) Europa was verzwakt door WO2 (economisch en militair) en had geen middelen voor koloniale oorlogen.\n(2) Nationalistische bewegingen in kolonien werden sterker, gesteund door de VS (anti-kolonialisme) en de VN (zelfbeschikkingsrecht).',
          antwoord_rubric: '1 pt per reden.' },
        { nr: 8, opgave: 4, punten: 2, type: 'open',
          context: 'Europese integratie. De EGKS (1951) en het Verdrag van Rome (1957).',
          vraag: '(a) Wat was het doel van de EGKS?\n(b) Beschrijf het economisch voordeel van de gemeenschappelijke markt.',
          antwoord: '(a) Gemeenschappelijke markt voor kolen en staal onder supranationaal toezicht, mede om toekomstige oorlogen te voorkomen.\n(b) Vrij verkeer van goederen, personen en kapitaal: lagere handelstarieven, grotere markt, meer concurrentie, lagere prijzen voor consumenten.',
          antwoord_rubric: '1 pt: EGKS-doel. 1 pt: economisch voordeel.' },
        { nr: 9, opgave: 5, punten: 2, type: 'open',
          context: 'Bron: toespraak Winston Churchill, 1946: "Wij moeten iets als de Verenigde Staten van Europa bouwen."',
          vraag: '(a) Welke historische context verklaart deze oproep in 1946?\n(b) In hoeverre is Churchills visie gerealiseerd?',
          antwoord: '(a) Vlak na WO2 (1939-1945): Europa verwoest, miljoenen doden. Churchill wilde herhaling voorkomen door samenwerking.\n(b) Deels gerealiseerd: de EU met gemeenschappelijke markt, euro, Europees parlement. Maar geen volledige politieke unie; lidstaten behielden soevereiniteit.',
          antwoord_rubric: '1 pt: context WO2. 1 pt: evaluatie EU.' },
        { nr: 10, opgave: 5, punten: 1, type: 'mc',
          context: 'De val van de Berlijnse Muur (9 november 1989).',
          vraag: 'Welk politiek gevolg had de val van de Berlijnse Muur?',
          options: ['A) Oprichting van de NAVO', 'B) Hereniging van Duitsland in 1990', 'C) Ontbinding van de Europese Gemeenschap', 'D) Begin van de Koude Oorlog'],
          correct_option: 1,
          antwoord: 'B) Op 3 oktober 1990 werd Duitsland herenigd.',
          antwoord_rubric: '1 pt: B.' }
      ]
    },
    {
      id: 'gs_vwo_2025_1', vakId: 'gs', titel: 'Geschiedenis',
      niveau: 'vwo', jaar: 2025, tijdvak: 1,
      duur_minuten: 180, max_punten: 76,
      bron: 'VW-3850-a-25-1-o',
      vragen: [
        { nr: 1, opgave: 1, punten: 3, type: 'open',
          context: 'De Franse Revolutie (1789-1799) en de Verlichting.',
          vraag: '(a) Hoe beinvloedde het verlichtingsdenken de Franse Revolutie?\n(b) Beschrijf de fases van de Revolutie.\n(c) Welke erfenis liet de Revolutie na voor Europa?',
          antwoord: '(a) Verlichting: rationalisme, volkssoevereiniteit (Rousseau), scheiding der machten (Montesquieu), mensenrechten (Locke) -> ideologische basis voor Revolutie.\n(b) Fases: constitutionele monarchie (1789-1792), radicale fase/Terreur (1793-1794, Robespierre), Directoire (1795-1799), Napoleon.\n(c) Verspreiding van ideeen: vrijheid, gelijkheid, broederschap. Nationalisme in Europa. Napoleontische codes (wetboek). Einde feodalisme.',
          antwoord_rubric: '1 pt per onderdeel.' },
        { nr: 2, opgave: 2, punten: 3, type: 'open',
          context: 'Bronanalyse. Toespraak van Lenin, April 1917: "Geen steun aan de Voorlopige Regering. Alle macht aan de sovjets."',
          vraag: '(a) Wat zijn de Aprilstellingen en in welke context werden ze uitgesproken?\n(b) Welk ideologisch verschil bestaat er tussen Lenin en de Mensjewieken?\n(c) Hoe rechtvaardigt Lenin de machtsovername in Oktober 1917?',
          antwoord: '(a) April 1917, na Februari-Revolutie. Lenin keert terug uit ballingschap, verwerpt samenwerking met bourgeois Voorlopige Regering.\n(b) Lenin: directe socialistische revolutie, avant-garde partij. Mensjewieken: eerst bourgeois democratie, dan geleidelijk socialisme.\n(c) Dialectisch materialisme: historische noodzaak, arbeidersklasse als revolutionair subject, imperialistische oorlog aantonen.',
          antwoord_rubric: '1 pt per onderdeel.' },
        { nr: 3, opgave: 3, punten: 2, type: 'open',
          context: 'De Holocaust en de Wannsee-conferentie (januari 1942).',
          vraag: '(a) Wat werd besloten op de Wannsee-conferentie?\n(b) Welke historische discussie bestaat er over de intentionaliteit van de Holocaust?',
          antwoord: '(a) Coordinatie van de Endlosung: systematische moord op alle Europese Joden, verantwoordelijkheden verdeeld over SS, politie, spoorwegen.\n(b) Intentionalisten: Hitler had al vroeg een plan (Mein Kampf). Functionalisten: de Holocaust ontstond geleidelijk uit bureaucratische dynamiek. Synthese: Hitler had ideologisch doel, maar implementatie was incrementeel.',
          antwoord_rubric: '1 pt: Wannsee-besluit. 1 pt: historiografisch debat.' },
        { nr: 4, opgave: 4, punten: 2, type: 'open',
          context: 'Dekolonisatie. Indonesie en de Politionele Acties (1945-1949).',
          vraag: '(a) Beschrijf de Nederlandse positie en de Indonesische reactie.\n(b) Hoe beinvloedde internationale druk de uitkomst?',
          antwoord: '(a) Nederland: koloniale gezag herstellen, economisch belang (handelsmonopolies). Indonesie: onafhankelijkheidsverklaring Soekarno (17 aug 1945), gewapend verzet.\n(b) VS en VN drukten Nederland. VS dreigde Marshallhulp stop te zetten. VN-Veiligheidsraad eiste staakt-het-vuren. Nederland moest capituleren: soevereiniteitsoverdracht 1949.',
          antwoord_rubric: '1 pt: standpunten. 1 pt: internationale druk.' }
      ]
    }
  ],

  ak: [
    {
      id: 'ak_havo_2025_1', vakId: 'ak', titel: 'Aardrijkskunde',
      niveau: 'havo', jaar: 2025, tijdvak: 1,
      duur_minuten: 150, max_punten: 68,
      bron: 'HA-3860-a-25-1-o',
      vragen: [
        { nr: 1, opgave: 1, punten: 2, type: 'open',
          context: 'Klimaat. Het KNMI meldt dat 2024 het warmste jaar was in Nederland ooit gemeten (+2,1 graden ten opzichte van het gemiddelde 1900-2000).',
          vraag: '(a) Noem twee menselijke oorzaken van klimaatverandering.\n(b) Noem twee gevolgen voor Nederland.',
          antwoord: '(a) (1) Verbranding van fossiele brandstoffen (CO2-uitstoot). (2) Ontbossing (minder CO2-opname).\n(b) (1) Zeespiegelstijging (gevaar voor laaggelegen gebieden). (2) Extremere weersomstandigheden (heviger regenval, hitte-eilanden in steden).',
          antwoord_rubric: '1 pt: oorzaken. 1 pt: gevolgen.' },
        { nr: 2, opgave: 1, punten: 2, type: 'open',
          context: 'Klimaatzones.',
          vraag: 'Beschrijf het verschil tussen een gematigd zeeklimaat en een landklimaat. In welke twee Europese landen zie je elk klimaat?',
          antwoord: 'Zeeklimaat: milde winters, koele zomers, veel neerslag het hele jaar (oceaanwerking). Voorbeeld: Nederland, Ierland.\nLandklimaat: strenge winters, hete zomers, weinig neerslag. Voorbeeld: Polen, Hongarije.',
          antwoord_rubric: '1 pt: beschrijving. 1 pt: voorbeelden.' },
        { nr: 3, opgave: 2, punten: 2, type: 'open',
          context: 'Bevolking. Nigeria heeft een bevolkingsgroei van 2,5% per jaar. De bevolking is nu 220 miljoen.',
          vraag: '(a) Bereken de bevolking na 20 jaar (gebruik: N = N0 * e^(r*t), of benadering).\n(b) Noem twee gevolgen van snelle bevolkingsgroei voor Nigeria.',
          antwoord: '(a) N = 220 * (1,025)^20 = 220 * 1,638 = 360 miljoen.\n(b) (1) Druk op onderwijs, gezondheidszorg en water. (2) Meer jongeren op arbeidsmarkt (demografisch dividend mogelijk, maar ook werkloosheid).',
          antwoord_rubric: '1 pt: ~360 mln. 1 pt: twee gevolgen.' },
        { nr: 4, opgave: 2, punten: 2, type: 'open',
          context: 'Migratie. In 2023 kwamen meer dan 400.000 mensen naar Nederland.',
          vraag: 'Onderscheid push- en pullfactoren voor migratie naar Nederland. Geef twee voorbeelden van elk.',
          antwoord: 'Push (factoren in herkomstland): oorlog/onveiligheid, economische armoede, klimaatramp.\nPull (factoren in Nederland): werkgelegenheid, hoog levenspeil, politieke stabiliteit.',
          antwoord_rubric: '1 pt: push. 1 pt: pull met voorbeelden.' },
        { nr: 5, opgave: 3, punten: 2, type: 'open',
          context: 'Globalisering. Apple laat zijn iPhones produceren in China, assembleert in meerdere landen en verkoopt wereldwijd.',
          vraag: '(a) Noem twee economische voordelen van globalisering voor multinationals als Apple.\n(b) Noem twee nadelen van globalisering voor arbeiders in productielanden.',
          antwoord: '(a) (1) Lagere productiekosten door goedkope arbeid. (2) Toegang tot wereldmarkt (hogere omzet).\n(b) (1) Lage lonen en slechte arbeidsomstandigheden. (2) Weinig sociale zekerheid / rechten.',
          antwoord_rubric: '1 pt: voordelen. 1 pt: nadelen.' },
        { nr: 6, opgave: 3, punten: 2, type: 'open',
          context: 'Wereldhandel. Vrijhandel versus protectionisme.',
          vraag: 'Geef twee argumenten voor vrijhandel en twee argumenten voor protectionisme.',
          antwoord: 'Vrijhandel: (1) Lagere prijzen door specialisatie en comparatieve voordelen. (2) Meer keuze voor consumenten.\nProtectionisme: (1) Bescherming van jonge industrieen. (2) Voorkomen van oneerlijke concurrentie (dumpingprijzen).',
          antwoord_rubric: '1 pt: vrijhandel-argumenten. 1 pt: protectionisme-argumenten.' },
        { nr: 7, opgave: 4, punten: 2, type: 'open',
          context: 'Duurzaamheid. Nederland wil in 2050 klimaatneutraal zijn.',
          vraag: '(a) Wat betekent klimaatneutraal?\n(b) Noem twee concrete maatregelen die Nederland neemt om dit doel te bereiken.',
          antwoord: '(a) Klimaatneutraal: de CO2-uitstoot is gelijk aan de CO2-opname (netto nul uitstoot).\n(b) (1) Uitfaseren van aardgas (overstap naar warmtepompen). (2) Uitbreiding windenergie op zee (Hollandse Kust).',
          antwoord_rubric: '1 pt: definitie. 1 pt: twee maatregelen.' },
        { nr: 8, opgave: 5, punten: 2, type: 'open',
          context: 'Stedelijke geografie. In Nederland groeit de bevolking in steden, terwijl plattelandsgemeenten krimpen.',
          vraag: '(a) Noem twee economische oorzaken van verstedelijking.\n(b) Noem twee ruimtelijke problemen die hoge verstedelijking met zich meebrengt.',
          antwoord: '(a) (1) Meer werkgelegenheid in steden. (2) Betere voorzieningen (onderwijs, zorg, cultuur).\n(b) (1) Woningtekort en hoge huizenprijzen. (2) Verkeerscongestie.',
          antwoord_rubric: '1 pt: oorzaken. 1 pt: problemen.' }
      ]
    },
    {
      id: 'ak_vwo_2025_1', vakId: 'ak', titel: 'Aardrijkskunde',
      niveau: 'vwo', jaar: 2025, tijdvak: 1,
      duur_minuten: 180, max_punten: 76,
      bron: 'VW-3860-a-25-1-o',
      vragen: [
        { nr: 1, opgave: 1, punten: 2, type: 'open',
          context: 'Klimaatmodellen. IPCC-rapport 2023 voorspelt 1,5-4,5C opwarming in 2100 afhankelijk van emissiescenario.',
          vraag: '(a) Beschrijf het verschil tussen een RCP2.6 en een RCP8.5 scenario.\n(b) Welke terugkoppelingsmechanismen versterken opwarming?',
          antwoord: '(a) RCP2.6: agressieve emissiereductie, opwarming beperkt tot ~1,5C. RCP8.5: business-as-usual, opwarming tot 4-5C.\n(b) (1) IJssmelting: wit ijs vervangt donker water -> minder reflectie (albedo-effect). (2) Permafrost-ontdooiing -> methaanemissie -> sterkere opwarming.',
          antwoord_rubric: '1 pt: RCP-onderscheid. 1 pt: terugkoppelingsmechanismen.' },
        { nr: 2, opgave: 2, punten: 3, type: 'berekening',
          context: 'Demografische transitie. Land X: geboortecijfer 38 promille, sterftecijfer 12 promille, bevolking 10 miljoen.',
          vraag: '(a) Bereken het natuurlijke groeipercentage.\n(b) In welke fase van de demografische transitie bevindt dit land zich?\n(c) Noem twee beleid-maatregelen om de bevolkingsgroei te remmen.',
          antwoord: '(a) Groei = 38-12 = 26 promille = 2,6% per jaar.\n(b) Fase 2/3: hoog geboortecijfer met dalend sterftecijfer -- ontwikkelingsland in transitie.\n(c) (1) Gezinsplanning en voorlichting. (2) Onderwijs voor vrouwen (hogere opleiding -> lagere vruchtbaarheid).',
          antwoord_rubric: '1 pt: 2,6%. 1 pt: fase 2/3. 1 pt: maatregelen.' },
        { nr: 3, opgave: 3, punten: 2, type: 'open',
          context: 'Mondialisering. Mondiale waardeketen van koffie: geteeld in Ethiopie, verwerkt in Europa, verkocht in Nederland voor EUR 4 per kopje.',
          vraag: 'Beschrijf hoe de toegevoegde waarde ongelijk wordt verdeeld in de koffie-waardeketen en welke rol macht speelt.',
          antwoord: 'Boeren in Ethiopie ontvangen <1% van de verkoopprijs (lage onderhandelingsmacht, grondstofprijs fluctueert). Verwerkingsbedrijven en retailers in rijke landen beheersen de waardeketen en houden het merendeel van de winst. Machtsverschil: multinationals bepalen contracten, transportbedrijven en supermarkten verdienen het meest.',
          antwoord_rubric: '2 pt: ongelijke verdeling + machtsanalyse.' },
        { nr: 4, opgave: 4, punten: 2, type: 'open',
          context: 'Waterproblematiek. Waterschaarste in Sahel-regio.',
          vraag: '(a) Noem twee fysisch-geografische oorzaken van waterschaarste in de Sahel.\n(b) Beschrijf een duurzame oplossing met voor- en nadelen.',
          antwoord: '(a) (1) Lage en onregelmatige neerslag (<400 mm/jaar). (2) Hoge verdamping door hoge temperaturen.\n(b) Druppelirrigatie: water efficienter toedienen aan gewassen. Voordelen: waterbesparend, hogere opbrengst. Nadelen: hoge installatiekosten, onderhoudsgevoelig.',
          antwoord_rubric: '1 pt: oorzaken. 1 pt: oplossing met afweging.' }
      ]
    }
  ],
